### ISSUE TITLE
Conan package for OpenCV

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [opencv/opencv#10020]
Hello,
Do you know about Conan package manager? Can you add Conan package for libpng and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by alalek** [comment]
OpenCV is package agnostic library based on CMake configuration tool.
We prefer to use CMake `find_package()` to search package.

There are many package managers (in both forms - source code / prebuilt binaries) for C++ libraries (probably because C++ standard doesn't have official way yet) and we have no resources to support/test them (even part of them).
