### ISSUE TITLE
cv::dnn::readNetFromTensorflow errors loading ssd_mobilenet_v1_coco_11_06_2017 in opencv 3.3.1

### ISSUE THREAD

**Issue by moorage** [opencv/opencv#10043]
In the [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), `ssd_mobilenet_v1_coco` is a newly trained model [to download](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz) (warning: large file)

If you download it and run the following line from OpenCV 3.3.1, you'll get an error.

```java
cv::dnn::Net net = cv::dnn::readNetFromTensorflow("ssd_mobilenet_v1_coco_11_06_2017/frozen_inference_graph.pb", "ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt");
```

The error message is:

```
[libprotobuf ERROR opencv-3.3.1/3rdparty/protobuf/src/google/protobuf/text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 113344:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp, line 72
opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt in function ReadTFNetParamsFromTextFileOrDie
```

The `pbtxt` file contains a node around line 113,344 that has the following type definition:

```
  attr {
    key: "T"
    value {
      type: DT_RESOURCE
    }
  }
```

Could this be fixed by updating OpenCV's embedded `dnn/src/tensorflow/tensor.proto` to match the updated `tensor.proto` at [github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto), which contains `DT_RESOURCE`? 

PS - it looks like the config file for `ssd_mobilenet_v1_coco` is here: https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_coco.config

**Comment by alalek** [comment]
BTW, There is OpenCV's version of [this network scheme](https://github.com/opencv/opencv_extra/blob/3.3.1/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt).

**Comment by juventi** [comment]
@alalek  python version of using ssd_mobilenet_v1_coco_11_06_2017 in opencv 3.3.1 is ok， but 
I could not use it in C++ version, I didn't know why
The cv::dnn::Net net = cv::dnn::readNetFromTensorflow() and Mat inputBlob = cv::dnn::blobFromImage() are ok,  process died in cv::Mat output = net.forward() with no outputs ? 
Didn't it support C++ version?

**Comment by dkurt** [comment]
@moorage, it seems to me that model is the same but it recreated to solve some issues with TensorFlow 1.4. The simplest solution for now is to use model from http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz.

**Comment by Bahramudin** [comment]
@moorage Did you solve the problem, I also have the same problem, if you have the answer please share it with me also, thanks!

**Comment by moorage** [comment]
@Bahramudin not at the moment; instead I'm going to take the route of including and calling the tensorflow (v1.4) C++ library directly to get bounding boxes; which is still a work in progress.

**Comment by Bahramudin** [comment]
@moorage Hmm... Good job, wish success! I will thank full if you have any good tutorial, especially "How to train my own model" using TensorFlow, to share with me too. :-)

**Comment by dkurt** [comment]
There are two models for now: actual http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_08.tar.gz and tested in OpenCV http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz . They are the same (mAP = 21 for both) but the last one was reserialized. We manage a graph import using text representation (https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt) with hardcoded names of weights (i.e. `FeatureExtractor/MobilenetV1/Conv2d_0/weights`) but newer version has obfuscated Const nodes names (i.e. `FeatureExtractor/MobilenetV1/Conv2d_0/weights/read/_104__cf__107`). Perhabs because of  optimize_for_inference tool call.

I think we need to replace all references introduced at https://github.com/opencv/opencv/pull/9750 and https://github.com/opencv/opencv_extra/pull/387 from "TensorFlow Object Detection Model Zoo" to a direct link (http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz).

**Comment by Bahramudin** [comment]
Thanks for the reply!! One question, can you tell when I want to read the net with this function:
`readNetFromTensorflow(String model, String config);`
Then from below which files are needed to give to this function?

> **pipeline.config**
> **saved_model** // is a folder which contains **saved_model.pb**
> **checkpoint**
> **frozen_inference_graph.pb
> model.ckpt.data-00000-of-00001
> model.ckpt.index
> model.ckpt.meta**

_I have built the OpenCV from the latest source (OpenCV 3.3.1)_

Thanks in advance!

**Comment by dkurt** [comment]
@Bahramudin, see https://github.com/opencv/opencv/blob/master/samples/dnn/mobilenet_ssd_python.py

**Comment by Bahramudin** [comment]
Thanks for the link! But I still have the error:
**1. There is no xxx.pbtxt inside the extracted folder. If I run with one parameter** `Dnn.readNetFromTensorflow(model)`  (only pass the model), then have this error:
> OpenCV Error: Unspecified error (Unknown layer type Cast in op ToFloat) in cv::dnn::experimental_dnn_v2::`anonymous-namespace'::TFImporter::populateNet, file C:\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 1299
> ToFloat:Cast(image_tensor)
> SrcT:[ ]
> DstT:[ ]

**2. If then I pass the `pipeline.config` file to the function:**
```
String model = basePath + "frozen_inference_graph.pb";
String config = basePath + "pipeline.config";
Net net = Dnn.readNetFromTensorflow(model, config);
```
Then I got this error：

> [libprotobuf ERROR C:\opencv\3rdparty\protobuf\src\google\protobuf\text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 1:7: Message type "tensorflow.GraphDef" has no field named "model".
> OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: C:\ssd_mobilenet_v1_coco_2017_11_08\pipeline.config) in cv::dnn::ReadTFNetParamsFromTextFileOrDie, file C:\opencv\modules\dnn\src\tensorflow\tf_io.cpp, line 72
> Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: C:\opencv\modules\dnn\src\tensorflow\tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: C:\ssd_mobilenet_v1_coco_2017_11_08\pipeline.config in function cv::dnn::ReadTFNetParamsFromTextFileOrDie
> ]

**3. Then I searched the internet and found one `ssd_mobilenet_v1_coco.pbtxt` file, then when I run the program, I got this error:**

> OpenCV Error: Unspecified error (Const input blob for weights not found) in cv::dnn::experimental_dnn_v2::`anonymous-namespace'::TFImporter::getConstBlob, file C:\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 555
> Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: C:\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:555: error: (-2) Const input blob for weights not found in function cv::dnn::experimental_dnn_v2::`anonymous-namespace'::TFImporter::getConstBlob
> ]

(: _Helpless_

**Comment by Bahramudin** [comment]
@dkurt It seems the problem has solved (there is no more exception reading the Net and forwarding the image), there is one problem, that, how can extract the data from the forward function? I searched a lot but did not find any example in C++. There is an example in Python, but I really did not understand the code, because there is not any description an also I did not learn the Python in the past.
So it is what I have done so far:
```
String model = basePath + "frozen_inference_graph.pb";
String config = basePath + "ssd_mobilenet_v1_coco.pbtxt";
Net tensorflow = Dnn.readNetFromTensorflow(model, config);

Mat img = Imgcodecs.imread("C:\\Users\\BAHRAMUDIN-ADIL\\Desktop\\Images\\space_shuttle.jpg");

Mat blob = Dnn.blobFromImage(img, 1, new Size(244, 244), new Scalar(104, 117, 123), true, true);
tensorflow.setInput(blob);
Mat forward = tensorflow.forward();
```

Now what should we do with `forward`?
Thanks!

**Comment by dkurt** [comment]
@Bahramudin, here is a C++ sample for SSD-like object detection model: https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_mobilenet_object_detection.cpp and a Java one: https://github.com/opencv/opencv/blob/master/samples/android/mobilenet-objdetect/src/org/opencv/samples/opencv_mobilenet/MainActivity.java.

**Comment by Bahramudin** [comment]
@dkurt Thanks, bro! It was the best, it is working now.

**Comment by kiran734** [comment]
@Bahramudin  Can you please share how you have solved "Const input blob for weights not found"?

**Comment by Bahramudin** [comment]
@kiran734 What language do you use, Java?

**Comment by dkurt** [comment]
@Bahramudin, I'm sorry but I don't understand what the problem is. All of object detection samples contain names of classes.

**Comment by kiran734** [comment]
@Bahramudin I am saving the trained graph in python and trying to load in C++.

**Comment by Bahramudin** [comment]
@kiran734  If so, then you can try the above @dkurt comment, which helped me also, there C++ and Java examples, I am using Java, and it works well.  Download [this](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz) and then and [this](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt) and it is solved the question of me.

**Comment by Bahramudin** [comment]
@kiran734 [This ](https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_mobilenet_object_detection.cpp )example is what you want, loading the trained data and execute detection. But one question, I am also trying to train my own module (train some images) how can I do this, if you have any good tutorial please share it with me. Thanks!

**Comment by kiran734** [comment]
@Bahramudin Thanks for the help, I will try to solve the issue and let you know if it works. Regaring training, I was loading the weights from .npy files. So, I don't know how to train my own module. I will share a tutorial if I find a good one.

**Comment by Bahramudin** [comment]
@kiran734 Hmm, good. Whish you have successfully done it!!

**Comment by chamathabeysinghe** [comment]
I have trained new model on top of ssd_mobilenet_v1_coco for a custom data set. This model works fine in tensorflow. But now I want to use this in OpenCV. So for the config file I add convert frozen_graph to pbtxt and add it. But then I got the following error
`[libprotobuf ERROR  /home/chamath/Projects/opencv/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 731:5: Unknown enumeration value of "DT_RESOURCE" for field "type".`

As a workaround I try to use [this](https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/ssd_mobilenet_v1_coco.pbtxt) config file mentioned in the thread but when I use it object detection is not working properly. Incorrect number of squares detected and they are misplaced. 
Is there any method to create a pbtxt config file that works with OpenCV.

**Comment by dkurt** [comment]
@chamathabeysinghe, please use http://answers.opencv.org for build/install/usage questions.

**Comment by moorage** [comment]
@Bahramudin FWIW, I finally posted the tutorial https://github.com/moorage/OpenCVTensorflowExample

**Comment by vagdevik** [comment]
**Issue Resolved in Python Version:**

In my case, I was trying to access the `.pbtxt` file stored in a github repository through my Google Colaboratory.  I just needed the file, so instead of cloning the whole repo, I tried to access it using `!wget` command. I did:
`https://github.com/<username>/somethingelse/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`.
The file seemed to be downloaded, but when I ran `cv2.dnn.readNetFromTensorflow`, it has thrown me an error saying:

`OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp, line 72
opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt in function ReadTFNetParamsFromTextFileOrDie`.

I realised I should have used the `raw` file in github to download, as follows:
`!wget https://raw.githubusercontent.com/---somethingelse as part of link---/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`

Since I did't use raw, the file downloaded in HTML format where as the expected file was `.pbtxt`. 

**So go to the file location in github repository->click on the raw option on top right corner->get the URL of this raw page-> use `!wget https://raw.githubusercontent.com/ ---somethingelse as part of link---/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`
has helped me resolved the issue.** 

Hope this helps someone!!  :-D
