### ISSUE TITLE
bug opencv3.3.1: cv::DataType<cv::Vec<uchar, 3>> has no member type

### ISSUE THREAD

**Issue by yanchao12122** [opencv/opencv#10115]
when I write code as follows in vs2015

cv::Mat img(10, 10, cv::DataType<cv::Vec<uchar, 3>>::type);

it has an error : cv::Mat img(10, 10, cv::DataType<cv::Vec<uchar, 3>>::type); has no member type

**Comment by alalek** [comment]
OpenCV traits system is reworked to avoid several bugs: #9457 (related issue #7599)

> cv::DataType<cv::Vec<uchar, 3>>::type

Consider to use:
- `CV_8UC3` directly if it is not part of code with templates
- `cv::traits::Type< cv::Vec<uchar, 3> >::value` (since OpenCV 3.3.1 only)
- or `#define OPENCV_TRAITS_ENABLE_DEPRECATED` before any OpenCV headers to allow old type traits (for example, in stdafx.h or via compiler defines in project properties).
