### ISSUE TITLE
Forward propagation works even if the input dimensions specified in deploy.prototxt do not match the input blob dimensions ( Loading Caffe Models in OpenCV 3.3 )

### ISSUE THREAD

**Issue by AyushP123** [opencv/opencv#10210]
I have already asked a question on stackoverflow regarding this -> [link](https://stackoverflow.com/questions/47416465/how-to-specify-input-dimensions-in-deploy-prototxt-for-forward-propagation-when). The problem is that there is no exception thrown when the input blob dimensions do not match the input dimensions specified in deploy.prototxt. Currently I think dnn::Net::forward() or dnn::Net::setBlob() resizes the input blob to the input dimensions specified by deploy.prototxt. So setting the input dimensions as either { 1, 1, 1, 1 } or { 1, 1, 200, 400 } or { 1, 1, 400 , 200 } in the deploy.prototxt works which confuses the user as to exactly how the input dimensions should be specified. Also another interesting observation: I tested all the 3 variations of the input dimensions for forward propagation and all of them led to the same output.

**Comment by dkurt** [comment]
@AyushP123, the first thing is that network deployment means you already know an input sizes because we can have some layers depend on it, i.e. fully-connected layer. On the other hand there are models that works with any size input so sizes from `.prorotxt` mostly mean nothing. In short words, keeping right input size is a responsibility of user. Please use http://answers.opencv.org for the further questions.
