### ISSUE TITLE
C API doesn't work anymore if building without optimizations

### ISSUE THREAD

**Issue by dkogan** [opencv/opencv#10246]
This is a duplicate of #8658. Linking any application that uses the OpenCV C API without optimizations now results in a undefined reference to cvRound. This is because this function is now defined ONLY in a C++-only header: fast_math.hpp.

The reply (by "alalek") on that bug was that the C API shouldn't be used anymore. I don't know who alalek is; is this the official position? This issue effectively kills the C API. I.e. it's no longer an OPTION to use the C API without experiencing pain. And this particular issue isn't even hard to fix. I can give you a patch, and we can agree to at least not kill the C API on purpose, yes?

**Comment by dkogan** [comment]
alalek: are you an "official opencv dev", whatever that means? If so, please state that breaking this is official policy. Then the distros and the people relying on this functionality can act accordingly. As a Debian dev, I would really appreciate having an explicit official statement.

**Comment by dkogan** [comment]
The main OpenCV website claims that OpenCV has "C++, C, Python and Java interfaces", which is conflicts with what you're saying here: i.e. currently there is no functional C interface. Is there an imminent plan to update the website and all that?

**Comment by alalek** [comment]
C API support is dropped somewhere before OpenCV 2.x.
Again, there are no new algorithms developed with C API in OpenCV for the last ~5 years.

There is just nothing to "fix" in your meaning, because there is no C API in the modern OpenCV. You could use OpenCV 1.0 anyway if you want, but don't.
Parts of OpenCV C API is still here - to provide easy migration of legacy apps, but you should compile these sources as C++ code (just reusing of structure/function names).
C compilation doesn't work (and leads for application crashes - check cvGetSize #6221 ) and not tested by OpenCV team.

Possible solution here is FFI (https://en.wikipedia.org/wiki/Foreign_function_interface) bindings for C  which should be able to emulate C++ features effectively.
To implement this we must think about emulation of C++ exceptions in C, classes/methods/objects, etc, including some "runtime library" to support this.
For example, you could take a look on "golang" approach from here: #10129 (but they completely lost C++ exceptions handling).
Also you could take a look on OpenCV Python bindings, there are exceptions are re-wrapped into Python "exceptions" leaving message string only. Classes are emulated via Python runtime.

This is my answer from the technical side of this question.
If you want strategic/political answer then you should ask @vpisarev .

**Comment by dkogan** [comment]
Thanks for the reply. I certainly have my thoughts about this question, but yall can do what you want with your library, I just wanted a clear answer. Can you please update the docs, and at least the front webpage to not claim there's a C API anymore?
