### ISSUE TITLE
Does DNN Opencv3.3.1 support Faster RCNN that Created by Tensorflow?

### ISSUE THREAD

**Issue by kerolos** [opencv/opencv#10393]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
I tested the ssd_mobilenet in Opencv3.3.1 , Furthermore, i want to use another model such as  Faster RCNN (Tensorflow). 

My question is, I have to convert the model and wight from Tensorflow to Caffe to be able to use in OpenCV or there is another alternative way to use it (.pbtxt 'conf text graph is not provided in a good format which should be readable in OpenCV )?

The second question about the parameters used in Ssdmobilenet inScaleFactor = 0.007843f, meanVal = 127.5. they are somehow not understandable for me, I will really appreciate if someone can explain those valves and how can be chosen, and it should change from model to another?

**Comment by dkurt** [comment]
@kerolos, we've implemented Faster-RCNN from Caffe recently. Please see https://github.com/opencv/opencv/pull/10306. So it seems to me that we have all necessary layers. I put `documentation` label for now because it require some guide how to prepare a text representation of TensorFlow graph. Raw serialized object detection models from TensorFlow usually is too mush complicated for parsing.

**Comment by dkurt** [comment]
@kerolos, We've opened a PR https://github.com/opencv/opencv/pull/11255 with a new script to import Faster-RCNN networks from [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection). Work is still in progress but you can test it and get a feedback! Thank you!
