### ISSUE TITLE
CMake Build Error

### ISSUE THREAD

**Issue by mhaghighat** [opencv/opencv#10511]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Windows 7 (64 Bit)
- Compiler => Visual Studio 2015

##### Detailed description

I 'd like to build the OpenCV 3.4.0 using CMake 3.10.1 on Windows 7. I use the default configuration with no extra modules. It configures properly, but when I hit the Generate button, it gives this error:

"**Error in generating process, project files may be invalid.**"

 I don't get this error when I build the OpenCV 3.3 following the exact same steps.

**Comment by alalek** [comment]
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
We don't help with remote investigation of problems (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.
