### ISSUE TITLE
Comments specifying about "cvWarpAffine"

### ISSUE THREAD

**Issue by victor-ludorum** [opencv/opencv#10652]
In the OpenCV imagproc modules every functions description is present and at the last of their description a line is present which is something like **"@see "function-name"** but [here](https://github.com/opencv/opencv/blob/master/modules/imgproc/include/opencv2/imgproc/imgproc_c.h#L399)  function name following is different and name specifying through "@see" is different as here the line is **@see cvWarpAffine** but the function following is **cvGetQuadrangleSubPix**

**Comment by terfendail** [comment]
@victor-ludorum 
OpenCV migrated to C++ API from old C-style API, but deprecated C-style API is still retained for backward compatibility. As a result documentation of functionality is migrated to C++ API as well. That fact is noticed in C-style API documentation by references to corresponding C++ API call. Most of functions have similar named pair mentioned with `@see` tag, but for cvGetQuadrangleSubPix there is no such direct pair since it is very similar to cvWarpAffine(that is noticed in description of cvWarpAffine mentioned by `@see` tag) and was replaced by extension of warpAffine functionality in C++ API.

**Comment by victor-ludorum** [comment]
Okay @terfendail, and sorry  for bothering I don't have knowledge about that. Thanks 😊.
