### ISSUE TITLE
filter2D does not utilize pixels outside ROI when kernel size > 11

### ISSUE THREAD

**Issue by vs-zhehangd** [opencv/opencv#10683]
**Description**

It is said
> ... now the filtering operations fully support the notion of image ROI, that is, pixels outside of the ROI but inside the image can be used in the filtering operations.

I found when calling `filter2D` to filter an ROI using a kernel larger than 11x11, the function does not utilize the pixels outside the ROI. Probably related to the fact that filter uses DCT instead of convolution beyond that size? I have tested 3.1, 3.2, 3.3, 3.4. This issue happens since 3.2. 3.1 does not have this issue.

**System information**
OpenCV 3.2, 3.3, 3.4
Ubuntu 16.04
g++ 5.4.0

**Steps to reproduce**

The following code produces the problem. It divides an image into blocks and filters each of them.

```c++

#include <iostream>
#include <vector>

#include <opencv2/opencv.hpp>

int main(void) {
  
  std::cout << "OpenCV version : " << CV_VERSION << std::endl;
  
  const char* input_file  = "roi_filter_test.jpg";
  const char* output_file = "roi_filter_test_output.jpg";
  
  cv::Mat image  = cv::imread(input_file);
  cv::Mat output = cv::Mat::zeros(image.size(), image.type());
  
  int BLOCK_SIZE = 64; // can be any
  
  std::vector<cv::Rect> regions;
  for (int r = 0; r < image.rows / BLOCK_SIZE; ++r)
    for (int c = 0; c < image.cols / BLOCK_SIZE; ++c)
      regions.emplace_back(c * BLOCK_SIZE, r * BLOCK_SIZE,
                           BLOCK_SIZE, BLOCK_SIZE);
      
  int ksize  = 12; // issue when > 11
  int ksize2 = ksize * ksize;
  cv::Mat kernel = cv::Mat::ones(ksize, ksize, CV_32F) / ksize2;
    
  for (const auto& region: regions) {
    cv::Mat roi_i(image,  region);
    cv::Mat roi_o(output, region);
    cv::filter2D(roi_i, roi_o, -1, kernel);
  }
  
  cv::imwrite(output_file, output); 
  
  return 0;
}

```
Input Image:
![roi_filter_test](https://user-images.githubusercontent.com/29877977/35364356-901f386e-0123-11e8-9373-40990bcea6d8.jpg)

Result @ OpenCV 3.1
![roi_filter_test_output_3_1](https://user-images.githubusercontent.com/29877977/35364363-9a283234-0123-11e8-8b7b-fc1cf41f739c.jpg)

Result @ OpoenCV 3.2, 3.3, 3.4
![roi_filter_test_output_3_4](https://user-images.githubusercontent.com/29877977/35364369-a3113422-0123-11e8-8c14-00c14623a61d.jpg)

**Comment by Riyuzakii** [comment]
@alalek I would like to fix this issue. Can you get me started? What files to look into and the basic way to fix the problem?

**Comment by mshabunin** [comment]
@Riyuzakii , probably you should take a look at the function: [dftFilter2d](https://github.com/opencv/opencv/blob/e801e336ede0d43cb8e7be698424b7320925b700/modules/imgproc/src/filter.cpp#L4835-L4842) it runs when `kernel_w * kernel_h > 50`.

**Comment by Riyuzakii** [comment]
@mshabunin, @vs-zhehangd 's your code gives me the following error on executing the executable:
```
OpenCV version : 3.3.1
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp, line 538
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp:538: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat
```

**Comment by mshabunin** [comment]
@Riyuzakii , I've been able to reproduce this issue on my machine using the sample provided in the beginning. Make sure you are reading correct image in `imread`.

In my previous comment I provided wrong condition. As can be seen from the code:
https://github.com/opencv/opencv/blob/e801e336ede0d43cb8e7be698424b7320925b700/modules/imgproc/src/filter.cpp#L4659-L4661
if SSE3 is available, algorithm switches to DFT branch only in case when `kernel_w * kernel_h >= 130`, that is why kernel size 11 works well and 12 fails.

If you compare two calls:
https://github.com/opencv/opencv/blob/e801e336ede0d43cb8e7be698424b7320925b700/modules/imgproc/src/filter.cpp#L4835-L4842

And:
https://github.com/opencv/opencv/blob/e801e336ede0d43cb8e7be698424b7320925b700/modules/imgproc/src/filter.cpp#L4845-L4854

You will see that parameters `full_width`, `full_height`, `offset_x`, `offset_y` are not used in the call to `dftFilter2D`, thus information about ROI is not available in this function. 

You can try to add missing arguments to the function and handle them correctly, so that underlying calls to `crossCorr` could use this information.

**Comment by Riyuzakii** [comment]
@mshabunin how did you compile the code? I used a standard CMakeLists.txt and added this line to it:
```set (CMAKE_CXX_STANDARD 11)
```
Otherwise emplace_back gave an error. and then did a make and executed the executable.

**Comment by vs-zhehangd** [comment]
@Riyuzakii 
Sorry it is a stupid bug:
```c++
for (int r = 0; r < image.cols / BLOCK_SIZE; ++r) {
  for (int c = 0; c < image.rows / BLOCK_SIZE; ++c) {
    regions.emplace_back(c * BLOCK_SIZE, r * BLOCK_SIZE,
                          BLOCK_SIZE, BLOCK_SIZE);
    
  }
}
```
Please switch `image.cols` and `image.rows`. I used to use a square image so I did not notice it.
