### ISSUE TITLE
Compilation time optimization in Debug build

### ISSUE THREAD

**Issue by Taraflex** [opencv/opencv#10734]
- OpenCV => 3.4
- Operating System => Windows 64 Bit
- Compiler => Visual Studio 2015

/GL flag must be disabled in the Debug build (even when the ENABLE_LTO option is enabled), because it needs the /LTCG flag when using opencl as a static library
`
opencv_core340d.lib(alloc.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
`
But /LTCG flag greatly increases the compilation time.

**Comment by alalek** [comment]
Why do you use the `ENABLE_LTO` flag in the Debug builds? static builds? (This flag is disabled by default)

**Comment by Taraflex** [comment]
Thanks for the answer/
ENABLE_LTO enable /LTCG and /GL in Debug and Release together (in generated Visual Studio solutions we have Debug and Release with same flags - we have to generate different solutions with different parameters. This is not very convenient).
There is any stantart way to enable  /LTCG and /GL only in the Release build in one solution with Debug like linker /INCREMENTAL and cflag /Zi option?

**Comment by mshabunin** [comment]
@Taraflex , please check whether the fix from the pull request #10759 works for you.

**Comment by Taraflex** [comment]
@mshabunin Thanks. I can not check right now. But maybe it would be better to unify the behavior of ENABLE_LTO for all compilers and change the description of the option to something like "Enable Release mode Link Time Optimization"?
https://github.com/mshabunin/opencv/blob/60f1c9dcdf6f9ef6e8a415a64563abea418792ad/CMakeLists.txt#L318
In the current patch, the behavior of the ENABLE_LTO option does not become obvious.

**Comment by mshabunin** [comment]
>But maybe it would be better to unify the behavior of ENABLE_LTO for all compilers

Do you mean "add `-flto` to RELEASE flags for GNU compiler"?

I don't think it is necessary, because different compilers can have different limitations, for example [gcc manual](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) says: "Combining -flto with -g is currently experimental and expected to produce unexpected results." Maybe someone will want to experiment with this combination :boom:

Visual Studio is special case, because single cmake configuration can be used to build two binary configurations, thus it should be fixed, but for GNU-compatible compilers it works as simple ON/OFF switch with obvious behavior.
