### ISSUE TITLE
Can't save image when use imwrite() to multi byte string path.

### ISSUE THREAD

**Issue by M-T-Asagi** [opencv/opencv#10773]
When I tried saving image to path including Japanese, function "imwrite" didn't work or inform.

##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2017

##### Steps to reproduce

Example not working.
```
cv::imwrite("C:\\Users\\someone\\ドキュメント\\image.png"), colorMat);
```

Working
```
cv::imwrite("C:\\Users\\someone\\Documents\\image.png"), colorMat);
```

**Comment by alalek** [comment]
OpenCV doesn't support Unicode.
More or less this works on Linux via UTF-8 encoding (no extra lines required, supported by libc). But this is not tested, because this is not the primary functionality for computer vision library.
Consider using ASCII symbols only. Or try `imencode()` with own file writer.

**Comment by M-T-Asagi** [comment]
OK, I understand.
thank you!
