### ISSUE TITLE
Why doesn't opencv.js include CvKNearest?

### ISSUE THREAD

**Issue by sid-kap** [opencv/opencv#10774]
It appears that the Javascript version doesn't include some classes, such as CvKNearest. Why is this? Where can I find a list of all the included/excluded classes and functions?

**Comment by sid-kap** [comment]
@alalek Why is this question invalid? This isn't documented anywhere, so I didn't know where else to ask.

**Comment by alalek** [comment]
Because this is not an action item.

Questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

Functions with "cv" prefix are legacy - they are not supported anymore and will be dropped.
OpenCV is C++ library, bindings just can't cover 100% of functionality due language limitations or different paradigms.
