### ISSUE TITLE
OpenCV build failed, Visual Studio 2017, Win 64bit

### ISSUE THREAD

**Issue by Bahramudin** [opencv/opencv#10804]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform =>Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description
I am trying to build OpenCV from the source in windows using CMake and Visual Studio 2017, everything goes well, but when the build process finished, it shows the below message:
`59>Done building project "opencv_cvv.vcxproj" -- FAILED.`
`========== Build: 77 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

The question is, does it make matter? If yes, what matter and how to solve?
Thanks!!
##### Steps to reproduce
In the CMake configuration, I deselect Java, Python, Test, and select QT and OpenGL

**Comment by alalek** [comment]
"cvv" is "opencv_contrib" module.
Missing actual build error message.
Missing information how QT is installed.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.
