### ISSUE TITLE
cv2.HoughLinesP does not filter correctly lines according the minLineLength

### ISSUE THREAD

**Issue by vict0ra** [opencv/opencv#10823]
OpenCV => 2.4.13.4
Operating System / Platform => Ubuntu

cv2.HoughLinesP does not filter correctly lines according the minLineLength

Example of my function :
```
def linesDetect(edges):
    minLineLength = 100
    maxLineGap = 5
    lines = cv2.HoughLinesP(edges,1,np.pi/180,50,minLineLength,maxLineGap)
    for x in range(0, len(lines)):
        for x1,y1,x2,y2 in lines[x]:
            lenL = np.sqrt((x1 - x2)**2 + (y1 - y2)**2)
            if (lenL < minLineLength):
                print "hog fails ?"
    return lines
```
Print systematically: print "hog fails ?"

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Return here with complete reproducer if bug is confirmed.

**Comment by totobrei** [comment]
According to the official Documentation ([HoughLinesP 3.0-beta](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html)) the usage is 
`lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength,maxLineGap)`

any change to minLineLength has no effect on the outcome. The function arguments are probably in the wrong order. Only if you speficy the parameters it works correctly:
`lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180, threshold=100, minLineLength=minLineLength, maxLineGap=maxLineGap)`

**Comment by pablogps** [comment]
I'm still a bit confused, but I agree with the bug report.

From the [documentation](https://docs.opencv.org/2.4/modules/imgproc/doc/feature_detection.html#houghlinesp), it seems like there is another parameter, `lines`, so that in the first case `maxLineGap` is actually working as `minLineLength`, and `minLineLength` is doing nothing at all.

See the method definition in Python:

`def HoughLinesP(image, rho, theta, threshold, lines=None, minLineLength=None, maxLineGap=None):`

This is corroborated by some experiments I'm doing right now: increasing `maxLineGap` returns only larger lines (as expected of increasing `minLineLength`) and changing `minLineLength` has no effect whatsoever.

**Comment by AleksandrPanov** [comment]
@vict0ra, missing parameter `line` in  `HoughLinesP`.  This parameter has been in opencv since version 2.4 and up to now.
 
`HoughLinesP` signature:
`HoughLinesP(	image, rho, theta, threshold[, lines[, minLineLength[, maxLineGap]]]	) ->	lines`

If parameter `lines` is useless, you should use `None`:
`lines = cv2.HoughLinesP(edges,1,np.pi/180,50,None,minLineLength,maxLineGap)`

It is recommended to use up-to-date opencv version (4.5.3) and up-to-date [documentation](https://docs.opencv.org/master/). The correct example of using `HoughLinesP` is [here](https://docs.opencv.org/master/d9/db0/tutorial_hough_lines.html).

[This tutorial ](https://docs.opencv.org/3.4/d6/d10/tutorial_py_houghlines.html)needs a fix.

**Comment by alalek** [comment]
Consider using "names" for optional parameters to skip `None`s / other params.
