### ISSUE TITLE
OpenCV 3.1(cv2.COLOR_BGR2GRAY) - Unable to know the result of the code

### ISSUE THREAD

**Issue by guruvishnuvardan** [opencv/opencv#10830]
HI,

I am working to detect, if the video/camera vision is blurred using OpenCV 3.1, Python 2.7, post executing the code in the terminal, I am not getting results at all(Meaning: No error for almost 5 mins or no video output) . Can you please let me know, whats wrong with the code or the mp4 video(which is downloaded from youtube) and cut using vidcutter in windows

![detect blurr](https://user-images.githubusercontent.com/31349523/36061760-db55a6ce-0e84-11e8-97bc-9ff4e6429d84.png)

Config: OpenCV 3.1(CUDA enabled), Python 2.7, GPU - NVIDIA GEFORCE GTX 970

Do i need to check anything with respect to mp4(video size is 510 KB)

Please find my attached code image

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.

You must refer to OpenCV samples at first instead of writing own custom code.
You lost waitKey() call - it is required for UI interaction, see OpenCV documentation.
Your loop is broken:
- infinite loop
- only last frame may be processed if infinite loop get fixed.
