### ISSUE TITLE
SystemError: new style getargs format but argument is not a tuple

### ISSUE THREAD

**Issue by satish15697** [opencv/opencv#10994]
I'm getting error while applying gabor filter as,
Traceback (most recent call last):
  File "gabor.py", line 71, in <module>
    result = gabor(im, W, angles)
  File "gabor.py", line 45, in gabor
    j * W + l)
SystemError: new style getargs format but argument is not a tuple.

complete code is given below,
def gabor(im, W, angles):
    (x, y) = im.size
    im_load = im.load()

    freqs = frequency.freq(im, W, angles)
    print "computing local ridge frequency done"

    gauss = utils.gauss_kernel(3)
    utils.apply_kernel(freqs, gauss)

    for i in range(1, x / W - 1):
        for j in range(1, y / W - 1):
            kernel = gabor_kernel(W, angles[i][j], freqs[i][j])
            for k in range(0, W):
                for l in range(0, W):
                    im_load[i * W + k, j * W + l] = utils.apply_kernel_at(
                        lambda x, y: im_load[x, y],
                        kernel,
                        i * W + k,
                        j * W + l)

    return im

please help me

**Comment by naserpiltan** [comment]
@alalek how didi you solve this problem?
i have same issue
can you help me?

**Comment by srijan14** [comment]
In case someone still faces the same issues, the problem was that the  `utils.apply_kernel_at` was returning a float value, though the value of pixels can only be int I suppose. typecasting the `utils.apply_kernel_at`  response as int seems to resolve the error.

`im_load[i * W + k, j * W + l] = int(utils.apply_kernel_at( lambda x, y: im_load[x, y],kernel,i * W + k,j * W + l))`
