### ISSUE TITLE
OE-1 "Maintaining OpenCV 1.x C API" discussion

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#11000]
the feature request about evolution proposal [OE-1](https://github.com/opencv/opencv/wiki/OE-1.-Old-C-API)

**Comment by kinchungwong** [comment]
/cc @alalek Re: https://github.com/opencv/opencv/issues/10246#issuecomment-350116500

> Possible solution here is FFI (https://en.wikipedia.org/wiki/Foreign_function_interface) bindings for C which should be able to emulate C++ features effectively.
> To implement this we must think about emulation of C++ exceptions in C, classes/methods/objects, etc, including some "runtime library" to support this.
> If you want strategic/political answer then you should ask

/cc @dkogan Re: https://github.com/opencv/opencv/issues/10246#issuecomment-350117100

>  Can you please update the docs, and at least the front webpage to not claim there's a C API anymore?

Dear Vadim, 

Please clarify whether a C-compatible FFI (foreign function interface) is within the scope of OE-1 or outside. Whether it is or not in OE-1, a C-compatible FFI needs to be on Evolution Proposals, because many open-source projects require the functionality of OpenCV. This issue also affects the relationship between OpenCV and the larger open-source community.

Some of them require OpenCV 1.x, but some of them may also require newer functionalities from 2.x or 3.x.

There may also be a need to ***either*** section off parts of [```core/cvdef.h```](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/cvdef.h) for C compilers, ***or*** to poison off the entire file for C compilers (so that it's clear it won't build).

**Comment by alalek** [comment]
This OE is about "OpenCV 1.x API" and about using of this API in other OpenCV parts.

C-compatible FFI is not covered here. Perhaps it would be another C-like API - at least internally (but compatibility headers/wrappers may be proposed).

**Comment by sturkmen72** [comment]
i think functions like [cvCanny](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/canny.cpp#L1124-L1132) can be cleaned up. i can work on this
