### ISSUE TITLE
OOB error in RandomForrest should care about sample weights. 

### ISSUE THREAD

**Issue by codingforfun** [opencv/opencv#11142]
I think there is an error in OOB error computation in case of training with sample weights. 
I don’t see weights taken into account anywhere in OOB error computation. 

https://github.com/opencv/opencv/blob/2dff9f4c6d1ae9982e253996fbdf6a289b108881/modules/ml/src/rtrees.cpp#L217-L221

Also the normalization of OOB error only uses number of samples. This should be the sample weight sum in case of weighted samples. 

https://github.com/opencv/opencv/blob/2dff9f4c6d1ae9982e253996fbdf6a289b108881/modules/ml/src/rtrees.cpp#L241

**Comment by JoseAF** [comment]
Somewhat related problem (possibly bug?)...

The OOB error is set to 0.0 and calculated only per tree, not per forest (i.e. no OOB error average gets calculated for all the trees). This means that at the end of the loop the OOB error that will be reported (and stored) will be either (1) 0.0 if OOB error was found to be < EPS for any (not all!) of the trees, or (2) the OOB error for the last tree that happened to be in the forest. 

Is this expected behavior?
