### ISSUE TITLE
Request to FIX OpenCv 2.4.13.6 cmake source

### ISSUE THREAD

**Issue by blaisexen** [opencv/opencv#11147]
[x] Request

Request to FIX OpenCv 2.4.13.6 cmake source to build OpenCv_World24136.DLL

minimum build x86 vc12,

because I can only build opencv_world with 3.x in vc14,vc15

**Comment by alalek** [comment]
> duplicate

Start from this label. opencv_world in 2.4 doesn't work since 2013.

> wontfix

Fixing of this problem requires serious refactoring of build scripts. This must be avoided because 2.4 branch in deep maintenance mode and critical bug fixes are accepted only. We don't want to break 2.4 builds.
This opencv_world build mode is optional - it doesn't provide/enable any new OpenCV functionality.

**Comment by blaisexen** [comment]
Ok,
I understand,
What version of OpenCv except from 3.x that can be made OpenCv_World? 2.3x or below 2013?
