### ISSUE TITLE
Build error with cmake configured on Win10 x64 OS

### ISSUE THREAD

**Issue by huzq85** [opencv/opencv#11343]
##### System information (version)

- OpenCV => The latest version of source code.
- Operating System / Platform => Win10 x64
- Compiler => Visual Studio

##### Detailed description

When trying to build opencv source code on Windows 10 with cmake, it will always show following error:
1>  '﻿setlocal' is not recognized as an internal or external command,
1>  operable program or batch file.

##### Steps to reproduce

1. To git clone the latest version of source code to local drive.
2. To open the cmake, and configure the build options for the source code with Visual Studio 2015.
3. After cmake configuration finish, then open Visual Studio 2015 and press F7 to build.
4. Error message will show in the output build panel in the VS IDE.

**Comment by alalek** [comment]
Provided error message is not enough to determine reason of the problem. Try to detect failed build target at least (check "output" view with full build log, avoid useless "errors" view).

Probably something like this: https://gitlab.kitware.com/cmake/cmake/issues/16824

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by huzq85** [comment]
hi,
I have attached related project files. 
[build_error_projs.zip](https://github.com/opencv/opencv/files/1929145/build_error_projs.zip)

**Comment by alalek** [comment]
I have similar project files on Windows systems with "setlocal" before "cmake" call. So I don't see wrong things here.

Verify that PATH / COMSPEC environment variables are not damaged on your system (and/or inside of MSVS/MSBuild processes).

**Comment by huzq85** [comment]
I checked the environment variables and the key ones should be fine compared with my other laptops. I even reinstall the Visual Studio, no good.
Finally, I reset the whole system and seems that this issue has gone. So, this issue should related with the system settings. This ticket can be closed now.
