### ISSUE TITLE
OpenCV failed with error C3861 when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [opencv/opencv#11355]
OpenCV failed with error C3861 when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**
1.git clone https://github.com/opencv/opencv D:\OpenCV\src
2.git clone https://github.com/opencv/opencv_extra D:\OpenCV\src\extra
3.open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\OpenCV\src
4.set CL=/permissive-
5.msbuild /p:Configuration=Release;Platform=Win32 build_x86\OpenCV.sln /t:Rebuild /m /p:BuildInParallel=true

**Error info:**
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(803): error C3861: 'CHECK_HR': identifier not found
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(860): note: see reference to class template instantiation '`anonymous-namespace'::CBaseAttributes<TBase>' being compiled
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(808): error C3861: 'CHECK_HR': identifier not found
d:\opencv\src\modules\videoio\src\cap_msmf.hpp(811): error C3861: 'CHECK_HR': identifier not found

**Comment by terfendail** [comment]
`CHECK_HR` macro is used in old `MediaSession`-based code for video processing. I'm going to replace it with `SourceReader`-based interface that won't use this macro. `CBaseAttributes` is used by `MediaSink` class that is part of `MediaSession`-based code for video processing for WinRT. I'm going to completely remove this code since video support for WinRT is implemented separately.

**Comment by alalek** [comment]
`CHECK_HR` macro is eliminated from OpenCV.
