### ISSUE TITLE
norm with NORM_HAMMING returns strange results

### ISSUE THREAD

**Issue by IdoWSC** [opencv/opencv#11426]
##### System information (version)

- OpenCV => 3.4.0
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2015

##### Detailed description

when using cv2.norm in python using NORM_HAMMING, the results are strange.
For instance the returned distance between 17 and 8 is 0, while clearly 17 = '00010001' and 8 = '00001000'
The real distance is 3.0

##### Steps to reproduce
    a = np.array([8], dtype=np.uint8)
    b = np.array([17], dtype=np.uint8)
    cv2.norm(a, b, cv2.NORM_HAMMING)
    0.0

**Comment by saskatchewancatch** [comment]
The problem is that the Python bindings call the version of `norm` that takes only one InputArray as an input.

You are expecting to call [this](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L691) but you end up calling [this](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core.hpp#L678). The call to the version you did not want to call somehow goes through and nonsense is returned.

According to [the doc on Python bindings](https://docs.opencv.org/master/df/da2/tutorial_py_table_of_contents_bindings.html), the way to get around this is to utilize the `CV_EXPORTS_AS` declaration.

I'm not super familiar with the Python bindings but I think one naive solution might be to do just what that doc suggests. Perhaps `CV_EXPORTS_AS(norm2) ......` in `core.hpp`?

**Comment by IdoWSC** [comment]
Hi  saskatchewancatch, Thx for replying.

> The problem is that the Python bindings call the version of norm that takes only one InputArray as an input.
> 
> You are expecting to call this but you end up calling this. The call to the version you did not want to call somehow goes through and nonsense is returned.

I'm not sure about this, I found out that when I use it with 2 arrays with shape[0] > 1 then norm behaves as expected.

**Comment by berak** [comment]
@saskatchewancatch the problem is only in python, and only with 1 element numpy arrays (because can be converted to a single number and back) so what it sees is like:

    cv2.norm(a, 17, [cv2.NORM_HAMMING])

17 == NORM_HAMMING2 | NORM_RELATIVE  (which ofc. returns nonsense results)
you could also try to reverse the argument order:

     cv2.norm( b, a, cv2.NORM_HAMMING )

(error: normType 8 not found)
do you have any real world data like that ? or was it just a test ?

**Comment by IdoWSC** [comment]
Hi Berak, Thanks for replaying.

> do you have any real world data like that ? or was it just a test ?

It was just a test.

I'll use your suggestion.

Thanks!
