### ISSUE TITLE
Better bring out info on contributing to docs + clarify search bars in new documentation

### ISSUE THREAD

**Issue by keikoro** [opencv/opencv#11423]
Hi there, it took me at least 15 minutes to find out how to contribute to the docs aka [this link](https://docs.opencv.org/master/d4/db1/tutorial_documentation.html) at the very end of the [How to contribute](https://github.com/opencv/opencv/wiki/How_to_contribute) page in the wiki.

Please add it to the repo's README or somewhere at the _top_ of the How To. Seeing as the How To talks about "enthusiastic coders" and "contributing code" right from the beginning, it's not obvious at all that _at the very end_, it does eventually contain a one-sentence reference to documentation...

The switch to a new documentation system is also confusing and not immediately obvious to newcomers to the project. Took me a while to figure out that the 2.4 Sphinx docs (which Google led me to, and which I meant to contribute to) are not part of this repo / meant to be updated (?). Finally, I thought the page I was looking at was gone in the new version (and hence the code) because there were no results for it when searching the new docs. Turns out there are two search bars, and only the less visible Google one at the top (not the one in the menu bar that says "Search") brings up the page.

**Comment by kerstin** [comment]
Additionally, for Mac users it'd be great if along with the links to download and install instructions, you could mentioned that Doxygen is available via Homebrew. I sadly can't open issues over at @doxygen to make them aware that that's missing from their own pages.

**Comment by alalek** [comment]
> about "enthusiastic coders" and "contributing code" right from the beginning

Documentation is a part of the same repository as regular C++ code. So contributors must know contribution basics, at least how to select base branch.

> Took me a while to figure out that the 2.4 Sphinx docs (which Google led me to, and which I meant to contribute to) are not part of this repo.

2.4 docs is still here. Just select 2.4 branch in the repository. Anyway, active development of 2.4 branch has been stopped 4+ years ago.

Do you want one click instead of two?
Perhaps, this will not be happen to avoid bloating of REAME links collection.


BTW, It is better to prepare proper patch via PR instead of writing long story of observed problems.

**Comment by kerstin** [comment]
> BTW, It is better to prepare proper patch via PR instead of writing long story of observed problems.

From your POV, sure. From mine, no. I want to know what (and who) I'm dealing with before digging into an OS project, especially if it's for undervalued contributions (which docs in general are) for a project I've been rarely using so far... This reads to me like you're not welcoming issues reported by users but are expecting everyone to be a dev / to jump right in. Ok.

**Comment by StevenPuttemans** [comment]
> especially if it's for undervalued contributions (which docs in general are)

Then you must have been using the wrong open source projects in my opinion. Good documentation is key to a thriving community and in my personal experience more important than adding the newest blingy line of code. Every single documentation-based commit I ever supplied to OpenCV has been highly appreciated.

> This reads to me like you're not welcoming issues reported by users but are expecting everyone to be a dev / to jump right in.

Seems a bit harsh no? He just states that it works faster through PR's seeing the amounts of less informative discussions at the issues tab. Simply providing a PR with a suggested change to make it more clear, would have drawn the devs directly to your issue.

**Comment by kerstin** [comment]
> Then you must have been using the wrong open source projects in my opinion. 

I feel very _lolsob_ about what you're implying here – about the OS software I use, and about my knowledge of "how OS projects work" in general, because we are actually in agreement about what makes a good OS community...

> Simply providing a PR with a suggested change to make it more clear, would have drawn the devs directly to your issue.

Please keep in mind that what's "simple" for you is not necessarily simple for someone else, and especially first-time contributors to a project. It's cool though that you can afford to submit PRs to all projects you use and think could use improvement.
