### ISSUE TITLE
About SSD PriorBox

### ISSUE THREAD

**Issue by zuoshaobo** [opencv/opencv#11484]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description
If we want to use intel inference engine in PriorBox layer, we should make the pbtxt file like this:
```yaml
node {
  name: "PriorBox_2"
  op: "PriorBox"
  input: "BoxPredictor_2/BoxEncodingPredictor/BiasAdd"
  input: "image_tensor"
  attr { key: "min_size" value { i: 100 } }
  attr { key: "max_size" value { i: 130 } }
  attr { key: "flip" value { b: true } }
  attr { key: "clip" value { b: false } }
  attr {
    key: "aspect_ratio"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
        }
        float_val: 2.0
        float_val: 3.0
      }
    }
  }
  attr {
    key: "variance"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 4
          }
        }
        float_val: 0.1
        float_val: 0.1
        float_val: 0.2
        float_val: 0.2
      }
    }
  }
}
```

But the tf_text_graph_ssd.py  script generate pbtxt like below:
```yaml
node {
  name: "PriorBox_2"
  op: "PriorBox"
  input: "BoxPredictor_2/BoxEncodingPredictor/BiasAdd"
  input: "image_tensor"
  attr { key: "flip" value { b: false } }
  attr { key: "clip" value { b: false } }
  attr {
    key: "width"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 6
          }
        }
        float_val: 150
        float_val: 171.026
        float_val: 212.132
        float_val: 106.066
        float_val: 259.808
        float_val: 86.6025
      }
    }
  }
  attr {
    key: "height"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 6
          }
        }
        float_val: 150
        float_val: 171.026
        float_val: 106.066
        float_val: 212.132
        float_val: 86.6025
        float_val: 259.808
      }
    }
  }
  attr {
    key: "variance"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 4
          }
        }
        float_val: 0.1
        float_val: 0.1
        float_val: 0.2
        float_val: 0.2
      }
    }
  }
}
```
the code https://github.com/opencv/opencv/blob/master/modules/dnn/src/layers/prior_box_layer.cpp#L274
```cpp
    virtual bool supportBackend(int backendId) CV_OVERRIDE
    {
        return backendId == DNN_BACKEND_DEFAULT ||
               backendId == DNN_BACKEND_INFERENCE_ENGINE && haveInfEngine() && !_explicitSizes;
    }
```
this pbtxt format generated by tf_text_graph_ssd.py will no longer support INFERENCE_ENGINE
So how to generate the pbtxt like the first format?

**Comment by zuoshaobo** [comment]
I know 3q

**Comment by dkurt** [comment]
@zuoshaobo,

> OpenCV => 3.1

OpenCV supports Inference Engine since 3.4.1 but not 3.1. 

> this pbtxt format generated by tf_text_graph_ssd.py will no longer support INFERENCE_ENGINE

All the layers which do not support this backend are computed using default implementation.

For now, all the SSD models work with Inference Engine backend. See some efficiency estimations at https://github.com/opencv/opencv/pull/10799, https://github.com/opencv/opencv/pull/10608, https://github.com/opencv/opencv/pull/10805.

However your question is correct and topical for non-CPU targets because it's better to run all the layers on the same device to prevent device->CPU->device data transfers. We could compute Caffe-like `min_size`, `max_size` and `aspect_ratio` from `width` and `height` however TensorFlow's anchors and Caffe's ones in different order so it causes wrong predictions (see http://answers.opencv.org/question/180105/tensorflow-custom-model-in-opencv/#post-id-183131 for details). That's why it's simpler to set explicit widths and heights of proposals.
