### ISSUE TITLE
unneeded cudaStreamSynchronize(stream_)

### ISSUE THREAD

**Issue by cyyever** [opencv/opencv#11511]
##### System information (version)

- OpenCV => git master branch 
- Operating System / Platform => ubuntu 18.04 64 Bit
- Compiler => gcc 7

##### Detailed description

StackAllocator::~StackAllocator() from opencv/modules/core/src/cuda_stream.cpp:

> 

    StackAllocator::~StackAllocator()
    {
        cudaStreamSynchronize(stream_);
        if (memStack_ != 0)
            memStack_->pool->returnMemStack(memStack_);
    }   

should be changed to 

> 
    StackAllocator::~StackAllocator()
    {
        if (memStack_ != 0) {
            cudaStreamSynchronize(stream_);
            memStack_->pool->returnMemStack(memStack_);
        }
    }   

or there is an unneeded cudaStreamSynchronize when we disable memory pool. 

##### Steps to reproduce
call cv::cuda::setBufferPoolUsage(false); before use cv::cuda::Stream.

**Comment by alalek** [comment]
Sounds reasonable.
/cc @nglee @tomoaki0705 Do you have any objectives?

**Comment by nglee** [comment]
@alalek Currently, the destructor of `StackAllocator` is called only when a `Stream` object is destructed. If the code remains as is, it will guarantee that every computation on that stream is finished when the `Stream` object is destroyed.

However, this guarantee might be unnecessary since the destructor of `Stream` calls [`cudaStreamDestroy`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1gfda584f1788ca983cb21c5f4d2033a62) which is designed to return immediately even if device is still doing work in the stream. So I won't object to changing the code as suggested.

**Comment by tomoaki0705** [comment]
I don't really have an opinion about this point.  No objection.
