### ISSUE TITLE
dnn.readNetFromDarknet() dosn't support "avgpool" layer

### ISSUE THREAD

**Issue by morozovsk** [opencv/opencv#11568]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => ubuntu 17.10
- Compiler => python

##### Detailed description

dnn.readNetFromDarknet() dosn't support "avgpool" layer

##### Steps to reproduce

`net = cv2.dnn.readNetFromDarknet('darknet.cfg', 'darknet.weights')`

result:
```OpenCV Error: Parsing error (Unknown layer type: avgpool) in ReadDarknetFromCfgFile, file /io/opencv/modules/dnn/src/darknet/darknet_io.cpp, line 503
Traceback (most recent call last):
  File "opencv_dnn_torch.py", line 15, in <module>
    net = cv2.dnn.readNetFromDarknet('darknet.cfg', 'darknet.weights')
cv2.error: /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:503: error: (-212) Unknown layer type: avgpool in function ReadDarknetFromCfgFile
```

I've tried 3 models from official site examples https://pjreddie.com/darknet/imagenet/
Each model uses 'avgpool' layer.

[darknet.cfg.txt](https://github.com/opencv/opencv/files/2027082/darknet.cfg.txt)

**Comment by dkurt** [comment]
@morozovsk, @berak, this PR https://github.com/opencv/opencv/pull/11766 adds support of average pooling layer from Darknet. Looks like it always works across all the spatial dimensions. There is `global_pooling` flag in Caffe for it:

https://github.com/BVLC/caffe/blob/2a1c552b66f026c7508d390b526f2495ed3be594/src/caffe/proto/caffe.proto#L936-L938

Unfortunately, ResNet-50 and ResNet-152 are not working for now because of `shortcut` (element-wise summation) which can work with non-equal shapes of inputs in Darknet.
