### ISSUE TITLE
adjust3rdMatrix not being used?

### ISSUE THREAD

**Issue by mdfirman** [opencv/opencv#11579]
`_imgpt1` and `_imgpt3` are optional inputs to `rectify3Collinear`. If provided, I believe they should be used to do a post-processing step in the function `adjust3rdMatrix`. If left empty, I believe that `adjust3rdMatrix` should not be called.

[Here](https://github.com/opencv/opencv/blob/e268fdc0ed89be11ce2e6d7a8832254fc4b67ccc/modules/calib3d/src/calibration.cpp#L3892) is the relevant code:

    if( !_imgpt1.empty() && _imgpt3.empty() )
        adjust3rdMatrix(_imgpt1, _imgpt3, _cameraMatrix1.getMat(), _distCoeffs1.getMat(),
                        _cameraMatrix3.getMat(), _distCoeffs3.getMat(), _Rmat1.getMat(), R3, P1, P3);

I think there is a bug here, and I believe it should read:

    if( !_imgpt1.empty() && !_imgpt3.empty() )

I'd be happy to open a PR if I can get some confirmation of this.

**Comment by alalek** [comment]
Sounds reasonable.
Feel free to prepare PR (to 3.4 branch, because it is bug fix).
Unfortunately there are no tests for this code ([coverage](http://pullrequest.opencv.org/buildbot/export/opencv_releases/3_4_coverage-lin64-debug/20180522-233730_38/coverage_html/opencv/modules/calib3d/src/calibration.cpp.gcov.html) of this file), so it would be great to add some test too.
There is [sample](https://github.com/opencv/opencv/blob/3.4.1/samples/cpp/3calibration.cpp) only (not sure about location of input data for this sample).
