### ISSUE TITLE
Can't cross compile w/ffmpeg since -I/usr/local/include always added

### ISSUE THREAD

**Issue by georgios-v** [opencv/opencv#11574]
##### System information (version)
- OpenCV => 3.4.0
- Operating System / Platform => Linux/Ubuntu 64bit
- Compiler => nvidia aarch64 gcc
- Target system => NVIDIA PX2

##### Detailed description

I cannot cross compile for aarch64 with FFMPEG. cmake fails the test:
```-- WARNING: Can't build ffmpeg test code```
That is because ```-I/usr/local/include``` is always added, regardless of properly using the NVIDIA toolchain. Thus the x86_64 headers fail the compilation.

The same configuration, builds, installs, and works fine, directly on the PX2. Nonetheless this is not a solution. NVIDIA advices against compiling directly on the PX2, plus I get the following warning:
```cc1plus: warning: <path-to>/opencv_ts_Release.gch: not used because `OPENCV_TRAITS_ENABLE_DEPRECATED' is defined [-Winvalid-pch]```

##### Steps to reproduce

On a host system with DriveInstall properly configured:
```
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DVIBRANTE_PDK:STRING=$VIBRANTE_PDK \
    -DCMAKE_TOOLCHAIN_FILE=/usr/local/driveworks-0.6/samples/cmake/Toolchain-V4L.cmake \
    -DCMAKE_INSTALL_PREFIX=./install \
    -DBUILD_PNG=ON \
    -DBUILD_TIFF=ON \
    -DBUILD_TBB=OFF \
    -DBUILD_JPEG=ON \
    -DBUILD_JASPER=ON \
    -DBUILD_ZLIB=ON \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_LIBV4L=ON \
    -DBUILD_FFMPEG=ON \
    -DBUILD_opencv_java=OFF \
    -DBUILD_opencv_python2=OFF \
    -DBUILD_opencv_python3=OFF \
    -DBUILD_TESTS=OFF \
    -DBUILD_PERF_TESTS=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DENABLE_NEON=ON \
    -DWITH_OPENCL=OFF \
    -DWITH_OPENMP=OFF \
    -DWITH_FFMPEG=ON \
    -DWITH_OPENGL=ON \
    -DWITH_LIBV4L=ON \
    -DWITH_GSTREAMER=OFF \
    -DWITH_GSTREAMER_0_10=OFF \
    -DWITH_CUDA=ON \
    -DWITH_GTK=ON \
    -DWITH_VTK=OFF \
    -DWITH_TBB=OFF \
    -DWITH_1394=OFF \
    -DWITH_OPENEXR=OFF \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
    -DCUDA_64_BIT_DEVICE_CODE=ON \
    -DCUDA_ARCH_BIN=6.2 \
    -DCUDA_ARCH_PTX="" \
    -DINSTALL_C_EXAMPLES=OFF \
    -DINSTALL_TESTS=OFF \
    -DVIBRANTE=TRUE \
    VERBOSE=1 \
    ..
```

**Comment by alalek** [comment]
We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

> That is because -I/usr/local/include is always added

I didn't see lines in OpenCV that directly do this.

Try starting from:
- uncomment line with `FATAL_ERROR` near "Can't build ffmpeg test code" message
- analyse of `cmake --trace` (or `--trace-expand`) to determine what line adds this.

Also please use the latest 3.4 branch - we don't amend already released code.

-----

> -Winvalid-pch

Try disabling precompiled headers (ENABLE_PRECOMPILED_HEADERS=OFF) in configurations with CUDA/GCC (there is no normal native support of PCH from the CMake side).
To speedup builds try using "ccache".
