### ISSUE TITLE
docs: calcHist() example code formatting is broken

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#11597]
Link: https://docs.opencv.org/3.4.1/d6/dc7/group__imgproc__hist.html#ga4b2b5fd75503ff9e6844cc4dcdaed35d

Screenshot:

![issue_calchist](https://user-images.githubusercontent.com/4981219/40580939-0141c58a-6154-11e8-9b11-41d586c340eb.png)

**Comment by catree** [comment]
Probably we should extract big snippet code into separate [code file](https://github.com/opencv/opencv/tree/3.4.1/samples/cpp/tutorial_code/snippets).

Other bad formatting code examples in `imgproc`:

- [HoughCircles()](https://docs.opencv.org/3.4.1/dd/d1a/group__imgproc__feature.html#ga47849c3be0d0406ad3ca45db65a25d2d)
- [HoughLinesP()](https://docs.opencv.org/3.4.1/dd/d1a/group__imgproc__feature.html#ga8618180a5948286384e3b7ca02f6feeb)
- [drawContours()](https://docs.opencv.org/3.4.1/d6/d6e/group__imgproc__draw.html#ga746c0625f1781f1ffc9056259103edbc)
- ...

Related #6938

Currently it will produce the snippet binaries as `example_tutorial_core_mat_checkVector` or `example_tutorial_core_merge`.
I think it would be better to prefix them with something like `snippet` instead of `tutorial`.
Each full example code with include and main should be extracted to separate files, small example code could be extracted into one example file with the name of the module (`example_snippet_core` or `example_snippet_core_various`, ...).
Big advantage: example code in the documentation will be compiled but it will increase the number of example binaries and the build time maybe?

**Comment by alalek** [comment]
The reason of incorrect formatting:
- Beautiful Soup (BS4) eliminates "unnecessary" indentation spaces during integration of Python symbol references.
