### ISSUE TITLE
remove unneeded check

### ISSUE THREAD

**Issue by cyyever** [opencv/opencv#11648]
##### System information (version)

- OpenCV => github master
- Operating System / Platform => ubuntu 1804
- Compiler => gcc 7

##### Detailed description

In  opencv/modules/core/include/opencv2/core/cvstd.inl.hpp:

> 

inline
String::String(const std::string& str)
    : cstr_(0), len_(0)
{
    if (!str.empty())
    {
        size_t len = str.size();
        if (len) memcpy(allocate(len), str.c_str(), len);
    }
}
the variable len can be removed.

> 
inline
String& String::operator = (const std::string& str)
{
    deallocate();
    if (!str.empty())
    {
        size_t len = str.size();
        if (len) memcpy(allocate(len), str.c_str(), len);
    }
    return *this;
}

same problem.
##### Steps to reproduce
see the code.

**Comment by alalek** [comment]
> allocate(len)

Really?

**Comment by alalek** [comment]
It was added in this commit: https://github.com/opencv/opencv/commit/71e188982553976997d3ee5ddd57180f04dbf718

because runtime sanitizers dislikes calling memcpy with zero length and generates.

My suggestion is to drop `if (!str.empty())` pre-check. Both `.empty()` and `.size()` has O(1) complexity.
