### ISSUE TITLE
OpenCV 3.4.1 + Windows 10 + VS 2017 ver 15.7.3 + CMake 3.11.3 + Cuda 9.2 = CMake FAIL

### ISSUE THREAD

**Issue by erichfrazer** [opencv/opencv#11731]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Windows 10, x64
- Compiler => Visual Studio 2017 ver 15.7.3
- CMake 3.11.3
- Cuda => 9.2

##### Detailed description

When load up CMake and point it to OpenCV 3.4.1, and tell it to delete cache then Configure, it barfs with this:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "opencv_cudev" in directory D:/opencv_341/source/modules/cudev
    linked by target "opencv_core" in directory D:/opencv_341/source/modules/core

earlier in the log, it says this:
  NVIDIA CUDA:                   YES (ver 9.2, CUFFT CUBLAS NVCUVID FAST_MATH)
    NVIDIA GPU arch:             30 35 37 50 52 60 61 70

Don't know what to suggest. You'd think this would be simple. I used to have the Cuda 9.1 SDK on it before today, but I removed it (all of it) and installed Cuda 9.2 SDK + the 1st patch.

**Comment by LaurentBerger** [comment]
@erichfrazer It seems you work at Microsoft. Please can you tell to VS team to send a big warning when there is an VS update and there is Nsight install in VS? warning =
 
**May be new VS is not compatible with your CUDA version.** 

There is a bug race between NVidia and microsoft when there is an update of VS or [cuda  ](https://devtalk.nvidia.com/default/topic/1022648/cuda-setup-and-installation/cuda-9-unsupported-visual-studio-version-error/1)

**Comment by JeffyOLOLO** [comment]
CUDA 9.2 [doesn't support (Table 2)](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#system-requirements) VS 15.7 yet :(
Recently I also failed to compile OpenCV #11652

**Comment by xsacha** [comment]
This issue keeps appearing regularly.
When a CUDA update comes out, it only supports an older version of MSVC -- not the latest.

**Comment by Iamthegeekdavid** [comment]
@Bleach665 , could you please provide a CMAKE log file of your successful X64 build OpenCV?
What does **_SP_** mean (CUDA-9.2 without sp)? 
Thanks,

David

**Comment by Bleach665** [comment]
Iamthegeekdavid, 
erichfrazer write
> I used to have the Cuda 9.1 SDK on it before today, but I removed it (all of it) and installed Cuda 9.2 SDK + the 1st patch.
I dont install it.
My Cmake log:
Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.14393.
Could NOT find PythonInterp: Found unsuitable version "2.7.15", but required is at least "3.4" (found C:/Lib/Python27/python.exe)
Could NOT find PythonInterp: Found unsuitable version "2.7.15", but required is at least "3.2" (found C:/Lib/Python27/python.exe)
AVX_512F is not supported by C++ compiler
AVX512_SKX is not supported by C++ compiler
Dispatch optimization AVX512_SKX is not available, skipped
libjpeg-turbo: VERSION = 1.5.3, BUILD = opencv-4.0.0-pre-libjpeg-turbo
Looking for Mfapi.h
Looking for Mfapi.h - found
found Intel IPP (ICV version): 2017.0.3 [2017.0.3]
at: C:/Lib/opencv/1111/3rdparty/ippicv/ippicv_win
found Intel IPP IW sources: 2017.0.3
at: C:/Lib/opencv/1111/3rdparty/ippicv/ippiw_win
CUDA detected: 9.2
CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-D_FORCE_INLINES
Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
Could NOT find BLAS (missing: BLAS_LIBRARIES) 
LAPACK requires BLAS
A library with LAPACK API not found. Please specify library location.
Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
Could NOT find Matlab (missing: MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
Found VTK 9.0.0 (C:/Lib/VTK/build_x64/lib/cmake/vtk-9.0/UseVTK.cmake)
Caffe:   NO
Protobuf:   NO
Glog:   NO
freetype2:   NO
harfbuzz:    NO
Module opencv_ovis disabled because OGRE3D was not found
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
Failed to find gflags - Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx512_skx.cpp
data: Download: face_landmark_model.dat
Tesseract:   NO
xfeatures2d/boostdesc: Download: boostdesc_bgm.i
xfeatures2d/boostdesc: Download: boostdesc_bgm_bi.i
xfeatures2d/boostdesc: Download: boostdesc_bgm_hd.i
xfeatures2d/boostdesc: Download: boostdesc_binboost_064.i
xfeatures2d/boostdesc: Download: boostdesc_binboost_128.i
xfeatures2d/boostdesc: Download: boostdesc_binboost_256.i
xfeatures2d/boostdesc: Download: boostdesc_lbgm.i
xfeatures2d/vgg: Download: vgg_generated_48.i
xfeatures2d/vgg: Download: vgg_generated_64.i
xfeatures2d/vgg: Download: vgg_generated_80.i
xfeatures2d/vgg: Download: vgg_generated_120.i

General configuration for OpenCV 4.0.0-pre =====================================
  Version control:               3.4.1-780-g387e92353

  Extra modules:
    Location (extra):            C:/Lib/opencv/source/opencv_contrib/modules
    Version control (extra):     3.4.1-113-g2231018c

  Platform:
    Timestamp:                   2018-06-22T07:06:17Z
    Host:                        Windows 10.0.14393 AMD64
    CMake:                       3.11.4
    CMake generator:             Visual Studio 15 2017 Win64
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe
    MSVC:                        1914

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (3 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe  (ver 19.14.26430.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP4   /MD /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi      /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP4   /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi        /MP4    /MD /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi        /MP4  /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          opengl32 glu32 cudart.lib nppc.lib nppial.lib nppicc.lib nppicom.lib nppidei.lib nppif.lib nppig.lib nppim.lib nppist.lib nppisu.lib nppitc.lib npps.lib cublas.lib cufft.lib -LIBPATH:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/lib/x64
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv datasets dnn dnn_objdetect dpm face features2d flann fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab viz xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    js world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj freetype hdf java matlab ovis python2 python3 sfm
    Applications:                tests perf_tests apps
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI: 
    QT:                          YES (ver 5.11.0)
      QT OpenGL support:         YES (Qt5::OpenGL 5.11.0)
    Win32 UI:                    YES
    OpenGL support:              YES (opengl32 glu32)
    VTK support:                 YES (ver 9.0.0)

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 1.5.3-62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.34)
    TIFF:                        build (ver 42 - 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES

  Video I/O:
    Video for Windows:           YES
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (ver 57.107.100)
      avformat:                  YES (ver 57.83.100)
      avutil:                    YES (ver 55.78.100)
      swscale:                   YES (ver 4.8.100)
      avresample:                YES (ver 3.7.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2017.0.3 [2017.0.3]
           at:                   C:/Lib/opencv/1111/3rdparty/ippicv/ippicv_win
    Intel IPP IW:                sources (2017.0.3)
              at:                C:/Lib/opencv/1111/3rdparty/ippicv/ippiw_win
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   YES (ver 9.2, CUFFT CUBLAS NVCUVID FAST_MATH)
    NVIDIA GPU arch:             30 35 37 50 52 60 61 70
    NVIDIA PTX archs:

  OpenCL:                        YES (no extra features)
    Include path:                C:/Lib/opencv/source/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            C:/Lib/Python27/python.exe

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Install to:                    C:/Lib/opencv/1111/install
-----------------------------------------------------------------

Configuring done

**Comment by Iamthegeekdavid** [comment]
@Bleach665 , 
OK. Install Cuda 9.2 without patch + VS2017(MSVC1914) + OpenCV 3.4.1. 

Previously, I had big trouble to install OpenCV +CUDA. All kinds of errors occurred even I switched various versions of MSVS and CUDA. My OS and other environments are similar to yours. I may follow your example. Thanks for the information. 

David

**Comment by jo143** [comment]
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
SSE3 is not supported by C++ compiler
SSSE3 is not supported by C++ compiler
SSE4_1 is not supported by C++ compiler
POPCNT is not supported by C++ compiler
SSE4_2 is not supported by C++ compiler
FP16 is not supported by C++ compiler
AVX is not supported by C++ compiler
Dispatch optimization SSE4_1 is not available, skipped
Dispatch optimization SSE4_2 is not available, skipped
Dispatch optimization AVX is not available, skipped
Dispatch optimization FP16 is not available, skipped
CMake Error at cmake/OpenCVCompilerOptimizations.cmake:524 (message):
  Compiler doesn't support baseline optimization flags: /arch:SSE /arch:SSE2
Call Stack (most recent call first):
  cmake/OpenCVCompilerOptions.cmake:270 (ocv_compiler_optimization_options)
  CMakeLists.txt:688 (include)


Configuring incomplete, errors occurred!
See also "F:/cmske/CMakeFiles/CMakeOutput.log".
See also "F:/cmske/CMakeFiles/CMakeError.log".


I am face this kind of error while install the openCV at my system can  any one solution at this error
[CMakeError.log](https://github.com/opencv/opencv/files/2705930/CMakeError.log)
[CMakeOutput.log](https://github.com/opencv/opencv/files/2705931/CMakeOutput.log)

**Comment by alalek** [comment]
@jo143 You using MSVS ARM compiler. How is this related to original problem with CUDA?

There is no "default" support for ARM MSVS compiler in OpenCV build scripts. Probably you need additional CMake flags/options (can't help here, we don't support/test this configuration).

---

Off-topic comments will be removed.
