### ISSUE TITLE
I want to help with documentation

### ISSUE THREAD

**Issue by mannyglover** [opencv/opencv#11758]
I come across documentation like this: https://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html , and I find it very helpful, but I have enough of a relevant background and a mastery of English to where I could in many instances make things more clear, correct/improve grammar, etc.  Does this OpenCV github maintain extensive documentation?  I cloned the repository, and I know there is some documentation, but I couldn't find a ton.

Thank you.

**Comment by alalek** [comment]
Documentation fixes / improvements are very appreciated!

> 3.0-beta

This is very old documentation drop (from 2014) based on Sphinx engine with .rst files - it was deprecated.

Documentation for modern OpenCV is generated by doxygen tool from C++ headers and from `.markdown` files. We using MathJax to show formulas.
Take a look on [OpenCV 3.4 documentation](https://docs.opencv.org/3.4/).

Mentioned page is migrated into [description](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#details) of `calib3d` module. Sources are [here](https://github.com/opencv/opencv/blob/3.4.1/modules/calib3d/include/opencv2/calib3d.hpp#L54).

There are also [separate tutorials for this module](https://docs.opencv.org/3.4/d6/d55/tutorial_table_of_content_calib3d.html) ([sources](https://github.com/opencv/opencv/tree/3.4.1/doc/tutorials/calib3d)).

Please refer to existed "documentation" [patches](https://github.com/opencv/opencv/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22category%3A+documentation%22).

Please note, that we don't amend already released documentation (like 3.0.0 or 3.4.1), it is possible to improve it for next upcoming maintenance releases only (like next 3.4.2).
Repository contains "master" branch - it is for next major release. So it is better to prepare improvements of current documentation into "3.4" branch instead of "master" (these patches will be propagated into "master" branch automatically - we do "merge 3.4" weekly/bi-weekly).

**Comment by mannyglover** [comment]
Thanks!
