### ISSUE TITLE
cv2.fillPoly outputs different color

### ISSUE THREAD

**Issue by jh0w3l05** [opencv/opencv#11801]
ISSUE:
cv2.fillPoly outputs different color than what is expected.

Screenshot:
<Right> PyQt5 Application View | <left> Saved Image using cv2.fillPoly
![cv2 fillpoly_issue](https://user-images.githubusercontent.com/40228894/41702900-2d9f5f58-7521-11e8-9e6c-fc2b549a166b.png)
RGB Value: 255, 255, 153

##### System information (version)
- Anaconda 4.5.4
- Python 3.6.5
- PyQt 5.9.2
- OpenCV 3.3.1
- OS Windows 10 64 Bit

##### Detailed description
I am creating an application using PyQt5 with shapes filled with color. When I am viewing it on the application, it is OK. Then I am adding a feature that the shapes drawn in the application be save in an image format. But when I saved that image using cv2.fillPoly() the color that was saved is different.

##### Steps to reproduce
Color setup:
In PyQt:
QtGui.QColor(255 ,255, 153, 255)

In cv2.fillCollor:
cv2.fillPoly(img, [_pts], (255,255,153)

**Comment by berak** [comment]
@jh0w3l05 , that's not an opencv bug, but a misconception in your program.

opencv uses bgr pixel order, qtgui uses rgb, thus your colors are reversed.

use : `cv2.imshow("poly", img); cv2.waitKey()`
or, if you still want to use qtgui, convert the order, like: `img cv2.cvtColor(img, cv2.COLOR_BGR2RGB)`

also please kindly close this issue (since it is invalid)

**Comment by alalek** [comment]
Most part of OpenCV functions uses BGR order for colors.

**Comment by jh0w3l05** [comment]
Thanks for the fast response. This is noted.
