### ISSUE TITLE
opencv otsu binarization not working

### ISSUE THREAD

**Issue by anupb08** [opencv/opencv#11824]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Ubuntu 16.04
- Compiler => python 3.5

##### Detailed description

I tried to apply opencv OTSU binarization on the following image, but it generates a black image. 
![test_otsu](https://user-images.githubusercontent.com/14246635/41848080-e08566be-7899-11e8-814a-c3afc0f3d20e.png)

Here is the following python code:
`import cv2

image = cv2.imread('test_otsu.png', 0)
ret, thresh = cv2.threshold(image, 0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
cv2.imwrite('temp.png', thresh)`

**Comment by terfendail** [comment]
Your image(at least the one attached) contains white border. Difference between values on the border and other values is essentially greater than difference between values of meaningful part of the image. So for this image histogram have two peaks at 255 and near 155 and OTSU estimated threshold at 159 which is greater than any value at meaningful part of the image.
In order to get the expected result white border should be removed prior to thresholding

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
