### ISSUE TITLE
opencv knn train dead loop

### ISSUE THREAD

**Issue by Jayhello** [opencv/opencv#11877]
##### System information (version)

- OpenCV: 3.3
- Operating System / Platform: ubuntu16
- Compiler: cmake & gcc5.4

##### Detailed description

opencv knn: dead loop

##### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>
#include <opencv2/ml.hpp>
#include <vector>
#include "opencv2/core/core_c.h"

using namespace std;
using namespace cv;
using namespace cv::ml;

using cv::Ptr;

int main(){

    Mat xTrainData = (Mat_<float>(5,2) << 1, 1, 1, 1, 2, 2, 2, 2, 2, 2);
    Mat yTrainLabels = (Mat_<float>(5,1) << 1, 1, 2, 2, 2);

    cout << "===============xTrainData===================="<< endl;
    cout << "xTrainData: "  << xTrainData<< endl;

    cout << "===============yTrainLabels===================="<< endl;
    cout << "yTrainLabels: "  << yTrainLabels << endl;

    // KNearest KDTree implementation
    Ptr<KNearest> knnKdt = KNearest::create();
    knnKdt->setAlgorithmType(KNearest::KDTREE);
    knnKdt->setIsClassifier(true);

   // When runs to this step, it does not run any more.
    knnKdt->train(xTrainData, ml::ROW_SAMPLE, yTrainLabels);

    float d_test[2][2] = {{1.3, 1.3}, {2.2, 2.4}};

    Mat xTestData = (Mat_<float>(2,1) << 1.1, 1.1, 2, 2.2);
    Mat zBestLabels;
    cout << "===============xTestData===================="<< endl;
    cout << "xTestData: "  << xTestData << endl;

    knnKdt->findNearest(xTestData, 1, zBestLabels);
    cout << "===============zBestLabels===================="<< endl;
    cout << "zBestLabels: "  << zBestLabels << endl;
}

```

When I runs it in clion:

![image](https://user-images.githubusercontent.com/16144935/42207391-61e4a88a-7edc-11e8-8eb9-7338ae273342.png)

What's wrong?

**Comment by berak** [comment]
related: https://github.com/opencv/opencv/issues/8917

i could reproduce it with latest 3.4. 
the KDTREE implementation seems to have a problem with duplicate (identical) train samples, 
like having (2,2) more than once in it. it works with train data like this:

        Mat xTrainData = (Mat_<float>(5,2) << 1, 1.1, 1.1, 1, 2, 2, 2.1, 2, 2.1, 2);

btw, you did not get that far, but it should be: 

       Mat xTestData = (Mat_<float>(2,2) << 1.1, 1.1, 2, 2.2);

in your sample.

**Comment by Jayhello** [comment]
And for the same datasets, when I use `kd tree method` like `knn->setAlgorithmType(KNearest::KDTREE);`.It gets error result, bu if I just use `BRUTE_FORCE` method it gets correct result.

So can I think the `kd tree` methods in opencv3 has bug?

**Comment by berak** [comment]
>  when I use kd tree method like knn->setAlgorithmType(KNearest::KDTREE);.It gets error result

same here. all `results` , `neighborResponses` , `dist` outputarrays seem to point to uninitialized memory, when using the KDTREE implementation.

there is a [unit test here](https://github.com/opencv/opencv/blob/master/modules/ml/test/test_emknearestkmeans.cpp#L295) , but unfortunately it is cheating, `bestLabels` are reused after the brute force test (L317). if we clear it like `bestLabels.release();` before the kdtree test, it will only contain garbage, too (and fail !), same as in your experiment above.
```
(bestLabels, neighbours, dist) :
-------------BFORCE---------------------------
[1;
 2]
[1, 1, 2;
 2, 2, 2]
[0.010000004, 0.010000004, 1.6199999;
 0.020000011, 0.040000018, 0.049999997]
-------------KDTREE---------------------------
[0;
 0]
[1, 1, 1;
 1, 1, 0]
[0, 0, 9.7048882e-035;
 3.8723429e-034, 0, 0]
```

**Comment by berak** [comment]
a couple of problems here:

* the KDTree does not do a supervised classification / regression, but unsupervised clustering.
  it's learning to assign cluster(nearest neighbour) indices to samples.
  the train responses are never used (never make it into the tree building)
* whatever is calculated inside the KDTree, it never makes it back into KDTreeImpl or KNearest. 
  the preallocated (CV_32F) OutputArrays are reallocated inside KDTree::findNearest:
```
Mat R; // expected result

// entering KNearest::findNearest 
OutputArray _results(R); 
_results.create(testcount, k, CV_32F);
Mat   res = _results.getMat();
Mat _res = res.row(i); // shallow copy (different Mat header, also a slice only)

// entering KDTree::findNearest()
OutputArray _labels(_res); 
_labels.create(nidx, 1, CV_32S, -1, true); // _results above no more point to the same thing
```
could be overcome by a strategy like this:

            Mat _res, _nr, _d; // use empty Mat's
            tr.findNearest(test_samples.row(i), k, Emax, _res, _nr, _d, noArray());
            // now copy, convert to our preallocated CV_32F Mat's from KNearest

* ` tr.findNearest(test_samples.row(i), k, Emax, _res, _nr, _d, noArray());`
  this wrongly assigns _neighborsIdx to _res, not _labels. (however, there's no difference, since the KDTree does not know about any class labels)
* from the docs: " In case of regression, the predicted result is a mean value of the particular vector's neighbor responses. In case of classification, the class is determined by voting."  -- it does not do any of this currently.
* again, the unit test reuses the result from the bruteforce check, and happily reports 100% accuracy
