### ISSUE TITLE
the latest release opencv3.4.2 can not used on windows7

### ISSUE THREAD

**Issue by shengxingdong** [opencv/opencv#12010]
the installed opencv_world342.dll need "Api-ms-win-downlevel-shlwapi-l1-1-0.dll" which is not in Windows 7. (vc2015_redist.exe already installed).

when I copy it from windows10, it works.

**Comment by yanchao12122** [comment]
just rebuild opencv in win7 is okay

**Comment by hglee** [comment]
Install platform update (KB2670838) : https://www.microsoft.com/en-nz/download/details.aspx?id=36805

It has that file. 

See file information in next link : https://support.microsoft.com/en-us/help/2670838/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1

**Comment by liudonghua123** [comment]
I have the same problem, and I use `dumpbin.exe C:\Anaconda3\Lib\site-packages\cv2\cv2.cp35-win_amd64.pyd /IMPORTS | grep dll` to find the required dlls and use `where <dll_file>` to search and found that `opencv api-ms-win-downlevel-shlwapi-l1-1-0.dll` is missing, then I googled and found that I need to install a update patcher(Platform Update for Windows 7, https://www.microsoft.com/en-nz/download/details.aspx?id=36805), then finally it worked.

see https://github.com/skvark/opencv-python/issues/36

**Comment by haozhao71** [comment]
> //support.microsoft.com/en-us/help/2670838/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1

thank you!

**Comment by ThadHouse** [comment]
Looking around, the issue is happening because an explicit link to `Shlwapi.lib` is not included in https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_msmf.cpp

I'm currently building to test, but it seems like adding `#pragma comment(lib, "Shlwapi.lib")` to that file seems to fix it. If it does, I'll PR the fix, and hopefully it can get backported to 3.4
