### ISSUE TITLE
Mat::at invokes undefined behavior

### ISSUE THREAD

**Issue by cc143** [opencv/opencv#12140]
The `Mat::at` methods dereference a pointer created by casting the underlying `uchar*` pointer to an element type pointer `_Tp*`. For example, see:
https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/mat.inl.hpp#L1089

This violates the C++ standard: it is an invalid use of type punning. There's a good explanation of strict aliasing and type punning in C and C++ here:
https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8

So far, as far as I know, this hasn't caused a problem in practice. However, a future compiler optimization may introduce bugs.

OpenCV ought to use the only standards-compliant way of type punning: `std::memcpy`. In practice, this would not result in less efficient code.

**Comment by kinchungwong** [comment]
### Call For Public Input

It will be deeply appreciated by the OpenCV community if one or several of these can be made available:

1. An annotated analysis of the source code in question, and the relevant sections in the C++ standard
2. Opportunities for connecting and collaborating with experts in the C++ standard to assist in such analysis
3. A piece of code (involving the caller's code and the OpenCV source code) that demonstrates the 
    problem, along with the relevant C++ compiler vendor and version
4. A C++ compiler farm, or a C++ static analysis farm, for exploring potential strict-aliasing issues.

### Present situation - Question 1

Is it possible for an OpenCV C++ user to trigger strict-aliasing violation that involve the use of the "cv::Mat::at" method?
	
Answer: Yes. However, the burden of preventing this issue is on the OpenCV C++ user.

See this link for a code example. 

*Note: this code example uses a mock version of the "Mat" class. As a result, it does not fully reproduce all behaviors of the OpenCV C++ API, and conclusions drawn from this code example might not necessarily apply to the OepnCV C++ API.*

https://gist.github.com/kinchungwong/e2e87beef0f6230dd22574e411a436b9

### Present situation - Question 2

Does OpenCV internally contains matrix-element-accessing code that violates strict-aliasing rules?

Answer: Presently there is insufficient information on this issue. It is ***likely*** that such code exists within OpenCV C++ code base, outside the scope specified below (of "cv::Mat" and "cv::Mat_" classes).

(See above: call for public input, items 3 and 4.)
(See below: personal opinion, section 2, automated unit testing as a safety net.)

### Personal opinion

The reasons why the more proactive approach of applying the code change is not being taken:

##### 1

Despite your claim, my current opinion is that the source code within the question scope (see disclaimer on scope, below) do not actually violate strict-aliasing rules, assuming that the users of OpenCV C++ library adhere to the recommended user code guidelines established for OpenCV C++ users.

##### Disclaimer on scope

This personal opinion only focus on the code that is in "the OpenCV Core module", files "mat.hpp", "mat.inl.hpp", "matrix.cpp", "matrix_operations.cpp", and so on.
	
It is quite possible that other OpenCV modules (including those commonly distributed along with the OpenCV Core module, such as "imgproc") might contain violations of strict-aliasing rules.
	
(See above: call for public input, items 3 and 4.)

##### 1.1 	

Strict-aliasing rules are violated if reads from and writes to objects are performed through incompatible types (casually speaking). 
	
For discussion purpose, an abridged description of the strict-aliasing rules is available online at:
https://en.cppreference.com/w/cpp/language/reinterpret_cast

##### 1.2	

However, OpenCV requires C++ users to use the template argument "_Tp" consistently with each instance of "cv::Mat" or "cv::Mat_<_Tp>".

##### 1.2.1	

For "cv::Mat", the burden is on C++ users to make sure their use of "_Tp" is consistent with how the matrix is allocated (the OpenCV matrix type code).

##### 1.2.2

For "cv::Mat_<_Tp>", the burden is on C++ users to make sure the template argument "_Tp" on the matrix handle is consistent with how the matrix is allocated, when the matrix handle is converted from "cv::Mat" to "cv::Mat_<_Tp>".

##### 1.3	

In both cases, the C++ user must keep using the same template argument "_Tp" for an instance of a matrix. Therefore, all reads from and writes to the elements of that matrix will be performed with the same type "_Tp". For this reason, reads and writes are not being performed through incompatible types. Therefore, strict-aliasing rules are not being violated.

##### 1.4

For multi-channel matrices, OpenCV provides C++ users with a convenience template "cv::Vec < typename _Tp, int cn >". As far as strict-aliasing adherence is concerned, should a C++ user make use of this convenience template, one should ensure such usage is consistent with how the matrix is allocated.
	
It should be pointed out that accesses via the fields or array members of a struct are tagged according to the struct. Thus, it would not be safe to use both "cv::Vec<_Tp, cn>" and a different user-defined channel-accessing structs on the same instance of a matrix.
	
##### 1.5

If the C++ user uses a combination of methods other than "cv::Mat::ptr" and "cv::Mat::at" to access the matrix elements, it would be up to the C++ users to ensure their use of aliased types do not violate strict-aliasing rules.

In addition to the status quo, which depends on C++ users, OpenCV has one layer of safety net to ensure that the library's source code will not be implicated in a future violation of strict-aliasing rules.
	
##### 2

OpenCV runs automated unit tests on multiple compilers and target architectures upon each pull-request. For generated code which are shared among different functionalities, any malfunctioning will be easy to discover.

##### 3

To the extent that the current coverage might not be comprehensive enough to catch violations of strict-aliasing rule, test cases can be added with the help of C++ standards experts. 

(See above: call for public input - experts on C++ standards.)

Currently, OpenCV performs C++ static analysis on its code base on an ad-hoc basis. This is because such static analysis are made possible courtesy of tool vendors and donors. As such, currently it is not possible as part of the automated pull-request handling.

**Comment by kinchungwong** [comment]
### Short response

The code in question is not an example of "type-punning". In typical usage, if a matrix is allocated with an element type other than `uchar`, then there should not be memory operations that attempt to access the underlying memory as if it were a `uchar`.

The class in question merely performs address calculations that involve temporarily converting pointers into `uchar*` and then converting back to `_Tp*` afterwards. The behaviors for such conversions (absent memory accesses) are well-defined.

**Comment by cc143** [comment]
> ...it is the C++ user's responsibility to make sure each matrix instance is only accessed using a type that is consistent with how the matrix is allocated.

But many `Mat` methods allocate the matrix for the user. It looks to me like matrices are typically allocated using [fastMalloc](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/core/src/alloc.cpp#L59), e.g. `StdMatAllocator::allocate` uses this. In that case, the data is allocated as an array of `uchar`.

The data will be aligned correctly - because `fastMalloc` ensures that it will be aligned to `CV_MALLOC_ALIGN` bytes - but the dynamic type of the allocated objects is still `uchar`.


> The class in question merely performs address calculations that involve temporarily converting pointers into `uchar*` and then converting back to `_Tp*` afterwards.

If I create a matrix by calling `Mat::Mat(int rows, int cols, int type)` then the data will be allocated as `uchar`.

**Comment by kinchungwong** [comment]
@cc143 

The C++ Standard allows the use of `uchar` in this way, as long as alignment issues are taken care of.

Specifically, the C++ Standard allows the underlying allocation to be performed with `char`, `unsigned char`, or `std::byte`. This is allowed because custom allocators (or placement new operators) cannot be implemented unless the Standard allows for such usage. Moreover, the use of `memcpy` on trivially-copyable types also depend on such usage.

----

By using [the code sample I have provided](https://gist.github.com/kinchungwong/e2e87beef0f6230dd22574e411a436b9), you can experiment with the effect of strict aliasing issues when a type other than a character type (such as `unsigned char`) is involved. By commenting and uncommenting the lines of code in the "main" function, and compiling with optimization "-O3", one can reproduce the behavior in which the compiler determines a potential aliasing is ruled out where in fact the aliasing has occurred, triggering an undefined behavior.

----

On the Gist page you linked, written by Shafik Yaghmour, there is a section titled ["Subtle Differences"](https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8#subtle-differences) and also a further link to [a Stack Overflow post](https://stackoverflow.com/questions/30114397/constructing-a-trivially-copyable-object-with-memcpy) in which the same author have written an answer. The summary of that information is that, in C++, the Standard contains an ambiguity about the nature of object lifetime when `memcpy` is used - specifically, the precise time when the object lifetime begins, and also on the characterization of that "beginning" as "assignment", "copy", or something else. The author proposes a clarification that is yet to be accepted into the C++ Standard. Within that clarification, the situation of `memcpy` is categorized as being that of "initialization".

----

On that Gist page, there is a short code snippet with the following wording:

> Neither of these methods is sufficient in C++ which requires placement new: 
> ...

The word "requires" is true for to objects which are not trivial. Trivial objects are those which are trivially copyable and which the default constructor is also trivial. For trivial objects, `memcpy` and `memmove` are sufficient for initialization.

----

In OpenCV, the typedef of `uchar` to `unsigned char` is declared at  https://github.com/opencv/opencv/blob/10ae0c4364ecf1bebf3a80f7a6570142e4da7632/modules/core/include/opencv2/core/hal/interface.h#L51

The Gist page written by Shafik Yaghmour does contain a cautionary remark that the Standard doesn't require the aforementioned accommodations for `std::uint8_t` or `std::int8_t`. In other words, it might be ill-advised to use `std::uint8_t` or `std::int8_t` as underlying memory allocation type for other data types, nor would it be safe to typedef `uchar` as `std::uint8_t`. Instead, `uchar` has to be typedef'd as `unsigned char`, always.

**Comment by cc143** [comment]
Sorry, I don't understand your logic. You say this:

> The C++ Standard allows the use of `uchar` in this way, as long as alignment issues are taken care of.

But then you say this:

>> Neither of these methods is sufficient in C++ which requires placement new:
>>...
>
> The word "requires" is true for to objects which are not trivial. Trivial objects are those which are trivially copyable and which the default constructor is also trivial. For trivial objects, `memcpy` and `memmove` are sufficient for initialization.

OpenCV is not using placement new, `memcpy` or `memmove`. That's the problem.

I am suggesting that OpenCV should change to use `memcpy` because OpenCV's current use of `uchar` is not allowed by the C++ Standard.

**Comment by mshabunin** [comment]
@cc143 , what will the following method look like?
```.cpp
template<typename _Tp> inline
_Tp& Mat::at(int i0, int i1)
{
    return ((_Tp*)(data + step.p[0] * i0))[i1];
}
```

**Comment by cc143** [comment]
@mshabunin - If you want to return a mutable reference to a `_Tp`, then you need to initialize a `_Tp`. Could you use placement new when the matrix is created?

**Comment by alalek** [comment]
`cv::Mat` can be used with scalars only which don't require ctor/dtor calls.
