### ISSUE TITLE
Decolor, grad_system function has a crash

### ISSUE THREAD

**Issue by drspam1991** [opencv/opencv#12167]
https://github.com/opencv/opencv/blob/9e1b1e5389237c2b9f6c7b9d7715d9836c0a5de1/modules/photo/src/contrast_preserve.hpp#L70

The first argument changed to 'const' in 3.4.1 release, and it makes crash in resize() function (line 258).

**Comment by alalek** [comment]
Crash or C++ exception?

Related #12165

**Comment by drspam1991** [comment]
Actually its a C++ exception.

**Comment by berak** [comment]
testcode:

     Mat dec, boost, img = imread("text.bmp");
     decolor(img, dec, boost);

with const:

    OpenCV(3.4.2-dev) Error: Assertion failed (!fixedSize() || ((Mat*)obj)->size.operator()() == _sz) in create, file C:\p\opencv\modules\core\src\matrix_wrap.cpp, line 1185
(we cannot resize a const Mat)

with const removed, it crashes [here](https://github.com/opencv/opencv/blob/9e1b1e5389237c2b9f6c7b9d7715d9836c0a5de1/modules/photo/src/contrast_preserve.cpp#L171)

    OpenCV(3.4.2-dev) Error: Assertion failed (mv[i].size == mv[0].size && mv[i].depth() == depth) in merge, file C:\p\opencv\modules\core\src\merge.cpp, line 458
(because the `lab` channels have the original size, and `dst` got resized to something smaller.)


so, removing the `const` is not a good solution, it rather should work with a new Mat header for the resize(), instead of trying it in-place.

i somewhat wonder, how the [test](https://github.com/opencv/opencv/blob/9e1b1e5389237c2b9f6c7b9d7715d9836c0a5de1/modules/photo/test/test_decolor.cpp#L57) can pass, currently.

**Comment by gdemarcq** [comment]
I think that you must pass by value as it was the case before.

**Comment by alalek** [comment]
Looks like original "const Mat&" should preserve "read-only" semantic.
Perhaps resize and next processing should be performed into some temporary array (or cv::Mat header).
