### ISSUE TITLE
OpenVino inference engine legal concerns/inclusion discussion?

### ISSUE THREAD

**Issue by TechnikEmpire** [opencv/opencv#12198]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Any
- Compiler => Any
##### Detailed description

Is there any developer discussion about not only including OpenVino's inference engine, but making it the default back-end when it is included? I went to enable this back end and ended up swimming in legal documents using scary terms about patent rights and such. So, I'm trying to figure out where the developer discussion about this took place to maybe help me understand the legal implications of leaning on apparently proprietary and patent-encumbered dependencies.

I wasn't sure whether to discuss this here or on the answer site, but just in case, I've opened the same discussion [there as well](http://answers.opencv.org/question/197273/license-discussion-around-including-intel-reference-engine/).

Please feel free to close this out if the answers site is the better site.

##### Steps to reproduce

 - Try to enable Intel inference engine.
 - Start a gofundme to go back to school for the next decade to become a lawyer in order to determine how much of your soul the engine requires, how many of your descendants it includes, or if you'll be filing for bankruptcy soon.

**Comment by alalek** [comment]
At first, it is better to contact with your own layer.

From technical side, OpenVINO dependency is optional and disabled in default builds (so there are no such questions by default).

You need proper OpenVINO installation:
- during OpenCV build step
- during running of OpenCV-based apps
So you need to agree with OpenVINO license in **both cases**.

**Comment by TechnikEmpire** [comment]
Its unfortunate that there's so much cautionary documentation about ffmpeg and friends but not such a word about this. But I guess it makes sense since it's Intel that you're agreeing to in this case.

**Comment by ebachard** [comment]
+1 for @TechnikEmpire : I'm not english fluent, so it's difficult for me to understand everything around legal in the Intel documents, but I share @TechnikEmpire feeling, and I completely agree with his request. 

FYI, I myself wanted to use Intel software with my students, when I discovered the legal nightmare Intel introduces when using such resources. The project has been canceled, and we use other solutions (OpenCV is still in the list, of course).

For OpenCV credibility, Intel Vino engine shouldn't be included nor associated to OpenCV image. Maybe as "contrib, but I'm not completely sure.

My 2 cents

-- 
ericb

**Comment by vpisarev** [comment]
1. Inference Engine from OpenVINO is not complied in nor supplied with OpenCV by default. You need to apply special effort to download it and enable. 
2. If you download OpenVINO from Intel site, there is be special build of OpenCV as a part of OpenVINO, and it comes with Inference Engine support compiled in and enabled by default. *By default* is not the same as *the only available*, i.e. you can still switch to our C++ or OpenCL implementation from OpenCV. Again, it's solely your decision to download and install it. You do not have to do it if you have any doubts.
3. OpenVINO acts as OpenCV DNN accelerator; it does not add any new functionality. Any topology that you can run using Infererence engine backend you can also run without using Inference Engine. In OpenCV we have a big chunk of tests to check DNN correctness in both modes - when it uses IE and when it does not.
4. The whole purpose of making Inference Engine the default backend *when* it's included into the build is to get automatic acceleration of DL inference without having to modify the source code. Sometimes you get 20% acceleration, sometimes you get 3x acceleration. Not bad for a piece of proprietary software.
5. Inference Engine is only enabled on x64 arch. When you build OpenCV for ARM, MIPS, PowerPC, OpenRISC etc. there is no Inference Engine there and consequently it's not enabled.
6. Just in case you are not aware of it, but for a few years already OpenCV is built *by default* with another proprietary closed-source library from Intel, Integrated Performance Primitives library, which is used *by default* to accelerate image processing operations. And yes, you can disable it as well if you have any doubts.
7. Forbes states that Intel has promised to release OpenVINO open-source, and hopefully that will happen soon.
8. If you can provide absolutely free and open-source backend that will beat Inference Engine on the popular topologies, we will gladly add support for it and make the default backend in OpenCV DNN.

I think, the discussion can be closed now, since it does not look quite constructive.

**Comment by TechnikEmpire** [comment]
@vpisarev I hope that Intel really does release it as open source. I was aware of everything you wrote except this point.

I realize that it is great software. I tried it, I used it, I got amazing results with a project of mine. Then I moved it to an AMD processor to test and of course it completely failed to operate. I realize this isn't any different from CUDA acceleration but I'm pretty sure that the same issues were contributing factors in not using CUDA as a DNN backend, so why does Intel get special treatment in this regard?

It's precisely the fact that OpenVino gives such a great boost to performance that I'm concerned, because it will draw in more work to integrate it further and focus on it further, and then proprietary software will self-propagate because it is so necessary to get great performance.

Anyway I'm sorry that you find points such as the inf engine being completely non-functional on non-Intel hardware to be non-constructive. That sort of makes my case here better than anything I could say - corporate interest appears to deem that failure outside of a specific company's hardware is not worth discussing.

I've already started writing in a new back end for my own purposes that is fully free and open source. It's not difficult. 99% of the poor performance can be found in the convolution layer implementation. Speed that up and you can smoke even the inference engine's performance on the CPU.

P.S. It's typically good manners to disclose one's conflicts of interest.

![image](https://user-images.githubusercontent.com/11234763/44042463-55c94808-9eee-11e8-98a8-b8251ad94a5c.png)
