### ISSUE TITLE
nullptr should be utilized instead of NULL

### ISSUE THREAD

**Issue by cv3d** [opencv/opencv#12769]
related #12760

As you already know, nullptr is superior in all its aspects, and since we are migrating to C++11, changing NULL to nullptr should be one of the first things we do.

As for simplifying the merge from 3.4 to master, we can introduce nullptr as an alias to NULL in case compilers do not know about it.

What do you think?

**Comment by cv3d** [comment]
> part of our legacy

Shall we also say: let's stick to C instead of C++, since it is our legacy?

> any serious reason

Can you tell me which overload `func(NULL)` calls? Is it `func(int);` or `func(size *);`?
Believe it or not, there is always a strong reason to introduce something into the standards, and `nullptr` is now part of it. I suggest reading [this document](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2431.pdf) before we continue any further discussion.

**Comment by seiko2plus** [comment]
> Shall we also say: let's stick to C instead of C++, since it is our legacy

Language is just a tool, not the goal. I don't even mind if we going to rewrite the whole project in "Rust" for example or any other language, if this really going to help the cause.

> Can you tell me which overload func(NULL) calls? Is it func(int); or func(size *);?

Let me repeat what @alalek, says " but even this case is covered well by all compilers / code analyzers."

In other words, "which overload func(NULL) calls? " simply compiler gonna trigger "Ambiguous Error"
Other example of converting to non-pointer:
```
int hit_me = NULL;
```
My beloved GCC  gonna raise warning message effected by option "conversion-null"

> Believe it or not, there is always a strong reason to introduce something into the standards, and nullptr is now part of it.

I bet that no one want to stand against the evolution, but in case NULL or nullptr for me it's just a matter of code style since NULL will remain exists due the necessary compatibility with C, however I don't mind to replace NULL with nullptr in our legacy code, just after we end support of 3.4.

> I suggest reading this document before we continue any further discussion.

thank you for sharing it, sure I will read it

**Comment by alalek** [comment]
Feel free to use `nullptr` in completely new code, but avoid touching that in already existed code.
