### ISSUE TITLE
build failure (link) with cudev in 4.0.0-beta

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#12865]
I tried to build the 4.0.0-beta with all contrib modules under Windows 7, VS 2017, 64 bits.
with CUDA 10

Building opencv_cudev fails with error :
LNK2019	unresolved external "__declspec(dllimport) bool cv::__termination" (__imp_?__termination@cv@@3_NA) in DllMain

it can be fixed by adding opencv_core400[d].lib in the dependencies of cudev

**Comment by alalek** [comment]
relates #12791 and issue #12750
Workaround:
```
cmake -DOPENCV_SKIP_DLLMAIN_GENERATION=ON ...
```

**Comment by secutron** [comment]
As for the one of above questions,
 
Q. how to add, the property of cudev? but the opencv_core hasn't build , error can't open file “..\..\lib\Debug\opencv_core400d.lib”, and the core depend on cudev

A. because of circular dependency, we can't add 'core project' to 'cudev'. so after first compile, you can add 'opencv_core400d.lib' to 'opencv_ cudev project' using 

'opencv_cudev' properties >> linker >> input >> additional dependencies".

**Comment by glb-seu** [comment]
> As for the one of above questions,
> 
> Q. how to add, the property of cudev? but the opencv_core hasn't build , error can't open file “....\lib\Debug\opencv_core400d.lib”, and the core depend on cudev
> 
> A. because of circular dependency, we can't add 'core project' to 'cudev'. so after first compile, you can add 'opencv_core400d.lib' to 'opencv_ cudev project' using
> 
> 'opencv_cudev' properties >> linker >> input >> additional dependencies".

but my first compile has been failed to execute, so there is no opencv_core400d.lib

**Comment by alalek** [comment]
Please validate this patch: #13209

**Comment by caomw** [comment]
Great !

**Comment by wahyubram82** [comment]
> cmkae -DOPENCV_SKIP_DLLMAIN_GENERATION=ON

where i put this options?
