### ISSUE TITLE
cudaoptflow: test failure of FarnebackOpticalFlow

### ISSUE THREAD

**Issue by tomoaki0705** [opencv/opencv#12895]
##### System information (version)

- OpenCV => recent 3.4 branch
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2015 + CUDA 10

##### Summarized description
 - When I run ```opencv_test_cudaoptflow --gtest_filter=CUDA_OptFlow*FarnebackOpticalFlow.Accuracy/19:CUDA_OptFlow*FarnebackOpticalFlow.Accuracy/23``` the test fails
 - The test fails on one the platform I own, but it doesn't on others

##### Detailed description
 - I traced and figured out that the output was different.
 - 
![gpudump-0000-44](https://user-images.githubusercontent.com/3737315/47286318-1dfe2c00-d629-11e8-9a77-04e5cef5f964.png)
 VS 
![gpudump-0000-44](https://user-images.githubusercontent.com/3737315/47286323-22c2e000-d629-11e8-90ab-360e49a0c0ab.png)
 - The result was a floating point array, but I dumped as 4 channel 8bit image.
 - You can see there is a "blob" near the bottom left of the image, which is much larger than just a rounding error

##### Starting tracking
- I traced back where this difference occours, and the difference was happening [here](https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L435)
https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L435
- The first 4 parameters are inputs and ```M``` is the output which differs between the platforms
- Now, already, ```curFlowX``` and ```curFlowY``` were different
- I traced back further and it started to look weird

##### Tracing back the curFlow
- This ```device::optflow_farneback::updateMatricesGpu``` exists inside the loop, and the data was corrupted from the first iteration.
- At [this section](https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L375-L381), ```flowx0``` is converted to ```curFlowX``` as well as Y.
https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L375-L381
- Now tracing back ```flowx0``` and ```flowy0```, they are passed from the parent function call ```calc```. but they don't heritate the initial flow, it just allocates new memory [here](https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L170-L173)
https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L170-L173
- but used as an input (uninitialized) [here](https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L375-L381)
https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/src/farneback.cpp#L375-L381
- Judging from the name ```OPTFLOW_USE_INITIAL_FLOW``` , it looks like the implementation is expecting ```flowx0``` and ```flowy0``` to have some initial value, but then why is it not passed from the beginning ?
- Also, judging from the [test code](https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/test/test_optflow.cpp#L328-L333) it looks like the test code is trying to give some kind of pre-computed flow as an initial value input.
https://github.com/opencv/opencv/blob/41398987c345678ce922bf6ada073f7d6e484ae3/modules/cudaoptflow/test/test_optflow.cpp#L328-L333

##### Actual behavior when the test passes
- When the test passes, ```flowx0``` has somehow pre-computed value.
- I don't know where the pre-computed value comes from, but it looks "reasonable" data
- So my guess is that this pre-computed value is the memory garbage of the previous computation, and luckily, it was pointing to a meaning memory area, so the computation passes.
- In another word, it's a miracle that the test passes usually, and it's supposed to fail.

##### My question
- This "memory garbage" comes from somewhere, and it'll require so much work to trace back, and I'm not sure if it's the correct way either.
- I just want to raise the issue first, and discuss how to fix.
- It started as a "environment specific issue" but now it looks like there are some weird code blocks
- There are some "my guess" in this issue, so I want to make sure that I'm on the correct track

##### Steps to reproduce
- run ```opencv_test_cudaoptflow --gtest_filter=CUDA_OptFlow*FarnebackOpticalFlow.Accuracy/19:CUDA_OptFlow*FarnebackOpticalFlow.Accuracy/23```

**Comment by nglee** [comment]
Hi, @tomoaki0705 ,
Based on your primary investigation, I've also looked into the issue. Following is my test environments.
```
GTX 1080    with CUDA 10.0 on Windows
GTX 1080 Ti with CUDA ( >= 8.0 && <= 10.0 ) on Ubuntu 16.04
```
In my case, the two tests mentioned fail on `GTX 1080 Ti`, and pass on `GTX 1080`.

I think the problem is that the `OPTFLOW_USE_INITIAL_FLOW` option is not considered in both CPU and GPU(CUDA) implementations. Actually, only the "OCL" implementation seems to consider this option.

[In the `calc` function](https://github.com/opencv/opencv/blob/3.4/modules/cudaoptflow/src/farneback.cpp#L164-L177), it seems that when the `OPTFLOW_USE_INITIAL_FLOW` is set, the value passed to `_flow` should be used as the initial value for `flowx` and `flowy`.

It should be fixed [as in this link](https://github.com/nglee/opencv/blob/4ffbd089677181f1da30c7fa974b6870a30e90d5/modules/cudaoptflow/src/farneback.cpp#L164-L190).

Also, [in the CPU implementation](https://github.com/opencv/opencv/blob/3.4/modules/video/src/optflowgf.cpp#L1096-L1115), `_flow0` is always reallocated whether the `OPTFLOW_USE_INITIAL_FLOW` is set or not.

Line 1115 of above code should be fixed [as in this link](https://github.com/nglee/opencv/blob/4ffbd089677181f1da30c7fa974b6870a30e90d5/modules/video/src/optflowgf.cpp#L1116-L1117).

The "OCV" implementation, however, seems to consider the case when the `_flow0` value is initialized, as the line 1077-1079 of [this code](https://github.com/nglee/opencv/blob/4ffbd089677181f1da30c7fa974b6870a30e90d5/modules/video/src/optflowgf.cpp#L1065-L1079) shows.

With fixes mentioned above, the tests that failed before pass.

**Comment by alalek** [comment]
@tomoaki0705 Please check latest code updates from @nglee.

**Comment by tomoaki0705** [comment]
Yep, I'll be back with test result

**Comment by tomoaki0705** [comment]
I confirmed that the failure is fixed
Win10 + GTX 1060 (3.4 branch)
Ubuntu 16.04 + GTX 1050ti (3.4 branch)
Ubuntu 16.04 + GTX 1050ti (master branch)
All passed

Great work @nglee !

Closing the issue
