### ISSUE TITLE
Can I compile opencv with specified cuda version?

### ISSUE THREAD

**Issue by bucktoothsir** [opencv/opencv#12941]
I have installed different versions of cuda  on my computer.  Can I specify one to compile opencv instead of using findcuda.cmake？

**Comment by alalek** [comment]
Check build scripts [manual](https://gitlab.kitware.com/cmake/cmake/blob/v3.12.4/Modules/FindCUDA.cmake).

**Comment by zchrissirhcz** [comment]
Same issue here. After reading @alalek' provided webpage, I'd like to make it clear.

It's `FindCUDA.cmake`'s source code, and if I just read and believe its comment, I will set `CUDA_BIN_PATH` variable before calling cmake. **However, I must set `CUDA_TOOLKIT_ROOT_DIR` instead of `CUDA_BIN_PATH`, according to its code and my experiment result**. e.g.:

```cmake
set CUDA_TOOLKIT_ROOT_DIR="D:/soft/NVIDIA GPU Computing Toolkit/CUDA/v8.0"

cmake ^
    -G "Visual Studio 14 2015 Win64" ^
    -D CMAKE_BUILD_TYPE=Release ^
    -D CMAKE_INSTALL_PREFIX=%cd%/install ^
    -D WITH_CUDA=ON ^
	-D CUDA_TOOLKIT_ROOT_DIR=%CUDA_TOOLKIT_ROOT_DIR% ^
    -D WITH_VTK=OFF ^
    -D WITH_MATLAB=OFF ^
    -D BUILD_DOCS=ON ^
    -D OPENCV_EXTRA_MODULES_PATH=D:/lib/opencv_contrib_310/modules ^
    ../sources
```
