### ISSUE TITLE
Add Fix K1...K4 and FX/FY For Fisheye Calibration

### ISSUE THREAD

**Issue by BananaHemic** [opencv/opencv#13450]
For my project, I had a-priori knowledge of the camera's distortion parameters, so I added a CALIB_FIX_FX and CALIB_FIX_FY to the fisheye calibration to allow me to use that a-priori information. Similarly, I changed the behaviour of CALIB_FIX_K1...K4 to use the provided distortion coefficients if CALIB_USE_INTRINSIC_GUESS is set, instead of just setting them to 0. These changes are currently working on my dev machine.

Before I make a full PR with the relevant changes to documentation, could someone confirm that this is a valid change that could be accepted upstream? I want to make sure that there was not some rational for the previous behaviour that I was missing.

**Comment by alalek** [comment]
Could you split patch into 2 PRs?

> cv::calibrateCamera:

CALIB_FIX_K1,...,CALIB_FIX_K6 The corresponding radial distortion coefficient is not changed during the optimization. **If CALIB_USE_INTRINSIC_GUESS is set, the coefficient from the supplied distCoeffs matrix is used**. Otherwise, it is set to 0.

> cv::fisheye::calibrate

fisheye::CALIB_FIX_K1..fisheye::CALIB_FIX_K4 Selected distortion coefficients are set to zeros and stay zero.


So, current behavior differ. It is not good really.
I believe we can align their behaviors to `cv::calibrateCamera`.

**Comment by weseu0131** [comment]
Excuse me.....how can I fix fx/fy ratio for fisheye module? I want to let fx=fy.
