### ISSUE TITLE
Android javacamera2 green color in screen

### ISSUE THREAD

**Issue by oumardiarra** [opencv/opencv#13526]
##### System information (version)

- OpenCV => :4.0.1  Android pack

##### Detailed description

When using Opencv Javacamera2View , I get a green color on the camera preview. When i switch to JavaCameraView, the camera diplays well.

![screenshot_20181225-162646](https://user-images.githubusercontent.com/20979107/50424414-00348980-085b-11e9-94d5-88414dc48d72.png)

**Comment by alalek** [comment]
Similar "incomplete" issues: #11501 or #11325

**Comment by hasseye** [comment]
Any progress on this?

**Comment by alalek** [comment]
Output of adb logcat (only related to app).
Android API level?
Device model?

**Comment by Victorlouisdg** [comment]
I have the same problem on my Moto C Plus, Android 7.0, OpenCV 4.1.0. 

The cause is the incorrect assumption that all devices will return NV21 frames when using ImageFormat.YUV_420_888 for the ImageReader. The pixel stride of planes[1] and planes[2] are equal to 1 on my device, not 2, as asserted on line 187.

If I read the 3 image planes separately and put them into a single Mat (as in JavaCameraView) and use the code Imgproc.COLOR_YUV2RGB_I420 for the conversion, the colors appear correctly.

**Comment by alalek** [comment]
@oumardiarra Please take a look on this patch #14342
