### ISSUE TITLE
Some javascript feature2d bindings not working ?

### ISSUE THREAD

**Issue by nestarz** [opencv/opencv#13641]
Is it feasible to merge some [Web-Sight](https://github.com/Web-Sight/opencvjs) and [Quramy](https://github.com/Quramy/opencvjs) bindings with master ? I don't really know how it can be done, but I would like to do it if so. 

It is used for example by @Quramy in his feature_matching demo (see [here](https://github.com/Quramy/opencv-wasm-knnmatch-demo))
to use feature2d functions like `cv.drawMatches`, `cv.knnMatch`, `cv.drawMatchesKnn`, `cv.drawKeypoints ` and so on which are not working in master repo (if I'm correct).

**Errors**
```javascript
let kp = new cv.KeyPointVector();
let descriptors = new cv.Mat();
let orb = new cv.ORB();
orb.detectAndCompute(src, new cv.Mat(), kp, descriptors);
cv.drawKeypoints(src, kp, dst); // Error here
kp.delete();
orb.delete();
```
raise following error
```
TypeError: Cannot convert "undefined" to unsigned int
```

and

```javascript
let kp = new cv.KeyPointVector();
let descriptors = new cv.Mat();
let orb = new cv.ORB();
orb.detectAndCompute(src, new cv.Mat(), kp, descriptors);

// Run a matcher.
let dm = new cv.DMatchVector();
let matcher = new cv.BFMatcher();
matcher.match(descriptors, descriptors, dm);
const matchingImage = new cv.Mat();
cv.drawMatchesKnn(src, descriptors, src, descriptors, dm, matchingImage);
```
raise
```
TypeError: cv.drawMatchesKnn is not a function
````
while 
```javascript
cv.drawMatches(src, descriptors, src, descriptors, dm, matchingImage); // Error (2)
```
raise
```
TypeError: Cannot convert "undefined" to unsigned int
```

**Environnement**
I built opencv.js upon opencv master branch and I added to core_bindings.cpp some lines from not merged pull request #12855 to get DMatch support (see [here](https://github.com/opencv/opencv/pull/12855/commits/05665f38979f49d87424b7113b8093f0f13b4c79#diff-1edbc1c9e1c9478205122f6accffa452R337)).

**Comment by dkurt** [comment]
`feature2d` module is added to opencv.js. See the following PRs:
https://github.com/opencv/opencv/pull/12659
https://github.com/opencv/opencv/pull/12767
https://github.com/opencv/opencv/pull/12855

**Comment by nestarz** [comment]
Sorry I was incomplete, but I would like to use feature matching and some functions are not working on master, even with a custom build. But are working when using Web-sight bindings. 
You can see [here](https://github.com/Web-Sight/opencvjs/blob/Optimizations/bindings.cpp
) that there is a lot of bindings and wrappers that are not existing in master's opencv bindings ([here](https://github.com/opencv/opencv/blob/master/modules/js/src/core_bindings.cpp)). 
For example now if I do
```
  const mask = new cv.Mat(), kp1 = new cv.KeyPointVector(), des1 = new cv.Mat(), kp2 = new cv.KeyPointVector(), des2 = new cv.Mat();
  const akaze = new cv.AKAZE(5, 0, 3, 0.001, 4, 4, 1);
  akaze.detectAndCompute(img1, mask, kp1, des1, false);
  akaze.detectAndCompute(img2, mask, kp2, des2, false);

  const matches = new cv.DMatchVectorVector();
  const bf = new cv.BFMatcher(2, false);
  bf.knnMatch(des1, des2, matches, 2, mask, false);

  const ratio = .5, good = new cv.DMatchVectorVector();
  for (let i = 0; i < matches.size(); i++) {
    const m = matches.get(i).get(0), n = matches.get(i).get(1);
    if (m.distance < ratio * n.distance) {
      const t = new cv.DMatchVector();
      t.push_back(m);
      good.push_back(t);
    }
  }

  const matchingImage = new cv.Mat(), mc = new cv.Scalar(-1, -1, -1, -1), sc = new cv.Scalar(0, 255, 0, 0), maskingCharVecVec = new cv.CharVectorVector();
  cv.drawMatchesKnn(img1, kp1, img2, kp2, good, matchingImage, mc, sc, maskingCharVecVec, 2);
  cv.imshow(canvasOutput, matchingImage);
```
It is not working, even with ORB.

**Comment by nestarz** [comment]
> `features2d` module is added to opencv.js. See the following PRs:
> #12659
> #12767
> #12855

@alalek I updated my issue to reflect better encountered issue.

**Comment by Yuan-Chen** [comment]
I have the same problem when trying to use cv.drawKeypoints as it shows
`TypeError: Cannot convert "undefined" to unsigned int`

I compile my opencv.js to WebAssembly on the master branch.

I find the function used to work fine, like https://github.com/ucisysarch/opencvjs/tree/master/test

**Comment by ArnaudHambenne** [comment]
Any update on this? I am getting the same error as @Yuan-Chen on `cv.drawKeypoints`. Also opencv.js from master branch.

**Comment by gorankarlic** [comment]
+1

**Comment by AlexandruPopovici** [comment]
+1

**Comment by itslove** [comment]
+1

**Comment by dkurt** [comment]
Ok guys. I'll check it this week 😄

**Comment by dkurt** [comment]
> Ok guys. I'll check it this week smile

Sorry for delay. It turned out a bit later. See https://github.com/opencv/opencv/pull/15107.

**Comment by scottsuhy** [comment]
This bug seems to have returned in 4.5.1

I verified it did work in 3.4.7 but when I replace opencv.js with 4.5.1 it fails with this error:

Uncaught BindingError {name: "BindingError", message: "Function 'drawKeypoints' called with an invalid nu…3Wired);↵arg3Wired_dtor(arg3Wired); // Scalar↵})!", stack: "BindingError: Function 'drawKeypoints' called with…ick (http://127.0.0.1:8082/opencv_align#:183:185)"}
message: "Function 'drawKeypoints' called with an invalid number of arguments (5) - expects one of (,,,function drawKeypoints(arg0, arg1, arg2) {↵if (arguments.length !== 3) {↵throwBindingError('function drawKeypoints called with ' + arguments.length + ' arguments, expected 3 args!');↵}↵var arg0Wired = argType0.toWireType(null, arg0); // Mat↵var arg1Wired = argType1.toWireType(null, arg1); // KeyPointVector↵var arg2Wired = argType2.toWireType(null, arg2); // Mat↵invoker(fn, arg0Wired, arg1Wired, arg2Wired);↵},function drawKeypoints(arg0, arg1, arg2, arg3) {↵if (arguments.length !== 4) {↵throwBindingError('function drawKeypoints called with ' + arguments.length + ' arguments, expected 4 args!');↵}↵var arg0Wired = argType0.toWireType(null, arg0); // Mat↵var arg1Wired = argType1.toWireType(null, arg1); // KeyPointVector↵var arg2Wired = argType2.toWireType(null, arg2); // Mat↵var arg3Wired = argType3.toWireType(null, arg3); // Scalar↵invoker(fn, arg0Wired, arg1Wired, arg2Wired, arg3Wired);↵arg3Wired_dtor(arg3Wired); // Scalar↵})!"
name: "BindingError"
stack: "BindingError: Function 'drawKeypoints' called with an invalid number of arguments (5) - expects one of (,,,function drawKeypoints(arg0, arg1, arg2) {↵if (arguments.length !== 3) {↵throwBindingError('function drawKeypoints called with ' + arguments.length + ' arguments, expected 3 args!');↵}↵var arg0Wired = argType0.toWireType(null, arg0); // Mat↵var arg1Wired = argType1.toWireType(null, arg1); // KeyPointVector↵var arg2Wired = argType2.toWireType(null, arg2); // Mat↵invoker(fn, arg0Wired, arg1Wired, arg2Wired);↵},function drawKeypoints(arg0, arg1, arg2, arg3) {↵if (arguments.length !== 4) {↵throwBindingError('function drawKeypoints called with ' + arguments.length + ' arguments, expected 4 args!');↵}↵var arg0Wired = argType0.toWireType(null, arg0); // Mat↵var arg1Wired = argType1.toWireType(null, arg1); // KeyPointVector↵var arg2Wired = argType2.toWireType(null, arg2); // Mat↵var arg3Wired = argType3.toWireType(null, arg3); // Scalar↵invoker(fn, arg0Wired, arg1Wired, arg2Wired, arg3Wired);↵arg3Wired_dtor(arg3Wired); // Scalar↵})!↵if (arguments.length !== 3) {↵throwBindingError('function drawKeypoints called with ' + arguments.length + ' arguments, expected 3 args!');↵}↵var arg0Wired = argType0.toWireType(null, arg0); // Mat↵var arg1Wired = argType1.toWireType(null, arg1); // KeyPointVector↵var arg2Wired = argType2.toWireType(null, arg2); // Mat↵invoker(fn, arg0Wired, arg1Wired, arg2Wired);↵},function drawKeypoints(arg0, arg1, arg2, arg3) {↵if (arguments.length !== 4) {↵throwBindingError('function drawKeypoints called with ' + arguments.length + ' arguments, expected 4 args!');↵}↵var arg0Wired = argType0.toWireType(null, arg0); // Mat↵var arg1Wired = argType1.toWireType(null, arg1); // KeyPointVector↵var arg2Wired = argType2.toWireType(null, arg2); // Mat↵var arg3Wired = argType3.toWireType(null, arg3); // Scalar↵invoker(fn, arg0Wired, arg1Wired, arg2Wired, arg3Wired);↵arg3Wired_dtor(arg3Wired); // Scalar↵})!↵    at BindingError.<anonymous> (https://docs.opencv.org/4.5.1/opencv.js:30:7565057)↵    at new BindingError (eval at createNamedFunction (https://docs.opencv.org/4.5.1/opencv.js:30:7564766), <anonymous>:4:34)↵    at throwBindingError (https://docs.opencv.org/4.5.1/opencv.js:30:7570184)↵    at Object.proto.<computed> [as drawKeypoints] (https://docs.opencv.org/4.5.1/opencv.js:30:7575164)↵    at Align_img (http://127.0.0.1:8082/opencv_align:333:16)↵    at HTMLAnchorElement.onclick (http://127.0.0.1:8082/opencv_align#:183:185)"

**Comment by dkurt** [comment]
@scottsuhy, please provide a code snippet with method usage. We added a test for that.

**Comment by scottsuhy** [comment]
See below.  This is library used: 

`    <script async src="https://docs.opencv.org/4.5.1/opencv.js" onload="onOpenCvReady();" type="text/javascript"></script>`

```
        function Align_img() {

            //STEP 1: READ IN IMAGES **********************************************************************"
            //im2 is the original reference image we are trying to align to
            let im2 = cv.imread(image_A_element);
            //im1 is the image we are trying to line up correctly
            let im1 = cv.imread(image_B_element);

            //STEP 2: CONVERT IMAGES TO GRAYSCALE *********************************************************
            let im1Gray = new cv.Mat();
            let im2Gray = new cv.Mat();
            cv.cvtColor(im1, im1Gray, cv.COLOR_BGRA2GRAY);
            cv.cvtColor(im2, im2Gray, cv.COLOR_BGRA2GRAY);

            //STEP 3: DETECT FEATURES & COMPUTE DESCRIPTORS************************************************
            let keypoints1 = new cv.KeyPointVector();
            let keypoints2 = new cv.KeyPointVector();
            let descriptors1 = new cv.Mat();
            let descriptors2 = new cv.Mat();

            var X = new cv.AKAZE();

            X.detectAndCompute(im1Gray, new cv.Mat(), keypoints1, descriptors1);
            X.detectAndCompute(im2Gray, new cv.Mat(), keypoints2, descriptors2);

            //draw all the keypoints on each image and display it to the user
            let keypoints1_img = new cv.Mat();
            let keypoints2_img = new cv.Mat();
            let keypointcolor = new cv.Scalar(0,255,0, 255);

            cv.drawKeypoints(im1Gray, keypoints1, keypoints1_img, keypointcolor);// Works Great
            cv.drawKeypoints(im2Gray, keypoints2, keypoints2_img, keypointcolor);// Works Great
			
	    cv.drawKeypoints(im1Gray, keypoints1, keypoints1_img, keypointcolor, 4);//FAILS
            cv.drawKeypoints(im2Gray, keypoints2, keypoints2_img, keypointcolor, 4);//FAILS
			
	    cv.drawKeypoints(im1Gray, keypoints1, keypoints1_img, keypointcolor, cv.DRAW_RICH_KEYPOINTS); //FAILS
            cv.drawKeypoints(im2Gray, keypoints2, keypoints2_img, keypointcolor, cv.DRAW_RICH_KEYPOINTS); //FAILS
			
            cv.imshow('keypoints1', keypoints1_img);
            cv.imshow('keypoints2', keypoints2_img);
			
			
	   etc...
```

**Comment by dkurt** [comment]
Can you check if `cv.DRAW_RICH_KEYPOINTS` is valid? just `console.log(cv.DRAW_RICH_KEYPOINTS)`. Seems to me it should be `cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS` instead (see https://docs.opencv.org/master/d4/d5d/group__features2d__draw.html#ga5d2bafe8c1c45289bc3403a40fb88920)

**Comment by scottsuhy** [comment]
now I'm just confused, I'll continue to review. 

I get the same results ("undefined") below with 3.4.7 and 4.5.1 using:

console.log("cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS: ", cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS);
console.log("cv.DRAW_RICH_KEYPOINTS: ", cv.DRAW_RICH_KEYPOINTS);
console.log("cv.DRAW_MATCHES_FLAGS_DEFAULT: ", cv.DRAW_MATCHES_FLAGS_DEFAULT);
console.log("cv.DRAW_MATCHES_FLAGS_DRAW_OVER_OUTIMG: ", cv.DRAW_MATCHES_FLAGS_DRAW_OVER_OUTIMG);
console.log("cv.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS: ", cv.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS);

result:

cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS:  undefined
cv.DRAW_RICH_KEYPOINTS:  undefined
cv.DRAW_MATCHES_FLAGS_DEFAULT:  undefined
cv.DRAW_MATCHES_FLAGS_DRAW_OVER_OUTIMG:  undefined
cv.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS:  undefined

**Comment by scottsuhy** [comment]
so, here is what I'm experiencing. 

1. In 3.4.8, using an INT as the 5th argument works
   cv.drawKeypoints(im1Gray, keypoints1, keypoints1_img, keypointcolor, 4);

2. In 3.4.8 using any of these fails because they are all 'undefined'
   cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS
   cv.DRAW_RICH_KEYPOINTS
   cv.DRAW_MATCHES_FLAGS_DEFAULT
   cv.DRAW_MATCHES_FLAGS_DRAW_OVER_OUTIMG   
  cv.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS

3. In 4.5.1, using an INT as the 5th argument (or any of the items in #2 above) gives me the 'called with an invalid number of arguments (5)' error

**Comment by dkurt** [comment]
@scottsuhy, can you please try the following constants?
```
DrawMatchesFlags_DEFAULT
DrawMatchesFlags_DRAW_OVER_OUTIMG
DrawMatchesFlags_DRAW_RICH_KEYPOINTS
DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
```

**Comment by scottsuhy** [comment]
That's it: 
    console.log("DrawMatchesFlags_DEFAULT: ", DrawMatchesFlags_DEFAULT);
    _**Uncaught ReferenceError: DrawMatchesFlags_DEFAULT is not defined**_

**However, this works:**
  cv.DrawMatchesFlags_DEFAULT:  0
  cv.DrawMatchesFlags_DRAW_OVER_OUTIMG:  1
  cv.DrawMatchesFlags_DRAW_RICH_KEYPOINTS:  4
  cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS:  2

**Comment by dkurt** [comment]
@scottsuhy, Sure, sorry about that,
```
cv.DrawMatchesFlags_DEFAULT
cv.DrawMatchesFlags_DRAW_OVER_OUTIMG
cv.DrawMatchesFlags_DRAW_RICH_KEYPOINTS
cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
```

**Comment by scottsuhy** [comment]
so it's a opencv.js documentation issue... oh, wait, there is no documentation :-) 

I'd at least put a note here: https://docs.opencv.org/master/d4/d5d/group__features2d__draw.html#ga2c2ede79cd5141534ae70a3fd9f324c8

**Comment by scottsuhy** [comment]
actually, i think this is more than a documentation issue.  when using cv.DrawMatchesFlags_DRAW_RICH_KEYPOINTS with 4.5.1 the api gets stuck inside the drawKeypoints call (nothing inside console.log).  the script just freezes.  when I use 3.4.8 it works great.
