### ISSUE TITLE
Why is there no Python documentation for the CUDA modules? 

### ISSUE THREAD

**Issue by rakshith95** [opencv/opencv#13653]
##### System information (version)

- OpenCV => :4.0.1-dev:
- Operating System / Platform => :Ubuntu 18.04, LinuxLinux 4.15.0-43-generic x86_64:
- Compiler => :3.10.2:

**Comment by berak** [comment]
@rakshith95 , there was a rudimentary attempt made, to expose GpuMat to python in opencv4, and you will find [documentation for this](https://docs.opencv.org/master/d0/d60/classcv_1_1cuda_1_1GpuMat.html)

unfortunately it stopped then. 
no function ever **using** GpuMat was wrapped, so far, that's why you cannot use it from python, and that's why you won't find any further documentation ;(

**Comment by rakshith95** [comment]
So the cuda modules cannot be used from Python?

**Comment by berak** [comment]
@rakshith95  -- as it is now, i'm afraid -- no.

**Comment by berak** [comment]
@rakshith95 , maybe you should close this ?
