### ISSUE TITLE
cmake trying to compile with AVX512 despite the negative test of AVX512 presence

### ISSUE THREAD

**Issue by mprevot** [opencv/opencv#13727]
##### System information (version)
- OpenCV => master
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- cmake => 3.13.0-rc3

##### Detailed description

[CMakeError.log](https://github.com/opencv/opencv/files/2813598/CMakeError.log)

##### Steps to reproduce
	cmake -G $target -T v141, host=x64 -j8 `
		-DBUILD_JAVA=0 -DWITH_MATLAB=1 -DBUILD_DOC=0 -DBUILD_PERF_TESTS=0 -DBUILD_TESTS=0 -DBUILD_opencv_world=0 `
		-DOPENCV_ENABLE_NONFREE=1 -DBUILD_opencv-apps=0 -DENABLE_PYLINT=0 -DENABLE_CXX11=1 -DWITH_VTK=1 `
		-DCUDA_SDK_ROOT_DIR="$env:CUDA_PATH" -DCUDA_ARCH_BIN="5.2" -DCUDA_VERBOSE_BUILD=0 -DBUILD_CUDA_STUBS=0 `
		-DWITH_OPENCL=1 -DWITH_CUDA=1 -DMKL_WITH_OPENMP=1 -DMKL_WITH_TBB=1 `
		-DOPENCV_EXTRA_MODULES_PATH="../opencv_contrib/modules" `
		-DINSTALL_CREATE_DISTRIB=1 -DCPACK_BINARY_ZIP=1 -DCPACK_SOURCE_ZIP=1 -DCMAKE_VERBOSE_MAKEFILE=0 `
		../opencv | Tee-Object -Variable RESULT

**Comment by mprevot** [comment]
cmake configuration was not finishing because of this error. However, I used the zipped sources (master today). Now I'm doing the same cmake configure with sources from git, and it finished, but compile fails somewhere else.

**Comment by alalek** [comment]
No, it is just check which fails (MSVS 2015 doesn't support AVX512). CMakeError.log is just log file with failed checks.
It should not lead to whole configuration failure. Check CMake's terminal output for error message.

Try to disable CUDA. Builds without CUDA should work fine (we have these builds on our CI). If not, something is wrong with build configuration.

Also VTK + CUDA may not work (no idea what VTK version is used in your case). See previous issues about them.

> somewhere else

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

Custom builds / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
