### ISSUE TITLE
Suggestion: install headers into opencv3 subdirectory for OpenCV3

### ISSUE THREAD

**Issue by huangqinjin** [opencv/opencv#13871]
It seems that OpenCV3 can coexist with OpenCV4. The problem is that OpenCV3 headers go into common directory `/usr/local/include`. The following example will link to OpenCV4 but use OpenCV3 headers. 
```
cmake_minimum_required(VERSION 3.1)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
find_package(Boost COMPONENTS filesystem)   # Boost installed in /usr/local/include
find_package(OpenCV 4 COMPONENTS core)
add_executable(MyExe main.cpp)
target_link_libraries(MyExe Boost::filesystem opencv_core)

```

**Comment by alalek** [comment]
Side-by-side installation of multiple OpenCV versions works if system paths are not used (you should not have system opencv packages or something installed into `/usr/local`).

**Compatibility is preserved by default** - so there is still no "3" suffix.

You can change install directory via CMake for OpenCV 3 build (ensure that you properly uninstall opencv3 at first):
`cmake -DOPENCV_INCLUDE_INSTALL_PATH=include/opencv3 ...`

---

BTW, `Boost` include directories should be passed as "system" includes (`-isystem` instead of `-I`) - you can check this via `make VERBOSE=1`.
