### ISSUE TITLE
fishey.projectPoints with cv.norm gives error

### ISSUE THREAD

**Issue by Eyshika** [opencv/opencv#13896]
# System information (version)
- OpenCV => 3.3.4
- Operating System / Platform => Mac
- Compiler => Visual Studio

# Detailed description
I am doing calibration for single camera for fisheye lens. It works good, but give an error while calculating reprojection error

This is the code for reprojection error:
```
for i in range(len(self.objpoints)):
            imgpoints2, _ = cv.fisheye.projectPoints(
                self.objpoints[i], self.rvecs[i], self.tvecs[i], self.M, self.D)
            error = cv.norm(
                self.imgpoints[i], imgpoints2, cv.NORM_L2) / len(imgpoints2)
            mean_error += error
```

This is the error:

> OpenCV(3.4.3) /Users/eyshika.agarwal/opencv-3.4.3/modules/core/src/norm.cpp:1092: error: (-215:Assertion failed) _src1.sameSize(_src2) && _src1.type() == _src2.type() in function 'norm'

Any suggestions or help ?
Thank You!

**Comment by Hannah-hh** [comment]
Excuse me. How do you solve this problem? I have an  error similar to yous. Thank you so much!

**Comment by Yingliangzhe** [comment]
I also have this problem. In my case I have fixed it. The problem is, that my **self.imgpoints[i]** and **imgpoints2** have different shape. If I print out the shape of each points set. **self.imgpoints[i]** has shape of (54,2) and **imgpoints2** has (54,1,2). I have used the reshape function to convert (54,1,2) into (54,2). Then this problem is gone.  

Hope this helps.

**Comment by mkoeda** [comment]
I met same issue. To solve, imgpoint2.reshape(self.imgpoints[i].shape) or imgpoint2.reshape(-1, 2) simply.
