### ISSUE TITLE
A library with LAPACK API not found. Please specify library location. VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file

### ISSUE THREAD

**Issue by JaosonMa** [opencv/opencv#14016]
Could NOT find BLAS (missing: BLAS_LIBRARIES) 
LAPACK requires BLAS
A library with LAPACK API not found. Please specify library location.
VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
CMake Error at cmake/OpenCVModule.cmake:370 (_glob_locations):
  Syntax error in cmake code at

    F:/product/opencv-4.0.1/cmake/OpenCVModule.cmake:370

  when parsing string

    F:\product\opencv_contrib-4.0.1\modules

  Invalid character escape '\p'.
Call Stack (most recent call first):
  modules/CMakeLists.txt:7 (ocv_glob_modules)

Configuring incomplete, errors occurred!
See also "F:/product/opecv401_vs2015/CMakeFiles/CMakeOutput.log".
See also "F:/product/opecv401_vs2015/CMakeFiles/CMakeError.log".

win7  + opencv4.01+opencv_contrib +cmake3.13

**Comment by marketmi** [comment]
Maybe try changing:

> F:\product\opencv_contrib-4.0.1\modules

to

> F:/product/opencv_contrib-4.0.1/modules

And see if that fixes the problem.

**Comment by alalek** [comment]
[Can't reproduce](http://pullrequest.opencv.org/buildbot/builders/master-contrib-win64-vc14/builds/10744/steps/cmake/logs/stdio).

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.
