### ISSUE TITLE
the demo of opencv.js is broken

### ISSUE THREAD

**Issue by kimown** [opencv/opencv#14020]
1. open link with chrome: https://docs.opencv.org/3.4/db/d64/tutorial_js_colorspaces.html, the `Try it` button is always disabled

```
Uncaught TypeError: cv.getBuildInformation is not a function
    at HTMLScriptElement.script.addEventListener (utils.js:11)
```

![image](https://user-images.githubusercontent.com/7932380/54096771-37412280-43e8-11e9-8911-3895929e7cc1.png)

**Comment by dkurt** [comment]
@kimown, Thank you!

It looks like OpenCV.js is compiled with WASM support since one day. In this PR https://github.com/opencv/opencv/pull/14021 we added a check for it. However I think we should also cover cases when WebAssembly is not supported by browser (need an alternative opencv.js which might be downloaded).
