### ISSUE TITLE
FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file

### ISSUE THREAD

**Issue by Blueblazers** [opencv/opencv#14123]
net = cv2.dnn.readNet("C://Users//helll//PycharmProjects//Text Recognisation//opencv-text-recognition//frozen_east_text_detection.pb")

For this above line I am getting the error as
Traceback (most recent call last):
  File "C:/Users/helll/PycharmProjects/Text Recognisation/Text.py", line 78, in <module>
    net = cv2.dnn.readNet("C://Users//helll//PycharmProjects//Text Recognisation//opencv-text-recognition//frozen_east_text_detection.pb","ssd_mobilenet_v1_coco.pbtxt")
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: C://Users//helll//PycharmProjects//Text Recognisation//opencv-text-recognition//frozen_east_text_detection.pb in function 'cv::dnn::ReadTFNetParamsFromBinaryFileOrDie'

I am using Open CV 4.0.0 and Python 3.7.2 in a 64 bit system and using Intel i5 8 gen processor with 8 gb ram.

**Comment by dkurt** [comment]
@Blueblazers, Try to avoid whitespaces in the paths and use espace symbols for Windows paths: `C:\\Users`.

**Comment by mohamed-elfiky** [comment]
did you find the solution ?

**Comment by vincenthesiyuan** [comment]
i have the same problem.  did you sovle this?

**Comment by mohamed-elfiky** [comment]
the .pb file was corrupted so using another file from different source solved the problem for me .
you should also make sure that the path to the file is correct.

**Comment by vagdevik** [comment]
In my case, I was trying to access the `.pbtxt` file stored in a github repository through my Google Colaboratory.  I just needed the file, so instead of cloning the whole repo, I tried to access it using `!wget` command. I did:
`https://github.com/<username>/somethingelse/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`.
The file seemed to be downloaded, but when I ran `cv2.dnn.readNetFromTensorflow`, it has thrown me an error saying:

`OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp, line 72
opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt in function ReadTFNetParamsFromTextFileOrDie`.

I realised I should have used the `raw` file in github to download, as follows:
`!wget https://raw.githubusercontent.com/<username>/somethingelse/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`

Since I did't use raw, the file downloaded in HTML format where as the expected file was `.pbtxt`. 

So go to the file location in github repository->click on the raw option on top right corner->get the URL of this raw page-> use `!wget https://raw.githubusercontent.com/<username>/somethingelse/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`
has helped me resolved the issue. Hope this helps someone :-D

**Comment by zihaomu** [comment]
> **Issue Resolved:**
> 
> In my case, I was trying to access the `.pbtxt` file stored in a github repository through my Google Colaboratory. I just needed the file, so instead of cloning the whole repo, I tried to access it using `!wget` command. I did:
> `https://github.com/<username>/somethingelse/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`.
> The file seemed to be downloaded, but when I ran `cv2.dnn.readNetFromTensorflow`, it has thrown me an error saying:
> 
> `OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp, line 72 opencv-3.3.1/modules/dnn/src/tensorflow/tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_11_06_2017/graph.pbtxt in function ReadTFNetParamsFromTextFileOrDie`.
> 
> I realised I should have used the `raw` file in github to download, as follows:
> `!wget https://raw.githubusercontent.com/---somethingelse as part of link---/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt`
> 
> Since I did't use raw, the file downloaded in HTML format where as the expected file was `.pbtxt`.
> 
> **So go to the file location in github repository->click on the raw option on top right corner->get the URL of this raw page-> use `!wget https://raw.githubusercontent.com/ ---somethingelse as part of link---/mask_rcnn_inception_v2_coco_2018_01_28.pbtxt` has helped me resolved the issue.**
> 
> Hope this helps someone!! :-D

Thanks. It works for me!

**Comment by sourabmaity** [comment]
I have same issue but i am using jupyter nootbook. How can i solve this type of error <br>
**OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\tensorflow\tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: E:/RealTimeObjectDetection/Tensorflow/workspace/models/saved_model/saved_model.pb in function 'cv::dnn::ReadTFNetParamsFromBinaryFileOrDie'**

**Comment by alalek** [comment]
> Failed to parse

Specified path is wrong, file is missing or file is got corrupted.

---

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
