### ISSUE TITLE
missing BUILD_opencv_python3 in OPENCV 4.1.0

### ISSUE THREAD

**Issue by wahyubram82** [opencv/opencv#14319]
why set automatically BUILD_opencv_python3 to OFF?

Trying to upgrade OPENCV to 4.1.0, but it's more difficult to binding it to python (3.7). I realize that cmake-gui never show BUILD_opencv_python3, different with opencv 4.0.0

then i see this script in Cmakelist.txt, never choose to turn it off

//Module opencv_python2 can not be built in current configuration
HAVE_opencv_python3:INTERNAL=OFF

I think this is the problem, should be not automatically set to OFF

**Comment by alalek** [comment]
It is disabled because required dependencies are not available.
You should check for required dependencies (python-devel, numpy and/or activated virtualenv) first.
If you change "external" configuration (upgrade python, compiler or other external libs), then you should clean CMake cache too (clean build directory is enough).

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by wahyubram82** [comment]
i already have opencv 4.0.0 with cuda and darknet yolo v3.

just want to upgrade to 4.1.0, means: all requirements not a problem
