### ISSUE TITLE
calibrateCameraRO fails with iFixedPoint>0 (new method for imperfect target)

### ISSUE THREAD

**Issue by nightgryphon** [opencv/opencv#14469]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32

##### Detailed description
Possible bug in calib3d calibrateCameraRO.  

I'm trying to use the new more accurate camera calibration method [182] "More accurate pinhole camera calibration with imperfect planar target." as described in documentation and camera calibration tutorial. When i use calibrateCameraRO for old slyle camera calibration with iFixedPoint = -1 everything work fine. But the same with iFixedPoint = pattern_width-1 fails with an error:  
```
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\core\src\matmul.dispatch.cpp:337: error: (-215:Assertion failed) type == B.type() in function 'cv::gemm'
```
##### Steps to reproduce
Using samples code samples/python/calibrate.py add this line after call to calibrateCamera at line 100:
```
    rms, camera_matrix, dist_coefs, rvecs, tvecs, newObjPoints2  = cv.calibrateCameraRO(
                        obj_points, img_points, (w, h), int(pattern_size[0]-1),
                        camera_matrix, dist_coefs, rvecs, tvecs, None, cv.CALIB_USE_INTRINSIC_GUESS | cv.CALIB_USE_LU, 
                        (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30,  2.2204460492503131e-16)  );
```
Run with opencv sample data set.

Throws error:
```
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\core\src\matmul.dispatch.cpp:337: error: (-215:Assertion failed) type == B.type() in function 'cv::gemm'
```

**Comment by nightgryphon** [comment]
This function become available in 4.0.0. Is milestone 3.4.7 ok?

**Comment by CobbsLab** [comment]
Same issue on the C/C++ code.

whit iFixedPoint > 0 I get:

`libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.1.0) /tmp/opencv-20190505-12101-14vk1fh/opencv-4.1.0/modules/core/src/matmul.dispatch.cpp:337: error: (-215:Assertion failed) type == B.type() in function 'gemm'`

**Comment by mattmyne** [comment]
This can currently be resolved by always providing at least one non-null standard deviation output array to calibrateCameraRO() (even if you have no need to otherwise).

So for C++ use [full parameter calibrateCameraRO](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga11eeb16e5a458e1ed382fb27f585b753) with one of `stdDeviationsIntrinsics`, `stdDeviationsExtrinsics` or `stdDeviationsObjPoints` being a predefined cv::Mat (the others can be noArray()). For python, I think the equivalent is to use cv.calibrateCameraROExtended() and specify at least one standard deviation parameter.

This works because of what I think is a bug in `calib3d/src/calibration.cpp` that causes the line [here](https://github.com/opencv/opencv/blob/61cc85556456bdddec769afbe9dfba21228348ca/modules/calib3d/src/calibration.cpp#L1762) to try and multiply an empty matrix `_Jo` when `calcJ` is true but `allocJo` is false. Defining at least one non-null standard deviation OutputArray always causes `allocJo` to be true (see [here](https://github.com/opencv/opencv/blob/61cc85556456bdddec769afbe9dfba21228348ca/modules/calib3d/src/calibration.cpp#L1591)).

The error occurs when `solver.state` does not equal `CvLevMarq::CALC_J` when setting the `allocJo` flag (making it false), but the solver state later switches to `CvLevMarq::CALC_J` making `calcJ` true and subsequently trying to multiply the unallocated _Jo.

This can be patched by always setting 'allocJo' true when using the RO version of calibrateCamera (potentially using a little unnecessary memory?) since it appears `_Jo` should always be allocated for the expected RO behaviour, but is rightly not always needed in the non-RO mode.

I've submitted a pull request #15451

**Comment by jhacsonmeza** [comment]
I also have problems using calibrateCameraRO in Python. I wait for more than five minutes and it does nothing. It does not return anything or any error arises, only stay running infinitely.

My system details:
* OpenCV: 4.0.1
* OS: Windows 10 (64 Bit)
* Python 3.7.3

Function presents the same behavior if I provide a standard deviation parameter as suggested.

**Comment by lingbo-yu** [comment]
Is the problem solved? I have encountered the same problem.

**Comment by apurvazaveri** [comment]
Ya, same problem here. Is this resolved?

**Comment by thewoz** [comment]
For sure the problem was fixed in the last version of the code

**Comment by YsanZyh** [comment]
I meet the same problem today. Can you help me?

`R1, R2, P1, P2, Q, roi1, roi2 = cv2.stereoRectify(left_K, left_distortion, right_K, right_distortion, (width, height), R, T, alpha=1)`

error:
`cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\matmul.dispatch.cpp:337: error: (-215:Assertion failed) type == B.type() in function 'cv::gemm'`
