### ISSUE TITLE
Inside pip opencv different version from python

### ISSUE THREAD

**Issue by DanTreg** [opencv/opencv#14495]
##### System information (version)
- OpenCV = 4.0
- Operating System / Platform => Ubuntu 16.04; 

##### Detailed description
So I have been trying to run some dnn libraries but I got next error:
```
Build OpenCV with Inference Engine to enable loading models from Model Optimizer. in function 'readFromModelOptimizer'
```

Then when I run:
```
import cv2
cv2.__version__
```
I get this:
```
'3.4.6-dev'
```
However if I run pip freeze, I get this:
```
opencv-contrib-python-headless==4.0.0.21
opencv-python==4.0.0.21

```
I believe OpenCV was compiled with OpenVino because, in folder with OpenVino I have another file opencv and i also have next bash file:
```
#!/usr/bin/env bash
export OpenCV_DIR=/opt/intel/computer_vision_sdk_2018.5.445/opencv/cmake
export LD_LIBRARY_PATH=/opt/intel/computer_vision_sdk_2018.5.445/opencv/lib:$LD_LIBRARY_PATH
```

So my question is, what am I doing wrong?

**Comment by alalek** [comment]
Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

---

You have mess with your Python installations.

> OpenCV_DIR

For Python you should take a look on PYTHONPATH variable.
OpenVINO setup vars must be called **after** virtualenv activation.

> pip freeze

can't show OpenVINO bindings (because they are not installed via `pip`)
