### ISSUE TITLE
Integrate OpenCV 4.0 with Android studio 3.4.1 ( Java language )

### ISSUE THREAD

**Issue by abdou31** [opencv/opencv#14924]
##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Windows 10 x64 
- Android studio : 3.4.1

##### Detailed description

I have android studio installed and I want to use OpenCV 4.0.1 with Android Studio 3.4.1 with Java.
I follow those [instructions](https://www.youtube.com/watch?v=VRLfzi5bdJs) but it seems that UI of the Android studio is different in the previous version, so I want to know what are instructions should I follow to get OpenCV working on Android Studio?
Thanks.

**Comment by alalek** [comment]
Mentioned instruction can't help with OpenCV 4.x (because instruction is outdated and Android package has been reworked in Dec 2018).

Try to open samples from OpenCV Android package. If you properly install Android SDK, Android NDK and required dependencies then it should work "from the box" (at least for Android Studio 3.2.1).


> UI of the Android studio is different in the previous version

Unfortunately we can help here - you have to learn how to use Android Studio. This is off-topic for OpenCV.

**Comment by abdou31** [comment]
You did not answer my question and you did not give any documentation how can I use OpenCV 4.0 with Android Studio 3.4.1 using SDK.
I really need this for using with tensorflow mobile 
Thanks

**Comment by StidOfficial** [comment]
In OpenCV-android-sdk/sdk/build.gradle file, you have all instructions :

```
// - Android Studio way:
//   (will copy almost all OpenCV Android SDK into your project, ~200Mb)
//
//   Import module: Menu -> "File" -> "New" -> "Module" -> "Import Gradle project":
//   Source directory: select this "sdk" directory
//   Module name: ":opencv"
...
// Add dependency into application module:
//
// - Android Studio way:
//   "Open Module Settings" (F4) -> "Dependencies" tab
```

He worked with OpenCV 4.2.0 and Android Studio 3.5.2
