### ISSUE TITLE
Video file reading gives Codec related  error

### ISSUE THREAD

**Issue by dvatsal** [opencv/opencv#14987]
![image](https://user-images.githubusercontent.com/1464312/60732223-1ee0af00-9f67-11e9-8fa6-e84aa6a41d5d.png)

I receive this message while trying to read a video file with extension mp4.

This is on The opencv version is 

##### System information (version)

- OpenCV => OpenCV 4.1
- Operating System / Platform => windows 10 pro
- Compiler => Python 3.6 (anaconda enviornment)
##### Detailed description

I have got a video from Hikvision IP camera DVR.That video can be viewed well in VLC and other applications however when I try to read it using OpenCV it gives the codec related error

**Comment by alalek** [comment]
It is ridiculous to post text messages via screenshots. Avoid that. Screenshots block searching for similar issues.

> I try to read it using OpenCV it gives the codec related error

Mentioned messages have nothing related to your camera. Or input video stream.
Because these messages are from VideoWriter (feel free to use code search) - about unsupported passed `fourcc` parameter.

> error

"error message"

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
