### ISSUE TITLE
how to install specific version of opencv on mac with brew?

### ISSUE THREAD

**Issue by IvyGongoogle** [opencv/opencv#15191]
Hello, it seems that I can only install opencv3.4.5 by running `brew install opencv@3`, but how to install specific version of opencv(like 3.4.0) on mac with brew?
Anyone can give some advises?

**Comment by Noctem** [comment]
```bash
brew edit opencv@3
```

And change the version number in the `url` to the desired one, and change the `sha256` to match the file you specified.

It would also be a good idea to [create a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap), especially if you want to customize or add multiple formulae.

**Comment by eofreire** [comment]
How do I find the sha256 to mach the file specified by me?

**Comment by shnaqvi** [comment]
Along the lines of @Noctem but better yet, you should override the content of your local `opencv.rb` file with that of the remote `opencv.rb` file found in brew's GitHub repo, that corresponds to the version of opencv you want to install. 

This way you get all the sha256 which are otherwise not available for the `tar.gz` files available on the Opencv's Releases GitHub page at: https://github.com/opencv/opencv/releases

Here's the breakdown of the steps:

1. Uninstall opencv: `brew uninstall opencv@4`
2. Open `opencv.rb` file:  `brew edit opencv@4`
3. Find the `opencv.rb` file on brew’s github page from its history of commits corresponding to the version of opencv you want to use: https://github.com/Homebrew/homebrew-core/commits/master/Formula/opencv.rb
4. Replace the contents of your local `opencv.rb` file with that of this remote `opencv.rb` file
5. Install opencv again: `brew install opencv@4`

This should work for other packages/formulas on brew as well. Though I haven't tried it.
