### ISSUE TITLE
image pixel location to world co-orinates opencv-python

### ISSUE THREAD

**Issue by chaitanyantr** [opencv/opencv#15387]
-->
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => ubuntu 16.04
- Compiler => python
-->

Purpose:- The camera from a drone detect an object ,i want the detected target in world co-orinates(distance in x,y,z wrt camera)

1.I have camera matrix ,dist matrix of webcam,and in python code i'm multiplying the pixel location (center) with the inverse of camera matrix to get the world co-ordinates.

But the result is not in world co-ordinates. am i missing somewhere.?

camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 5.4014190422145293e+02, 0., 3.2592120378599321e+02, 0.,
       5.3886426820909787e+02, 2.2949992756422435e+02, 0., 0., 1. ]
dist_coeff: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.1732796767172591e-01, -8.2829250344969640e-01,
       -6.4060273618329350e-03, 1.0422470844751927e-03,
       9.3098139284766768e-01 ]

    //python code example
   

P = np.array([[7.9140218607464226e+02, 		0.000000e+00,			 5.0316927833967725e+02], 
              		  [0.000000e+00, 				7.8965880952273460e+02,  2.8858718240614047e+02], 
              		  [0.000000e+00, 				0.000000e+00,			 1.00000]])

		P_inv = np.linalg.pinv(P)
		#print('cam_mat',P_inv)
		image_co = np.matrix([[center[0]],[center[1]],[1]])#[u,v,1]
		world_co = P_inv*image_co
		print(world_co)

**Comment by catree** [comment]
You cannot inverse the camera intrinsic matrix and expect to retrieve the depth of the scene.

That's why you have two eyes, and a brain to infer depth using also some prior knowledge / assumption. Head movement is also used, e.g. the [depth perception in the pigeon](https://www.researchgate.net/publication/19202602_Binocular_depth_perception_in_the_pigeon).

Here some computer vision materials:
 - [Computer Vision: Algorithms and Applications, Richard Szeliski](http://szeliski.org/Book/drafts/SzeliskiBook_20100903_draft.pdf)
 - [CS231A: Computer Vision, From 3D Reconstruction to Recognition](http://web.stanford.edu/class/cs231a/syllabus.html)
