### ISSUE TITLE
undefined reference to cv::imread

### ISSUE THREAD

**Issue by shivSD** [opencv/opencv#15426]
Hi,

I have built Opencv3.4.5 with cuda support and below is the cmake command and after compiling opencv 3.4.5 and installing it i get following error while testing it. Please can you correct me if there is anything wrong in cmake command. cuda10.0 installed on GTX 1080, OS- ubuntu.

g++ -o test test.cpp /tmp/ccK24DIr.o:
In function main': test.cpp:(.text+0xfb): **undefined reference to cv::imread(cv::String const&, int)'**

**cmake command:** 
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D WITH_CUDA=ON -D WITH_TBB=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python -D WITH_QT=OFF -D BUILD_EXAMPLES=OFF -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D CUDA_NVCC_FLAGS=--expt-relaxed-constexpr -D WITH_LIBV4L=ON -D WITH_V4L=ON ..

thanks in advance

**Comment by yasamoka** [comment]
cv::imread involves functions implemented in libopencv_core.so and libopencv_imgcodecs.so. You can find those in /usr/local/lib since you installed OpenCV to /usr/local.

What you are getting here is a linker error. GCC fails to link the compiled result of your code to the function being called.

Add the linker flags "-lopencv_core" and "-lopencv_imgcodecs" as such:
```
g++ -o test test.cpp -lopencv_core -lopencv_imgcodecs
```
The error should be gone.

**Comment by shivSD** [comment]
Thanks i totally forgot to link libraries. this is what happens if you start working too much on python :)
