### ISSUE TITLE
Failed to build with python2

### ISSUE THREAD

**Issue by seraphzl** [opencv/opencv#15469]
##### System information (version)

- OpenCV => master
- Operating System / Platform => Linux (CentOS 6.10 x64)
- Compiler => cmake 3.13.4, gcc/g++ 4.8.5

##### Detailed description
The python2 is found, but failed to build. The output is:

-- Found PythonInterp: /home/lz/app/python-2.7.15/bin/python (found suitable version "2.7.15", minimum required is "2.7") 
-- Found PythonLibs: /home/lz/app/python-2.7.15/lib/libpython2.7.a (found suitable exact version "2.7.15") 
-- Could NOT find PythonInterp: Found unsuitable version "2.7.15", but required is at least "3.2" (found /home/lz/app/python-2.7.15/bin/python)
...
--     Unavailable:                 java js python2 python3
...
--   Python (for build):            /home/lz/app/python-2.7.15/bin/python
...

##### Steps to reproduce
CMake build with "-D PYTHON2_PACKAGES_PATH=$HOME/app/opencv-4.1.1-dev/lib/python2.7/site-packages -D PYTHON2_EXECUTABLE=$HOME/app/python-2.7.15/bin/python
-D PYTHON2_LIBRARY=$HOME/app/python-2.7.15/lib/libpython2.7.a -D PYTHON2_INCLUDE_DIR=$HOME/app/python-2.7.15/include/python2.7 -D PYTHON2_NUMPY_INCLUDE_DIRS=$HOME/app/python-2.7.15/lib/python2.7/site-packages/numpy/core/include", but it failed to build the python2 binding.

**Comment by alalek** [comment]
During each experiment clean your build directory (because CMake has cache of external dependencies and you are playing with them).
Try to add `PYTHON2_INCLUDE_PATH` with the same value as `PYTHON2_INCLUDE_DIR`.
`numpy` is required for OpenCV bindings (`import numpy` should work).

> /home/lz/app/python-2.7.15

Is this virtualenv from system python? Perhaps is OK.
custom python setup (other than system) - unpredictable.

> libpython2.7.a

`.so` file is expected here.
Using static lib is not a good idea (python may crash after loading of C++ extensions especially after upgrade).

---

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
This tracker is for issues and bugs that needs fix in OpenCV.
