### ISSUE TITLE
/usr/bin/ld: cannot find -llib64 when compiling with CUDA

### ISSUE THREAD

**Issue by onno182** [opencv/opencv#15892]
When compiling the latest version with CUDA, the linker gives the following error:

`/usr/bin/ld: cannot find -llib64`

This library is nonexistent on Debian and OpenSC compiles fine when removing this.

**Comment by RuRo** [comment]
I am having similar(?) problems on Arch. I think that the problem is due to the `opencv4.pc` config for `pkg-config`.

The `Libs.private` string ends with

```
-L-L/opt/cuda -llib64 -L-L
```

Which looks malformed to me, since `lib64` is not a real library as far as I can tell and the `-L` is duplicated for some reason.

I think, the issue has to be somewhere in `cmake/OpenCVGenPkgconfig.cmake` in the `OPENCV_PC_LIBS_PRIVATE` variable.

**Comment by alalek** [comment]
@RuRo Thank you for investigation!

Auto generation of .pc file is not well supported (simple case works only).
Also it is disabled by default (due zero support of that from maintainers team - our recommendation is using CMake's `find-package()`) - check #13154

**Comment by Midhun7495** [comment]
I'm also facing this issue. I'm trying to install opencv4 with CUDA 10.1. The make doesn't complete and gives this same error. Is it some bug?

**Comment by sasan-m** [comment]
Same issue here.

Latest code from repo as of 18 Feb 2020.
Cuda 10.1
Ubuntu 19.10

**Comment by sasan-m** [comment]
In my case this was due to CUDNN_LIBRARY being set to the wrong path. cmake hadn't been able to find cudnn, so I'd manually set the path variables using -D CUDNN_INCLUDE_DIR and -D CUDNN_LIBRARY. The former must point to the folder containing "cudnn.h" (in my case "/usr/lib/cuda/include"). The latter must point to the folder **containing the "lib64" folder** (in my case "/usr/lib/cuda" - don't put "lib64" at the end). Don't forget to set CUDNN_VERSION if you're going manually.

I also faced a couple of other issues to do with a bug in cmake v3.13 which wouldn't let cmake find lpthreads -- an upgrade to cmake 3.16 fixed it. Also, for some reason IPP modules were causing fatal errors during compile, so I set WITH_IPP to OFF which I don't need anyway.

**Comment by sangkisuke** [comment]
> In my case this was due to CUDNN_LIBRARY being set to the wrong path. cmake hadn't been able to find cudnn, so I'd manually set the path variables using -D CUDNN_INCLUDE_DIR and -D CUDNN_LIBRARY. The former must point to the folder containing "cudnn.h" (in my case "/usr/lib/cuda/include"). The latter must point to **libcudnn.so** -- not the folder containing it(in my case "/usr/lib/cuda/lib64/libcudnn.so").
> 
> Don't forget to set CUDNN_VERSION if you're going manually.
> 
> I also faced a couple of other issues to do with a bug in cmake v3.13 which wouldn't let cmake find lpthreads -- an upgrade to cmake 3.16 fixed it.

I have been stuck at this for days.. i manually point the cudnnlibrary to the folder because CMAKE cant find it.. 
"/usr/lib/cuda/lib64/libcudnn.so" suggestion help me from getting 'unstuck' 💯 . many thanks!
