### ISSUE TITLE
Point could be made optional when the size of the src is the same as dest?

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#15928]
https://github.com/opencv/opencv/blob/1acadd363b0d0ffcdabac8af3196cb65bef426b1/modules/photo/src/seamless_cloning.cpp#L82

When src is the same as desk, and a mask is provided, the expected behaviour could be to blend the dest inside the src where the mask are 255,255,255 instead of requiring the p (the centre) to be specified?

I had 
```
src.shape   = 500,500
src_mask    = 500,500
dest.shape = 500,500

h, w = src_mask.shape[:2]
```
at this point I didn't see the use of the required argument p, as I expected the function to match the mask. But since it's a required argument, I provided `(w//2, h//2)` for p (the centre of everything). But instead of having the src aligned into dest, the resulting cloning was shifted up to the centre of the screen!

**Comment by alalek** [comment]
Documentation says that "p" is:
> Point in dst image where object is placed.

---

> I didn't see the use of the required argument p

Are you expecting API of "normalClone()"? (it is not exposed in public API)

**Comment by tati-z** [comment]
Hey alalek, thank you for the response. 
**Yes, I was expecting the behaviour of normalClone()**.
I have tried using (src.mask.width, src.mask.height) as value of p like:
```python
out=cv2.seamlessClone(src, dest, dest_mask,(dest_mask.shape[1], dest_mask.shape[0]),flags= cv2.NORMAL_CLONE)`
```
so that p.x and p.y in the implementation get set to (0,0), causing the rectangle to align at (0:0, w:h) but I am now getting an error:
`cv2.error: OpenCV(4.1.2) /tmp/opencv-20191011-54662-iy13f9/opencv-4.1.2/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'`

is there any way I can use the public API to have the behaviour of normalClone()?

**Comment by tati-z** [comment]
i have just also noticed that a bounding rect is put around the mask beforehand [Rect roi_s = boundingRect(mask);](https://github.com/opencv/opencv/blob/a7b954f6551e62ead3b5ac4ab5b34da3da6b3b43/modules/photo/src/seamless_cloning.cpp#L80)
this explains why the ROI gets shifted.
I guess in the meantime i will make a dummy 1px white line around the mask

**Comment by tati-z** [comment]
I got the expected behaviour by using a rect of thickness 2 
```python
h, w = src_mask.shape[:2]
# rect of thickness > 1
cv2.rectangle(src_mask,(0,0), (w, h) ,255, 2)
# the clone will now aligns from the centre
out=cv2.seamlessClone(src, dest, src_mask,(w//2, h//2),flags= cv2.NORMAL_CLONE)
```
a rect of 1 thickness did not work.

**Comment by alalek** [comment]
@sturkmen72 I believe request here is for avoiding mask ROI handling through `boundingRect()`. Or at least use the same ROI for destination, like this:

```
Rect roi_s = boundingRect(mask);
if (roi_s.empty()) return;

Rect roi_d = roi_s;
if (p.x == -1 && p.y == -1)
{
    CV_Assert(src.size() == dest.size());
}
else
{
    roi_d = Rect(p.x - roi_s.width / 2, p.y - roi_s.height / 2, roi_s.width, roi_s.height);
}
```
