### ISSUE TITLE
How can I get Coordinates of Points of Contour corners in OpenCV.js?

### ISSUE THREAD

**Issue by sundowatch** [opencv/opencv#16162]
I'm using OpenCV.js with JavaScript and trying to get points of an approxPolyDP return. Here is my code:

```
let src = cv.imread(imgElement);
let contours = new cv.MatVector();
let hierarchy = new cv.Mat();
let poly = new cv.MatVector();

cv.findContours(src, contours, hierarchy, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE);

let cnt = contours.get(0);

cv.approxPolyDP(cnt, poly, 0.02 * peri, true);
```

That draws perfect with drawContours() function. But I want to get the coordinates of points of the corners. It's simple to get it on Python, but not JavaScript.

How can I get the points' coordinates of corners? Is there a function regarding that?

**Comment by ColinEberhardt** [comment]
The coordinates are stored in the `cv.MatVector`, which is a wrapper around the underlying C++ representation of the data.

You can obtain its size as follows:

```
> poly.size()
{width: 1, height: 3}
```
In this case it is a 1 dimensional array with 3 datapoints, i.e. a polygon with three vertices. You can inspect the underlying data as follows:

```
> poly.data
Uint8Array(24) [243, 1, 0, 0, 16, 2, 0, 0, 236, 1, 0, 0, 20, 2, 0, 0, 243, 1, 0, 0, 20, 2, 0, 0]
```
You'll notice that this is more than the 6 points you'd expect for 3 vertices. This is because you need to use the correct data 'accessor' that matches the underlying encoding. In this case, the vertices are stored as unsigned 32 bit integers.

```
> poly.data32S
Int32Array(6) [499, 528, 492, 532, 499, 532]
```
And there you have your datapoints!

**Comment by ramasai-badam** [comment]
is that possible in python ? getting the coordinates of corner points in contours ?

**Comment by ramasai-badam** [comment]
> The coordinates are stored in the `cv.MatVector`, which is a wrapper around the underlying C++ representation of the data.
> 
> You can obtain its size as follows:
> 
> ```
> > poly.size()
> {width: 1, height: 3}
> ```
> 
> In this case it is a 1 dimensional array with 3 datapoints, i.e. a polygon with three vertices. You can inspect the underlying data as follows:
> 
> ```
> > poly.data
> Uint8Array(24) [243, 1, 0, 0, 16, 2, 0, 0, 236, 1, 0, 0, 20, 2, 0, 0, 243, 1, 0, 0, 20, 2, 0, 0]
> ```
> 
> You'll notice that this is more than the 6 points you'd expect for 3 vertices. This is because you need to use the correct data 'accessor' that matches the underlying encoding. In this case, the vertices are stored as unsigned 32 bit integers.
> 
> ```
> > poly.data32S
> Int32Array(6) [499, 528, 492, 532, 499, 532]
> ```
> 
> And there you have your datapoints!

Is this possible in python ?
