### ISSUE TITLE
i,m trying to detect objects in an hsv image with the help of trackbar and mask   -->    res = cv.bitwise_and(frame,frame,mask=mask)   TypeError: Expected Ptr<cv::UMat> for argument '%s'

### ISSUE THREAD

**Issue by abhishek9069** [opencv/opencv#16311]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by abhishek9069** [comment]
here is the code 
pls help me to resolve this :

def nothing(x):
    pass
cv.namedWindow("Tracking")
cv.createTrackbar("LH","Tracking",0,255,nothing)
cv.createTrackbar("LS","Tracking",0,255,nothing)
cv.createTrackbar("LV","Tracking",0,255,nothing)
cv.createTrackbar("UH","Tracking",255,255,nothing)
cv.createTrackbar("US","Tracking",255,255,nothing)
cv.createTrackbar("UV","Tracking",255,255,nothing)
while True:
    frame = cv.imread("C:/Users/acer/Desktop/insects/New folder/ins.jpg")
    hsv = cv.cvtColor(frame,cv.COLOR_BGR2HSV)
    
    l_h = cv.getTrackbarPos("LH","Tracking")
    l_s = cv.getTrackbarPos("LS","Tracking")
    l_v = cv.getTrackbarPos("LV","Tracking")
    
    u_h = cv.getTrackbarPos("UH","Tracking")
    u_s = cv.getTrackbarPos("US","Tracking")
    u_v = cv.getTrackbarPos("UV","Tracking")
    
    l_b = np.array([l_h,l_s,l_v])
    u_b = np.array([u_h,u_s,u_v])
    
    mask = (hsv,l_b,u_b)
    
    res = cv.bitwise_and(frame,frame,mask=mask)
    
    cv.imshow("frame",frame)
    cv.imshow("mask",mask)
    cv.imshow("res",res)
    
    key = cv.waitKey(1)
    if key == 27:
        break
cv.destroyAllWindows()

**Comment by alalek** [comment]
This message means that passed parameters are not valid or not supported.
This can't be fixed in OpenCV, so you should fix your code.

Message itself has been fixed, however it may be useless (last error is showed only, not the real reason).
Latest OpenCV versions (3.4.9/4.2.0) have `OPENCV_PYTHON_DEBUG=1` environment variable which may help with investigation of such problems.

---

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by abhishek9069** [comment]
can u tell me how can i fix my code?
