### ISSUE TITLE
SimpleBlobDetector filterByColor fails

### ISSUE THREAD

**Issue by charlie0389** [opencv/opencv#16411]
##### Overview

With the SimpleBlobDetector, the filterByColor parameter creates incorrect results when running the detector's detect function. Below is an example of a failure to detect a large black blob in a black & white image, with all other filtering options turned off.

Referenced image can be found at: [https://imgur.com/tgcI5XB](https://imgur.com/tgcI5XB)

##### System information (version)
- opencv-python 4.1.2
- Operating System / Platform => Ubuntu 18.04 64-bit

##### Steps to reproduce

1. Execute the below code (assuming "filterByColor_bug.png" is in the working directory). Note that the shadow of the highlighter (a large black blob) is not detected.
2. Change this line:
`params.filterByColor = True # Toggle only this line`
To:
`params.filterByColor = False # Toggle only this line`
3. Execute the code again. Note that the shadow is now detected.

Please note that this line:
`assert(set(un_vals) == set([0,255])) # Proves that only 'colours' in image are 0 and 255`

Proves that all pixels are 0 or 255 (i.e. black or white).

```
import cv2
import itertools as it
import numpy as np

test_photo = r"filterByColor_bug.png"
image_threshold = cv2.imread(test_photo, cv2.IMREAD_GRAYSCALE)

# ------- this part proves image is black and white only-----------
un_vals = set(list(it.chain(*image_threshold)))
assert(set(un_vals) == set([0,255])) # Proves that only 'colours' in image are 0 and 255
# -------------------------------------------------------------------------------

params = cv2.SimpleBlobDetector_Params()

params.minThreshold = 127
params.minRepeatability = 1
params.filterByCircularity = False
params.filterByInertia = False
params.filterByArea = False
params.filterByConvexity = False

params.filterByColor = True # Toggle only this line
params.blobColor = 0

detector = cv2.SimpleBlobDetector_create(params)
keypoints = detector.detect(image_threshold)

image_keypoints = cv2.drawKeypoints(image_threshold, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# -------- display the detected blobs ----------------
win_name = "Display Window"
cv2.namedWindow(win_name,cv2.WINDOW_NORMAL)
cv2.imshow(win_name,image_keypoints)
cv2.waitKey(0)
cv2.destroyWindow(win_name)
```

**Comment by charlie0389** [comment]
Even if only confirmation that this is a bug could be provided, this would still be very useful.

**Comment by alalek** [comment]
See documentation of [SimpleBlobDetector](https://docs.opencv.org/3.4.9/d0/d7a/classcv_1_1SimpleBlobDetector.html).

> **By color.** This filter compares the intensity of a binary image at the center of a blob to blobColor. If they differ, the blob is filtered out. Use blobColor = 0 to extract dark blobs and blobColor = 255 to extract light blobs.

Filtering code is [here](https://github.com/opencv/opencv/blame/3.4.9/modules/features2d/src/blobdetector.cpp#L273-L277).

> highlighter (a large black blob) is not detected.

Actually, It is detected, but it is filtered as requested by sample code.

Try `params.blobColor = 255` to see detection center of this object (blob's center is "white").

---

`FilterByColor` works as expected (described in documentation).

Perhaps you want own filtering process. So extract all candidates (with disabled color filtering) and then filter out them in your app directly (using some own algorithm).

**Comment by charlie0389** [comment]
Can I please suggest a fix for the [SimpleBlobDetector documention](https://docs.opencv.org/master/d0/d7a/classcv_1_1SimpleBlobDetector.html) - i.e. add the text in bold:

By color. This filter compares the intensity of a binary image at the center of a blob to blobColor. If they differ, the blob is filtered out. Use blobColor = 0 to extract ~~dark~~ blobs **with dark centers** and blobColor = 255 to extract ~~light~~ blobs **with light centers - note that the color at the center of the blob may differ to the color of the blob itself.**

**Comment by alalek** [comment]
Sure, Feel free to propose Pull Request with update to 3.4 branch

**Comment by mlgtechuser** [comment]
I don't have a local repository for this project, so can't submit a pull request as alalek recommends.  Nevertheless...

Thank you for your detailed report, @charlie0389.  I read [HERE](https://learnopencv.com/blob-detection-using-opencv-python-c/) that the filterByColor function has/had a bug and appreciate your raising the issue to clarify that this is a non-intuitive behavior rather than a bug.

I've updated my reference notes on simpleBlobDetector per your language and have an additional refinement: replacing the term 'center' with ['centroid'.](https://ahdictionary.com/word/search.html?q=centroid)  This avoids the ambiguity that you encountered, where "center" encourages one to assume that the center is within the detected blob body.  Centroid is a standard term to indicate an object's center of mass.  A C-channel, for example, has a centroid somewhere within the mouth of the 'C'.

_Use blobColor = 0 to extract blobs with a dark **centroid** and blobColor = 255 to extract  blobs with a light **centroid**.
NOTE: the color at the **centroid** of the blob may differ to the color of the blob itself, given that a **centroid** of a blob may reside outside of the blob._

For anyone who wonders how one could intuit that the "center" lies within a curved blob's body, consider that a wing has a chord running down its center.  If the midpoint of this chord is taken as the "center" of the wing--a very reasonable and useful definition--the center of an extremely curved wing will still lie within the cross section of the wing.
