### ISSUE TITLE
Android install aar

### ISSUE THREAD

**Issue by huangqinjin** [opencv/opencv#16454]
I found that building opencv for android produced `opencv-release.aar` under `build/opencv_android/opencv/build/outputs/aar`. It's useful if this file gets installed. For a android project depending on opencv, we can simply declare gradle dependencies like below
```
dependencies {
     implementation files('libs/opencv-release.aar')
}
```
rather than adding a module and then copy scoure files into it and build together with our projects.

**Comment by yangcheng** [comment]
that's what I did in my local project. there are several thirdparty repos on github offering pre-build aars but none is well maintained and up to date. Really hope opencv can officially support release library as aar and publish to maven central or jitpack

**Comment by hannesa2** [comment]
I helped myself https://github.com/hannesa2/LiveEdgeDetection/blob/master/library/build.gradle#L32-L35 and there is  always latest release available. It's built by my own CI, because it is too big for github as a free repository, and I've issues with jitpack.io to publish it https://github.com/jitpack/jitpack.io/issues/4119

**Comment by asmorkalov** [comment]
https://central.sonatype.com/artifact/org.opencv/opencv/overview
