### ISSUE TITLE
Cant access google groups dev forum

### ISSUE THREAD

**Issue by tompollok** [opencv/opencv#16511]
As announced on https://opencv.org/opencv-hackathon-is-coming/

There is a link to: https://groups.google.com/forum/#!forum/opencv-dev-forum

But unfortunately i cant access it: Error: # 418 "You Do Not Have Permission"

Does it need an invitation?

**Comment by mihaibujanca** [comment]
On a similar note, the link to the slack channel (not sure if it's used at all) is expired

**Comment by boulabiar** [comment]
I think the google group is not used anymore since around 2015?

**Comment by tompollok** [comment]
Then why was it part of the Hackaton anouncement?

**Comment by asmorkalov** [comment]
@vpisarev Could you handle this?

**Comment by berak** [comment]
same problem here: https://groups.google.com/forum/#!forum/opencv-gsoc-2020

**Comment by asmorkalov** [comment]
@vpisarev Friendly reminder.

**Comment by vpisarev** [comment]
@tompollok, @berak, @asmorkalov, terribly sorry for the slow reaction. Soon after noticing the problem I adjusted the settings, but did not test it properly, and was sure the problem is fixed. Now it should have been finally fixed. Too late for this hackathon, but for next hackathon it should work :) I've also fixed permissions for the gsoc forum, @berak, thanks for reporting it!

**Comment by tompollok** [comment]
works now
