### ISSUE TITLE
Cannot build opencv 4.1.2. with CUDA on Jetson TX2

### ISSUE THREAD

**Issue by mesimolnar** [opencv/opencv#16541]
Hello,

I have to use CUDA on my JETSON TX2 devkit, but I cannot build the opencv 4.1.2 with CUDA.
Without -D WITH_CUDA option the cmake command can be run, but if I use this option, in the and it says : Configuring incomplete, errors occured, and in the log files I don't see any reason of it.
Have anyone else this problem, and how can I solve this.

**Comment by Ayke** [comment]
Mine had the same problem. But I finally made it with '-D WITH_CUDA'. You should look into the specific error it pops up, and try to solve that error

**Comment by WisdomPill** [comment]
Have a look at this https://github.com/jetsonhacks/buildOpenCVTX2

**Comment by mesimolnar** [comment]
Dear all! I could install it, but in c++ I cannot use it. The CUDA relevant headers are in the opencv4/openc2 dir, but the compiler cannot see this. e.g. cudaarithm.hpp. Have you any idea for the problem solution?

**Comment by Ayke** [comment]
I can only guess, my suggestion is to install opencv with '-D WITH_CUDA', '-D OPENCV_GENERATE_PKGCONFIG=YES'

If opencv in python works but doesn't work in C++, it is probably because of pkgconfig, which corresponds to the latter command. Also I have install opencv on tx2 just days ago, you can take a look at my gist as well, feel free to write comments!

**Comment by YashasSamaga** [comment]
@mesimolnar https://answers.opencv.org/question/209687/which-gcc-compiler-is-need-to-run-opencv4-code/?answer=209754#post-id-209754

**Comment by mesimolnar** [comment]
@YashasSamaga thank you it is worked :)
