### ISSUE TITLE
Possible bug in cornerHarris

### ISSUE THREAD

**Issue by YoniChechik** [opencv/opencv#16624]
##### System information (version)
- OpenCV => 3.4.8.29
- Operating System / Platform => Windows10 64 Bit
- Compiler => python

##### Detailed description

a posible bug in harris corner detector:
this are inputs and outputs of a constant gradient to cornerHarris:
```
import cv2
import numpy as np
import plotly.express as px

x = 10
aa = [[np.array(range(x))+2*i] for i in range(x)]
a = np.block(aa).reshape(x,x)
a = (a/np.max(a)*255).astype(np.uint8)
# a = 10*np.array(range(x**2)).reshape(x,x)
px.imshow(a).show()

res = cv2.cornerHarris(a.astype(np.uint8), 5, 5, 0.04)
px.imshow(res).show()
```
![image](https://user-images.githubusercontent.com/16686924/74941093-202df180-53fb-11ea-9963-499c2b97e454.png)

- Boarder is wrong.
- As I saw in the source code, you are using the covariance matrix of the patch without subtracting the mean. Why is this? I can think of this as PCA without subtracting the mean- which can result in an error

**Comment by catree** [comment]
> Boarder is wrong.

You should look at the [documentation](https://docs.opencv.org/) and test with different boarder types.
Also, try, compare with [`skimage.feature.corner_harris`](https://scikit-image.org/docs/0.16.x/api/skimage.feature.html#skimage.feature.corner_harris).

> As I saw in the source code, you are using the covariance matrix of the patch without subtracting the mean. Why is this? I can think of this as PCA without subtracting the mean- which can result in an error

There are many resources that describe the method, e.g. [Szeliski](http://szeliski.org/Book/drafts/SzeliskiBook_20100903_draft.pdf#page.212) or the [IPOL paper](https://www.ipol.im/pub/art/2018/229/).

**Comment by catree** [comment]
@YoniChechik 

I like [your courses](http://www.aiismath.com/pages/toc/) because I like when both the [theory](http://www.aiismath.com/pages/c_08_features/features.pdf) and [practical examples](http://www.aiismath.com/pages/c_08_features/harris_nb/) are present.

There are some tutorials in OpenCV. If one day, there are some efforts to improve the OpenCV tutorials, or to add computer vision courses, it would be great to follow the same idea. 

---

> As I saw in the source code, you are using the covariance matrix of the patch without subtracting the mean. Why is this? I can think of this as PCA without subtracting the mean- which can result in an error

Probably you know better but looking at the [slides](http://www.aiismath.com/pages/c_08_features/features.pdf), I see no issue.

The `A` matrix is the auto-correlation matrix, for instance in the [Szeliski book](http://szeliski.org/Book/drafts/SzeliskiBook_20100903_draft.pdf#page.212):

![image](https://user-images.githubusercontent.com/8229425/80924501-98188080-8d89-11ea-8fcd-267289572ce8.png)

---

The chosen cost function for Harris corner detector is the SSD:

![image](https://user-images.githubusercontent.com/8229425/80924319-8f737a80-8d88-11ea-982b-b40cefb8fec1.png)

---

Taylor-expansion:

![image](https://user-images.githubusercontent.com/8229425/80924347-add97600-8d88-11ea-9d28-d59e1821b21b.png)

---

Some developments:

![image](https://user-images.githubusercontent.com/8229425/80924396-f2fda800-8d88-11ea-87f6-135e50b72800.png)

---

And we should get the `A` matrix mentioned above:

![image](https://user-images.githubusercontent.com/8229425/80924490-8505b080-8d89-11ea-9193-381f257f89c7.png)

---

Probably that by using another cost function, for instance normalized SSD, you would have to subtract the mean. There are some similarities with the PCA, but as I understand it, it comes naturally with the definition of the cost function.
