### ISSUE TITLE
Adding a cv::Vec2f to a 2-channel cv::Mat doesn't work anymore (Assertion error).

### ISSUE THREAD

**Issue by Pfaeff** [opencv/opencv#16632]
I use a 2-channel float matrix for storing a grid of points. I am adding a `cv::Vec2f` as an offset to those points. I am testing this on two machines:

- Ubuntu 16.04 with OpenCV 3.4.5. and GCC where this works
- Ubuntu 18.04 with OpenCV 3.4.8. and 3.4.9. and GCC where this will throw an assertion error

The assertion checks for the number of channels to be either 1 or 4. Of course, I am working in 2D, so this assertion fails. I am assuming that somewhere something is implicitly cast differently compared to the old version and causing this problem, since this assertion seems to exist in the old version as well.

`OpenCV(3.4.9) /data/third_party/opencv-3.4.9/modules/core/src/arithm.cpp:665: error: (-215:Assertion failed) type2 == CV_64F && (sz2.height == 1 || sz2.height == 4) in function 'arithm_op'`

**Comment by alalek** [comment]
Thank you for the report!

Please provide simple code snippet with reproducer (like [here](https://github.com/opencv/opencv/pull/16597#issuecomment-589283105)).

**Comment by Pfaeff** [comment]
Sure. Here you go:

```
cv::Mat pointMat(10, 10, CV_32FC2);
cv::Vec2f offset(7, 11);
pointMat + = offset;
```

**Comment by saskatchewancatch** [comment]
I did some looking into, some thoughts:

- assertion is tripped on that assertion foremost because the assertion expects type of data to be CV_64F, whereas example uses CV_32F type. So it seems there is restriction on FP precision as well.

- As per that assertion, addition of Vec+Mat of below types will also fail, which seems like an unnecessary restriction:
  - Vec(2/3/4)(f) with Mat of CV_32FC(2/3/4)
  - Vec(2/3)(d) with Mat of CV_64FC(2/3)

Why add arithmetic handler has these restrictions is a good question. [Last change in `arithm.cpp` concerning that assertion was ](https://github.com/opencv/opencv/commit/b4bcdd10a160dc19788efeca80f0db1a21bacc36)

I haven't studied `arithm.cpp:arith_op` in detail, but FWIW, building with that assertion disabled and running core accuracy tests on WIN64 doesn't cause failures.

**Comment by alalek** [comment]
`Mat + Scalar` should be used instead of `Mat + Vec` to modify matrix values.
