### ISSUE TITLE
Vector of a class that heredity a standard OpenCV class

### ISSUE THREAD

**Issue by thewoz** [opencv/opencv#17302]
Hi all,

I try to run this code but I have some troubles.
The code is the following:

    class point3D_t : public cv::Point3f { };
    class point2D_t : public cv::Point2f { };
    
    int main(int argc, const char * argv[]) {
      
      std::vector<point3D_t> input;
      std::vector<point2D_t> output;
    
      cv::Mat R,T,K;
      std::vector<double> distCoeffs;
      
      cv::projectPoints(input, R, T, K, distCoeffs, output);
    
      return 0;
      
    }

It gives me back as error in:

```
#include <opencv2/opencv.hpp>
#include "opencv2/core.hpp"
#include "opencv2/core/traits.hpp"

template<typename _Tp> inline
_InputArray::_InputArray(const std::vector<_Tp>& vec)
{ init(FIXED_TYPE + STD_VECTOR + traits::Type<_Tp>::value + ACCESS_READ, &vec); }
```

this:

    Incomplete definition of type 'cv::traits::Type<point3D_t>'

**Comment by mshabunin** [comment]
You have to specify `cv::traits::Type<...>` in your code to be able to use custom types like this. It will not work if your types has additional data fields or a vtable, because they will be treated as a `float[2]` or `float[3]` internally by `projectPoints` and it can corrupt memory if type layout does not match.

**Comment by thewoz** [comment]
@mshabunin thanks for the answer.
I do not undesired what I need to do. Therefore as you suggest  I will post on http://answers.opencv.org
