### ISSUE TITLE
Find a replacment for lena images

### ISSUE THREAD

**Issue by opoplawski** [opencv/opencv#17461]
##### System information (version)
- OpenCV => 4.3.0
- Operating System / Platform => Fedora/Debian

##### Detailed description

The lena images have been determined by Debian and Fedora to not be distributable and must be removed from source tarballs which is a pain to deal with.  Could a suitable alternative image be found?  Thanks.

**Comment by dkurt** [comment]
Hi! Can you please provide source of that information?

**Comment by alalek** [comment]
Package maintainers should handle this according to their policies.
Part of upstream files can be removed safely before processing (images/videos are not required to compile OpenCV binaries).

---

https://en.wikipedia.org/wiki/Lenna
and discussion here: https://en.wikipedia.org/wiki/File:Lenna_(test_image).png

**Comment by opoplawski** [comment]
Also - https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html

**Comment by sergiomb2** [comment]
> Also - https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html

quoting "This image is distributable but not free". So yes please find a replacement for Lena image .

**Comment by sergiomb2** [comment]
On https://en.wikipedia.org/wiki/Lenna#Criticism we can read
 
The use of the image has produced controversy because Playboy is "seen (by some) as being degrading to women",[10] and the Lenna photo has been pointed to as an example of sexism in the sciences, reinforcing gender stereotypes.

In a 1999 essay on reasons for the male predominance in computer science, applied mathematician Dianne P. O'Leary wrote:

    Suggestive pictures used in lectures on image processing ... convey the message that the lecturer caters to the males only. For example, it is amazing that the "Lena" pin-up image is still used as an example in courses and published as a test image in journals today.[6]

A 2012 paper on compressed sensing used a photo of the model Fabio Lanzoni as a test image to draw attention to this issue.[13][14][15][16]

The use of the test image at the magnet school Thomas Jefferson High School for Science and Technology in Fairfax County, Virginia provoked a guest editorial by a senior in The Washington Post in 2015 about its detrimental impact on aspiring female students in computer science.[17]

In 2017, the Journal of Modern Optics published an editorial titled "On alternatives to Lenna"[18] suggesting three images (Pirate, Cameraman and Peppers) that "are reasonably close to Lenna in feature space".

In 2018, the Nature Research family of journals announced that they would no longer consider articles using the Lenna image.[19]

On 31 October 2018, the TensorFlow Lite C++ image classification demo used an image of female computer science pioneer and US Navy Rear Admiral Grace Hopper as a test image.

On 19 November 2019, Code Like a Girl released a film and campaign called Losing Lena,[20] with the aim of eliminating use of the Lena image in order to encourage more female participation in computing.[21] 

[18] https://www.tandfonline.com/doi/full/10.1080/09500340.2016.1270881

**Comment by noverby** [comment]
@alalek 
Is an upstream fix not an option? Have there been any internal discussion about this in the OpenCV project?
