### ISSUE TITLE
How to get 2D image correspondances for 3D CAD model points for non textured objects?

### ISSUE THREAD

**Issue by astronaut71** [opencv/opencv#17706]
Hi

I have to estimate a very accurate 6D Pose of regular shape objects (like blocks for construction ) without any textured. I have the 3D CAD model of the object, and I know roughly the coordinates of the blocks. So the camera is pointing down to the object and can use stereo cameras or ZED. 

I know roughly the coordinates on the object and the camera will be placed around 1m away from the object. I would like to use OpenCV solvePnP method and for that need to find the 2d correspondences of the scene image for 3D CAD model points of the objects.

I search and found this tutorial for [https://docs.opencv.org/master/dc/d2c/tutorial_real_time_pose.html](url)  but in my case the objects are nontextured. So I can not use such key descriptors like SURF or SIFT or ORB. And also I would like to use it in real-time and as input to take my camera input.

Hence, research in this area has focused on tracking using natural features, such as edge-based, optical flow-based,template-based, and keypoint-based. Is this relevant so I can find the 2d correspondences for 3d cad model points for non-textured objects like construction blocks and can get the 6D Pose?

Also, I know that exists Harris Corners, Hough Lines, Canny Edge, or Fast Corners descriptors but not sure if using them can track the object and find the 2D-3D points correspondences. Can I use them in [https://docs.opencv.org/master/dc/d2c/tutorial_real_time_pose.html](url) and modify the source code for real-time so I can track my non-textured objects? If yes what should I change in the source code and how to run it in real-time?

Any help would appreciate.

**Comment by catree** [comment]
Forget about the tutorial. It relies on keypoint matching (so textured object) to find the 2D/3D correspondences for `solvePnP`.
Or use it as an inspiration for your developments, learning purposes.

This is a whole topic. See [5th International Workshop on Recovering 6D Object Pose](http://cmp.felk.cvut.cz/sixd/workshop_2019/) for a quick overview of recent techniques (and previous editions for anything that is not deep-learning related). Refer also to benchmark datasets like LineMOD and related datasets.

---

You get the idea : how to retrieve the 2D/3D correspondences for `solvePnP` method. Depending on the constraints, prior assumptions you can made for your problem, some relatively easy ad-hoc solutions to extract the 2D coordinates from prior knowledge could be done, using e.g. contour of the object, etc.

Also, since you are using 3D camera, you can exploit 3D knowledge and look for ICP-like methods for 3D registration. Look at PCL for ready to use techniques, and methods that use features extraction / matching on 3D data. There is also in OpenCV contrib this module : [GSoC 2014 - New Surface Matching in OpenCV using Point Pair Features](https://www.youtube.com/watch?v=uFnqLFznuZU). Point Pair Features seems like a good candidate for what you want to achieve. Look also at bin-picking problems for 3D techniques and object pose estimation.

Finally, once the initial object pose has been computed, subsequent object poses can be computed using tracking and registration techniques. See [Monocular Model-Based 3D Tracking of Rigid Objects: A Survey](https://www.semanticscholar.org/paper/Monocular-Model-Based-3D-Tracking-of-Rigid-Objects%3A-Lepetit-Fua/4c51ca3b2bd924d689713862d0fdbaafa5b24e5b).

**Comment by astronaut71** [comment]
I already exploit ICP method and Point Cloud registration. Didn't performed a bad bit still want to compare this one with 3D CAD and 2D Images. I have look at the [https://docs.opencv.org/3.0-beta/modules/surface_matching/doc/surface_matching.html](url) but still not clear about it. Does it use training data? Does the method find correspondences between the 3D CAD model and the Depth  Cameras Point Clouds or between 3D CAD and 2D Images? Not clear. Then How can I run and try it? I know that in the tutorial [https://docs.opencv.org/3.0-beta/modules/surface_matching/doc/surface_matching.html](url) there is A Complete Sample but still not clear. Can you bit explain it to me about it? 
Thanks

**Comment by astronaut71** [comment]
Also when try to build [https://docs.opencv.org/3.0-beta/modules/surface_matching/doc/surface_matching.html](url) with `make` I got the following error:
```
CMakeFiles/surface_matching.dir/surface_matching.cpp.o: In function `main':
surface_matching.cpp:(.text+0x9eb): undefined reference to `cv::ppf_match_3d::transformPCPose(cv::Mat, double*)'
```
Any help?

**Comment by astronaut71** [comment]
I want to use in real time. So I have the 3D CAD model and the Camera (ZED Camera) pointing down to the object and would ike to track and estimate the 6D Pose in Real time.

**Comment by tolsicsse** [comment]
HI I am alos intersted in this topic. Did you find any solution?

**Comment by ram-bhaskara** [comment]
Interested in this topic. If I could suggest - 
1) project the 3D CAD model onto an image plane with the same intrinsics as that of the camera
2) extract 2D image features 
3) search for the feature coordinates in the {x,y,z} frames (x,y,z points reshaped into a 2D matrix) -> needs the use of interpolation techniques to find the closest match.

**Comment by AndreAhmed** [comment]
@ram-bhaskara 
@BojanAndonovski71 
I'm using ZED Camera and I ran into the same issue. Can you please elaborate how did you solve it ? please

**Comment by ram-bhaskara** [comment]
> [@ram-bhaskara](https://github.com/ram-bhaskara) [@BojanAndonovski71](https://github.com/BojanAndonovski71) I'm using ZED Camera and I ran into the same issue. Can you please elaborate how did you solve it ? please

Caution: I have not used a zed camera but experimented my approach in simulations. 
My input is same as the above. Using camera pose and intrinsics, project the CAD onto an image plane. This image should have the same geometry as captured on zed camera. Then you are comparing between two similar images to establish feature correspondence. 

How to project? I used openGL lookAt transform model as my simulation used this convention. Using depth from zed camera you can get the images at the same scale. Just using a monocular camera will not work as it would have scale ambiguity.

**Comment by AndreAhmed** [comment]
@ram-bhaskara Can you elaborate on this more please?
I'm currently to projecting the CAD Model using world to screen coordinate from ZED camera, and I have another image that I object detected it and I have it's bounding box and it's segmented mask. I will compute the features and do matching between both using ORB, and a matcher. Then I have to use solvepnp? is that correct ?

**Comment by ram-bhaskara** [comment]
1. Transform your 3D model into the frame of camera and then to image. This requires extrinsics {R,t} and intrinsics -> image formation model. 
2. Verify that the projected image and the captured image coarsely match (approximately).
3. You have features from your image. 
4. Use the pixel coordinates in the image (and the corresponding (same) coordinates in the projected image). The feature positions must be the same if projection model is perfect. 
5. Use the pixel coordinates to get the 3D coordinates. (u,v) and scale should help you get the (x,y) coordinates. Search for z in your 3D point cloud using the IDs for x and y.

**Comment by AndreAhmed** [comment]
@ram-bhaskara Thanks so much for the steps. But I need to get the pose

**Comment by AndreAhmed** [comment]
I have a 2D object detection model using yolo, and I don't have segmentation, right now I'm using ZED stereo Camera and its SDK to get a 3D BBOX out of it, as shown

I would like to align a 3D Game object to it, the 3D BBox doesn't have orientation, so I would like to align a virtual 3D object over the real 3D Object.

I'm looking for an algorithm or an approach.

![Image](https://github.com/user-attachments/assets/ababa03b-2793-4e7e-8e16-d789b9145f9c)

**Comment by ram-bhaskara** [comment]
> Thanks so much for the steps. But I need to get the pose

My bad for not talking about the elephant in the room. PnP and pose optimization. 
Here is what I have done previously but not sure if there is any simpler solution: 
1. Start with an initial pose guess
2. Find the image feature locations in the projected image.
3. Error metric is feature_loc_projected_img - feature_loc_actual_img
4. Jacobian calculation is tricky and super sensitive but since you have the scale - please constrain the projection. What I have done was - perturb the pose around the guess systematically and use a least squares regression to numerically get a Jacobian.   
5. Pray for convergence

This is my algorithm: https://arxiv.org/pdf/2212.12668.pdf

Again, this is for one shot pose estimation. If you have multiview data (best case) SfM is very easy using COLMAP.
