### ISSUE TITLE
Can't limit CPU threads when running DNN with inference engine and ngraph 

### ISSUE THREAD

**Issue by lahavy** [opencv/opencv#17787]
##### System information (version)
- OpenCV => 4.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

I use cv::setNumThreads(0) to run on only one logical processor.

running DNN with OCV dnn backhand works correctly.
running DNN with Inference engine works correctly.
running DNN with Inference engine and ngraph uses more than one logical processors

**Comment by dkurt** [comment]
Have you tried ` cv::setNumThreads(1) ` ?

**Comment by lahavy** [comment]
Yes, it doesn't work.

Had to add a direct call to IE:
    ie.SetConfig({ { CONFIG_KEY(CPU_THREADS_NUM), std::to_string(1) } }, device_name);

**Comment by alalek** [comment]
Fixed here: #17806

**Comment by cdc65130** [comment]
I have the same problem on Win10, VS 2017, openvino2021.4.2.
I think the above PR [#17806](https://github.com/opencv/opencv/pull/17806) fixed the case when the NN Builder API backend was enabled.
However, since 2020.4, Inference Engine don't provide NN builder API anymore.
Could you also fix the case when the Ngraph API backend is enabled?
