### ISSUE TITLE
Inconsistent "cameraMatrix" in documentation

### ISSUE THREAD

**Issue by decadenza** [opencv/opencv#17828]
##### System information (version)
- OpenCV => master

##### Detailed description
The "camera matrix" is commonly intended as a 3x4 matrix that maps a 3D point to a 2D point (image), e.g. on [Wikipedia](https://en.wikipedia.org/wiki/Camera_matrix).
Someone else, indeed, uses the term to refer to the 3x3 intrinsics camera matrix, e.g. [Stanford University slides](https://web.stanford.edu/class/cs231a/course_notes/01-camera-models.pdf).

The OpenCV documentation is using the term "projection matrix" for the 3x4 matrix and the term "camera matrix" for the intrinsics. Some examples:

- [`calibrateCamera`](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d): here **cameraMatrix** is intended as a 3x3 matrix, but it is actually the **intrinsic parameters** matrix!
- [`stereoRectify`](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6) uses cameraMatrix referring to intrinsics as well
- The [detailed description](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#details) is indeed clear that **A** is the intrinsic camera matrix.

But the term "camera matrix" is too confusing and should be replaced/specified more. I suggest at least to indicate "intrinsic camera matrix" or 3x3 to avoid any doubt.

**Comment by catree** [comment]
I think most of the initial terminology of this doc comes from this paper: [A Flexible New Technique for Camera Calibration, Zhengyou Zhang](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf). For instance by using `A` for the camera intrinsic parameters while I am seeing `K` nowadays.

I would suggest to use `camera intrinsic matrix` as in the paper instead of just `camera matrix`:

![image](https://user-images.githubusercontent.com/8229425/87339788-666d2400-c547-11ea-8ed9-310c0d578d18.png)

---

Documentation for `stereoRectify()` can be improved, it looks like this:

![image](https://user-images.githubusercontent.com/8229425/87340029-d2e82300-c547-11ea-8cdf-f0abb1ea1cdb.png)

Documentation for `calibrateCamera()` is fine I think (maybe use instead `camera intrinsic matrix` instead of just `camera matrix`):

![image](https://user-images.githubusercontent.com/8229425/87340155-00cd6780-c548-11ea-91e9-aacee51bdbc0.png)

**Comment by catree** [comment]
In my opinion, a better approach would be to define once `A`, distortion coefficients, etc. at the top of the documentation in the details section, and for the documentation of individual function to refer to them (if it is possible with doxygen with a direct link).

This would avoid copy/paste error and the need to define each time what is the camera matrix, distortion coefficients, ...

**Comment by decadenza** [comment]
Yes @catree , I agree that specify camera _intrinsic_ matrix every time should be a sufficient heads up for who's starting to use OpenCV.

**Comment by victor1234** [comment]
@catree could we close this issue?
