### ISSUE TITLE
Error in function computeShapeByReshapeMask, when loading official ONNX model (mask-rcnn)

### ISSUE THREAD

**Issue by MrModez** [opencv/opencv#17914]
##### System information (version)
- OpenCV => 3.4.11
- Operating System / Platform =>Windows 7 64 Bit
- Compiler => clang-cl

##### Detailed description

When I load ONNX model with OpenCV DNN module I get this error:
OpenCV(4.3.0) D:\Git\opencv\modules\dnn\src\layers\reshape_layer.cpp:133: error: (-5:Bad argument) Copy dim[3] (which has zero size) is out of the source shape bounds in function 'computeShapeByReshapeMask'

##### Steps to reproduce

cv::dnn::readNetFromONNX( "MaskRCNN-10.onnx" );
ONNX model can be found here: https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by dkurt** [comment]
Please try the latest release

**Comment by MrModez** [comment]
Same error:
OpenCV(4.4.0) D:\git\opencv\modules\dnn\src\layers\reshape_layer.cpp:133: error: (-5:Bad argument) Copy dim[3] (which has zero size) is out of the source shape bounds in function 'computeShapeByReshapeMask'

**Comment by mshabunin** [comment]
Reproduced with latest _master_ branch version. Marking it as a feature request because support for this network was tested only for TensorFlow format.

**Comment by sl-sergei** [comment]
The problem is connected with string parameters for input width and height, OpenCV loader replaces them to zeroes by default. Original ONNX network was converted from FAIR repository maskrcnn-benchmark with modifications from https://github.com/BowenBao/maskrcnn-benchmark/tree/onnx_stage
![image](https://user-images.githubusercontent.com/62052793/90729436-46abe700-e2cf-11ea-881f-792eaea689ba.png)
But even if the issue is fixed, there are several NonZero layers, which are not supported right now.
