### ISSUE TITLE
G-API : any plans for human readable serialization ?

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#17947]
Are there any plans to, or on the contrary evidences for not to plan to, make a human readable serialization of G-API graphs descriptions ?
In my opinion, it could be useful for scripting by allowing live modification of text files polled by a pre-compiled binary.

**Comment by asmorkalov** [comment]
@dmatveev could you comment the issue?

**Comment by dmatveev** [comment]
@chacha21 we have plans on a Python API which should fill the gap. Meanwhile, could you briefly explain the way use see this feature to be used?

**Comment by chacha21** [comment]
My use case would be : 

I build a image processing pipeline framework.
One of the pipeline item could be a generic G-API  processor : once loaded with a G-API serialized in a file, it could process images.

My framework would not have to know the details of the G-API computation, and the user just have to provide a file to load into the framework.

**Comment by dmatveev** [comment]
Thanks, I've got your point.

G-API is itself a pipelining framework since OpenCV 4.2: https://opencv.org/hybrid-cv-dl-pipelines-with-opencv-4-4-g-api/

Making it a node in some other pipelining framework may also make sense, given that this abstract GComputation could handle a non-trivial logic inside - and then you want to e.g. redistribute it across the net (speaking of the distributed processing).

Human-readable format is for sure possible, but we see it as a staged approach. As a very first step, we'd introduce a more generic C++ API to build G-API graphs -- our current API is very human-oriented (expression based), but is not very machine friendly. Once we provide a more machine-friendly API (factory-like), then, as a next stage, human-readable serialization layer could appear on top of it, and it could be an app's own format (not owned/defined by G-API), too.

The more "standard" thing may come based on these findings, but, again, a human readable text format needs to be thoroughly designed. It may be human-oriented, too (but then there's a Python binding so you could load a `.py` script which expresses a graph for you), or a machine oriented (more friendly for GUI tools, builders, etc).

Once it becomes a thing, it needs to be properly maintained, supported, versioned, etc etc. People may start writing on it, so then asking for backwards compatibility, etc. etc. These may be counted as evidences not to plan too :)

We're open to proposals, too! E.g., how such format could look like in general or in some particular case.

**Comment by chacha21** [comment]
Ok, I perfectly understand that cautious approach. I will take time to really become familiar with G-API before working more on that subject.
