### ISSUE TITLE
OpenCV 4.4 -  error: call to implicitly-deleted default constructor of 'cv::gimpl::Op'

### ISSUE THREAD

**Issue by AngryPenguinPL** [opencv/opencv#17952]
##### System information (version)
- OpenCV => 4.4
- Operating System / Platform => Linux OpenMandriva Cooker
- Compiler => LLVM/Clang 10.0.1

##### Detailed description

Trying build new OpenCV 4.4 for OpenMabdriva Cooker and at build time see error: 
`/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_construct.h:109:38: error: call to implicitly-deleted default constructor of 'cv::gimpl::Op'
`
Full build log here: https://file-store.openmandriva.org/api/v1/file_stores/a96e50f00d1eb39a0ab11bd9da473347a3446f11.log?show=true
##### Steps to reproduce
Install OpenMandriva Cooker
Try build OpenCV 4.4 with Clang 10.0.1

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by mshabunin** [comment]
**cc** @dmatveev

**Comment by dmatveev** [comment]
Thanks, will look into it

**Comment by aDanPin** [comment]
@AngryPenguinPL 
Could you provide more information about how you build OpenCV?

**Comment by mshabunin** [comment]
@aDanPin , most information is available in [the build log](https://file-store.openmandriva.org/api/v1/file_stores/a96e50f00d1eb39a0ab11bd9da473347a3446f11.log?show=true). Or what do you mean?

**Comment by AngryPenguinPL** [comment]
@aDanPin build log above and spec here: https://github.com/OpenMandrivaAssociation/opencv/blob/AngryPenguinPL-patch-3/opencv.spec

**Comment by dmatveev** [comment]
So basically the problem is with [this code](https://github.com/opencv/opencv/blob/4.4.0/modules/gapi/src/backends/common/serialization.hpp#L270):

```c++
template<typename T>
I::IStream& operator >> (I::IStream& is, std::vector<T> &ts) {
    //std::size_t sz = 0u;
    uint32_t sz = 0u;
    is >> sz;
    if (sz == 0u) {
        ts.clear();
    }
    else {
        ts.resize(sz);
        for (auto &&i : ade::util::iota(sz)) is >> ts[i];
    }
    return is;
}
```

When it is called for {{Op}} as an element type, the STL fails to find its default constructor (or a copy constructor), due to constant fields defined in this structure.

@aDanPin couldn't reproduce the issue with clang 10 installed on Ubuntu with the default compile flags. Replicating the flags as mentioned in the log files also caused some issues which Danil is currently trying to resolve (at a cmake level).

Removing the `const` qualifiers from fields of `cv::gimpl::Op` (defined in gmodel.hpp) should help. @AngryPenguinPL please try if you can and let me know if it works.

**Comment by aDanPin** [comment]
Thanks everyone for the logs provided
I did some work and I want to share the results and ask some questions

I tried to reproduce the error with keys provided in [logs](https://file-store.openmandriva.org/api/v1/file_stores/a96e50f00d1eb39a0ab11bd9da473347a3446f11.log?show=true) using
Ubuntu 18.04.4 LTS
CMake 3.18.0
Ninja 1.8.2
Clang 10.0.1 (from [official package](https://apt.llvm.org))

The problem is not reproducible with optimization levels -O0, -O1, -O2, -O3.
With optimization level -Os, cmake could not generate a build files
I find a [similar problem](https://github.com/android/ndk/issues/721)

@AngryPenguinPL 
As far as I understand you are using clang from source right?

**Comment by berolinux** [comment]
I'm running into the same problem when using clang 11.0-rc1.
The difference between the working and non-working builds are probably the STL implementations - @AngryPenguinPL and I are both using libstdc++ from gcc 10.1.

The problem is that in the code you posted, `ts.resize(sz)` is called to resize the the vector -- which allocates objects to be added to the vector, but `T` in this case is `cv::gimpl::Op` which doesn't have a constructor. The default constructor isn't there because `cv::gimpl::Op` contains a `cv::GKernel`, which in turn contains a `const GSpecs` and a `const GShapes`. Removing the `const` from the `inSpecs` and `outShapes` members of `cv::GKernel` "fixes" (rather, hides) the problem.

**Comment by berolinux** [comment]
The error from clang 11 is a bit more readable
```
In file included from ../modules/gapi/src/backends/common/serialization.cpp:7:
In file included from /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/set:60:
In file included from /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_tree.h:67:
In file included from /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/ext/alloc_traits.h:34:
In file included from /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/alloc_traits.h:33:
/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_construct.h:109:38: error: call to implicitly-deleted default constructor of 'cv::gimpl::Op'
    { ::new(static_cast<void*>(__p)) _Tp(std::forward<_Args>(__args)...); }
                                     ^
/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_uninitialized.h:567:8: note: in instantiation of function template specialization 'std::_Construct<cv::gimpl::Op>' requested here
                std::_Construct(std::__addressof(*__cur));
                     ^
/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_uninitialized.h:623:2: note: in instantiation of function template specialization 'std::__uninitialized_default_n_1<false>::__uninit_default_n<cv::gimpl::Op *, unsigned long>' requested here
        __uninit_default_n(__first, __n);
        ^
/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_uninitialized.h:685:19: note: in instantiation of function template specialization 'std::__uninitialized_default_n<cv::gimpl::Op *, unsigned long>' requested here
    { return std::__uninitialized_default_n(__first, __n); }
                  ^
/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/vector.tcc:627:8: note: in instantiation of function template specialization 'std::__uninitialized_default_n_a<cv::gimpl::Op *, unsigned long, cv::gimpl::Op>' requested here
                std::__uninitialized_default_n_a(this->_M_impl._M_finish,
                     ^
/usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/10.1.1/../../../../include/c++/10.1.1/bits/stl_vector.h:940:4: note: in instantiation of member function 'std::vector<cv::gimpl::Op, std::allocator<cv::gimpl::Op>>::_M_default_append' requested here
          _M_default_append(__new_size - size());
          ^
../modules/gapi/src/backends/common/serialization.hpp:279:12: note: in instantiation of member function 'std::vector<cv::gimpl::Op, std::allocator<cv::gimpl::Op>>::resize' requested here
        ts.resize(sz);
           ^
../modules/gapi/src/backends/common/serialization.cpp:497:8: note: in instantiation of function template specialization 'cv::gimpl::s11n::operator>><cv::gimpl::Op>' requested here
    is >> s.m_ops >> s.m_datas >> s.m_counter >> s.m_proto;
       ^
../modules/gapi/src/compiler/gmodel.hpp:58:25: note: default constructor of 'Op' is implicitly deleted because field 'k' has a deleted default constructor
    cv::GKernel         k;
                        ^
../modules/gapi/include/opencv2/gapi/gkernel.hpp:42:23: note: default constructor of 'GKernel' is implicitly deleted because field 'inSpecs' of const-qualified type 'const cv::GSpecs' (aka 'const vector<cv::detail::ArgSpec>') would not be initialized
    const GSpecs      inSpecs;    // specs of kernel's inputs (FIXME: below)
                      ^
1 error generated.
```

**Comment by dmatveev** [comment]
>  Removing the const from the inSpecs and outShapes members of cv::GKernel "fixes" (rather, hides) the problem.

Yep this is exactly what I recommended to do. If it helps, please push an MR and we'll close this.
Thanks!

**Comment by jiapei100** [comment]
Same here... The file to be modified is **gkernel.hpp.**

**Comment by OrestChura** [comment]
Hello, @AngryPenguinPL @berolinux @jiapei100! Did the quick-fix mentioned by dmatveev/berolinux/jiapei100 help?
How it is going with a solution of this issue? If you have already found and, more important, **tested** one, it'll be so kind of you to publish it in a PR. Would you like to do that?

**Comment by choffmann** [comment]
> > Removing the const from the inSpecs and outShapes members of cv::GKernel "fixes" (rather, hides) the problem.
> 
> Yep this is exactly what I recommended to do. If it helps, please push an MR and we'll close this.
> Thanks!

I had the same issue. Removing the const in `GKernel` "fixed" issue. May I ask what MR stands for?

**Comment by OrestChura** [comment]
>  May I ask what MR stands for?

@choffmann, dmatveev meant to open a Pull Request / Merge Request in this repo to "fix" this issue if you've figured out the proper changes already.

**Comment by dmatveev** [comment]
@OrestChura  can you please do it?

**Comment by dmatveev** [comment]
@mshabunin @alalek can we finally add that faulty config to our CI? Seems people are using a broader / newer range of compilers/etc than we validate

**Comment by choffmann** [comment]
Ok, I created a PR #18320.
