### ISSUE TITLE
Is wrap_flow(flow, flow) correct?

### ISSUE THREAD

**Issue by hzxie** [opencv/opencv#18015]
https://github.com/opencv/opencv/blob/77b01deb805b7166e938bbd17d393f051aad88c1/samples/python/dis_opt_flow.py#L85

I guess it should be `wrap_flow(prev_gray, flow)`, isn't it?

**Comment by asmorkalov** [comment]
@hzxie According to [documentation](https://docs.opencv.org/master/df/dde/classcv_1_1DenseOpticalFlow.html#a20037021dec04e9006149204ad610d04) the 3rd parameter of `calc` call is just optical flow, but not remapped frame. It's logical to put just `flow` without warping and all other dense optical flow samples does it. I'll check it with source code and return back.

**Comment by vpisarev** [comment]
@hzxie, since it's a helper function in a sample that tries to predict motion in the next moment of time, it's hard to classify it as "correct" or "incorrect". We are rather talking about the quality of prediction.

Assume we have a moving person and a still background

```
....................
.......>>>.......
.....>>>>>.....
.....>>>>>.....
....................
```
dots denote still background, `>` denote pixels on the object (e.g. car) moving from the left to the right. Pixels on the car have flow `dx(x,y) = v, dy(x,y) = 0`. Background pixels have flow `dx(x,y) = dy(x,y) = 0`. If we take just the previous flow, we will not take into account that the pixels have shifted. `wrap_flow()` function in the sample correctly predicts that points on the left side of the car will become still next frame (as some background behind the car will be unveiled). But it does not predict that pixels in front of the car will belong to the car on the next frame and thus optical flow there will become nonzero. For that, you need to extend wrap_flow() to do not just backward-in-time warping, but also forward-in-time warping and then combine the results somehow.

Since it's just initial approximation of the flow, such errors in prediction are normally corrected during the further optimization process, so it's not a big deal. You can just pass optical flow from the previous frame to the optical flow estimation function.

Passing prev_gray to wrap_flow would be an obvious bug, because we are trying to predict the flow (inter-frame pixel shift), not the pixel values. You can try your variant, I'm sure, the results will become quite bad.
