### ISSUE TITLE
applyColorMap, BGR and RGB

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#18409]
OpenCV 4.4.0
By default, cv::applyColorMap() will transform gray to BGR. Could there be an additional flag to generate RGB instead ?

To keep the current prototype, it could be an option of the enum, like
```
cv::applyColorMap(src, dst, cv::COLORMAP_JET)//current behaviour
cv::applyColorMap(src, dst, cv::COLORMAP_JET | cv::COLORMAP_RGB)//generate RGB instead of BGR
```

**Comment by sturkmen72** [comment]
i believe simply applying BGR to RGB color conversion after `applyColorMap` is enough.

**Comment by chacha21** [comment]
> i believe simply applying BGR to RGB color conversion after `applyColorMap` is enough.

Of course, but the question is also about "does it worth it" ? It depends on the implementation of applyColorMap().

**Comment by catree** [comment]
I also think that it does not worth it.

OpenCV already assumes BGR format due to some historical reason. Patching one of the multiple functions in OpenCV to support natively RGB format does not seem reasonable or consistent for me.

`applyColorMap()` uses LUT. BGR to RGB conversion should be mostly memory bounded. Moreover `applyColorMap()` is not a critical function that should have required high performance code. So in my opinion doing a conversion afterward is fine.

**Comment by chacha21** [comment]
Ok for me.
