### ISSUE TITLE
cv::findHomography failure (divide by zero operation) when run using RANSAC in some particular cases

### ISSUE THREAD

**Issue by CEDRICKORNY** [opencv/opencv#18592]
##### System information (version)
- OpenCV => 4.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
##### Detailed description
 In some rare cases, some src and dst keypoints generate an error in computeError (fundam.cpp), line 205, where a division by zero occurs.
This error can be observed when calling cv::findHomography with RANSAC method 
##### Steps to reproduce
 I've attached a zip file containing:
code snippet to reproduce the issue (observed on 4.1.0 version of the lib, but likely still there in 4.5.0).
a yml file containing src and dst keypoints (this set generates the divide by zero on my system). Some others sets can be provided if needed.
The attached code snippet will load the source and dst keypoints from the keypoints yml file, and perform homography search using RANSAC.... and will crash due to divide by zero when looking for inliners/outliners.
[code_snippet_cvbug.zip](https://github.com/opencv/opencv/files/5382936/code_snippet_cvbug.zip)

```
std::string keyPoints = "cvbug_keypoints.yml";
test_utils::BuildPathToInputImage(keyPoints);

//-- Localize the object
std::vector<cv::Point2f> obj;
std::vector<cv::Point2f> scene;

cv::FileStorage fs(keyPoints.c_str(), cv::FileStorage::READ);
cv::FileNode srcFileNode = fs["srcPoints"];
read(srcFileNode, obj);
cv::FileNode dstFileNode = fs["dstPoints"];
read(dstFileNode, scene);
fs.release();

cv::Mat h = cv::Mat();
try
{
	h = cv::findHomography(scene, obj, cv::noArray(), cv::RANSAC);
}
catch(...)
{
	// Here all the trouble started ....
	// divide by zero triggered by fundam.cpp, line 205 (denominator in operation to compute ww evaluates to zero)
	
}
```

Related code:

https://github.com/opencv/opencv/blame/4.1.0/modules/calib3d/src/fundam.cpp#L205

##### Issue submission checklist
 - [ X] I report the issue, it's not a question
 - [ ] I updated to latest OpenCV version and the issue is still there
Could not update yet. OpenCV is used in our production code and I wasn't able to  perform the switch yet. Will do it later on..
 - [X ] There is reproducer code and related data files

**Comment by alalek** [comment]
Can't reproduce on latest master branch (4.5.0) in Debug/Release modes (Linux, GCC 9.3.1).

Computed `h` is:
```
[1.01318322685745, 0.009049972560262031, -977.2192607504069;
 -0.001132336172027372, 1.015476130131031, -322.2156619110543;
 2.121797712739678e-06, -1.169427687159016e-06, 1]
```

**Comment by CEDRICKORNY** [comment]
dammit!
thank you very much for the very quick reply.
Maybe the findInliers code that uses it has changed between 4.1.0 and
4.5.0....
This being said, are you able to also test it under windows 64 bits (vc
141). I wouldn't be surprised the float operations leading to the
denominator at 0.0 wouldn't give the exact same results between the 2
architectures.
To give a better overview, this problem occurs very rarely (we're working
now on evaluating our code robustness and thus generate some cases where we
degrade our input images). This issue appeared only a few times out of
thousands operations done.
And looking at the code in computeError function, I don't see any reason
that would prevent the denominator in the ww computation from being at zero
How can I help digging further into that issue?
Kind regards
Cédrick

**Comment by alalek** [comment]
However I see passes with zero denominator. But there is no exceptions (IEEE-574 allows division by zero with inf/nan results).
ww ==> inf
err[i] ==> inf

and then `errptr[i] <= t` condition (`RANSACPointSetRegistrator::findInliers()`) should go into `false` for both `inf/nan` error values.

---

So, no problem expected here.

**Comment by JMVOLLE** [comment]
Hello.
At least on intel architecture, division by zero raising an exception or propagating a NAN is configurable through FPU registers.
Unless opencv handles correctly this FPU configuration for any supported HW, opencv behavior is not frozen at compilation time. The issue is that CPU configuration might require specific privileges and impacts all running processes.

From my point of view this really is an issue. The safe (and portable) approach (that we apply in our code ) is checking before hand if a division by zero will happen. Then raising an exception or propagating a NAN becomes an implementation choice (and not a runtime event).

More of this subject:
https://stackoverflow.com/questions/37262572/on-which-platforms-does-integer-divide-by-zero-trigger-a-floating-point-exceptio

**Comment by alalek** [comment]
integer division != floating point division. Their defaults and behavior are differ.

Current OpenCV code follows the behavior of IEEE-574 standard instead of some "debug" features like FPU exceptions.
Also current OpenCV code doesn't expect signaling NaNs.

---

Feel free to propose Pull Request with strict handling under `#ifdef ENABLE_STRICT_MATH` guard.
You can switch mode through passing this definition via `cmake -DOPENCV_EXTRA_FLAGS=-DENABLE_STRICT_MATH=1 ...`

Currently this is is low priority issue for OpenCV dev team (huge efforts, especially on validation side, with currently low impact).
