### ISSUE TITLE
Opencv 3.4.1 3rdparty file

### ISSUE THREAD

**Issue by akshayrb9** [opencv/opencv#18618]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform =>  
- Compiler => 

##### Detailed description

I am using a SDK in my project which uses  "opencv 3.4.1", the source for opencv 3.4.1 in your github page contains a folder named "3rdparty" . It has 16 dependency components and cmake files.
I have to get approval for all these 16 components from legal team to use. So please let me know whether opencv 3.4.1 uses these 16 components during run time or not. If it uses can you please let me know the versions for each of them so that I will search these dependencies source codes and get approvals. 

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
> 3.4.1

This is outdated version with outdated 3rdparty libraries (probably with CVEs).
1. Upgrade to the latest version first. It is better to avoid 3.4.x releases in new projects due to ancient Android NDK r10 dependency.
2. Almost all 3rdparty libraries are optional (but disable some functionality of OpenCV library)
3. Check getBuildInformation() / CMake output for exact versions. Also check [Android pack](http://pullrequest.opencv.org/buildbot/builders/master_pack-android) builder logs.
4. If version is missing in CMake output, then you can check git history comments for related components in 3rdparty directory.
5. You may want to tune [these build scripts](https://github.com/opencv/opencv/tree/master/platforms/android) for your needs.

**Comment by akshayrb9** [comment]
Hi Thanks for the information. But we are not directly using the opencv in our project. One of SDK in our project uses opencv version 3.4.1. 
So we want to make sure whether the 16 dependencies in "3rdparty" folder are used by opencv or not. These 16 are ,
carotene, cpufeatures, ffmpeg, include, ippicv, ittnotify, libjasper, libjpeg, libpng, libtiff, libwebp, openexr, openvx, protobuf, tbb and zlib. Can you please confirm whether these are optional or not? . we are unable to find it in SDK since its a binary. Thanking in advance.

**Comment by alalek** [comment]
> These 16 are
> "include"

Please check binaries in `sdk/native/3rdparty` from SDK package instead of source directory. Most part of these sources are not used in default Android builds.

- `carotene` - released as part of OpenCV (ARM CPU optimizations), optional
- `cpufeatures` - upstream code is located in Android SDK (from Google)

**Comment by mshabunin** [comment]
@akshayrb9 , all these dependencies ar optional except maybe _zlib_ and _cpufeatures_. But most of them are enabled by default, especially on Android. Some dependencies will be enabled only on specific platforms, e.g. _carotene_ on ARM or _ippicv_ on x86_64. 
So you should consult with your OpenCV SDK provider - actual configuration depends on options used for the build. See also: https://docs.opencv.org/master/db/d05/tutorial_config_reference.html

**Comment by akshayrb9** [comment]
Hi, For documentation purpose and release process i need the Export control classification number(ECCN) for these if applies.
Can anyone please let me know the ECCN ?

**Comment by alalek** [comment]
https://github.com/opencv/opencv/issues/16402#issuecomment-577069572 (disclaimer: do not rely on legal information from Internet, contact your legal department)

**Comment by 66Ton99** [comment]
Yes this 3rdparty folder with own licences is very annoying.
Would be nice to get these dependencies directly from they repositories or at list move to some separate repository.
