### ISSUE TITLE
Direct ROI loading from large image, instead of loading the whole image and then cropping

### ISSUE THREAD

**Issue by nai-kon** [opencv/opencv#18866]
Is there any functions to load ROI region of image?
I have a very large .jpg image, but only needs specified region(coordinates).
In general, loading entire image using imread then cropping it. But it needs a lot of memory so don't wanna to do.

If there are no function like this, I want it on future update.

**Comment by alalek** [comment]
OpenCV doesn't decode images itself or the most cases. So efficient support is possible if used backends (3rdparty libraries) support that.

In general it is better to use specialized Media I/O libraries for required formats instead of OpenCV.
OpenCV tries to keep API simple which covers most things.

**Comment by nai-kon** [comment]
@alalek 

Thank you the reply.
I will consider another way, such as use 3rd party library or self decoding.
Close this issue.
