### ISSUE TITLE
test cases for OpenCL should only use default GPU device 0

### ISSUE THREAD

**Issue by diablodale** [opencv/opencv#18917]
Two test cases for the OpenCL execution context request the 2nd GPU device. As per https://github.com/opencv/opencv/pull/18907#discussion_r529774863_ the test cases should only use GPU device 0.

##### System information (version)
- OpenCV => 4.5.0
- Operating System / Platform => Windows 10 64-Bit
- Compiler => Visual Studio Community 2019 v16.8.2

##### Steps to reproduce

Code review at

https://github.com/opencv/opencv/blob/85b0fb2a9c46958f1bbe1b11bf2f2389ddbd14f2/modules/core/test/test_opencl.cpp#L123

and

https://github.com/opencv/opencv/blob/85b0fb2a9c46958f1bbe1b11bf2f2389ddbd14f2/modules/core/test/test_opencl.cpp#L164

##### Result

The 2nd GPU device is associated with the Execution Context. My computer has two devices in order: Nvidia, and Intel. Therefore, in these test cases, it is the Intel that is associated.

##### Expected

The GPU device 0 to be associated. On my system it would be the Nvidia.

##### Issue submission checklist

 - [X] I report the issue, it's not a question
 - [X] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
 - [X] I updated to latest OpenCV version and the issue is still there
 - [X] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
The first test with `GPU:1:` was added by PR #18186 with adding support for different GPUs. No need to eliminate that case just because it is not covered by public CI.

1. Public CI can't validate all possible configurations (resources are limited). It covers testing of some generic / default / frequently used configurations.
2. Tests can be skipped if tests don't meet prerequisites.
3. No need to block testing of some cases on developer machines or other non-public CI through removal of such cases.
4. By default test should cover the "default" configurations. Exotic configurations should be required if it is really necessary in the test case (as stated initially by https://github.com/opencv/opencv/pull/18907#discussion_r529326385 ).

---

So, issue's statement should avoid the "only" requirement:

```.diff
-test cases for OpenCL should only use default GPU device 0
+test cases for OpenCL should use default GPU device 0
```

However it is not accurate too.

There is external switcher of OpenCL device for OpenCV tests which is used actively (since 2013: #2054 ):
- `export OPENCV_OPENCL_DEVICE=:GPU:0` (for example, iGPU)
- `export OPENCV_OPENCL_DEVICE=:GPU:1` (for example, second dGPU)
- `export OPENCV_OPENCL_DEVICE=:CPU:0` (to debug issues during the development)

Finally,

```
test cases for OpenCL should use default OpenCL device
```

(can't argue with that)
