### ISSUE TITLE
how to install cv2 in MacBook Pro 2020 M1 Mac

### ISSUE THREAD

**Issue by vivek-ram** [opencv/opencv#19113]
need help with installing got errors when installing this.

**Comment by ShinnnosukeNakamura** [comment]
I set the terminal to (launched in Rosetta) and ran this command and it worked
pip install opencv-python

**Comment by Rustam-Z** [comment]
Hi there, after searching the web I have successfully installed OpenCV on my Mac M1. 
1. Probably you don't have *brew* installed, so here's how you should install it:
   - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
   - `brew install wget`
   - `brew install miniforge`
   - `brew install cmake`, you will need cmake for building OpenCV code
2. Then just follow this blog: https://sayak.dev/install-opencv-m1/#Install-conda
   - OR, here is the YouTube video which explains the second step: https://youtu.be/x_kAkabk-5o

P.S. If  `mdfind cv2.cpython` returning an empty string then try to delete the `build` folder and compile opencv again. Otherwise, you have done everything correctly.

**Comment by alalek** [comment]
See also: https://github.com/opencv/opencv-python/issues/429
