### ISSUE TITLE
Installing OpenCV under macOS for Java --> No jar file(s)

### ISSUE THREAD

**Issue by pa5cal** [opencv/opencv#19116]
##### System information (version)
- OpenCV => 4.5.0_5
- Operating System / Platform => macOS Big Sur Version 11

##### Detailed description
I have installed OpenCV 4.5 using homebrew following this [OpenCV Java Tutorial](https://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html#install-opencv-3-x-under-macos).

Unfortunately, I don't get any Java directory and jar files (and the dylib library) under: /usr/local/Cellar/opencv/4.5.0_5/share/opencv4

##### Steps to reproduce
See  [OpenCV Java Tutorial](https://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html#install-opencv-3-x-under-macos)

##### Issue submission checklist
 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
 - [x] I updated to latest OpenCV version and the issue is still there

**Comment by pa5cal** [comment]
Same problem has been also reported on Stack Overflow: [MacOS OpenCV 4.5 for Java](https://stackoverflow.com/questions/64531929/macos-opencv-4-5-for-java)

**Comment by alalek** [comment]
Check logs from [OpenCV Public CI](http://pullrequest.opencv.org/buildbot/builders/master-mac/builds/11383) and compare its content with logs on your side (start from CMake "stdio").

---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by jonnio** [comment]
I have found this to be true when cmake can't find ant or other required dependencies for building java. Maybe someone could write up a nice document describing how it works.
