### ISSUE TITLE
Missing function to copy cv::Umat to cv::ocl::Image2D without allocating space on device

### ISSUE THREAD

**Issue by JulienMaille** [opencv/opencv#19140]
I'm experimenting with using OpenCV to launch my own openCL kernels.
Everything works fine so far, I followed this example: https://stackoverflow.com/a/28644721

However it seems that passing a `UMat` to the kernel as a `const image2d_t` requires
```c++
cv::ocl::Image2D image(umat_src);
```
But this will both allocate memory and perform the `UMat` to `Image2D` copy:
https://github.com/opencv/opencv/blob/b5a9ef6b7b79762c16365de82e2f278f579441b2/modules/core/src/ocl.cpp#L7105
https://github.com/opencv/opencv/blob/b5a9ef6b7b79762c16365de82e2f278f579441b2/modules/core/src/ocl.cpp#L7134

But if you want to process data in a loop and call the kernel multiple times, then `Image2D` constructor will keep allocating memory and device until it is full. A copy function would solve this.
Or am I doing it wrong?

**Comment by alalek** [comment]
Check this PR: #19135

---

> call the kernel multiple times

Avoid re-sheduling using the same `ocl::Kernel` instance.
Its `finit()` callback doesn't work with multiple scheduled kernels.

**Comment by JulienMaille** [comment]
I'm sorry I don't understand your comment. Do you mean an ocl::Kernel should be used only once?
Sound like a huge waste of time allocating/deallocating every time.
I'm running a kernel on a camera stream, how can I efficiently process a new image without reallocation? Would you have a tutorial to redirect me to? Thanks

**Comment by JulienMaille** [comment]
dear @alalek I suppose you are quite busy, do you still believe my PR doesn't make sense?

**Comment by diablodale** [comment]
Hi. answering your question...
> Do you confirm it makes sense to reuse (sequentially, not in //) a kernel and associated image2d memory?
This is what I was doing using low level OpenCL (but I'm moving away from nvidia toolkit, trying to leverage on opencv capabilities)

I do not. 😆 I do not yet have a wide view on the entire opencl and kernel subsystem of opencv. My issue and related PR about Image2D on a Kernel I found as I was tracing one of the memory allocation pathways and saw an irregularity/inconsistency. Alalek wrote in that discussion that Kernels can't be reused. They also implied that Image2D themselves can be reused by attaching them to new kernels. Based on what they wrote, I would think the sequence is create an Image2D, create a kernel, set() it on the kernel, run the kernel, get results, then destroy/raii the kernel, create a new kernel, set() that same Image2D on this 2nd kernel, etc...

However, I do not fully understand the logic flow of kernels and images. The file to explore is `ocl.cpp` and I can see relevant code there.

**Comment by JulienMaille** [comment]
Thanks for stopping by!
Did you answer based in how one should work with OpenCL or how one should call openCL through OpenCV?
It seems that reusing a kernel is absolutely normal when writing raw openCL code, see here for instance: https://community.khronos.org/t/calling-the-same-kernel-object-multiple-times/1340/2
I have been doing this for years without issues.

**Comment by alalek** [comment]
> could be shared among kernels

Right.

What is the problem to pass `cv::ocl::Image2D` multiple times (create `cv::ocl::Image2D` outside of the loop)? Please provide usage example.

---

> reusing a kernel is absolutely normal when writing raw OpenCL code

Right.

Main difference here is that OpenCV's ocl::Kernel does some lifetime management of used OpenCV buffers/images (including buffer pools). By default OpenCL processing in OpenCV is asynchronous.

Lifetime management of asynchronous calls is done through OpenCL callbacks for now.
This callback is binded to ocl::Kernel directly. So multiple callbacks can't be managed properly.
To resolve this, some "execution" object (dedicated class) should be created on each kernel enqueue to handle completion callback and lifetime of buffers (with own 1-1 callback and used buffers/images).

Until this is implemented, there is strong recommendation to use `ocl::Kernel` instance for single "use" only.

**Comment by JulienMaille** [comment]
> What is the problem to pass `cv::ocl::Image2D` multiple times (create `cv::ocl::Image2D` outside of the loop)? Please provide usage example.

This is not what I'm trying to do, so I don't have a ready made example, but I'm afraid that #19135 cleaning will clear the Image2D after the first kernel call.

> By default OpenCL processing in OpenCV is asynchronous.
What do you recommend to do if we're good with synchronous calls?

How are we supposed to take advantages of operation on Umat already being on the GPU together with OpenCL on those Umat (through Image2D) without constant reallocation/reupload?

**Comment by diablodale** [comment]
If we all three can agree on what the current code was intended to do, then we can verify that code and see if it does.

* I suspect the existing OpenCV Kernel code does not do what was intended. The cleanup after the Kernel runs sync/async is not consistent. That's what I'm exploring in my issue https://github.com/opencv/opencv/issues/19134
* Alalek tells us the existing implementation of OpenCV does not support (and was not designed for) reliable reuse of OpenCV Kernels
* Julien would like to reuse Image2D without re-upload to the GPU. This is unrelated to 19134 and its PR because OpenCV is not designed for Kernel reuse. Julien can not reuse Kernels to achieve his goal.

Julien, I recommend that you explore again Umat->Image2D and persist that var. Then make new OpenCV Kernels each time you need them. That matches that is currently implemented in OpenCV. And then attach the same Image2D saved in that var on each them. The code in `ocl.cpp` around lines 3532-3554 seems to only get the pointer to the Image2D and set it on the Kernel as a parameter with `clSetKernelArg`. I don't see any explict (re)allocation or upload.

Alalek, can you help clarity the intention of the cleanup code via issue# 19134. Then I can fix/close if there are any needed changes.

**Comment by alalek** [comment]
I believe it is better to provide use case first, preferable in form of test. `test_opencl.cpp` should be the right location for that.
This should help to resolve the issue itself instead of guessing what is the problem here.

**Comment by JulienMaille** [comment]
> * Julien would like to reuse Image2D without re-upload to the GPU. This is unrelated to 19134 and its PR because OpenCV is not designed for Kernel reuse. Julien can not reuse Kernels to achieve his goal.

Well I can, but UMat to Image2D conversion will reallocate data every time and lead to memory saturation.

> Julien, I recommend that you explore again Umat->Image2D and persist that var. Then make new OpenCV Kernels each time you need them. That matches that is currently implemented in OpenCV. And then attach the same Image2D saved in that var on each them. The code in `ocl.cpp` around lines 3532-3554 seems to only get the pointer to the Image2D and set it on the Kernel as a parameter with `clSetKernelArg`. I don't see any explict (re)allocation or upload.

Reallocation doesn't happen around 3252, but at line 7105

**Comment by diablodale** [comment]
Why would you do such a UMat->Image2D multiple times? Do it once as I wrote above, and reuse that one var.
If you have ever changing data, then I see no alternative. OpenCl doesn't allow reuse of Kernel args data.

I'm somewhat in Alalek's view. We need a clear repo case so we can investigate your needs. Every time we provide you solutions, you don't like them -- even though they should work. It is unclear what you are asking.

**Comment by JulienMaille** [comment]
> Why would you do such a UMat->Image2D multiple times?

I'm processing an image stream coming from a camera. If I'm doing it wrong, i'll be happy to fix my mistake.

> We need a clear repo case so we can investigate your needs.

I will cleanup and share code, just give me some time

> Every time we provide you solutions, you don't like them -- even though they should work. It is unclear what you are asking.

Huh? You make me sound like a stubborn kid. The only solution I read was to create/destroy kernels at the same rate my camera is generating images. Did I miss something?

**Comment by diablodale** [comment]
It is likely your camera data is written to CPU RAM. True?
And can also be said, your camera data is not directly written by the camera hardware to GPU memory. True?
Cameras typically do not DMA data directly from its sensor to GPU memory. It usually travels through CPU/CPU memory.

If all that is true, then the camera frame data resides in CPU RAM. Every new frame is in CPU RAM. Repeatedly.
That means that new camera frames are either processed in CPU RAM....or...each new frame is uploaded to the GPU memory.
You can upload them with UMat or indirectly with Image2D and attach either on to a ocl::Kernel.
That frame of data will stay on the GPU as long as OpenCL and the graphics driver wants it to stay. There are limited guarantees (or no guarantee) as I wrote above with `clSetKernelArg`.

So you could write pseudocode like...
```c++
ocl::Image2D image_for_kernel;
while (true) {
  cv::Umat camera_frame= getCameraUMatFrame();
  if (!camera_frame.empty()) image_for_kernel = ocl::Image2D(camera_frame);
  always_new_kernel.set(1, image_for_kernel);
  always_new_kernel.run()
}
```

You must always create a new Kernel. Therefore you must always set() your data on that Kernel. However, you do not have to repeatedly create UMat or Image2D until you get new data from your camera. Previous frames stored in Image2D may not be retained in GPU memory -- the standard I linked above makes no guarantees. The UMat itself might still be in GPU memory and so when the Image2D references it in the set(), it might be able to reuse or do a quicker GPU->GPU copy rather than a full CPU->GPU copy.

That's my thinking. What have you done to explore this?

**Comment by JulienMaille** [comment]
Sorry for not being able to reply earlier, I will try to simplify my use case below.
```c++
class demo {
  private:
    cv::ocl::Kernel _kernel;
    cv::UMat _inImg, outImg;
    cv::ocl::Image2D _in2dImg;
  
  void init(int w, int h)
  {
    _inImg.create(cv::Size(w, h), CV_32FC1, cv::USAGE_ALLOCATE_DEVICE_MEMORY);
    _outImg.create(cv::Size(w, h), CV_32FC1, cv::USAGE_ALLOCATE_DEVICE_MEMORY);
    _in2dImg = cv::ocl::Image2D(_inImg);
    _kernel.create("demo", loadProgram());
  }
  
  void processingLoop()
  {
    while (true) {
      cv::Mat camera_frame = getCameraFrame(); // camera buffer to cv::Mat
      _inImg= preprocessing(camera_frame); // many OpenCV calls on cv::UMat

      _in2dImg.copy(_inImg); // the copy operator from my rejected PR #19144
      _kernel.args(_in2dImg, _outImg, param1, param2, param3); // update arguments
      _kernel.run(2, globalThreads, localsize, true); // run kernel

      postProcess(_outImg); // many OpenCV calls on the cv::Umat produced by the kernel
    }
  }
}
```
Please let me know what is not clear, so I can detail it.
Before my PR, I was calling instead `_in2dImg= ocl::Image2D(_inImg);` of `_in2dImg.copy(_inImg)` and this resulted in memory explosion, because of the reallocations.

**Comment by diablodale** [comment]
> You must always create a new Kernel.

**Comment by JulienMaille** [comment]
Why? Standard openCL code doesn't need a new kernel for each image. Sounds like this will kill the performances

**Comment by diablodale** [comment]
Why? Because OpenCV requires it. the core team documented that above https://github.com/opencv/opencv/issues/19140#issuecomment-746995684

OpenCL might support it, but not OpenCV at this time.

**Comment by JulienMaille** [comment]
To me it looks like they do not support parallel scheduling of the same kernel, in my case this won't happen.
As said above, I've been using my PR on a 30fps camera without crash or memory issues.
I was asked by @alalek to share a use case, which I did today. If you can detail a bit more what you had in mind when you said
> To resolve this, some "execution" object (dedicated class) should be created on each kernel enqueue to handle completion callback and lifetime of buffers (with own 1-1 callback and used buffers/images).

maybe we can work that way
