### ISSUE TITLE
Test ExposureCompensate.SimilarityThreshold fails on Windows 10 in master branch

### ISSUE THREAD

**Issue by asmorkalov** [opencv/opencv#19184]
##### System information (version)
- OpenCV => 4.5.1-pre (git 46e275dfe4616b07cd2492c17698d1a0be0aa6df )
- Operating System / Platform => Windows 10 x64
- Compiler => Visual Studio 2019 Community Editon x64, Ninja

##### Detailed description

```
C:\Slave\workspace\nightly-master\windows10\opencv\modules\stitching\test\test_exposure_compensate.cpp:66
Expected: (psnr_similarity_mask) > (300), actual: 38.0114 vs 300
```

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by LupusSanctus** [comment]
The problem was reproduced also on Linux. The PSNR results don't change in accordance with ``similarity_threshold`` value, thus we get unexpected behaviour:
``(psnr_similarity_mask) > (300), actual: 38.0114 vs 300``

It depends on OpenCL implementation. Test failures appear on Nvidia cards when OpenCL is used, in our case:
* GeForce RTX 2070 SUPER, OpenCL 1.2 (Ubuntu)
* GeForce RTX 2080, OpenCL 1.2 (Win)

Test passes with below configurations:
* AMD Radeon RX 5700, OpenCL 2.0
* AMD Radeon RX 5700, OpenCL 1.2 pocl 1.6-1
* GeForce RTX 2070 SUPER, OpenCL 1.2 pocl 1.1-5

**Comment by LupusSanctus** [comment]
Running the test on Nvidia (1) OpenCL backend, the second test case with [``similarity_threshold=0.1``](https://github.com/opencv/opencv/blob/master/modules/stitching/test/test_exposure_compensate.cpp#L64) returns the [same result](https://github.com/opencv/opencv/blob/master/modules/stitching/test/test_exposure_compensate.cpp#L63) as [the first one](https://github.com/opencv/opencv/blob/master/modules/stitching/test/test_exposure_compensate.cpp#L51) with [``similarity_threshold=1``](https://github.com/opencv/opencv/blob/master/modules/stitching/test/test_exposure_compensate.cpp#L41):
`opencv_test_stitching --gtest_filter='*ExposureCompensate.SimilarityThreshold*'`

However, changing backend to (2) OpenCL pocl or running the test on AMD Radeon RX 5700 (with enabled OpenCL) - we get expected test behaviour, different PSNR values.

A possible way of the above-described problem investigation was examination of the appropriate OCL kernels, checking the ``similarity_threshold`` value - whether it was changed or cached. However, no kernels for the methods from [``exposure_compensate``](https://github.com/opencv/opencv/blob/master/modules/stitching/src/exposure_compensate.cpp#L336) (especially those where ``similarity_threshold`` is used - ``buildSimilarityMask(...)``) were revealed. Threshold value is correctly set inside ``GainCompensator`` class: ``similarity_threshold_`` field and used in [``buildSimilarityMask(...)``](https://github.com/opencv/opencv/blob/master/modules/stitching/src/exposure_compensate.cpp#L343) method. 
I've compared the execution sequence of the methods running the test on (1) and (2) - it was equivalent. Comparison of the ``vector<UMat> similarities_`` populated with [``buildSimilarityMask``](https://github.com/opencv/opencv/blob/master/modules/stitching/src/exposure_compensate.cpp#L336) (the values depend on ``similarity_threshold``) showed their equality in both cases, (1) and (2).

@alalek, @vpisarev, could you, please, take a look at this issue. Maybe, there are some possible OpenCV-OCL pecularities that can lead to the [described](https://github.com/opencv/opencv/issues/19184#issuecomment-752216183) above test behaviour?

**Comment by tomoaki0705** [comment]
I'm surprised I started debugging this issue few days ago, and some one already created an issue for this topic.

I faced this issues on following platforms
 - Failed
   - firefly-rk3399
   - odroid-c4
   - odroid-n2-plus
   - odroid-xu4
   - tinkerboard
   - rock-pi-4c
 - Passes
   - jetson-nano 
   - jetson-tx1 
   - jetson-tx2 
   - jetson-xavier 
   - jetson-xavier-nx 
   - le-potato
   -  raspberry-pi-3
   -  raspberry-pi-4 
 - I'll update the detail of each platform soon, but the platforms that filed has Arm Mali as a GPU and has an OpenCL capability.
 - The passed one doesn't have OpenCL capability, so CPU version implementation will be kicked.
 - Also, on the failed platforms, if I set environmental variable `OPENCV_OPENCL_DEVICES=disabled`, then CPU version is kicked and test passes.
 - Now, I narrowed down the behavior of the test, and the difference comes from [here](https://github.com/opencv/opencv/blob/63bb2abadab875fc648a572faccafee134f06fc8/modules/stitching/src/exposure_compensate.cpp#L157).

https://github.com/opencv/opencv/blob/63bb2abadab875fc648a572faccafee134f06fc8/modules/stitching/src/exposure_compensate.cpp#L157

 - This `bitwise_and` function does nothing when OpenCL is enabled.
 - In another way, if I temporarily disable OpenCL just for this `bitwise_and` function, the test passes
```
+bool flag = cv::ocl::useOpenCL();
+cv::ocl::setUseOpenCL(false);
 bitwise_and(intersect, similarity, intersect);
+cv::ocl::setUseOpenCL(flag);
```
 - Test result

```
[       OK ] ExposureCompensate.SimilarityThreshold (93847 ms)
[----------] 1 test from ExposureCompensate (93848 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (93849 ms total)
[  PASSED  ] 1 test.
``` 
 - This passed `UMat` is 32x32 and it contains either `0` or `0xff`
 - Though `similarity` sometime has `0`, the `and` operation does nothing, and `0xff` is kept.  That's where the behavior differs.
 - Additionally, I tried the same test in `opencv_test_core` by  kicking `OCL_Arithm/Bitwise_and.Mat/0` (`8UC1`) and fixing the size as 32x32, but the test passed.  So, there's something under the hood which triggers this `bitwise_and` to do nothing.

**Comment by tomoaki0705** [comment]
If OpenCL version implementation is kicked, I could trace down the call arrives [here](https://github.com/opencv/opencv/blob/63bb2abadab875fc648a572faccafee134f06fc8/modules/core/src/arithm.cpp#L265)

https://github.com/opencv/opencv/blob/63bb2abadab875fc648a572faccafee134f06fc8/modules/core/src/arithm.cpp#L264-L265

 - The `opts` passed to the OpenCL kernel [here](https://github.com/opencv/opencv/blob/63bb2abadab875fc648a572faccafee134f06fc8/modules/core/src/arithm.cpp#L115-L122) was 

```
"-D BINARY_OP -D OP_AND -D DOUBLE_SUPPORT -D dstT=uchar16 -D DEPTH_dst=0 -D dstT_C1=uchar -D workST=uchar16 -D cn=16 -D rowsPerWI=1"
```
 - As I mentioned in the previous post, I modified the `opencv_test_core` to give same size of `UMat` in the test.  I could confirm that exactly same `opts` was passed to OpenCL kernel, and this time, `opencv_test_core` passes.
 - I suspected that this error only happens when certain `opts` was used, but it seems the condition is much more complicated.

**Comment by tomoaki0705** [comment]
Also, this temporally fix [putting in here](https://github.com/opencv/opencv/blob/63bb2abadab875fc648a572faccafee134f06fc8/modules/stitching/src/exposure_compensate.cpp#L157) worked.

```
- bitwise_and(intersect, similarity, intersect);
+ bitwise_and(intersect.clone(), similarity, intersect);
```

The combination is still not determined yet, but in this case, this binary operation takes `Mat`, `UMat` and written back to `Mat`.
The `Mat` are processed **in-place** and that seems one of the cause.
Now, making a copy every time here is kind of a dirty fix, and may be something should be fixed in memory management side.

**Comment by alalek** [comment]
@tomoaki0705 Thank you for investigation!

> bitwise_and(intersect, similarity, intersect);

OpenCL kernels for operations with "in-place" src/dst buffers should be implemented with another kernels code. This is a bug to be fixed in `core` module.

---

Workaround without `.clone()` (reduced performance impact):
```
Mat_<uchar> intersect_updated;
bitwise_and(intersect, similarity, intersect_updated);
std::swap(intersect, intersect_updated);
```

**Comment by tomoaki0705** [comment]
Thanks for the updated fix propose.
I hired the `swap` approach and created a PR.
The PR is for master, since this test doesn't exists in 3.4 branch
