### ISSUE TITLE
Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'

### ISSUE THREAD

**Issue by ZurMaD** [opencv/opencv#19218]
##### System information (version)

- OpenCV == 4.4.0.46
- Operating System / Platform => Debian 10.7

requirements:

```
gdown==3.12.2
numpy==1.19.1
pandas==1.1.0
streamlit==0.72.0
opencv-contrib-python-headless==4.4.0.46
```

##### Detailed description

Hello, I trained weights based on [yolo3-tiny.cfg](https://github.com/roboflow-ai/yolov3/blob/master/cfg/yolov3-tiny.cfg) provided by [Roboflow-ai](https://github.com/roboflow-ai/yolov3/tree/master/cfg). However, when I try to do an inference with 

```
net = cv.dnn.readNetFromDarknet(configPath, weightsPath)
```
appears

```
error: OpenCV(4.4.0) /tmp/pip-req-build-xgme2194/opencv/modules/dnn/src/darknet/darknet_io.cpp:908: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'
Traceback:

File "/home/user/.local/lib/python3.7/site-packages/streamlit/script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "/home/user/Desktop/gits/fishv3/app.py", line 50, in <module>
    run()
File "/home/user/Desktop/gits/fishv3/app.py", line 31, in run
    boxes, idxs = yolo.runYOLOBoundingBoxes_streamlit(image, yolopath, confidence, threshold)
File "/home/user/Desktop/gits/fishv3/utils/yolov3.py", line 222, in runYOLOBoundingBoxes_streamlit
    net = cv.dnn.readNetFromDarknet(configPath, weightsPath)
```

##### Steps to reproduce

```
git clone https://github.com/DZPeru/fishv3
cd fishv3
pip3 install -r requirements.txt
curl-L https://raw.githubusercontent.com/roboflow-ai/yolov3/master/cfg/yolov3-tiny.cfg --output "fishv3/fish_test.cfg" 
gdown --id 1y2y15XWY4SQSb_A5sHtKim6OSSRrdyd7 --output ./fishv3/fish.weights # Weights
streamlit run app.py
```

##### Issue submission checklist

I also checked https://github.com/opencv/opencv/issues/17483 https://github.com/opencv/opencv/issues/17298 https://github.com/opencv/opencv/issues/15502 and didn't work

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by LupusSanctus** [comment]
The below error:
`(-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'
`
occures because of provided ``fish.weights`` format:
```
gdown --id 1y2y15XWY4SQSb_A5sHtKim6OSSRrdyd7 --output ./fishv3/fish.weights # Weights
```
it returns zip-archive. [Darknet *.weights](https://pjreddie.com/darknet/yolo/) are binary files. Thus, OpenCV expects darknet format of weights. Reading weights with [``ReadDarknetFromWeightsStream(...)``](https://github.com/opencv/opencv/blob/master/modules/dnn/src/darknet/darknet_io.cpp#L1010), first three ints are taken from the stream:
int32_t major_ver, minor_ver, revision;
ifile.read(reinterpret_cast<char *>(&major_ver), sizeof(int32_t));
ifile.read(reinterpret_cast<char *>(&minor_ver), sizeof(int32_t));
ifile.read(reinterpret_cast<char *>(&revision), sizeof(int32_t));

as you feed zip-archive (``fish.weights``), we expectedly get wrong values, for example, `major_ver = 67324752, minor_ver =  134742016`. Hence, we go to the following (``if(transpose)``)[https://github.com/opencv/opencv/blob/master/modules/dnn/src/darknet/darknet_io.cpp#L895]:
```
bool transpose = (major_ver > 1000) || (minor_ver > 1000);
if(transpose)
    CV_Error(cv::Error::StsNotImplemented, "Transpose the weights (except for convolutional) is not implemented");
```

In case of binary darknet *.weights, it supposed that the first three ints contain appropriate information about major_ver, minor_ver, revision. For example, `yolov3.weights` contains:
```
major_ver = 0
minor_ver =  2
revision = 0
```

**Comment by ZurMaD** [comment]
Thanks for the explanation! OpenCV will support zipped weights in the future?
