### ISSUE TITLE
[branch next]: seg. fault in imgproc putText method when a certain TTF font is used 

### ISSUE THREAD

**Issue by drahoslavzan** [opencv/opencv#19224]
##### System information (version)

OpenCV => next
OS => Linux x64

##### Detailed description

Most of the fonts work as expected, but with some TTFs an app will crash.

##### Steps to reproduce

1. Download TTF font from https://www.fontsquirrel.com/fonts/fff-tusj
2. Set it to FontFace instance and use it with getTextSize method

The app with crash in **stb_truetype.cpp** on line 3512. Due to **new_bufsz** in **memset** being a negative number.

```.cpp
     ...
     gbm.pixels = *buf;
     if (gbm.pixels) {
         memset(gbm.pixels, 0, new_bufsz);  // <----- HERE
         gbm.stride = gbm.w;
         stbtt_Rasterize(&gbm, 0.35f, vertices, num_verts, scale_x, scale_y,
                         shift_x+pad_x, shift_y+pad_y, scaled_ix0, scaled_iy0, 1, info->userdata);
    ...
```

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by asmorkalov** [comment]
@vpisarev please take a look.

**Comment by vpisarev** [comment]
Sorry, that took extremely long time to reproduce. I took the latest 5.x branch snapshot and temporarily edited [Drawing.ttf_text test](https://github.com/opencv/opencv/blob/cd5dbf9389a569a5b961234d5ae87f7841498ed7/modules/imgproc/test/test_drawing.cpp#L761): replaced

```
FontFace sans("sans");
```

with

```
FontFace sans("/home/vpisarev/Downloads/FFF_Tusj.ttf");
```

everything worked well. Of course, the test did not pass because of the different appearance, but if you [enable visualization in the same test](https://github.com/opencv/opencv/blob/cd5dbf9389a569a5b961234d5ae87f7841498ed7/modules/imgproc/test/test_drawing.cpp#L843), you will see correctly rendered text.

I assume, the problem has been resolved. If not, please, provide specific test that reproduces the problem.
