### ISSUE TITLE
Darwin collision of Point/Rect/Size types is still happening

### ISSUE THREAD

**Issue by imxieyi** [opencv/opencv#19254]
##### System information (version)

- OpenCV => 4.5.1
- Operating System / Platform => macOS 11.1, iOS 14.3
- Compiler => Xcode 12.3, CMake 3.19.2

##### Detailed description

Either the old `.framework` or the new `.xcframework` won't compile with pure Swift project. The collision was supposed to be fixed by #18977. However it is still happening with both 4.5.1 and master branch (005508a0). Example log:
```
/Users/x/Library/Developer/Xcode/DerivedData/opencv-test-fergxwbmhhedlzemnxjfnzmrvlbj/Build/Products/Debug-iphoneos/opencv2.framework/Modules/opencv2.swiftmodule/arm64-apple-ios.swiftinterface:29:122: error: ambiguous type name 'Size' in module 'opencv2'
  @nonobjc public class func calibrateCamera(objectPoints: [opencv2.Mat], imagePoints: [opencv2.Mat], imageSize: opencv2.Size, cameraMatrix: opencv2.Mat, distCoeffs: opencv2.Mat, rvecs: inout [opencv2.Mat], tvecs: inout [opencv2.Mat], stdDeviationsIntrinsics: opencv2.Mat, stdDeviationsExtrinsics: opencv2.Mat, perViewErrors: opencv2.Mat, flags: Swift.Int32, criteria: opencv2.TermCriteria) -> Swift.Double
                                                                                                                 ~~~~~~~ ^
opencv2.Size:1:12: note: found candidate with type 'Size'
open class Size : NSObject {
           ^
Darwin.Size:1:18: note: found candidate with type 'Size' (aka 'Int')
public typealias Size = Int
                 ^
```

##### Steps to reproduce

1. Build `xcframework` according to [platforms/apple/readme.md](https://github.com/opencv/opencv/blob/master/platforms/apple/readme.md).
2. Create a new iOS Swift project in Xcode.
3. Import `opencv2.xcframework` from step 1 to the project.
4. Add `import opencv2` in any of the `.swift` files.
5. Build the project.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by chrisballinger** [comment]
I have a commit that fixes this in a semi-breaking way, but it was taken out of that PR. Let me see if I can dig it up, hopefully it wasn't lost in a force-push.

**Comment by chrisballinger** [comment]
These commits should do the trick: 

* https://github.com/Rightpoint/opencv/pull/4/commits/00497a798ca29b542ec5ce7923c4a1d9bbfc6998
* https://github.com/Rightpoint/opencv/pull/4/commits/c0b7113cdd542496361aa10436d6b0e9a48c3765
* https://github.com/Rightpoint/opencv/pull/4/commits/ed46c569d903c631547369dadf29fc649442dc95

Want me to cherry pick them into a new PR?

**Comment by komakai** [comment]
@chrisballinger 2 questions
 - why does this only happen when using the .xcframework ? (I have not had this problem using just the plain iOS .framework)
 - in the Swift type system we can use the framework name to resolve any ambiguity (i.e. it should always be possible to say `opencv2.Size` to distinguish our `Size` from somebody else's `Size`) - so why isn't Swift able to distinguish `opencv2.Size` from `Darwin.Size`?

**Comment by komakai** [comment]
Hello - I have done some investigation into the issue:
I built the xcframework with this command line
`./opencv/platforms/apple/build_xcframework.py --out xcframetest --iphoneos_archs arm64,armv7 --iphonesimulator_archs x86_64,arm64 --build_only_specified_archs`
then I tried importing just the plain iOS framework - that worked fine
then I tried importing just the plain iOS Simulator framework -  that worked fine
then I tried importing the xcframework - reproduced the issue
From what I can work out, the import works differently when importing a xcframework - it is using the **swiftinterface** file rather than whatever a plain framework import uses.
In any case this looks like a bug in the Swift compiler - basically the error messages is saying:
"When you say `opencv2.Size` I can't tell whether you mean `opencv2.Size` or `Darwin.Size`"
I believe the compiler should be able to work out that `opencv2.Size` means `opencv2.Size`
If this interface really were ambiguous then the compiler should give an error when generating the interface not when importing it.
I have created a project at https://github.com/komakai/XcFrameworkTest that isolates the conditions needed to reproduce the problem.
Will head over to https://github.com/apple/swift and see if someone there can help

**Comment by chrisballinger** [comment]
@komakai Thanks for confirming the issue. Want me to re-submit a PR with my original fix?

**Comment by komakai** [comment]
Hello @chrisballinger 
If you check the comments below - you will see that the only time a breaking change is really acceptable is an OpenCV major version change.
https://github.com/opencv/opencv/pull/17165#issuecomment-635910748
https://github.com/opencv/opencv/pull/17165#issuecomment-636014196
But even on a major version change I do not think it is a good idea to make a breaking change to OpenCV to work around a bug in a third party compiler. The correct thing to do would be to raise an issue against the compiler and wait for it to be fixed (this is what I meant when I said I would "head over to https://github.com/apple/swift and see if I could find someone to help me" - sorry if that wasn’t very clear).
In the meantime I suggest the following work-arounds. Users that don’t need the xcframework can carry on using the existing plain iOS/macOS frameworks.
For users that absolutely need an xcframework I propose the following workaround:
I saw you added a cmake flag SWIFT_DISABLE - can you make a PR that will set this flag if "--disable_swift" is passed to `./platforms/ios/build_framework.py` or `./platforms/osx/build_framework.py`
and then update `build_xcframework.py` to forward this flag if set.
This will mean that the xcframework will not include the idiomatic Swift extensions but this can be worked round  by manually add these files here http://xtravision.stars.ne.jp/swift-extensions/OpenCV-Swift.Extensions.zip to any project import OpenCV via the xcframework.
Once the bug in the Swift compiler is fixed then we can revert this workaround.
Just one final word on the breaking change you keep proposing: Lots of my personal projects are using the Point/Size/Rect Swift objects without any issue. It would be a major inconvenience if I had to change all these due to your breaking change.

**Comment by chrisballinger** [comment]
@komakai My PR isn't technically a fully breaking change, it has typealias shims for backwards compatibility. For instance, the test suite is unmodified and uses the OpenCV versions of `Point`, `Rect`, and `Size`, see https://github.com/Rightpoint/opencv/commit/ed46c569d903c631547369dadf29fc649442dc95.

Not using XCFrameworks will not be an option for many developers somewhat soon, it's required if you want to use the iOS Simulator on an Apple Silicon Mac.

But you do raise a good point about moving the Swift files to a separate target (ideally not using CMake), because it would workaround the issues with compiling Swift for Mac Catalyst using CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/21436

**Comment by komakai** [comment]
> My PR isn't technically a fully breaking change, it has typealias shims for backwards compatibility. For instance,
> the test suite is unmodified and uses the OpenCV versions of Point, Rect, and Size, see Rightpoint@ed46c56.

@chrisballinger thanks for the clarification about your change - I hadn't spotted the type aliases. If you have that working and there are no client code changes required then I'm good with it.

**Comment by komakai** [comment]
I have created a bug report for the Swift import error: https://bugs.swift.org/browse/SR-14079

**Comment by siyaofa** [comment]
This problem still in opencv 4.5.2 with  Xcode12.5. Swift compiler bugfix too slow .... The only way solve this is compiling different version for both real device and simulator as komakai mentioned before.

**Comment by komakai** [comment]
@siyaofa Thanks for checking. Please see my comment over on https://github.com/opencv/opencv/issues/19992
