### ISSUE TITLE
OpenCV cannot load Intel MKL on import

### ISSUE THREAD

**Issue by Alpheron** [opencv/opencv#19577]
##### System information (version)

- OpenCV =>  4.5.1-dev
- Operating System / Platform => Mac OS X, 11.2.1
- Compiler => Apple Clang

##### Steps to reproduce

I was trying to build OpenCV from source and I have gotten this error when importing running import cv2 in the Python3 shell. The specific version of OpenCV that I cloned to build from source can be found [here](https://github.com/Alpheron/LibraryBuildScripts/blob/main/MacOsX/OpenCV/Mac_OS_X-OpenCV-CMake-Params.txt). I ended up testing to import the cv2 module before I am greeted with this error.

```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/opencv/build/lib/python3/cv2.cpython-38-darwin.so, 2): Library not loaded: @rpath/libmkl_intel_lp64.1.dylib
  Referenced from: /usr/local/lib/opencv/build/lib/python3/cv2.cpython-38-darwin.so
  Reason: image not found
```

All the environment variables are passed into all the commands using `sudo -E` and when first generating the CMake configurations, all the paths are loaded and are configured properly. 

MKL: Downloaded from oneApi 2021 version
TBB: Downloaded from `brew install tbb` and is 2020 3.x 

The MKL directory is configured as can be seen when running the code snippet below.
```
❯ echo $DYLD_LIBRARY_PATH
/opt/intel/oneapi/mkl/latest/lib
```

All the paths and modules are defined and are picked up when running the CMake configuration command above. If the CMakeCache.txt file is used to build the library, what is concerning is how CMake is able to get the proper paths and configure everything properly when generating a configuration but not able to build the library using that same data. 

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
> `DYLD_LIBRARY_PATH`

Apple may reset this variable if you launch any shell scripts before python (or probably even python itself). Check SIP policies.

Details:
- https://apple.stackexchange.com/questions/286315/system-integrity-protection-breaks-dyld-library-path-for-python-scripts
- https://stackoverflow.com/questions/39927235/alternative-for-the-dyld-library-path-trick-since-mac-os-10-11-el-capitan-with-s

Workaround is embedding rpaths into `cv2.cpython-38-darwin.so` or libopencv_core.dylib, so they become work without `DYLD_LIBRARY_PATH`.
- https://medium.com/@donblas/fun-with-rpath-otool-and-install-name-tool-e3e41ae86172
- CMake's `CMAKE_INSTALL_RPATH` variable

**Comment by Alpheron** [comment]
After modifying the `@rpath` of each individual problematic `.dylib` file, OpenCV was able to successfully be imported.
