### ISSUE TITLE
OpenCV4.5.1 / Darknet / forward problem (Always the same result)

### ISSUE THREAD

**Issue by LFRS** [opencv/opencv#19643]
Hi,

When i run the forward pass to get output of the output layers, the first frame i get the output boxes correctly but in the following frames, always return the output boxes of the first frame.
Has anyone encountered this symptom? 

- OpenCV => 4.5.1
- Operating System / Platform => Ubuntu
- Compiler => Cmake 3.19
- Darknet
- Yolov4 tiny model 

Example (Just an example):

      //Set Model
      netCV= readNetFromDarknet (sModel_Config_Path, sModel_Weights_Path);
      
      //Set CUDA
      netCV.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
      netCV.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
      
      for (;;)
      {
          vector<Mat> vMat_Outs;
          
          //read frame
          cap.read(matFrame);
    
          // Create a 4D blob from a frame.
          matBlob= blobFromImage(matFrame, 1 / 255.0, cv::Size(iMatAnalysis_Width, iMatAnalysis_Height), Scalar(0, 0, 0), true, false);
          
          //Sets the input to the network	
          sAIS_Status.AI.OpenCV.netCV.setInput(matBlob);
          
          // Runs the forward pass to get output of the output layers
          netCV.forward (vMat_Outs, get_OutputsNames(netCV));
    
         //->  The "vMat_Outs" result is always the same, but the Mat frame is always different.
      }

Thanks,
Luis

**Comment by alalek** [comment]
Reproducer must be complete including all necessary input data (image frames and model).

**Comment by LFRS** [comment]
Hi,

Below is the source code of the test (Any model can be used to test it):
[Test_Code.zip](https://github.com/opencv/opencv/files/6065385/Test_Code.zip)

Detections start to malfunction when i use the system command to send a command to the operating system in a separate thread.

I'm using a Jetson Xavier Nx with Jetpack 4.5.1.

Thanks,
Luis

**Comment by LFRS** [comment]
> Reproducer must be complete including all necessary input data (image frames and model).

Hi Alexander,

Can you change the status, i added a code to reproduce the error, so i belive that is not incomplete any more.

Thanks

**Comment by YashasSamaga** [comment]
```
constexpr float CONFIDENCE_THRESHOLD = 0.7;
constexpr int NUM_CLASSES = 1;
```
1. The `NUM_CLASSES` constant controls the classwise NMS procedure. You should set it to 80 if you want all classes to be considered. By setting it to one, you're performing NMS for objects of the first class (persons class) and it just happens that there are no people in your images. Therefore, you get no detections all the time (and vacuously same detection every time).
2. The confidence threshold might be very high and it leads to no detections.

I changed `NUM_CLASSES` to `80` and `CONFIDENCE_THRESHOLD` to 0.2 and it's working. I can see eggs being detected as orange, apple, etc with YOLOv4 model.

> Detections start to malfunction when i use the system command to send a command to the operating system in a separate thread.

This is making no difference on my end.

**Comment by juacamgo** [comment]
@LFRS why you are using blob and forward instead of DetectionModel class? [dnn DetectionModel class](https://docs.opencv.org/4.5.1/d3/df1/classcv_1_1dnn_1_1DetectionModel.html)

**Comment by heuripedes** [comment]
I've run into a similar issue but with Python, perhaps this can help someone.

If I use CUDA and run a subprocess AFTER `forward()` I get repeated outputs from the second frame onwards:

https://user-images.githubusercontent.com/59172/124690861-384bc700-deb1-11eb-941e-26d64eded6e4.mp4

But if I run the subprocess BEFORE `forward()` the program works as expected:

https://user-images.githubusercontent.com/59172/124690867-3a158a80-deb1-11eb-981b-839a0f2a7966.mp4

The problem disappears if I use the default backend instead.

* Script and input file: [rep.zip](https://github.com/opencv/opencv/files/6773834/rep.zip) (edit the first vars in main() to change behavior)
* [yolov4.weights](https://drive.google.com/open?id=1L-SO373Udc9tPz5yLkgti5IAXFboVhUt) file from AlexeyAB's model zoo
* [yolov4.cfg](https://drive.google.com/open?id=1hSrVqiEbuVewEIVU4cqG-SqJFUNTYmIC) file from AlexeyAB's model zoo

* System: Ubuntu 20.04.2 amd64
* Kernel: 5.10.0-1034-oem
* CPU: Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
* GPU: NVIDIA Corporation GP107M [GeForce GTX 1050 3 GB Max-Q]
* NVIDIA Driver: 470.42.01
* CUDA Version: 11.3
* cuDNN: 8.2.2.26
* OpenCV 4.5.2

**Comment by YashasSamaga** [comment]
> Script and input file: rep.zip (edit the first vars in main() to change behavior) model from AlexeyAB's model zoo: yolov4.weights yolov4.cfg

Thanks. I am not able to reproduce locally with the code you provided. It's working in both `subprocess_first` set to `True` and `False` (with `cuda=True`). I am using OpenCV 4.5.3-dev (5aa7435d2537e677611390b530e31b3b204773a3) cuDNN 8.2.4, CUDA 11.4 and driver 470.57.02. It may be broken on @LFRS's system too but his reproducer also worked correctly on my laptop with older versions.

Since there are many people facing the issue (in C++ as well as python with multiprocessing), something is wrong. From what I understand with your reproducer, it looks like the mere act of creating a subprocess (a totally unrelated program that doesn't even interact with the parent python process) somehow breaks the DNN inference. This is quite absurd. My guess is that this has something to do with CUDA context initialization/destruction. If you **initialize** (first forward pass) the `net` object and then create a random subprocess (could be anything), the DNN inference just stops working. If you create a subprocess first, the **initialization** happens in the next forward pass and the DNN inference continues to work. To confirm this, can you re-initialize after creating the subprocess and check whether it works?

```
if not subprocess_executed and subprocess_first:
            subprocess.run(["python3", "--version"])
            subprocess_executed = True
            net = initialize("yolov4.cfg", "yolov4.weights", use_cuda)
```

Few more questions:
1. Can you see if your GPU is being used in the case where you see repeated boxes? (a quick look into `nvidia-smi` should be sufficient)
2. Can you profile the python script using Nsight Systems? Nsight Systems comes with CUDA Toolkit. Pass `python` as the program and the script as arguments to the program. The report should help establish what's happening as it shows API calls, kernels that execute, memory transfers, etc.

**Comment by alalek** [comment]
Subprocesses through `fork()` calls should be avoided in applications. It is not able to clone properly multi-threaded application.
Details: #5150

**Comment by zj88** [comment]
Hi, I have the same problem, maybe my info will help.
Driver 470.57.02
CUDA 11.4
cuDNN 8.2.2
OpenCV every version (5aa7435, 4.5.3, 4.5.0, 4.4.0, 4.3.0)

I use Tesseract in my pipeline, running through pytesseract which uses subprocess.Popen. When commenting out the lines responsible for using pytesseract, it works fine. With those lines, it returns the same result with second image onwards. So as you suggested it looks like creating subprocess messes up GPU inference. But everything works great on CPU, exactly the same code fails on GPU but works on CPU. Maybe there is some way to fix this.

> Can you see if your GPU is being used in the case where you see repeated boxes? (a quick look into nvidia-smi should be sufficient)

Yes, it is used

I also tried setting input to None just before using the image:
```
docNet.setInput(None)
docNet.setInput(blob)
```
I helps - the detections returned look good, but the program crashes every time on different image. Sometimes numbers returned by forward() are crazy, like:
```
out=[array([[0.01223295, 0.00526417, 0.02081972, ..., 0.        , 0.        ,
        0.        ],
       [0.00671947, 0.0101717 , 0.03875341, ..., 0.        , 0.        ,
        0.        ],
       [0.01071563, 0.00379547, 0.10056212, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.991202  , 0.9851894 , 0.03600844, ..., 0.        , 0.        ,
        0.        ],
       [0.9889194 , 0.98757166, 0.0384307 , ..., 0.        , 0.        ,
        0.        ],
       [0.98935705, 0.9886463 , 0.14541773, ..., 0.        , 0.        ,
        0.        ]], dtype=float32), array([[-4.31781515e+17, -1.03346501e-04, -5.47870468e-06, ...,
        -2.26314733e-05, -2.58598800e+16, -1.07284054e-01],
       [-3.49913250e-07, -3.95221582e+14, -4.11411544e-04, ...,
        -4.13326372e-04, -2.16349214e-08, -3.93022492e+14],
       [-1.65330549e-03, -8.70071730e-08, -3.95230138e+14, ...,
        -6.35900456e+15, -1.66093500e-03, -5.40895773e-09],
        ...
     nms_indices = cv2.dnn.NMSBoxes(box, conf, confThreshold, nmsThreshold)
OverflowError: Python int too large to convert to C long

box=[[2517283778239270923734877408885221621760, 0, 0, 0], [36253126539130027050544508622707097600, 119370297839198848524607730608777461760, 2399680412568603966509217715165593600, 101583940334220753197114327040], [8930194869656054142484579614720, -14691070795304655033067203609514475520, 0, 29382141590609310066134407219028951040], [69, 479, 1252, 806], [47, 456, 1295, 852], [31, 459, 1332, 846], [47, 481, 1289, 823], [30, 468, 1325, 847], [27, 474, 1338, 836]]
```

**Comment by heuripedes** [comment]
@YashasSamaga 

The problem does not happen if I restart the network after spawning the new process.

>Can you see if your GPU is being used in the case where you see repeated boxes? (a quick look into nvidia-smi should be sufficient)

Yes. In both cases GPU usage goes up to 35-50% and VRAM usage up to 1000MiB.

>Can you profile the python script using Nsight Systems? Nsight Systems comes with CUDA Toolkit. Pass python as the program and the script as arguments to the program. The report should help establish what's happening as it shows API calls, kernels that execute, memory transfers, etc.

I'm unable to do this. `nsys` is segfaulting and `nsight` runs forever.

**Comment by drakorg** [comment]
Has it been fixed? If not I'd leave it open at least.

**Comment by YashasSamaga** [comment]
@drakorg Please see below:

> Subprocesses through fork() calls should be avoided in applications. It is not able to clone properly multi-threaded application.
> Details: #5150
> 
> Use native threads (but take a look on Python GIL)

**Comment by drakorg** [comment]
In order to use opencv one must commit to not use any function based on fork()? That's really the official response from opencv?

**Comment by alalek** [comment]
Read this why it doesn't work (and would not): http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

**Comment by drakorg** [comment]
@heuripedes Could you please show me what method/startmethod are you using to create the subprocess? Apparently there are alternatives for spawning child processes without necessarily using the fork() mechanism, like forkserver and spawn. I haven't tried any of that yet, though.

In my case, this is the exact line where I spawn the new process:

`self.ffmpeg = subprocess.Popen(cmd.split(' '), stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, bufsize=0)

From what I understand the startmethod is set globally, and then taken into account in every following invocation of Popen.

Since I don't explicitly specify any startmethod, the default for linux systems is fork. Maybe changing that would make a difference. I've no idea yet how changing the start method would affect the way the subprocess works and or I can communicate with it. Will have to try/dig a bit into that, but it'd be nice to know if you are also using the default startmethod, and if changing it to something like spawn or forkserver would solve your problem (and/or mine).

**Comment by drakorg** [comment]
@alalek I've read all the problems that fork() can cause in multithreaded applications, but I think you all rushed in blaming the call to fork() as the origin of the problem. fork() is only called as a mechanism to create a new process, with all the problems that are mentioned there, but there is one important detail: that it's followed by en exec(), so it's not that the forked process (exact copy of the parent or an attempt to be) is meant to keep running the parent process image, but it's meant to be replaced with a new image, in my case ffmpeg, in @heuripedes's case probably another external program. In both cases the fork() is immediately followed by an exec() so, we don't really care that the child process will not be able to run the parent threads, etc, it's only forked() to later be replaced with a new executable image. No harm in that. And the fact that the parent forked a child should not change or affect in any way the parent process that was forked. So, the use of fork() does not explain why the parent process is affected by that. I'd understand if the child process failed because, as @YashasSamaga said, its not able to clone properly multithreaded applications, but since the clone is of no interest to me (because it's going to be replaced with the other program im trying to execute), I don't see how that could affect the parent process which is the one still running the application and that has all the opencv stuff initialized.

Please correct me if I'm wrong.

**Comment by roflcoopter** [comment]
This is causing a lot of problems in one of my projects using Python.
My project runs an NVR which records detected objects by spawning subprocesses with ffmpeg commands.

If a subprocess is spawned at the same time as detection runs then the output boxes freezes and always return the same result.
To get around this i need to hold a lock when running detection and on every single subprocess.Popen or subprocess.run call.
This is adding extra overhead and limits my FPS.

So i am not trying to run OpenCV in a subprocess, but it somehow affects OpenCV in the main process anyway

**Comment by jlcd** [comment]
Also having the same issue.

If I enable CUDA support, such as
``` python
 net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
 net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
```

Then every frame after the first stays the same. But without activating CUDA support, I get all the frames normally.

I don't have any sub process running on my code (see below):

``` python
import cv2
import imutils
import numpy as np
import random
import colorsys

# inspiration and some code pieces were copied from https://github.com/haroonshakeel/yolo_get_preds/blob/master/my_utils.py

def get_random_bright_colors(size):
    for i in range(0,size-1):
        h,s,l = random.random(), 0.5 + random.random()/2.0, 0.4 + random.random()/5.0
        r,g,b = [int(256*i) for i in colorsys.hls_to_rgb(h,l,s)]
        yield (r,g,b)


def get_yolo_preds(net, video_url, confidence_threshold, overlapping_threshold, labels = None, frame_resize_width=None):

    # List of colors to represent each class label with distinct bright color
    colors = list(get_random_bright_colors(len(labels)))

    ln = net.getLayerNames()
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
    cap = cv2.VideoCapture(video_url)
    #cap = cv2.VideoCapture('video.mp4')

    try:
        if not cap.isOpened():
            print("Error opening video stream or file")
            return

        yolo_width_height = (416, 416)

        counter = 0
        max_count = 0

        while True:
            (_, frame) = cap.read()

            counter += 1 

            if frame_resize_width:
                frame = imutils.resize(frame, width=frame_resize_width)
            (H, W) = frame.shape[:2]

            # Construct blob of frames by standardization, resizing, and swapping Red and Blue channels (RBG to RGB)
            blob = cv2.dnn.blobFromImage(frame, 1 / 255.0, yolo_width_height, swapRB=True, crop=False)
            net.setInput(blob)
            layerOutputs = net.forward(ln)
            boxes = []
            confidences = []
            classIDs = []
            for output in layerOutputs:
                for detection in output:
                    scores = detection[5:]
                    classID = np.argmax(scores)
                    confidence = scores[classID]
                    if confidence > confidence_threshold:
                        # Scale the bboxes back to the original image size
                        box = detection[0:4] * np.array([W, H, W, H])
                        (centerX, centerY, width, height) = box.astype("int")
                        x = int(centerX - (width / 2))
                        y = int(centerY - (height / 2))
                        boxes.append([x, y, int(width), int(height)])
                        confidences.append(float(confidence))
                        classIDs.append(classID)

            # Remove overlapping bounding boxes
            bboxes = cv2.dnn.NMSBoxes(
                boxes, confidences, confidence_threshold, overlapping_threshold)
            if len(bboxes) > 0:
                for i in bboxes.flatten():
                    (x, y) = (boxes[i][0], boxes[i][1])
                    (w, h) = (boxes[i][2], boxes[i][3])
                    color = [int(c) for c in colors[classIDs[i]]]
                    cv2.rectangle(frame, (x, y), (x + w, y + h), color, 2)
                    text = "{}: {:.4f}".format(labels[classIDs[i]], confidences[i])
                    
                    # draw bounding box title background
                    text_offset_x = x
                    text_offset_y = y
                    text_color = (255, 255, 255)
                    (text_width, text_height) = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, fontScale=1.0, thickness=1)[0]
                    box_coords = ((text_offset_x, text_offset_y), (text_offset_x + text_width - 80, text_offset_y - text_height + 4))
                    cv2.rectangle(frame, box_coords[0], box_coords[1], color, cv2.FILLED)
                    
                    # draw bounding box title
                    cv2.putText(frame, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, text_color, 1)


            cv2.putText(frame, "Frame: "+str(counter), (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (255, 255, 255), 1)
            cv2.putText(frame, "Boxes: "+str(len(bboxes)), (10, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (255, 255, 255), 1)

            #if len(bboxes) > max_count:
            #    max_count = len(bboxes)
            #    cv2.imwrite('captured_' + str(counter) + '.jpg', frame) 
            cv2.imshow("YOLOv4 Object Detection", frame)
            key = cv2.waitKey(1) & 0xFF
            # if the `q` key was pressed, break the loop
            if key == ord("q"):
                break
    finally:
        cap.release()
        cv2.destroyAllWindows()


with open("model/coco.names","r", encoding="utf-8") as f:
    labels = f.read().strip().split("\n")

yolo_config_path = "model/yolov4.cfg"
yolo_weights_path = "model/yolov4.weights"

useCuda = True

net = cv2.dnn.readNetFromDarknet(yolo_config_path, yolo_weights_path)

if useCuda:
    net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
    net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

video_url = "https://cdn-004.whatsupcams.com/hls/hr_pula01.m3u8" # "http://localhost:1999"

frame_width = 1200

if __name__ == '__main__':
    get_yolo_preds(net, video_url, 0.8, 0.1, labels,frame_width)
```

**Comment by jlcd** [comment]
As per my comment above, I'm not sure the issue is related with the main topic here, as I just discovered that by naming the cv2 window, all the frames start to work as expected... I have no idea how this change impacted the main issue of only returning the first frame.

 All I did was adding
``` python
        windowName = "YOLOv4 Object Detection"
        cv2.namedWindow(windowName)        # Create a named window
```

Full script after this change (working):
``` python
import cv2
import imutils
import numpy as np
import random
import colorsys

# inspiration and some code pieces were copied from https://github.com/haroonshakeel/yolo_get_preds/blob/master/my_utils.py

def get_random_bright_colors(size):
    for i in range(0,size-1):
        h,s,l = random.random(), 0.5 + random.random()/2.0, 0.4 + random.random()/5.0
        r,g,b = [int(256*i) for i in colorsys.hls_to_rgb(h,l,s)]
        yield (r,g,b)


def get_yolo_preds(net, video_url, confidence_threshold, overlapping_threshold, labels = None, frame_resize_width=None):

    # List of colors to represent each class label with distinct bright color
    colors = list(get_random_bright_colors(len(labels)))

    ln = net.getLayerNames()
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
    cap = cv2.VideoCapture(video_url)
    # cap = cv2.VideoCapture('video.mp4')

    try:
        if not cap.isOpened():
            print("Error opening video stream or file")
            return

        yolo_width_height = (416, 416)

        counter = 0
        max_count = 0

        windowName = "YOLOv4 Object Detection"
        cv2.namedWindow(windowName)        # Create a named window
        # cv2.moveWindow(windowName, 40,30)  # Move it to (40,30)

        while True:
            (_, frame) = cap.read()

            counter += 1 

            if frame_resize_width:
                frame = imutils.resize(frame, width=frame_resize_width)
            (H, W) = frame.shape[:2]

            # Construct blob of frames by standardization, resizing, and swapping Red and Blue channels (RBG to RGB)
            blob = cv2.dnn.blobFromImage(frame, 1 / 255.0, yolo_width_height, swapRB=True, crop=False)
            net.setInput(blob)
            layerOutputs = net.forward(ln)
            boxes = []
            confidences = []
            classIDs = []
            for output in layerOutputs:
                for detection in output:
                    scores = detection[5:]
                    classID = np.argmax(scores)
                    confidence = scores[classID]
                    if confidence > confidence_threshold:
                        # Scale the bboxes back to the original image size
                        box = detection[0:4] * np.array([W, H, W, H])
                        (centerX, centerY, width, height) = box.astype("int")
                        x = int(centerX - (width / 2))
                        y = int(centerY - (height / 2))
                        boxes.append([x, y, int(width), int(height)])
                        confidences.append(float(confidence))
                        classIDs.append(classID)

            # Remove overlapping bounding boxes
            bboxes = cv2.dnn.NMSBoxes(
                boxes, confidences, confidence_threshold, overlapping_threshold)
            if len(bboxes) > 0:
                for i in bboxes.flatten():
                    (x, y) = (boxes[i][0], boxes[i][1])
                    (w, h) = (boxes[i][2], boxes[i][3])
                    color = [int(c) for c in colors[classIDs[i]]]
                    cv2.rectangle(frame, (x, y), (x + w, y + h), color, 2)
                    text = "{}: {:.4f}".format(labels[classIDs[i]], confidences[i])
                    
                    # draw bounding box title background
                    text_offset_x = x
                    text_offset_y = y
                    text_color = (255, 255, 255)
                    (text_width, text_height) = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, fontScale=1.0, thickness=1)[0]
                    box_coords = ((text_offset_x, text_offset_y), (text_offset_x + text_width - 80, text_offset_y - text_height + 4))
                    cv2.rectangle(frame, box_coords[0], box_coords[1], color, cv2.FILLED)
                    
                    # draw bounding box title
                    cv2.putText(frame, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, text_color, 1)


            cv2.putText(frame, "Frame: "+str(counter), (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (255, 255, 255), 1)
            cv2.putText(frame, "Boxes: "+str(len(bboxes)), (10, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (255, 255, 255), 1)

            #if len(bboxes) > max_count:
            #    max_count = len(bboxes)
            #    cv2.imwrite('captured_' + str(counter) + '.jpg', frame) 
            cv2.imshow(windowName, frame)
            key = cv2.waitKey(1) & 0xFF
            # if the `q` key was pressed, break the loop
            if key == ord("q"):
                break
    finally:
        cap.release()
        cv2.destroyAllWindows()


with open("model/coco.names","r", encoding="utf-8") as f:
    labels = f.read().strip().split("\n")

yolo_config_path = "model/yolov4.cfg"
yolo_weights_path = "model/yolov4.weights"

useCuda = True

net = cv2.dnn.readNetFromDarknet(yolo_config_path, yolo_weights_path)

if useCuda:
    net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
    net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

video_url = "https://cdn-004.whatsupcams.com/hls/hr_pula01.m3u8" # "http://localhost:1999"

frame_width = 1200

if __name__ == '__main__':
    get_yolo_preds(net, video_url, 0.6, 0.1, labels,frame_width)
```

But if I comment line 37 (`cv2.namedWindow(windowName)`), then the issue starts again.

*IF YOU ARE GOING TO TRY IT, TRY IT TWICE, AS SOMETIMES THE FIRST TIME WITHOUT LINE 37, IT STILL WORKS*

I'm aware this doesn't make any sense... but I'm posting here anyways as someone may find the relation between all this nonsense and either point me to what was the actual issue with my code or maybe find some distant connection with the main issue.

**Comment by teaglin** [comment]
Having this issue as well! This seems like a major bug!! Using any kind of python wrapper that calls out to FFMPEG breaks it. Using https://abhitronix.github.io/vidgear/v0.2.5-stable/ breaks it. Also using any kind of monitoring process breaks it like. https://pypi.org/project/gpuinfo/ Also had some issues with pymongo that were breaking it. To be safe any time I make database calls I have to reinit the DNN model.

**Comment by aromm** [comment]
Been having this issue as well (see #21707 for reproduction code) 😞 . I agree that this seems like a major bug. There are situations where applications require `fork()`, particularly python applications due to the GIL, and sadly the OpenCV dnn module cannot be reliably used.

For those experiencing this issue, in my testings not all OpenCV + CUDA code breaks, for example cv2.cuda.ORB still works in the main process after a subprocess has been forked. Also, PyTorch + CUDA doesn't break either, so even though it is slower and more memory intensive it can be used as a workaround.

**Comment by YashasSamaga** [comment]
Maybe we could detect forks and force reinitialization. This comes with a performance penalty but that's anyway required in the current scenario where the user needs to manually reinitialize.

**Comment by aromm** [comment]
Personally speaking, either option would be very very helpful!

**Comment by willieprinsloo** [comment]
Did anybody resolve this issue?

**Comment by drakorg** [comment]
To my knowledge no, and I find it hard to understand how there's so little
interest in making this work. I was forced to move from opencv's dnn module
to other implementations because of this.

**Comment by teaglin** [comment]
> Did anybody resolve this issue?

Unfortunately not. Had to roll a custom ffmpeg wrapper that didn't rely on fork.
