### ISSUE TITLE
DirectShow: VideoCapture returns blank frames for OBS Virtual Camera on Windows

### ISSUE THREAD

**Issue by letmaik** [opencv/opencv#19746]
##### System information (version)
- OpenCV => 4.5.1.48 (opencv-python)
- Operating System / Platform => Windows 10 64 Bit

##### Detailed description

[OBS](https://obsproject.com/) installs a DirectShow virtual camera which works fine in Zoom etc. but not in OpenCV via VideoCapture, all frames are either zeros or a bit of garbage at the top of the frame. I also checked it against the [CommandCam](https://github.com/mrihtar/CommandCam) tool which is a simple C++ frame grabber written in a single straight-forward file. No problems there as well. This is what `commandcam.exe /details` shows:

```
  2. OBS Virtual Camera
     Pin: Video Output, 6 caps
       Cap  0: FORMAT_VideoInfo, NV12, 12 bits, 1920x1080 @ 30 fps
       Cap  1: FORMAT_VideoInfo, I420, 12 bits, 1920x1080 @ 30 fps
       Cap  2: FORMAT_VideoInfo, YUY2, 16 bits, 1920x1080 @ 30 fps
       Cap  3: FORMAT_VideoInfo, NV12, 12 bits, 1280x720 @ 20 fps
       Cap  4: FORMAT_VideoInfo, I420, 12 bits, 1280x720 @ 20 fps
       Cap  5: FORMAT_VideoInfo, YUY2, 16 bits, 1280x720 @ 20 fps
```

I tried all pixel formats and resolutions (with the tool) and it worked for all combinations.

##### Steps to reproduce

First, install OBS. The virtual camera always streams a dummy picture.
Then, grab a frame with OpenCV.

```py
def decode_fourcc(fourcc):
    return chr((fourcc & 0xff)) + chr((fourcc & 0xff00) >> 8) + chr((fourcc & 0xff0000) >> 16) + chr((fourcc & 0xff000000) >> 24)

vc = cv2.VideoCapture(2, cv2.CAP_DSHOW)
assert vc.isOpened()

fourcc = decode_fourcc(int(vc.get(cv2.CAP_PROP_FOURCC)))
print(f'fourcc: {fourcc}') # fourcc: }ë6ä  --> with my real webcam this is YUY2

for _ in range(1000):
    ret, frame_captured = vc.read()
    assert ret
    print(frame_captured.min(), frame_captured.max())
    # 0 0
```

I should also mention that I set the environment variable `OPENCV_DSHOW_SAVEGRAPH_FILENAME=graph.grf` and [GraphEdit](https://docs.microsoft.com/en-us/windows/win32/directshow/using-graphedit) cannot open the file. It can open the file when I capture something from my real webcam device however. So somehow the filter graph must be broken.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by DavraYoung** [comment]
still an issue.

Can any one suggest a temporary solution for this?

**Comment by Avasam** [comment]
> still an issue.
> 
> Can any one suggest a temporary solution for this?

@DavraYoung Use the VirtualCam plugin https://obsproject.com/forum/resources/obs-virtualcam.949/

**Comment by DavraYoung** [comment]
@Avasam thank you for your suggestion. 
I tried it, and it worked!

However, setting higher fps values in settings crashes OBS studio.

How can I get 100FPS virtual camera screen capture?

**Comment by DavraYoung** [comment]
@Avasam thank you for you suggestion, I was able to get a picture in opencv using this plugin. The crash issues that I had was not related to the plugin, but rather to Capture method in Display capture Source.

This method worked with higher than 60 fps values, with good enough hardware I was able to get stable 120 FPS on Ryzen 7 5800x and RTX3080ti

**Comment by RobotRoss** [comment]
+1 to this issue, ran into this the other day and spent the better part of my day (unsuccessfully) debugging the issue.

**Comment by Avasam** [comment]
With OBS 28, my suggestion/workaround is no longer valid, as that plugin won't be updated.
It's now completely impossible to use OpenCV with the OBS Virtual Camera.

**Comment by ManuGraiph** [comment]
> With OBS 28, my suggestion/workaround is no longer valid, as that plugin won't be updated. It's now completely impossible to use OpenCV with the OBS Virtual Camera.
> 
> Btw here's the error if you turn them on:
> 
> ```
> cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp:365: error: (-2:Unspecified error) could not retrieve channel 0 in function 'cv::VideoCapture::retrieve'
> ```
> 
> Edit: workaround is back, I've updated the plugin: https://github.com/Avasam/obs-virtual-cam/releases

It's the same for me, opencv keeps showing me nothing (well, instead of an array with 0, now it's an array with 128)

**Comment by ElliMary** [comment]
Without the plugin I get a black screen and warnings, with the plugin I get a gray screen, but not the expected images from the OBS virtual camera. Is there another workaround?

**Comment by jasperan** [comment]
> Without the plugin I get a black screen and warnings, with the plugin I get a gray screen, but not the expected images from the OBS virtual camera. Is there another workaround?

Literally the same, grey screen after the plugin is installed

**Comment by Avasam** [comment]
This is getting worse. With OBS 29 now OpenCV causes Windows to just kill my application. No error, no trace, just this in the Event Viewer:
```
Faulting application name: python.exe, version: 3.9.13150.1013, time stamp: 0x6283d009
Faulting module name: obs-virtualcam-module64.dll, version: 29.0.0.0, time stamp: 0x63b8a352
Exception code: 0xc0000005
Fault offset: 0x0000000000009cd6
Faulting process ID: 0x774
Faulting application start time: 0x01d9287829757f23
Faulting application path: C:\Program Files\Python39\python.exe
Faulting module path: C:\Program Files\obs-studio\data\obs-plugins\win-dshow\obs-virtualcam-module64.dll
Report ID: 40c957e7-69e9-48a1-b1ea-d07e3858f6d2
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by alalek** [comment]
> Faulting module name: obs-virtualcam-module64.dll, version: 29.0.0.0, time stamp: 0x63b8a352

This is not a part of OpenCV actually:

> obs-virtualcam-module64.dll

@Avasam Perhaps you should report this crash problem somewhere here: https://github.com/obsproject/obs-studio/issues/3635 (e.g, old OBS 27.2.4 ~~doesn't crash (and doesn't work as expected)~~ crashed with extra parameters, see below)

---

> `priority: low`

Just to clarify, OBS built-in virtual camera uses DirectShow API for virtual camera (CAP_DSHOW), which is deprecated in OpenCV in favor of Microsoft Media Foundation (CAP_MSMF) backend (about 4+ years ago, before OpenCV 4.0).
So, due to deprecation there are no plans to significantly rework DSHOW backend.
Also, due to deprecation "acceptable fix" is a 2-5 lines disabler of this unsupported case (but this can't satisfy OBS users) to avoid breaking of existed code.

---

Perhaps, problem is that `SetFormat()` doesn't fail on this line (`hr=0` / S_OK) during request of `RGB24` format:
https://github.com/opencv/opencv/blame/4.7.0/modules/videoio/src/cap_dshow.cpp#L2618

After that in debug mode these errors are reported: `ERROR: SampleCB() - buffer sizes do not match` (this is a case if format is not changed properly)

---

Forcing ["native"](https://github.com/obsproject/obs-studio/blob/27.2.4/plugins/win-dshow/virtualcam-module/virtualcam-filter.hpp#L12-L13) resolution of OBS camera crashes the process (by default OpenCV DSHOW backend requests 640x480):

```
    capture.set(CAP_PROP_FRAME_WIDTH, 1920);
    capture.set(CAP_PROP_FRAME_HEIGHT, 1080);
```

WinDbgX shows this stacktrace of the crash (from non-main thread):

```
[0x0]   obs_virtualcam_module64!memcpy_repmovs + 0xe   
[0x1]   obs_virtualcam_module64!VCamFilter::Frame + 0x1b5   
[0x2]   obs_virtualcam_module64!VCamFilter::Thread + 0x24b   
[0x3]   obs_virtualcam_module64!std::thread::_Invoke<std::tuple<<lambda_4e6f779957cbddf8fba6c1db701dac17> >,0> + 0x11   
[0x4]   obs_virtualcam_module64!thread_start<unsigned int (__cdecl*)(void *),1> + 0x5a   
[0x5]   KERNEL32!BaseThreadInitThunk + 0x14   
[0x6]   ntdll!RtlUserThreadStart + 0x21   
```

with `r8d` "size" register value: `0x00000000007e9000` (or 8294400).

RGB24 frame size is 1920*1080*3 = 6220800  (this is requested)
RGB32 frame buffer size is 1920*1080*4 = 8294400 (this value we see during the crash)

So, looks like format is not switched to RGB24 properly.

---

I would blame on this OBS code with `IAMStreamConfig::SetFormat` method implementation which ignores passed input and returns S_OK **unconditionally**:

https://github.com/obsproject/libdshowcapture/blob/2fa2e488b7dc4a266eb8f5be56ced626e39a6159/source/output-filter.cpp#L346-L363

`IAMStreamConfig::SetFormat` documentation and expected behavior: https://learn.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-iamstreamconfig-setformat

**Comment by Avasam** [comment]
@alalek You're right, the crash I recently mentioned seems to be caused by changing resolutions, a nd not necessarily the new OBS version.
Thanks for your analysis.

**Comment by Avasam** [comment]
Sorry to bother, how can I test this patch in Python? I'd like to make sure it actually fixes my issue.

**Comment by GadgetNutt** [comment]
Still an issue with current OBS and OpenCVSharp
