### ISSUE TITLE
module 'cv2.cv2' has no attribute 'sfm'

### ISSUE THREAD

**Issue by iAmJuan550** [opencv/opencv#19853]
##### System information (version)
- OpenCV => 4.5.1
- Operating System / Platform => Ubuntu 20.04
- Compiler => Pycharm

##### Detailed description

Unable to use sfm with opencv-python.

```
import cv2
help(cv2.sfm)
```
error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2.cv2' has no attribute 'sfm'
```
##### Steps to reproduce
```
import cv2
help(cv2.sfm)
```
##### Issue submission checklist

 - [X] I report the issue, it's not a question
 - [X] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
 - [X] I updated to latest OpenCV version and the issue is still there

**Comment by iAmJuan550** [comment]
@alalek why is this an invalid question?

**Comment by dkurt** [comment]
@iAmJuan550, please try to run the same script from the console. Seems like problem is PyCharm related.

**Comment by gasparitiago** [comment]
@iAmJuan550 

Have you installed all the dependencies?
https://docs.opencv.org/master/db/db8/tutorial_sfm_installation.html

**Comment by alalek** [comment]
> Unable to use sfm with opencv-python.

SFM is module from "opencv_contrib".

Problem is related to `opencv-python` vs `opencv-contrib-python` wrong selection.

Item 3 "Select the correct package for your environment" from the [package's description](https://pypi.org/project/opencv-python/) should be read carefully first.

---

Anyway there is no SFM in `opencv-contrib-python` (at least `4.5.1.48`) due to specific extra 3rdparty dependencies.

Right issue tracker for asking enabling features in these packages is here (link from package's description, BTW): https://github.com/opencv/opencv-python (and there is already such opened issue, no need to open duplicates)

---

At this moment you need to build OpenCV Python bindings yourself with pre-installed all necessary 3rdparty dependencies.
You may want to check these resources:
- https://docs.opencv.org/4.5.2/d2/de6/tutorial_py_setup_in_ubuntu.html
- [CI logs](http://pullrequest.opencv.org/buildbot/builders/master-contrib-lin64) + example of packages in [CI configuration](https://github.com/opencv-infrastructure/opencv-worker-config/blob/linux/images/ubuntu--20.04/docker/Dockerfile) + you need to install Ceres dev package too

---

There is nothing to fix in OpenCV source code. Closing.
