### ISSUE TITLE
grfmt_exr.cpp:652:40: error: ‘DWAA_COMPRESSION’ was not declared in this scope

### ISSUE THREAD

**Issue by Misoknisky** [opencv/opencv#19925]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
More details are required:
- CMake stdout (from clean build)
- files from build folder: CMakeCache.txt and CMakeVars.txt (as attachment or use "grep" for related problem keyword - EXR)
- failed command line via `make VERBOSE=1` (without any `-j` option)

**Comment by SangerY** [comment]
I met the same problem.
My opencv version is 4.5.2，contrib 4.5.2，centos7, cmake version 3.14.3
My command:
cmake -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.5.2/modules -D OPENCV_GENERATE_PKGCONFIG=ON -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..

There is no problem in stage cmake.
Then I do : make -j4
I met 
opencv-4.5.2/modules/imgcodecs/src/grfmt_exr.cpp:652:40: error: ‘DWAA_COMPRESSION’ was not declared in this scope
                 header.compression() = DWAA_COMPRESSION;

![image](https://user-images.githubusercontent.com/12136347/115360727-7c082c00-a1f2-11eb-8b97-5deda60227da.png)

**Comment by alalek** [comment]
Used OpenEXR version is still required. This information is available on CMake stdout.

**Comment by xkszltl** [comment]
Hit this issue recently as well.
It is only found on CentOS 7, but not on Ubuntu 18.04.
OpenEXR on CentOS is v1.7.1-8.

**Comment by xkszltl** [comment]
Given there's also an openexr in 3rdparty dir, I wonder if the build system is broken and listing the wrong header (from /usr/include) for use.

**Comment by xkszltl** [comment]
CC @asmorkalov in the original PR: https://github.com/opencv/opencv/pull/19540
Will try reverting to 4.5.1.

**Comment by asmorkalov** [comment]
OpenEXR project introduced compression option in release v2.2.0. It looks like we need to guard the option with version check. `OpenEXRConfig.h` contains `OPENEXR_VERSION_MAJOR` and `OPENEXR_VERSION_MINOR` suitable for it. I file a patch in meantime.

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/pull/19998

**Comment by asmorkalov** [comment]
The corresponding fix has been merged.

**Comment by liushuanpeng** [comment]
[-Wundef]
 #if ((OPENEXR_VERSION_MAJOR * 1000 + OPENEXR_VERSION_MINOR) >= (2 * 1000 + 2)) // available since version 2.2.0
       ^
/home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/imgcodecs/src/grfmt_exr.cpp:682:38: 警告：“OPENEXR_VERSION_MINOR”未定义 [-Wundef]
 #if ((OPENEXR_VERSION_MAJOR * 1000 + OPENEXR_VERSION_MINOR) >= (2 * 1000 + 2)) // available since version 2.2.0
                                      ^
/home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/imgcodecs/src/grfmt_exr.cpp:696:5: 警告：“OPENEXR_VERSION_MAJOR”未定义 [-Wundef]
 #if OPENEXR_VERSION_MAJOR >= 3
     ^
In file included from /home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/imgcodecs/src/grfmt_exr.cpp:48:0:
/home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/imgcodecs/src/grfmt_exr.cpp: 在成员函数‘virtual bool cv::ExrEncoder::write(const cv::Mat&, const std::vector<int>&)’中:
/home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/imgcodecs/src/grfmt_exr.cpp:699:136: 错误：‘OPENEXR_VERSION_MAJOR’在此作用域中尚未声明
             CV_LOG_ONCE_WARNING(NULL, "Setting `IMWRITE_EXR_DWA_COMPRESSION_LEVEL` not supported in OpenEXR version " + std::to_string(OPENEXR_VERSION_MAJOR) + " (version 3 is required)");
                                                                                                                                        ^
/home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/core/include/opencv2/core/utils/logger.hpp:118:30: 附注：in definition of macro ‘CV_LOG_WITH_TAG’
         cv_temp_logstream << __VA_ARGS__; \
                              ^
/home/liushuanpeng/workspace/opencv470/opencv-4.7.0/modules/imgcodecs/src/grfmt_exr.cpp:699:13: 附注：in expansion of macro ‘CV_LOG_ONCE_WARNING’
             CV_LOG_ONCE_WARNING(NULL, "Setting `IMWRITE_EXR_DWA_COMPRESSION_LEVEL` not supported in OpenEXR version " + std::to_string(OPENEXR_VERSION_MAJOR) + " (version 3 is required)");
             ^
在全局域：
cc1plus: 警告：无法识别的命令行选项“-Wno-unnamed-type-template-args”
make[2]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_exr.cpp.o] 错误 1
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] 错误 2
make: *** [all] 错误 2
[liushuanpeng@nbadev.bj.sm build]$ ll opencvlib/^C
[liushuanpeng@nbadev.bj.sm build]$ cmake3 -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.7.0/modules ..^C
[liushuanpeng@nbadev.bj.sm build]$ cd ../.cache/
ade/           data/          ippicv/        wechat_qrcode/ xfeatures2d/

**Comment by liushuanpeng** [comment]
编译遇到了上述错误，有遇到过相同的大神吗

**Comment by evangoe** [comment]
> 编译遇到了上述错误，有遇到过相同的大神吗

use this cmd:
cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_OPENEXR=0 -D CMAKE_INSTALL_PREFIX=/usr/local/opencv -D BUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF ..


CMAKE_INSTALL_PREFIX=/usr/local/opencv is your dir~~

CHINA NO.1！！！！

**Comment by xkszltl** [comment]
Those guards like `OPENEXR_VERSION_MAJOR` does not exist in openexr 1.7, so depending on them without checking for their existence first actually causes a regression.
