### ISSUE TITLE
opencv3.4.10，the same issue：gaussianfilter memory leak

### ISSUE THREAD

**Issue by HOWARD201314** [opencv/opencv#19974]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by HOWARD201314** [comment]
detail like this: https://github.com/opencv/opencv/issues/11449, but I test opencv3.4.10 version

**Comment by rogday** [comment]
Could you provide your cmake build flags and the output of `getBuildInformation()`?

**Comment by alalek** [comment]
IPP implementation of GaussianBlur is disabled by default (see #15197, applied on 3.4.8+, so it can't leak on 3.4.10).

PR #17092 allows to enable IPP optimizations of GaussianBlur through CMake option `OPENCV_IPP_GAUSSIAN_BLUR=ON` (OpenCV 3.4.11+). But there is no leak with provided IPPICV package (fixed by #11541 for OpenCV 3.4.2+).
