### ISSUE TITLE
videoio: build issues with upcoming FFmpeg 5.0

### ISSUE THREAD

**Issue by crackwitz** [opencv/opencv#20147]
related:
https://forum.opencv.org/t/error-avstream-aka-struct-avstream-has-no-member-named-codec/3506

ffmpeg changed its `AVStream` structure. in ffmpeg v3.1 (~2016) the `codecpar` member was introduced to replace `codec` member. `codec` has been deprecated since then. it is still available in ffmpeg v4.4 but not in the master branch.

availability is modulated by `#define FF_API_LAVF_AVCTX (LIBAVFORMAT_VERSION_MAJOR < 59)`

this version was bumped to 59 a month ago in https://github.com/FFmpeg/FFmpeg/commit/85ba17f36dbfde1baeaa47e14d30c337add52c0d

OpenCV v4.5.2/master still assumes the existence of the `codec` member:
https://github.com/opencv/opencv/blob/ae4cc404c15a206e7bc953e183e9a6812df6d5b0/modules/videoio/src/cap_ffmpeg_impl.hpp#L606

I've checked issues and pull requests for mentions of `codecpar` and it seems this hasn't been reported yet.

**Comment by makingglitches** [comment]
filename it would appear as well.

so to get this working we have to downgrade ffmpeg to 3.1 ?

**Comment by crackwitz** [comment]
no, only 4.4, which was the latest release when I opened this issue.

**Comment by makingglitches** [comment]
4.4 was what i was using when i got the error.
also ever get an empty python module after a successful build ?

**Comment by crackwitz** [comment]
use the forum or a new issue, present all information, including complete log output. _this_ is not the place.

**Comment by makingglitches** [comment]
so like.. the second issue is something else which is not valid, sorry.  but as to the forum, i am interested in seeking some clarification, where is it on the main page ?

**Comment by lifegpc** [comment]
I got same problem when I try to use my own build of ffmpeg.
![image](https://user-images.githubusercontent.com/41434272/124883852-52e28500-e004-11eb-8349-85569a6e93c9.png)

**Comment by makingglitches** [comment]
You have to downgrade to 3.1

> I got same problem when I try to use my own build of ffmpeg.
> 
> ![image](https://user-images.githubusercontent.com/41434272/124883852-52e28500-e004-11eb-8349-85569a6e93c9.png)
> 
>

**Comment by crackwitz** [comment]
@makingglitches do you have evidence that ffmpeg 4.4 does *not* work? it should. ffmpeg master branch shouldn't.

**Comment by ebachard** [comment]
Hello,

The ffempeg API was heavily modified in ffmpeg 4.4 (new API, the old one was simply removed). Means OpenCV can build perfectly even if you are building with ffmpeg 4.3.x, but 4.4 will break.

On my side, I fixed all the warnings (tested on Linux only) and the build is possible with the 4.4 version. 

BUT I'm sorry : this is not the solution. Indeed, OpenCV builds but got:

- some crashes in runtime, caused by broken ffmpeg API (the code shoud work, but ... ffmpeg maybe has issues with missing implementations)
- the nice thing is cap_ffmpeg_impl.hpp is the right and the only place for changes
- cap_ffmpeg_impl.hpp contains a forest of #ifdef ... and so on, and this is not clean for 4.x version of OpenCV
 
IMHO, the right way to fix all of that is to rewrite cap_ffmpeg_impl.hpp completely. That's what I'm doing, but this will need some times. If ever I can find more time, I'll attach some little changes to this issue.

Last but not least : IMHO, ffmpeg 4.4. has still some issues (API is IMHO not that stable yet).

For your information, the 4.3. version works perfectly (cross compiled Windows version builds ok too): 

````
~ $ ffmpeg -version
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --enable-shared --enable-pic --enable-opengl --enable-libpulse --enable-libopus --enable-openal --enable-libmodplug --enable-libgme --enable-libvpx --enable-libv4l2 --enable-libopenjpeg --enable-openssl --enable-vaapi --enable-libdav1d --enable-vulkan --enable-libx264 --enable-libx265 --enable-gpl --enable-nonfree --enable-libvidstab --enable-libxvid --enable-libxml2 --enable-postproc --enable-libcaca --enable-libopenh264 --enable-vulkan --enable-nonfree --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-thumb
libavutil      56. 51.100 / 56. 72.100
libavcodec     58. 91.100 / 58.135.100
libavformat    58. 45.100 / 58. 78.100
libavdevice    58. 10.100 / 58. 14.100
libavfilter     7. 85.100 /  7.111.100
libswscale      5.  7.100 /  5. 10.100
libswresample   3.  7.100 /  3. 10.100
libpostproc    55.  7.100 / 55. 10.100

````

My 2 cents

**Comment by makingglitches** [comment]
> ffmpeg master branch shouldn't work. ffmpeg v4.4 **should** work.
> 
> @makingglitches do you have evidence that ffmpeg 4.4 does _not_ work? it should because the code still contains all the plumbing. you probably forgot some defines, or set them wrong. please visit the opencv forum thread I linked in the very first post. someone else claims that 4.4 works, so that contradicts your statement.
> 
> it is definitely **not** a good idea to downgrade all the way to ffmpeg 3.1. firstly, that is **not** needed. secondly, that is very old code.

yes that's a build against a successful build of the 4.4 release, failing because of it.
I downgraded to 3.1 and it built right away.

**Comment by rgaufman** [comment]
Any update on this one?

**Comment by barracuda156** [comment]
`gegl` build fails now with this error too: `error: 'AVStream' has no member named 'codec'`.

**Comment by Xueqc** [comment]
try change #if LIBAVFORMAT_BUILD >= CALC_FFMPEG_VERSION(59, 16, 100) in cap_ffmpeg_impl.hpp
