### ISSUE TITLE
ibopencv_cudaarithm.so.4.5: undefined symbol: _ZN2cv3MatC1Ev

### ISSUE THREAD

**Issue by the-cat-crying** [opencv/opencv#20436]
File "/home/gy/mount_sdc/work_zp/darknet_train/20210713-yolov4/darknet-ab-20210713/darknet_video.py", line 4, in <module>
    import cv2
  File "/home/gy/Applications/anaconda3/envs/opencv/lib/python3.8/site-packages/cv2/__init__.py", line 129, in <module>
    bootstrap()
  File "/home/gy/Applications/anaconda3/envs/opencv/lib/python3.8/site-packages/cv2/__init__.py", line 112, in bootstrap
    import cv2
ImportError: /usr/local/opencv-4.5.3/lib/libopencv_cudaarithm.so.4.5: undefined symbol: _ZN2cv3MatC1Ev

**Comment by alalek** [comment]
1. At first, reproducer should be minimal - drop `darknet_video.py` and just try `import cv2`
2. Ensure that you don't have installed multiple OpenCV versions
3. Ensure that you have properly built and install OpenCV binaries.
4. Use `LD_DEBUG=libs` or `LD_DEBUG=libs,syms` to investigate problem.

---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

Usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

**Comment by the-cat-crying** [comment]
Allocate additional workspace_size = 52.43 MB 
Loading weights from yolov4.weights...Done! Loaded 162 layers from weights-file 
Loaded - names_list: ./data/coco.names, classes = 80 
[ERROR:0] global /home/gy/Applications/opencv/opencv-4.5.3/modules/videoio/src/cap.cpp (587) open VIDEOIO(GSTREAMER): raised OpenCV exception:

OpenCV(4.5.3) /home/gy/Applications/opencv/opencv-4.5.3/modules/videoio/src/cap_gstreamer.cpp:1590: error: (-215:Assertion failed) !filename.empty() in function 'open'


[ERROR:0] global /home/gy/Applications/opencv/opencv-4.5.3/modules/videoio/src/cap.cpp (587) open VIDEOIO(CV_IMAGES): raised OpenCV exception:
