### ISSUE TITLE
Cannot read one image by calling cv::imread with static libraries of opencv 4.5.2 and VS 2015 on Windows 64bit

### ISSUE THREAD

**Issue by yzy888** [opencv/opencv#20629]
### System information (version)

- OpenCV => 4.5.2
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2015
  
### Detailed description
I have got static libraries including opencv_core452.lib, opencv_highgui452.lib, opencv_imgcodecs452.lib, opencv_imgproc452.lib, opencv_ml452.lib after building the code of opencv 4.5.2 with cmake and VS 2015. Then I built a C++ Win32 Console Application project to test reading one image with VS2015 and changed the configuration to Release x64. I changed the "Include Directories", "Library Directories" and "Additional Dependencies" of the project and I made the project depend on the static libraries including opencv_core452.lib, opencv_highgui452.lib, opencv_imgcodecs452.lib, opencv_imgproc452.lib, opencv_ml452.lib. I could compile the project successfully but when the project was running, I watched the variable named "matData" after the "cv::imread" method was executed, I found that the data of "matData" was NULL.

However, after I replaced the libs with opencv_core345.lib, opencv_highgui345.lib, opencv_imgcodecs345.lib, opencv_imgproc345.lib, opencv_ml345.lib and changed the "Additional Dependencies" of the project and replaced the include files with the include files of opencv 3.4.5 and I continued to use the same main code in the same project,  I found that the data of the variable named "matData" was not NULL when the project was running. 

The unique difference was that the libs used in the former were static while the libs used in the latter were not static. and I want to know how could I read the image successfully with the static libs of opencv 4.5.2.

### Steps to reproduce
My main code is as follows:

	#include "stdafx.h"
	#include <iostream>
	#include <opencv2\core.hpp>
	#include <opencv2\highgui.hpp>
	int main()
	{
		std::cout << "test:" << std::endl;
		cv::Mat matData = cv::imread("E:\\1.jpg");
		std::getchar();
		return 0;
	}

**Comment by alalek** [comment]
Can't reproduce. Tests for [static builds (Win64 MSVS 2015)](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14-static) works well.

Try to compare used build options with provided logs.

> I have got static libraries including opencv_core452.lib, opencv_highgui452.lib, opencv_imgcodecs452.lib, opencv_imgproc452.lib, opencv_ml452.lib

This list in not complete for **static builds**. There are several libraries of 3rdparty codecs are missing. At least you lost somewhere `build\3rdparty\lib\Release\libjpeg-turbo.lib`.

---

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by yzy888** [comment]
Thank you. I have solved the problem. It was because that I included a wrong file named "opencv_imgcodecs452.lib" and I did not included several libraries of 3rdparty codecs. @alalek
