### ISSUE TITLE
Unsupported asymmetric padding in convolution layer in function 'cv::dnn::BaseConvolutionLayerImpl::BaseConvolutionLayerImpl'

### ISSUE THREAD

**Issue by FrancescoMandru** [opencv/opencv#20964]
When do you plan to provide support for asymmetric padding in OpenCV? I would like to load my tensorflow model converted in ONNX format.

**Comment by enricomrk** [comment]
Hi there, I'm having the same kind of issue I think.
OpenCV 4.5.3.
I've a model in tensorflow .pb format which runs fine with OpenCV dnn module (I can get inferences).
I've converted the same working model into ONNX using tf2onnx and then I try to load it usin readNetFromONNX().

Here the error:
`OpenCV(4.5.3) /opencv/opencv-4.5.3/modules/dnn/src/onnx/onnx_importer.cpp:2146: error: (-2:Unspecified error) in function 'handleNode'
> Node [Conv]:(conv1_bn/FusedBatchNorm:0) parse error: OpenCV(4.5.3) /opencv/opencv-4.5.3/modules/dnn/src/layers/convolution_layer.cpp:96: error: (-213:The function/feature is not implemented) Unsupported asymmetric padding in convolution layer in function 'BaseConvolutionLayerImpl'`

The point is that OpenCV dnn module can actually infer using this model, therefore there is something not ok with the onnx parsing.

More than happy to help if you give me some pointer...

**Comment by alalek** [comment]
@enricomrk Try to upgrade. 4.5.3 is old release.

You need this commit: https://github.com/opencv/opencv/commit/b42152ffebde546964fa4fde40242678ccd16173

---

> The point is that OpenCV dnn module can actually infer using this model, therefore there is something not ok with the onnx parsing.

This doesn't mean that TF and ONNX format must have exactly the same set of layers for mentioned model.

---

Original issue is considered as invalid because author removed the issue's template and didn't provide required information.
Closing.
