### ISSUE TITLE
is offset required here for accessing output buffer?

### ISSUE THREAD

**Issue by anonymouss** [opencv/opencv#21021]
https://github.com/opencv/opencv/blob/17234f82d025e3bbfbf611089637e5aa2038e7b8/modules/videoio/src/cap_android_mediandk.cpp#L95

```cpp
uint8_t* codecBuffer = AMediaCodec_getOutputBuffer(mediaCodec.get(), bufferIndex, &bufferSize);
buffer = std::vector<uint8_t>(codecBuffer + info.offset, codecBuffer + bufferSize);
```

Per Android NDK code, `AMediaCodec_getOutputBuffer()` already returns underlying raw buffer contains offset
https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/NdkMediaCodec.cpp#575
```cpp
EXPORT
uint8_t* AMediaCodec_getOutputBuffer(AMediaCodec *mData, size_t idx, size_t *out_size) {
    if (mData->mAsyncNotify != NULL) {
        // Asynchronous mode
        sp<MediaCodecBuffer> abuf;
        if (mData->mCodec->getOutputBuffer(idx, &abuf) != 0) {
            return NULL;
        }

        if (out_size != NULL) {
            *out_size = abuf->capacity();
        }
        return abuf->data();
    }
...
```
https://android.googlesource.com/platform/frameworks/av/+/913efd2bb99a056eb44395a93c6aa361a96dde6a/include/media/stagefright/foundation/ABuffer.h#39
```cpp
    uint8_t *base() { return (uint8_t *)mData; }
    uint8_t *data() { return (uint8_t *)mData + mRangeOffset; }
    size_t capacity() const { return mCapacity; }
    size_t size() const { return mRangeLength; }
    size_t offset() const { return mRangeOffset; }
```

Which means `codecBuffer` already have `info.offset`. Hence, is `codecBuffer + info.offset` still required?

BTW: `info.offset` is from `MediaCodecBuffer/ABuffer` `.offset()` too.
https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/NdkMediaCodec.cpp#627
https://android.googlesource.com/platform/frameworks/av/+/3fdb405/media/libstagefright/MediaCodec.cpp#405

**Comment by alalek** [comment]
relates #14005
/cc @komakai

**Comment by komakai** [comment]
@anonymouss - thanks for raising this.
If I have understood your explanation, the call to `AMediaCodec_getOutputBuffer` already adjusts for the buffer `offset` in the NDK code so adjusting again for the `offset` in the OpenCV code is a bug. Correct?
(And so far the only reason this bug has had no ill effect is because with the current NDK implementation `offset` is always 0).

Your analysis sounds reasonable and I have checked other sample/test sources that call `AMediaCodec_getOutputBuffer` and they also do not adjust for `offset`. If you could put together a PR for this issue it would be much appreciated.
