### ISSUE TITLE
G-API: Sporadic failures of DivCPerfTestFluid/DivCPerfTest (2022-02-03)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#21584]
All x86 platforms, Linux/Windows/OSX, 32/64-bit.

Nightly builds:
- http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV-lin32/builds/1708
- http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/11794
- http://pullrequest.opencv.org/buildbot/builders/master-mac/builds/11794
- etc 1-3 failed [nightly builds](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-4.x&width=7) per day

Precommits:
- http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/35426
- http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/31845
- http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/32334
- etc

Message:

```
Tolerance_FloatRel_IntAbs error: err=32768  tolerance=1  depth=CV_16SC1
```

---

Probably related to this PR: https://github.com/opencv/opencv/pull/21474#issuecomment-1028943352

/cc @anna-khakimova @dmatveev

**Comment by anna-khakimova** [comment]
@alalek 
@dmatveev 
This behavior is observed because of OpenCV's issue for CV_16SC1 destination type. The expected behavior (IEEE standard) is that if there are zeros in the denominator, the results of division by zero are replaced by zero values. But OpenCV, contrary to the standard, does not replace the results of division by zero with zero values in the case when Destination type is 16S. 
This issue have already been raised by me 3 month ago for OpenCV team. However, the issue is still not fixed.
So, I faced to add workaround to GAPI tests.

**Comment by alalek** [comment]
Mentioned issue about OpenCV implementation is here: #21044

Main problem here is a **sporadic** failures.
- We should not have sporadic behavior in tests at all. Tests must be 100% reproducible.
- No idea that performance is measured by sporadic tests.

**Comment by anna-khakimova** [comment]
> Mentioned issue about OpenCV implementation is here: #21044
> 
> Main problem here is a **sporadic** failures.
> 
> * We should not have sporadic behavior in tests at all. Tests must be 100% reproducible.
> * No idea that performance is measured by sporadic tests.

The sporadic failures are observed because scalar values is initialized by random. In case when scalar is initialized by one or more zero values and they (zero values) become denominator value and this failures are reproduce.

**Comment by anna-khakimova** [comment]
Workaround delivered in the PR "**GAPI Perf Tests:Workaround for the OpenCV's issue.**" #21626
