### ISSUE TITLE
opencv 4.5.5 32 bits build fails

### ISSUE THREAD

**Issue by Mingli-Yu** [opencv/opencv#21597]
./opencv-4.5.5/git/modules/gapi/src/backends/fluid/gfluidcore_simd_sse41.hpp:387:47: error: '_mm_insert_epi64' was not declared in this scope; did you mean '_mm_insert_epi8'?
  387 |                     val_0 = _mm_unpacklo_epi8(_mm_insert_epi64(val_0, *reinterpret_cast<const int64_t*>(&tmp[4 * (chanNum * mapsx[x + 1] + 1)]), 0), zero);
      |                                               ^~~~~~~~~~~~~~~~
      |                                               _mm_insert_epi8

**Comment by alalek** [comment]
@Mingli-Yu As workaround you could use lower CPU_BASELINE option, e.g. SSSE3 (ensure that you don't have `-march=native`)

**Comment by Yamakuzure** [comment]
In `/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/include/smmintrin.h` there is:

```
    429 #ifdef __x86_64__
    430 #define _mm_insert_epi64(D, S, N)                                       \
    431   ((__m128i) __builtin_ia32_vec_set_v2di ((__v2di)(__m128i)(D),         \
    432                                           (long long)(S), (int)(N)))
    433 #endif
```

The error happens on 32bit builds, because `modules/gapi/src/backends/fluid/gfluidcore_simd_sse41.hpp` checks against `__i386__` only at one point (line 238), and at the other parts where `_mm_insert_epi64()` is used, it is done so without any checks.

A user at [bugs.gentoo.org](https://bugs.gentoo.org/830185) tried to fix this by adding guards themselves, but had to give up because they (quote) "fell down into a cast hell".

This only happens with opencv-4.5.5.
opencv-4.5.4 builds just fine for both 64bit and 342bit using gcc-11.2.1.

**Comment by anna-khakimova** [comment]
This issue will be fixed with merge PR "GAPI Fluid Resize: Fix for 32bit build issue." #21628
