### ISSUE TITLE
Error while loading yolor_p6.onnx: expand op doesn't support multiple axes for constant input

### ISSUE THREAD

**Issue by abdessamad-abid** [opencv/opencv#21665]
I'm trying to load yolor after i converted it from pytorch to onnx. buti get this error:

Node [Expand@ai.onnx]:(815) parse error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:2389: error: (-213:The function/feature is not implemented) Expand op doesn't support multiple axes for constant input in function 'parseExpand'

my code :
`import cv2`
`onnx_model = cv2.dnn.readNetFromONNX('yolor_p6.onnx')`

**Comment by ninenox-dev** [comment]
I had same error, How to fix it?

**Comment by abdessamad-abid** [comment]
> 

unfortunately i still haven't solved this issue.

**Comment by fengyuentau** [comment]
Could you provide your model?

**Comment by fengyuentau** [comment]
This issue is fixed via https://github.com/opencv/opencv/pull/22290. Latest OpenCV can now read 'yolor_p6.onnx'. Get the latest opencv-python package to test: `pip install "opencv-python-rolling<5.0"`.

By the way, [this issue](https://github.com/WongKinYiu/yolor/issues/7) can help converting yolor_p6.pt to yolor_p6.onnx.

**Comment by abdessamad-abid** [comment]
> This issue is fixed via #22290. Latest OpenCV can now read 'yolor_p6.onnx'. Get the latest opencv-python package to test: `pip install "opencv-python-rolling<5.0"`.
> 
> By the way, [this issue](https://github.com/WongKinYiu/yolor/issues/7) can help converting yolor_p6.pt to yolor_p6.onnx.

fiiinally
