### ISSUE TITLE
We want to commit a new SIMD support in HAL ...

### ISSUE THREAD

**Issue by gititgo** [opencv/opencv#21808]
We have finished adding LoongArch SIMD (LASX) support in HAL based on opencv-4.5.4. Which branch we can contribute the new feature to ?

**Comment by gititgo** [comment]
Incompatible improvements or large features should be targeted to 5.x branch
Compatible improvements or small features should go to 4.x branch
i think we can target the PR to 4.x branch, right ?

**Comment by fengyuentau** [comment]
I think you can target on 4.x first.

**Comment by asmorkalov** [comment]
Hello @gititgo Sound good! OpenCV team discusses universal intrinsics redesign right now. Modern ARM v9 SVE2 and RISC-V RVV propose alternative approach for SIMDs rather than classic SSE and NEON and we want to accommodate to get the best performance. My colleague is working on prototype and proposal document with rationale and design changes. I think it could be joint effort. Could you do the following:
- Write short description what are missing from your point of view in universal intrinsics and what you want to propose in general.
- Provide small prototype that includes some classic OpenCV function as example of changes.

**Comment by vpisarev** [comment]
@gititgo, this is interesting! Yes, I agree that it should be contributed to 4.x branch.

As @asmorkalov mentioned, it will probably be some update in our universal intrinsics API to support vector extensions RVV and SVE2, but I hope that we could do it with minor modifications and 95% of the code will still be valid.

For example, instead of v_float32::nlanes we will have to write something like VecTraits<float>::nlanes, but such a change could be done easily with a batch replacement.

So, please, go ahead and contribute your backend that provides compatible API with the current wide universal intrinsics.

**Comment by gititgo** [comment]
@vpisarev, Ok, thanks. We are making preparations for it.

**Comment by asmorkalov** [comment]
@gititgo I think we can close the ticket, right?

**Comment by gititgo** [comment]
OK, Done.

**Comment by asmorkalov** [comment]
Related PRs:
- https://github.com/opencv/opencv/pull/23929
- https://github.com/opencv/opencv/pull/24565
