### ISSUE TITLE
How to contriube opencv if the algorithm needs gram-shmidt process?

### ISSUE THREAD

**Issue by RoyAmoyal** [opencv/opencv#21817]
hey, I want to contribute an algorithm to the library. 
 
I just read that I can't use extra dependencies. 

Do I have to write all the math operations from scratch (like gram-Shmidt and so on) for the algorithm? 

thanks.

**Comment by asmorkalov** [comment]
Hello @RoyAmoyal You are welcome for contributions to OpenCV! OpenCV team is not totally against 3rd party code in case if it's really useful and add significant value to the project. The major items here:
- OpenCV supports a lot of platforms, including Android, iOS, Windows and some more exotic that relies on cross compiler. A new 3rd party dependency adds more headache. That's why OpenCV team is very conservative here.
- It's usually not make sense to add 3rd party library, if you need only one function and it's isolated mathematical algorithm. In particular the Gramm-Shmidt process does not look too complex and can be proposed as part of your patch.
- OpenCV has optional dependencies like Eigen, BLAS, etc. You can make the functionality with new process optional only for the case, if required 3rd party is found.
