### ISSUE TITLE
cvRound and std::round

### ISSUE THREAD

**Issue by ShihanWang** [opencv/opencv#21885]
##### System information (version)
- OpenCV => :  4.5.5
- Operating System / Platform => Ubuntu16.04
- Compiler => :g++

##### Detailed description
Using two functions: std::round() and cvRound(), result is:
value: 0.5       std and cv round: [1,0]
value: -0.5     std and cv round: [-1,0]
value: 962.5   std and cv round: [963,962]
value: 1085.5 std and cv round: [1086,1086]

#### Question
What is the reason? Thanks a lot!

**Comment by Kumataro** [comment]
>What is the reason? Thanks a lot!

(If this answer is not correct, sorry. )

There are two method to round to nearest integer.[^1]  
    - (A) [Round to nearest, ties to even](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even)
    - (B)  [Round to nearest, ties away from zero](https://en.wikipedia.org/wiki/Rounding#Round_half_away_from_zero)

- IEEE754 default is (A). (So cvRound()  works with (A) )   [^2]
- std::round is (B) . [^3]

> Round to nearest
> Returns the integral value that is nearest to x, with halfway cases rounded away from zero.

So that result of (A) and (B) are not same.

[^1]: https://en.wikipedia.org/wiki/IEEE_754#Roundings_to_nearest
[^2]: https://stackoverflow.com/questions/27989989/x64-rounding-inconsistency-in-cvround-mm-cvtsd-si32 .
[^3]: https://www.cplusplus.com/reference/cmath/round/

**Comment by ShihanWang** [comment]
Thanks again for your reply !   My confusion was solved.
