### ISSUE TITLE
Dummy support of CV_32U/CV_64S/CV_64U

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#21979]
I understand that there are many reason to *not* support CV algorithms for CV_32U/CV_64S/CV_64U
However, just wrapping data in cv::Mat is very handy.
Would it be possible to support CV_32U/CV_64S/CV_64U for data wrapping only (supporting basic memory operations like copy/roi/raw data access) ?

**Comment by vpisarev** [comment]
Hello @chacha21, indeed, it's planned to make complete type list, including CV_32U, CV_64S, CV_64U, CV_16BF, CV_BOOL, CV_NONE/CV_EMPTY etc.

There are a few problems to implement it right now:
1. the type is encoded as bit-field in cv::Mat::flags and we unwisely allocated just 3 bits for it (the lowest 3 bits of flags, followed by 9 or so bits, allocated for channels), and all 7 options are taken. We need to allocate a few more bits, unconnected with the lowest 3, to specify the type:
  was:
  ```
  flags ~ ....CCCCCCCCCTTT
  ```
  should become
  ```
  flags ~ .....TTTTTTTT....CCCCCCCCCTTT
  ```
  Of course, Mat::depth(), Mat::type(), Mat::elemSize() will be affected, but in the library there are many other places where Mat::flags is used directly. Actually, even Mat::type() is combined representation of element type (i.e. depth) and channels, and it's used many times, e.g. as an index to a table of function pointers.
2. The number of places to check after such a change is really big.
3. It will break compatibility, because upper bits of cv::Mat::flags are now used by some other things, e.g. the upper 16 bits are signature bits. Therefore we can do such a change only in OpenCV 5.0, which is still in progress.
4. You say, it would be enough to provide placeholders for the new types, but, of course, we'd have to provide at least some basic support, i.e. Mat::create(), Mat::copyTo(), Mat::setTo(), Mat::convertTo(), Mat::at(), flip(), transpose(), I/O (FileStorage & print) etc.

Nevertheless, as I said, it's planned to do. See also https://github.com/opencv/opencv/wiki/OE-5.-OpenCV-5
