### ISSUE TITLE
G-API: build warnings (GCC 12)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#22023]
Compiler: GCC 12.1
Warnings are related to `GAPI_Assert(false ...);` code.
`GAPI_Error()` with "noreturn" attribute should be used instead.

```
[2464/3435] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/compiler/gislandmodel.cpp.o
/home/alalek/projects/opencv/dev/modules/gapi/src/compiler/gislandmodel.cpp: In member function ‘ade::NodeHandle cv::gimpl::GIsland::producer(const ade::Graph&, const ade::NodeHandle&) const’:
/home/alalek/projects/opencv/dev/modules/gapi/src/compiler/gislandmodel.cpp:124:1: warning: control reaches end of non-void function [-Wreturn-type]
  124 | }
      | ^
[2483/3435] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/executor/gstreamingexecutor.cpp.o
/home/alalek/projects/opencv/dev/modules/gapi/src/executor/gstreamingexecutor.cpp: In member function ‘bool cv::gimpl::GStreamingExecutor::pull(cv::GRunArgsP&&)’:
/home/alalek/projects/opencv/dev/modules/gapi/src/executor/gstreamingexecutor.cpp:1832:1: warning: control reaches end of non-void function [-Wreturn-type]
 1832 | }
      | ^
/home/alalek/projects/opencv/dev/modules/gapi/src/executor/gstreamingexecutor.cpp: In member function ‘bool cv::gimpl::GStreamingExecutor::pull(cv::GOptRunArgsP&&)’:
/home/alalek/projects/opencv/dev/modules/gapi/src/executor/gstreamingexecutor.cpp:1863:1: warning: control reaches end of non-void function [-Wreturn-type]
 1863 | }
      | ^
[2491/3435] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/cpu/gcpustereo.cpp.o
In file included from /home/alalek/projects/opencv/dev/modules/core/include/opencv2/core/matx.hpp:52,
                 from /home/alalek/projects/opencv/dev/modules/core/include/opencv2/core/mat.hpp:51,
                 from /home/alalek/projects/opencv/dev/modules/gapi/include/opencv2/gapi/opencv_includes.hpp:13,
                 from /home/alalek/projects/opencv/dev/modules/gapi/include/opencv2/gapi/gmat.hpp:14,
                 from /home/alalek/projects/opencv/dev/modules/gapi/include/opencv2/gapi/stereo.hpp:10,
                 from /home/alalek/projects/opencv/dev/modules/gapi/src/backends/cpu/gcpustereo.cpp:7:
/home/alalek/projects/opencv/dev/modules/gapi/src/backends/cpu/gcpustereo.cpp: In static member function ‘static void GCPUStereo::run(const cv::Mat&, const cv::Mat&, cv::gapi::StereoOutputFormat, cv::Mat&, const StereoSetup&)’:
/home/alalek/projects/opencv/dev/modules/core/include/opencv2/core/base.hpp:342:32: warning: this statement may fall through [-Wimplicit-fallthrough=]
  342 | #define CV_Assert( expr ) do { if(!!(expr)) ; else cv::error( cv::Error::StsAssert, #expr, CV_Func, __FILE__, __LINE__ ); } while(0)
      |                                ^~
/home/alalek/projects/opencv/dev/modules/gapi/include/opencv2/gapi/own/assert.hpp:20:21: note: in expansion of macro ‘CV_Assert’
   20 | #define GAPI_Assert CV_Assert
      |                     ^~~~~~~~~
/home/alalek/projects/opencv/dev/modules/gapi/src/backends/cpu/gcpustereo.cpp:66:17: note: in expansion of macro ‘GAPI_Assert’
   66 |                 GAPI_Assert(false && "This case may be supported in future.");
      |                 ^~~~~~~~~~~
/home/alalek/projects/opencv/dev/modules/gapi/src/backends/cpu/gcpustereo.cpp:67:13: note: here
   67 |             default:
      |             ^~~~~~~
```

**Comment by alalek** [comment]
Fixed by #22935

**Comment by code-affinity** [comment]
When I build OpenCV 4.5.4 or 4.5.5 with gcc 12.2.0 on Linux, for the debug build configuration, these warnings are treated as errors, preventing me from successfully building OpenCV.  

I didn't do anything that I'm aware of to promote these warnings to errors; I simply configured CMake with the desired WITH_* and BUILD_* options to support the features I use, then built it with ```cmake --build```.

Here is an example of the error message that I get when building OpenCV 4.5.5 from the [Conan recipe](https://conan.io/center/opencv), but I also get this error when I follow the instructions from the Linux [installation tutorial](https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html).

> /home/tcrews/.conan2/p/t/openceda8febf22a32/b/src/modules/gapi/src/compiler/gislandmodel.cpp: In member function ‘ade::NodeHandle cv::gimpl::GIsland::producer(const ade::Graph&, const ade::NodeHandle&) const’:
> /home/tcrews/.conan2/p/t/openceda8febf22a32/b/src/modules/gapi/src/compiler/gislandmodel.cpp:124:1: error: control reaches end of non-void function [-Werror=return-type]
>   124 | }

Is G-API integral to OpenCV 4.5?  The documentation gives the impression that it is still experimental.  Our application does not directly use it, but perhaps one of the modules that we are using relies on G-API internally.  Our application currently uses these OpenCV modules: core, imgcodecs, imgproc, calib3d, features2d, flann, photo, videoio.

Is there a CMake WITH_* or BUILD_* option I can disable that will allow me to proceed without building G_API?  Or is there an option that will allow me to continue treating this warning as a warning instead of an error?

**Comment by dmatveev** [comment]
@code-affinity disabling WITH_ADE might turn off building g-api, so the code with the issues is excluded in the build as well. Please let us know if the issue is still there for 4.8+
