### ISSUE TITLE
cv::norm(...,...,cv::NORM_L2SQR) is 10x slower than calling cv::normL2Sqr(...)

### ISSUE THREAD

**Issue by tompollok** [opencv/opencv#22143]
Used Version: OpenCV 4.5.4 and OpenCV 4.6.0

Calling cv::norm is 10x slower than calling cv::normL2Sqr directly.

I tested measured the time with 2.5 Million float vectors with 512 dimensions.

cv::normL2Sqr:     308ms
cv::norm:            3092ms

Im wondering how there can be such an performance loss.

There is also no avx optimization in opencv for cv::norm, but i found some implementations:

https://github.com/anas-899/l2_distance_SIMD/blob/master/Source.cpp
https://gist.github.com/matsui528/583925f88fcb08240319030202588c74 

Maybe somebody with avx knowledge wants to take this over?

**Comment by alalek** [comment]
SIMD optimization for norm L2 is here: https://github.com/opencv/opencv/blame/4.6.0/modules/core/src/norm.cpp#L145-L170
Or it just reuses cv::normL2Sqr: https://github.com/opencv/opencv/blame/4.6.0/modules/core/src/norm.cpp#L260

It is expected that there is some overhead of full-featured OpenCV API functions (at least on types dispatching).
But on images (HD/FHD) this overhead it is not very significant.

Please provide your benchmark code.

**Comment by tompollok** [comment]
cv::normL2Sqr:              185ms
cv::hal::normL2Sqr_:    1051ms
cv::norm:                     1970ms

**Comment by tompollok** [comment]
I dont know why the hal version performs worse in my benchmark code, but in my production code calling cv::hal::normL2Sqr_ is faster than calling cv::normL2Sqr, which also was my expected result at the beginning.

The reason why i got misleaded was because F2 on cv::norm brought me here in my code editor:
https://github.com/opencv/opencv/blob/a6ca48a1c22a2f0e7e3b493b78bd2ac4a5a7acf0/modules/core/include/opencv2/core/matx.hpp#L935

However, do i see it corretly, that the SIMD version is not called at all in cv::norm? If so, is this expected behaviour? I was expecting that SIMD optimized functions are called, if available.

**Comment by alalek** [comment]
800ms / 2500000 = 320ns per iteration.

320 nanoseconds is used to dispatching to the right code path (based on type of input matrices, enabled/used modes/etc).
BTW, RAM latency is about 30-80ns.

Dispatching overhead for 1ms call (FHD image) is 0,03% . This is acceptable for images.
For processing of small vectors and reducing overhead  need to use another API, raw array instead of cv::Mat, etc.

For experiments with overhead try:
- `dimensions = 1`
- `dimensions = 1000000` and `entries = 1000`

---

> because F2 on cv::norm brought me here in my code editor

Editors are not reliable. Need to use debuggers instead.
