### ISSUE TITLE
Choosing `patternSize` parameter in `findChessboardCorners`

### ISSUE THREAD

**Issue by jonathanloganmoran** [opencv/opencv#22387]
Hello,

Quick question here on the `patternSize` parameter of `findChessboardCorners()` —

I need to know how to properly define the number of "inner corner points" along the rows, cols of a simple 2D chessboard calibration target. 

Here's one of the calibration target images I'm using:
![GOPR0059](https://user-images.githubusercontent.com/22329957/184963456-b3733efb-8f56-4ce6-be85-82dd442c5e80.jpg)

And how I assume the inner corner coordinates should be mapped:
![2022-08-10-Figure-3-Chessboard-Corners](https://user-images.githubusercontent.com/22329957/184963640-f245b16d-7967-489f-92e7-d761f92ba592.jpg)

Resulting in a `patternSize = (8,6)` which I assume is the correct inner point count (starting at 1, not zero). 

However, in the OpenCV [`py_calibration.markdown`](https://github.com/opencv/opencv/blob/3.4/doc/py_tutorials/py_calib3d/py_calibration/py_calibration.markdown) tutorial, the calibration pattern of `patternSize = (7,6)` (but actually `(8,6)` by my logic) has the following detected inner points:
![calib_pattern](https://user-images.githubusercontent.com/22329957/184964441-91affe09-2140-420f-a8a9-32c081d00ea6.jpg)
which seem to only include the second-to-last corner of each square (shown as the lower corner point in the upper-most row of black squares, but *not* the upper corner points).

Can you help clarify this in the context of my calibration pattern? Thanks!

**Comment by catree** [comment]
In your last image, it is a `9x6` pattern. See this: https://github.com/opencv/opencv_contrib/issues/3291#issuecomment-1164919071

You should use an asymmetric pattern: https://github.com/opencv/opencv/blob/4.x/doc/pattern.png to have unique chessboard poses.

---

Ultimately, what should matter is the **precision in the extraction** of the 2D corners coordinates and to **properly cover** the camera field of view. That is:
- no blurry images,
- enough images to cover the camera field of view,
- images with the pattern in the image borders (to properly model the camera distortion).

Using a `7x6` pattern instead of a `9x6` pattern will lead to less points and thus maybe a less precise calibration, but should not lead to a wrong calibration.
