### ISSUE TITLE
Wrong frame size and crash in VideoWriter::~release() when used with tiny frame sizes

### ISSUE THREAD

**Issue by fhwedel-hoe** [opencv/opencv#22420]
##### System information (version)
- OpenCV => 4.2 to 4.6
- Operating System / Platform => Ubuntu 20.04 Linux amd64
- Compiler => 9.4.0

##### Steps to reproduce

Build and execute this program:

```.cpp
#include <opencv2/opencv.hpp>

int main(int, char**) {
    cv::Mat img = cv::Mat::zeros(cv::Size(7,7), CV_8UC3);
    auto fourcc = cv::VideoWriter::fourcc('M','J','P','G');
    cv::VideoWriter vw;
    vw.open("test.avi", fourcc, 25.0, img.size());
    vw << img;
    return 0;
}
 ```

##### Detailed description

When using the ffmpeg backend to write a video with a small dimension (less than 8 by 8), the program receives SIGABRT because of `free(): invalid next size (fast)` when calling the `~VideoWriter()` destructor.

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6b0d859 in __GI_abort () at abort.c:79
#2  0x00007ffff6b7826e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6ca2298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff6b802fc in malloc_printerr (str=str@entry=0x7ffff6ca4600 "free(): invalid next size (fast)") at malloc.c:5347
#4  0x00007ffff6b81bac in _int_free (av=0x7ffff6cd7b80 <main_arena>, p=0x5555555a7f90, have_lock=0) at malloc.c:4249
#5  0x00007ffff7f92635 in CvVideoWriter_FFMPEG::close() () at /usr/local/lib/libopencv_videoio.so.406
#6  0x00007ffff7f92821 in std::_Sp_counted_ptr_inplace<cv::(anonymous namespace)::CvVideoWriter_FFMPEG_proxy, std::allocator<cv::(anonymous namespace)::CvVideoWriter_FFMPEG_proxy>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () at /usr/local/lib/libopencv_videoio.so.406
#7  0x00007ffff7f504fd in cv::VideoWriter::release() () at /usr/local/lib/libopencv_videoio.so.406
#8  0x00007ffff7f5051e in cv::VideoWriter::~VideoWriter() () at /usr/local/lib/libopencv_videoio.so.406
#9  0x0000555555556600 in main(int, char**) ()
```

The output file actually gets written, but has incorrect dimensions, in this example 6 by 6 (one less in each dimension).

Using the built-in `cv::CAP_OPENCV_MJPEG` backend works fine.

I am aware that producing tiny videos is probably an edge-case, but I feel this should be documented somewhere. I know some encoders need minimum sizes, but I am not aware of MJPEG having such a restriction. Even then, the program should not crash or at least trip an assertion.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution  
    (this is not #20498)
 - [x] I updated to the latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc  
  (Contained in code sample.)

**Comment by asmorkalov** [comment]
Findings:
1. **FFmpeg backend**. The issue is reproducible with Ubuntu 20.04, but not Ubuntu 18.04. It looks like some bug in FFmpeg itself. I'll try do run valgrind or some other memory checker to prove it.
2. **OpenCV MJPEG**. OpenCV uses underlying JPEG library to encode frames and the final frame size depends on libjpeg version:
- Default Ubuntu 18.04 libjpeg produces video 6x6. The same true for FFmpeg and GStreamer (libjpeg-turbo8-dev:amd64, 1.5.2-0ubuntu5.18.04.6).
- Default Ubuntu 20.04: produces video 7x7 (libjpeg-turbo8-dev:amd64, 2.0.3-0ubuntu1.20.04.3).
- libjpeg turbo in OpenCV 3rdparty (-DBUILD_JPEG=ONN) produces video with 7x7 (ver 2.1.3-62).

So, It's not OpenCV issue. Please update libjpeg and/or ffmpeg to get correct result.
