### ISSUE TITLE
cv2.resize() produces different results on x86_64 Linux and ARM64 MacOS

### ISSUE THREAD

**Issue by Askannz** [opencv/opencv#22477]
##### System information (version)

- OpenCV => `4.6.0.66`, Python wheels from pypi
- Operating System / Platform => Linux x86_64 / MacOSX ARM64
- Compiler => ?

##### Detailed description

`cv2.resize()` with the flag `interpolation=cv2.INTER_CUBIC` produces slightly different results on M1 Mac compared x86_64 Linux.
Doesn't seem to happen with the default interpolation method (linear).

Also, when OpenCV is downgraded to `4.2.0.34` on Linux it matches the MacOS behavior.

##### Steps to reproduce

```python
import numpy as np
import cv2

img = np.array([[0, 255, 0], [255, 0, 255]], dtype=np.uint8)
img = cv2.resize(img, fx=1.5, fy=1.5, dsize=None, interpolation=cv2.INTER_CUBIC)
print(f"{img[0, 1]=}")
```

Outputs:
 * Linux + opencv-python=4.2.0.34: `img[0, 1]=155`
 * Linux + opencv-python=4.3.0.38: `img[0, 1]=156`
 * Linux + opencv-python=4.6.0.66: `img[0, 1]=156`
 * MacOS + opencv-python=4.6.0.66: `img[0, 1]=155`

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by asmorkalov** [comment]
some of interpolation options uses 3rdparty libs for acceleration like IPP and floating arithmetic. Floating point arithmetic may produce slightly different result due to different computation order, vectorization, etc. Use interpolation modes with suffix `_EXACT` to get bit exact results on all platforms. They are implemented with integer and fixed point arithmetic and do not suffer from these side effects.

**Comment by LightSun** [comment]
I met a similar problem.  same machine. but one is c++ one is python
