### ISSUE TITLE
Poor performance of imread for OpenCV version >=4.1.1.26

### ISSUE THREAD

**Issue by Piecer-plc** [opencv/opencv#22472]
##### System information (version)

- OpenCV = 4.5.1.48 ; OpenCV = 4.1.0.25
- Operating System: Linux Ubuntu 16.04
CPU: Intel(R) Core(TM) i9-9900K CPU
GPU: TITAN V
- Python = 3.7.10

##### Detailed description
- I have found that ```cv2.imread``` runs longer in the new version compared to the old version. 
- In my program, when the openCV-python version was **4.5.1.48**, the execution time was **31s**, but when I changed the  openCV-python to the **4.1.0.25**, the execution tim was **21s**.
- I also tested other versions of openCV-python, and the detailed experiments The results are shown in the table below.
**My question is, why is there a new version that take more execution time and is there a way to fix it?**

 Execution time(s) | Version
-- | --
 31| 4.5.1.48
 31| 4.4.0.46
31| 4.3.0.36
31| 4.2.0.34
31| 4.1.2.30
31| 4.1.1.26
21| 4.1.0.25
21| 4.0.0.21
##### Steps to reproduce
1: Download dataset
This dataset contains many images, so I upload this dataset to Google Drive. You can download this dataset by click this link.
[Click me to download the dataset](https://drive.google.com/file/d/1b40XG_0ktdGu9WqI28yW2Y5DLaG0Wtu6/view?usp=sharing)
2: Install OpenCV-Python
```pip install opencv-python ==  4.5.1.48```
3: Code
```python
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
train = pd.read_csv("train.csv")
import cv2
import time
start_time = time.time()
base_path = "images/"
def read_img(img_path):
    img = cv2.imread(base_path + img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img
import tqdm
for i, file in enumerate(tqdm.tqdm(train["image_id"])):
    img = read_img(file + ".jpg")
over_time = time.time()
total_time = over_time - start_time
print("Time: %s s" % total_time)
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by catree** [comment]
Could you copy/paste the output of the following command between two versions that give different execution time?

```python
cv2.getBuildInformation()
```

**Comment by PerformanceDetect** [comment]
Execution time 21s: [4.1.0.25.txt](https://github.com/opencv/opencv/files/9492855/4.1.0.25.txt)

Execution time 31s: [4.1.1.26.txt](https://github.com/opencv/opencv/files/9492856/4.1.1.26.txt)

Execution time 31s: [4.5.1.48.txt](https://github.com/opencv/opencv/files/9492854/4.5.1.48.txt)



> Could you copy/paste the output of the following command between two versions that give different execution time?
> 
> ```python
> cv2.getBuildInformation()
> ```

**Comment by catree** [comment]
The differences:

![image](https://user-images.githubusercontent.com/8229425/188585522-9b2dd87e-e140-4e09-abcb-02bc7d46df9e.png)

Starting from `4.1.1.26`, built-in `libjpeg-turbo` in OpenCV is directly shipped.
This most likely explain the drop of performance since system `libjpeg-turbo` contains code optimized for your CPU while the one in OpenCV does not (currently).

See also:
- https://github.com/opencv/opencv/pull/11497
- https://github.com/opencv/opencv/pull/22372

---

One option would be:
- install [libjpeg-turbo](https://packages.ubuntu.com/jammy/libjpeg-turbo8) manually
- build OpenCV manually instead of `pip install`

I don't know if installing first `libjpeg-turbo` then `pip install` would make OpenCV uses system `libjpeg-turbo`, but you can also try that.

**Comment by alalek** [comment]
Self-sourced libjpeg-turbo in `opencv/3rdparty` doesn't use SIMD optimizations (since #11497).
There is no such issue if using system jpeg library (`opencv-python` package ignores this anyway).

This PR should improve this: #22372

---

> I don't know if installing first `libjpeg-turbo` then `pip install` would make OpenCV uses system libjpeg-turbo, but you can also try that.

1. Something like `libjpeg-devel` / `-dev`
2. Try to switch `pip install` from source code (and ensure that build process using system library): `pip install --no-binary opencv-python opencv-python`
