### ISSUE TITLE
OpenCV 4.6.0 does not compile on Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by lgmventura** [opencv/opencv#22646]
### System Information

OpenCV version: 4.6.0
Operating System / Platform: Ubuntu 22.04
Compiler version: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

### Detailed description

I'm trying to compile **OpenCV for C++** again on Ubuntu 22.04 and the compiling process stops at 20%. I clone the repository, create a folder "build" in the same folder where opencv is located, enter it and run `cmake ../opencv` to configure. When it finishes, I run `make` to compile. When it gets to around 20%, it outputs an error and stops compiling:

```
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_obsensor/obsensor_uvc_stream_channel.cpp.o
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_obsensor/obsensor_stream_channel_v4l2.cpp.o
[ 20%] Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libavcodec.a(lpc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:365: lib/libopencv_videoio.so.4.6.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:2309: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

After getting the error on `make`, I noticed I had some warnings before on `cmake` that some files could be hidden by other files with the same name in the Anaconda Python installation folder. Since I'm compiling OpenCV to use with C++ and not with Python, I tried to solve the warnings hoping to get the compilation process to finish without errors, I commented all lines from `~/.bashrc` and restarted the terminal, being able to run `cmake` with no warnings. But running `make` again leads to the same error, the only difference is that it appears on 22% of the compiling process:

```
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_obsensor/obsensor_uvc_stream_channel.cpp.o
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_obsensor/obsensor_stream_channel_v4l2.cpp.o
[ 20%] Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libavcodec.a(lpc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:365: lib/libopencv_videoio.so.4.6.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:2309: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

The hint "recompile with -fPIC" does not help either. I found some badly explained instructions [here](https://stackoverflow.com/questions/18604301/edit-cmakelists-txt-to-compile-with-fpic) to "recompile with -fPIC" and none of them work. Only adding `SET(Boost_USE_STATIC_LIBS OFF)` at the beginning of `CMakeLists.txt` doesn't throw an error when calling `cmake`, but leads to the same error on running `make`.

### Steps to reproduce

To reproduce:
```
git clone https://github.com/opencv/opencv.git
mkdir -p build && cd build
cmake ../opencv
make
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by fengyuentau** [comment]
OpenCV is not officially tested on Ubuntu 22.04. This error `/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libavcodec.a(lpc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC` looks like a 3rd party issue to me. I think you can have a try with installing `libavcodec.so` instead of its static version.

**Comment by lgmventura** [comment]
Hi, @fengyuentau , thanks for your response. Libavcodec was already installed. I was able to compile following these steps:

Open terminal in the desired compilation path:
```
git clone https://github.com/opencv/opencv.git # if not done yet
conda deactivate # so it doesn't look at Anaconda libraries. Don't need to manually activate again, just open a new terminal
sudo mv /usr/lib/x86_64-linux-gnu/libavcodec.a /usr/lib/x86_64-linux-gnu/_libavcodec.a_ # so this static library is not found during compilation - it will look for the dynamic one
mkdir -p build && cd build
cmake ../opencv -DBUILD_TIFF=ON # flag to force recompile libtiff instead of looking for an existing shared object
make
sudo mv /usr/lib/x86_64-linux-gnu/_libavcodec.a_ /usr/lib/x86_64-linux-gnu/libavcodec.a # rename this back to its original name
```

However, programs compiled used OpenCV don't open, they look for `libopencv_photo.so.406`, which doesn't exist. I found a suggestion to run `sudo ldconfig -v` so it recreates the links required by programs to run, such as a symbolic link called `libopencv_photo.so.406` from `libopencv_photo.so`. After this, my compiled program is not looking for that anymore, but now, it's looking for the so `libdc1394.so.22`. It doesn't exist in Ubuntu 22.04, since it has the newer version `libdc1394.so.25`.

When do you plan to update OpenCV for it to support Ubuntu 22.04 and related systems?

**Comment by fengyuentau** [comment]
> When do you plan to update OpenCV for it to support Ubuntu 22.04 and related systems?

AFAIK, we don't have such a plan for now. One of our main and active development environment is Ubuntu 20.04.

**Comment by lgmventura** [comment]
But the current LTS version of Ubuntu is 22.04 now.
Anyway, if you don't plan to update it any soon, could you please provide compiled versions of OpenCV for Linux as well as you do for Windows and Mac OS?

**Comment by mshabunin** [comment]
Can not reproduce the issue with a clean Ubuntu 22.04 (in docker):

##### Dockerfile
```
FROM ubuntu:22.04
RUN apt-get update && apt-get install -y cmake make g++ git
RUN git clone --depth=1 https://github.com/opencv/opencv
RUN mkdir -p build
WORKDIR build
RUN cmake ../opencv && make -j12
```

We do not have Ubuntu 22.04 in CI, but it does not mean we do not support it. Many developers use it everyday without problems.

**Comment by asmorkalov** [comment]
Ubuntu provides both dynamic and static libraries for FFmpeg by default. CMake uses dynamic version by default and it works with OpenCV like a charm. Just checked with my Kubuntu  22.04 installation. I have not found simple way to force static libraries usage in OpenCV. In case if you force the option. You need to take a look on `ENABLE_PIC` option in OpenCV CMake. It's synonym for cmake CMAKE_POSITION_INDEPENDENT_CODE: https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html. It manages -fPIC behaviour in OpenCV and does what compiler recommends you. In any case the issue is not relevant to OpenCV code base.

**Comment by Sherif-Elshafei** [comment]
Here is what I did that got me through on my system 
(installing Opencv4.6.0 on Linux Mint 21 (Vanessa) which is an Ubuntu 220.04 based system)

1) Download the Opencv4.6.0 release from https://github.com/opencv/opencv/releases/tag/4.6.0 (scroll down to Source code.zip file and download the file opencv-4.6.0.zip)

2) Unzip the Source code.zip (opencv-4.6.0.zip) at your home directory using the command 
$unzip /path/to/location/open-4.6.0.zip -d /home/xyz/
Avoid unzipping to a different directory than your home directory. I believe the way cmake is configured requires that you keep opencv directory in your home dir.

3) Do the conventional steps to run cmake gracefully:
$ cd opencv (#get inside the opencv folder)
$ mkdir build/
$ cd build/
$ cmake -S .. -B . (#run cmake using its source (i.e. CMakeLists.txt which is located in the opencv dir, and building in the build dir which you are in). Note: don't use any flags/switches running the cmake command. Just run its most plain version. I found that the job gets done this way. If anything goes wrong, then:
$ cd ..
$ rm -rf build/   (# remove the build/ dir)
and go to step 3) above. 

4) Now build (i.e. compile) the source of opencv.
$ make (# you are still in build/). Note: you could use the -j followed by the number of processors on the core of your system's processor. However, I recommend using straight make without -j, it will take a bit longer but it could avoid possible read-before-write errors. Let's play it safe to get the job done.

5) Install the library (where all header files and libraries are taken to their destination as a final step)
$ sudo make install (# you need sudo here because you are writing root privileged directories)

Now that you have installed opencv let's make sure things are aligned by executing a "hello world" opencv code.

1) Go to a workspace directory of your choice and 
$ touch main.cpp

2) I use vscode as IDE. So I start vscode from within the workspace directory as my main.cpp
$ code . &

3) Open main.cpp in the editor and include the following lines of code:
#include <opencv2/highgui.hpp>
int main() {
    cv::Mat image;
    image = cv::imread("/path/to/any/image/testImage.jpg", cv::IMREAD_COLOR);
    cv::imshow("Test Image", image);
    cv::waitKey(0);
    return 0;
}

4) I use the following command to build my application (use it in a terminal, in a make file, in a .sh file, or you can configure the tasks.json file of your vscode and use the Run build task under the Terminal tab in vscode (control+shift+B):
$ g++ main.cpp -I/usr/local/include/opencv4/ -lopencv_core -lopencv_videoio -lopencv_highgui -lopencv_imgcodecs

5) The executable a.out will be created. Then run it:
$ ./a.out (# testImage.jpg shall popup in a separate window)

Good luck!

**Comment by TheSpecialOne45** [comment]
> Here is what I did that got me through on my system (installing Opencv4.6.0 on Linux Mint 21 (Vanessa) which is an Ubuntu 220.04 based system)
> 
>     1. Download the Opencv4.6.0 release from https://github.com/opencv/opencv/releases/tag/4.6.0 (scroll down to Source code.zip file and download the file opencv-4.6.0.zip)
> 
>     2. Unzip the Source code.zip (opencv-4.6.0.zip) at your home directory using the command
>        $unzip /path/to/location/open-4.6.0.zip -d /home/xyz/
>        Avoid unzipping to a different directory than your home directory. I believe the way cmake is configured requires that you keep opencv directory in your home dir.
> 
>     3. Do the conventional steps to run cmake gracefully:
>        $ cd opencv (#get inside the opencv folder)
>        $ mkdir build/
>        $ cd build/
>        $ cmake -S .. -B . (#run cmake using its source (i.e. CMakeLists.txt which is located in the opencv dir, and building in the build dir which you are in). Note: don't use any flags/switches running the cmake command. Just run its most plain version. I found that the job gets done this way. If anything goes wrong, then:
>        $ cd ..
>        $ rm -rf build/   (# remove the build/ dir)
>        and go to step 3) above.
> 
>     4. Now build (i.e. compile) the source of opencv.
>        $ make (# you are still in build/). Note: you could use the -j followed by the number of processors on the core of your system's processor. However, I recommend using straight make without -j, it will take a bit longer but it could avoid possible read-before-write errors. Let's play it safe to get the job done.
> 
>     5. Install the library (where all header files and libraries are taken to their destination as a final step)
>        $ sudo make install (# you need sudo here because you are writing root privileged directories)
> 
> 
> Now that you have installed opencv let's make sure things are aligned by executing a "hello world" opencv code.
> 
>     1. Go to a workspace directory of your choice and
>        $ touch main.cpp
> 
>     2. I use vscode as IDE. So I start vscode from within the workspace directory as my main.cpp
>        $ code . &
> 
>     3. Open main.cpp in the editor and include the following lines of code:
>        #include <opencv2/highgui.hpp>
>        int main() {
>        cv::Mat image;
>        image = cv::imread("/path/to/any/image/testImage.jpg", cv::IMREAD_COLOR);
>        cv::imshow("Test Image", image);
>        cv::waitKey(0);
>        return 0;
>        }
> 
>     4. I use the following command to build my application (use it in a terminal, in a make file, in a .sh file, or you can configure the tasks.json file of your vscode and use the Run build task under the Terminal tab in vscode (control+shift+B):
>        $ g++ main.cpp -I/usr/local/include/opencv4/ -lopencv_core -lopencv_videoio -lopencv_highgui -lopencv_imgcodecs
> 
>     5. The executable a.out will be created. Then run it:
>        $ ./a.out (# testImage.jpg shall popup in a separate window)
> 
> 
> Good luck!

Hi !

I had the same issue as the author of the issue but with OpenCV 4.7.0 therefore I tried the solution proposed by @Sherif-Elshafei with OpenCV 4.6.0.

After following the exact procedure described, I still get this error : 

[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/videoio_registry.cpp.o
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/videoio_c.cpp.o
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap.cpp.o
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_images.cpp.o
[ 20%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_mjpeg_encoder.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_mjpeg_decoder.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/backend_plugin.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/backend_static.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/container_avi.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_dc1394_v2.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o
[ 21%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
[ 21%] Linking CXX shared library ../../lib/libopencv_videoio.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libswscale.a(hscale_fast_bilinear_simd.o): relocation R_X86_64_32S against `.text.unlikely' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:283: lib/libopencv_videoio.so.4.6.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:2353: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

Here is the complete output of the terminal : 
[terminal_output_opencv460.txt](https://github.com/opencv/opencv/files/10686398/terminal_output_opencv460.txt)

Anyone has an idea to solve this problem ?

Many thanks :D

**Comment by TheSpecialOne45** [comment]
Hi

Thanks for your message @alalek ! 

I removed anything related to anaconda from my bashrc file and redid the whole procedure.

I still got the same error.

Then I checked /usr/lib/x86_64-linux-gnu/ and noticed that I have a file called libswscale.a, one called libswscale.so.5 and another one called libswscale.so.5.9.100

When I did the command : cmake -S .. -B .
I noticed the following warning :
-- Checking for modules 'libavcodec;libavformat;libavutil;libswscale'
--   Found libavcodec, version 58.134.100
--   Found libavformat, version 58.76.100
--   Found libavutil, version 56.70.100
--   Found libswscale, version 5.9.100
CMake Warning at cmake/OpenCVUtils.cmake:884 (message):
  ocv_check_modules(FFMPEG): can't find library 'swscale'.  Specify
  'pkgcfg_lib_FFMPEG_swscale' manually
Call Stack (most recent call first):
  modules/videoio/cmake/detect_ffmpeg.cmake:25 (ocv_check_modules)
  modules/videoio/cmake/init.cmake:7 (include)
  modules/videoio/cmake/init.cmake:11 (add_backend)
  cmake/OpenCVModule.cmake:298 (include)
  cmake/OpenCVModule.cmake:361 (_add_modules_1)
  cmake/OpenCVModule.cmake:385 (ocv_glob_modules)
  CMakeLists.txt:931 (ocv_register_modules)


Not sure what I'm supposed to do based on that ... any ideas ?

**Comment by TheSpecialOne45** [comment]
Finally managed to solve my problem and complete the procedure described by @Sherif-Elshafei.

To do so I did :
sudo mv /usr/lib/x86_64-linux-gnu/libswscale.a /usr/lib/x86_64-linux-gnu/_libswscale.a_
make
sudo mv /usr/lib/x86_64-linux-gnu/_libswscale.a_ /usr/lib/x86_64-linux-gnu/libswscale.a

Thanks all for your help :D

**Comment by Bycob** [comment]
I had the same problem with `libavcodec.a`
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libavcodec.a(lpc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```
Looking further, it looks like Cmake did not detect `libavcodec.so` and instead used the `.a`

I fixed the problem by changing a line in my `CMakeCache.txt`
```
pkgcfg_lib_FFMPEG_avcodec:FILEPATH=/usr/lib/x86_64-linux-gnu/libavcodec.a -> pkgcfg_lib_FFMPEG_avcodec:FILEPATH=/usr/lib/x86_64-linux-gnu/libavcodec.so
```
