### ISSUE TITLE
CI of github action was canceled unexpectedly

### ISSUE THREAD

**Issue by zihaomu** [opencv/opencv#22720]
### System Information

CI system

### Detailed description

When the PR has been updated, old actions should be canceled.
But I found some actions were canceled for no reason when there is no PR update.

### Steps to reproduce

For example: https://github.com/opencv/opencv/actions/runs/3350926191/attempts/1

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by alalek** [comment]
- 2022-10-29T09:29:01Z: PR has been created from commit [25a28a1](https://github.com/opencv/opencv/pull/22718/commits/25a28a1bc183b111ac812d5a0c04de826e59755d)
- 2022-10-29T09:34:42Z: CI jobs are triggered
- 2022-10-29T09:34:39Z: PR is updated by commit [17b98dd](https://github.com/opencv/opencv/commit/17b98dd005cd9739e0afdc24e0dc52067abcbb9b) (+ 5 min ) - **perhaps this pushed "update" event**
- Sat, 29 Oct 2022 09:47:01 GMT: CI cancels jobs from attempt 1
- 2022-10-29T11:24:34Z: CI is re-triggered (+2 hours)


The is some lag/mess between 2nd and 3rd events because they are handled by different services.
No idea about 2h delay for the re-trigger handling.

---

This is how it looks on Buildbot CI for one of configuration:
![pr-cancel](https://user-images.githubusercontent.com/4981219/198833634-18963c26-eaa6-4dd5-af51-b9bf2363b823.png)

[link](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64)

**Comment by alalek** [comment]
BTW, there is another strange cancelling: https://github.com/opencv/opencv/actions/runs/3382180061

In bottom there are 2 annotations/errors

---

Annotations
2 errors
[TIM-VX / x86-simulator-build-test](https://github.com/opencv/opencv/actions/runs/3382180061/jobs/5617369885)
Canceling since a higher priority waiting request for 'OCV-timvx-backend-tests-4.x-' exists
[TIM-VX / x86-simulator-build-test](https://github.com/opencv/opencv/actions/runs/3382180061/jobs/5617369885#step:10:1969)
The operation was canceled.

---

> `OCV-timvx-backend-tests-4.x-`

Looks like PR-id is missing here.

**Comment by zihaomu** [comment]
Yes, I have no idea about this. Maybe @fengyuentau can help.
Actually, this unexpected cancellation happens all the time.
For example, https://github.com/opencv/opencv/actions/runs/3374452035/attempts/2.

**Comment by fengyuentau** [comment]
Just guessing: maybe commits from different pull requests are lined up together. One commit comes in, the old one is cancelled.

**Comment by zihaomu** [comment]
Update:
Creating or updating a PR will close all the running patches.

**Comment by fengyuentau** [comment]
We observed that if one triggers jobs in github actions, running jobs in other pull requests will be cancelled.

I suspect that this is somehow related to https://github.com/opencv/ci-gha-workflow/pull/74 which may control the concurrency incorrectly.

**Comment by fengyuentau** [comment]
We observed that if one triggers jobs in github actions, running jobs in other pull requests will be cancelled.

I suspect that this is somehow related to https://github.com/opencv/ci-gha-workflow/pull/74 which may control the concurrency incorrectly.
