### ISSUE TITLE
cv.LUT is missing in openCv 4.6.0

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [opencv/opencv#22751]
### Descripe the feature and motivation

Hi,
Thank-you for this awesome js library.  There was a use case which involved useing cv.LUT however it is not available as of now. This function is available in openCV c++ and python versions.  Requesting you to please add this function in opencv js library with a proper documentation which will help developers like me

Kind Regards,
Aditya

**Comment by alalek** [comment]
There is no official opencv.js distribution (docs.opencv.org variant is for demo purposes only).
In general opencv.js should be build from the source code.
There is no goal to expose all public API, because it blows up opencv.js file size (40Mb+).
Adapt this configuration for your needs: https://github.com/opencv/opencv/blob/4.6.0/platforms/js/opencv_js.config.py
Build instruction is here: https://docs.opencv.org/4.x/d4/da1/tutorial_js_setup.html

**Comment by aditya-padhi-kbl** [comment]
Hi,
Thank-you for the details.  As suggested I added LUT to the core section of opencv_js.config.py
```
core = {
    '': [
        'absdiff', 'add', 'addWeighted', 'bitwise_and', 'bitwise_not', 'bitwise_or', 'bitwise_xor', 'cartToPolar',
        'compare', 'convertScaleAbs', 'copyMakeBorder', 'countNonZero', 'determinant', 'dft', 'divide', 'eigen',
        'exp', 'flip', 'getOptimalDFTSize','gemm', 'hconcat', 'inRange', 'invert', 'kmeans', 'log', 'magnitude',
        'max', 'mean', 'meanStdDev', 'merge', 'min', 'minMaxLoc', 'mixChannels', 'multiply', 'norm', 'normalize',
        'perspectiveTransform', 'polarToCart', 'pow', 'randn', 'randu', 'reduce', 'repeat', 'rotate', 'setIdentity', 'setRNGSeed',
        'solve', 'solvePoly', 'split', 'sqrt', 'subtract', 'trace', 'transform', 'transpose', 'vconcat',
        'setLogLevel', 'getLogLevel', 'LUT'
    ],
    'Algorithm': [],
}
```

The build get's successfully generated, however when I add it index.html I am getting "maxm call stack exceeded"
