### ISSUE TITLE
Cannot open BigTiff file

### ISSUE THREAD

**Issue by felleet** [opencv/opencv#22795]
### System Information

OpenCV version: 4.6.0
Operating System: Windows 10 x64

### Detailed description

I use opencv_java.jar and opencv_java.dll to work with images in java-project.
Error occuries when i try to open BigTiff images.
**Example 1**:
image size >4.5GB, resolution 94012x16837 pixels.
> CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.6.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgcodecs\src\loadsave.cpp:77: error: (-215:Assertion failed) pixels <= CV_IO_MAX_IMAGE_PIXELS in function 'cv::validateInputImageSize'

**Example 2**:
image size 2GB, resolution 62675x11224 pixels.
> imread_('D:\temp\testfiles\sample_bigtif_small.tif'): can't read data: OpenCV(4.6.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgcodecs\src\grfmt_tiff.cpp:663: error: (-215:Assertion failed) ((uint64_t)tile_width0 * tile_height0 * ncn * std::max(1, (int)(bpp / bitsPerByte)) < MAX_TILE_SIZE) && "TIFF tile size is too large: >= 1Gb" in function 'cv::TiffDecoder::readData'

Images were created in Photoshop using http://bigtiff.org
Moreover I tried to load tiff files with big resolution (1000000x12000 px), created in paint.net. And the same error occurred.
Seems like not all assertions improved in #18717

### Steps to reproduce

1. Create simple java maven project.
2. Put opencv_java.jar into lib folder and set up as system-scope dependency
3. Put opencv_java.dll into src/main/resources/META-INF/native/windows64
4. Setup dependency for hawtjni-runtime:
`<dependency> 
    <groupId>org.fusesource.hawtjni</groupId> 
        <artifactId>hawtjni-runtime</artifactId> 
        <version>1.15</version>
</dependency>`
5. Try to load image with this code sample:

public static void main(String[] args) { 	

    Library library = new Library("opencv_java", "4.6.0", Loader.class.getClassLoader());
    library.load(); 
    String absolutePath = "D:\\temp\\testfiles\\sample_bigtif.tif"; 
    Mat mat = Imgcodecs.imread(absolutePath); 
    if (mat.dataAddr() == 0) { 
        throw new RuntimeException("OpenCV can't load image: " + absolutePath); 
    }
}

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by felleet** [comment]
Our customer is looking forward to being able to upload large files. Is it possible to know approximately when to expect a solution to this problem? Date or release. Thanks

**Comment by felleet** [comment]
deleted question, please bring back bug label

**Comment by Kumataro** [comment]
Maybe it is user-application-usage-problem, not opencv-bug.

## About memory size limitation.

To decode tiff images, 3 memories are allocated.

- (a) Destination Mat, which is limitated by CV_IO_MAX_IMAGE_*.
- (b) libtiff working memory.
- (c) imgcodec working memory, which is limited by 1GB.

And we should consider operation system resource limitation. 

## Example 1:

> image size >4.5GB, resolution 94012x16837 pixels.

Currently maximum limitation to read is here. You can override with environment parameters. ( Please read https://answers.opencv.org/question/210482/read-and-display-image-of-large-size/ ) 

- width is ( 1 << 20 ) = 1,048,576 pixel
- height  is ( 1 << 20 )  = 1,048,576 pixel
- pixels is (1 << 30) = 16,777,216 pixels

https://github.com/opencv/opencv/blob/b0dc474160e389b9c9045da5db49d03ae17c6a6b/modules/imgcodecs/src/loadsave.cpp#L66-L68

This image contains 94012 * 16837 = 1,582,880,044 pixels.it exceeds by 16M pixels. Expected result is happen "Assertion failed" by (a).

OpenCV reports "Assertion failed" correctly. So this is not **bug**.

> CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.6.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgcodecs\src\loadsave.cpp:77: error: (-215:Assertion failed) pixels <= CV_IO_MAX_IMAGE_PIXELS in function 'cv::validateInputImageSize'


## Example 2:

> image size 2GB, resolution 62675x11224 pixels.

This image contains 62675 * 11224 * 3 = 2,110,392,600 byte, it exceeds by 1GB. Expected result is happen "Assertion failed" by (c).

OpenCV reports "Assertion failed" correctly. So this is not **bug**.

> imread_('D:\temp\testfiles\sample_bigtif_small.tif'): can't read data: OpenCV(4.6.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgcodecs\src\grfmt_tiff.cpp:663: error: (-215:Assertion failed) ((uint64_t)tile_width0 * tile_height0 * ncn * std::max(1, (int)(bpp / bitsPerByte)) < MAX_TILE_SIZE) && "TIFF tile size is too large: >= 1Gb" in function 'cv::TiffDecoder::readData'

## Moreover I tried to load tiff files with big resolution (1000000x12000 px),

This image contains 1,000,000 * 12,000 * 3(RGB?) = 36,000,000,000byte, it exceeds by 1GB. Expected result is happen "Assertion failed" by (c). 

If OpenCV reports "Assertion failed" correctly,  So this is not **bug**. 

## Additional information.

I hope [this fix](https://github.com/opencv/opencv/pull/22404)  helps your projects.

This patch is to try decoding by each lines instead of whole image. so memory usage is reduced.
( But it cannot supports all images.  . For example, it requests RGB/non-tiled/...).

If you're in a hurry, I recommend compiling the library yourself from git repository instead of waiting for the official release.

On the other hand, more simple solution is remove assert line by your own risk.  I think you will be able handle very large images (until operation system limitation.) In this case, you must be build from code by yourself.

**Comment by LaurentBerger** [comment]
`Currently maximum limitation to read is here. You can override with environment parameters. ( Please read https://answers.opencv.org/question/210482/read-and-display-image-of-large-size/ )`
or this [one](https://forum.opencv.org/t/how-to-deal-with-large-images/952/1)

**Comment by felleet** [comment]
Environment parameters overriding helped. Thank you!
