### ISSUE TITLE
DNN - 'handleNode' - 'getMemoryShapes'

### ISSUE THREAD

**Issue by gonulsinem** [opencv/opencv#22803]
### System Information

OpenCV version: 4.6.0
OS: Ubuntu 20.04
Python version: 3.8.10

### Detailed description

Hello there,
I am using OpenCV 4.6.0 and Ubuntu 20.04.
I am using DNN "static quantization" and I get the error in the image.
I tried both model NPU and CPU. I can read my normal ONNX model. But I run into these problems when reading the "quantize model".

What method would you suggest?

![dnn_getmemory_shape](https://user-images.githubusercontent.com/82284108/201652473-afa6da0e-4eac-439f-816d-dbcd204d0e90.PNG)

### Steps to reproduce

net = cv2.dnn.readNetFromONNX("ONNX_model_path")

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by fengyuentau** [comment]
Hello @gonulsinem , thank you for the report! Could you provide your model for us to debug?

**Comment by gonulsinem** [comment]
Thank you for your answer @fengyuentau.
I am using Khadas VIM3 and
NPU: Amlogic A311D


Files in ".zip"
[onnx_model.zip](https://github.com/opencv/opencv/files/10013222/onnx_model.zip)

**Comment by fengyuentau** [comment]
Models quantized in QDQ style have just been supported in https://github.com/opencv/opencv/pull/22666. You could have a try with latest OpenCV: `pip install opencv-python-rolling<5.0`. One thing you need to know is we do not release pre-built binaries with TIM-VX backend enabled, so you will need to compile following [this wiki](https://github.com/opencv/opencv/wiki/TIM-VX-Backend-For-Running-OpenCV-On-NPU) in order to run the model on NPU with TIM-VX backend.

But keep this in mind: you cannot run your model (`mobilenet_v2_uint8.onnx`, QDQ quantized) efficiently on the Khadas VIM3 NPU which only supports int8/uint8 calculation natively. QDQ style quantization is mainly used for shrinking the size of the model, and the actual calculation in inference will go back to FP32 instead of int8/uint8. If you are using onnxruntime for quantization, you could have a try with QOperator quantization ([example](https://github.com/opencv/opencv_zoo/blob/c79d9191ff792df933d348bd1c4de05edf77ddf9/tools/quantize/quantize-ort.py#L73-L77)). Find more details on QDQ and QOperator quantization at https://onnxruntime.ai/docs/performance/quantization.html#onnx-quantization-representation-format.

**Comment by gonulsinem** [comment]
Thanks a lot for your answer!
I had already tried installing with the "TIM-VX" backend (as per the https://github.com/opencv/opencv/wiki/TIM-VX-Backend-For-Running-OpenCV-On-NPU instructions) and was getting an error. I got the same error again.
When I run the command "make -j 8"
It gave error when "60%", but I tried many times. this is "%" "71%", "80%" etc. is changing. And as a result I couldn't install OpenCV TIM-VX on Khadas VIM.
What could be the reason for this? Is there a method you can recommend me?



![opencv](https://user-images.githubusercontent.com/82284108/202161316-0e082a51-9c90-414e-9dae-8d532ffa9492.png)
