### ISSUE TITLE
An nparray that uses an inconsistent save from cv2.imwrite

### ISSUE THREAD

**Issue by enhengxiaoxie** [opencv/opencv#23011]
### System Information

// example for python user
OpenCV python version: 4
Operating System / Platform: Ubuntu 20.04
Python version: 3.8

### Detailed description

I ran the following code, The outputs should be the same. Why are they different?

### Steps to reproduce

import cv2
import numpy as np
from PIL import Image
a = np.zeros([512,512,3]).astype(np.uint8)

for i in range(100):

    if i>50:
        a[i][i][0] = i
        a[i][i][1] = i
        a[i][i][2] = i

    else:
        a[i][i][0] = i
        a[i][i][1] = i
        a[i][i][2] = i

print(a.max())
cv2.imwrite("1.jpg",a)

img = cv2.imread("1.jpg")
print(img.max())

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by Libra2003** [comment]
Do i just answer the question or do i need to commit something somewhere plz guide?

**Comment by Libra2003** [comment]
The Reason they are different is because the array "a" is an in-memory array of 8-bit unassigned integers while "img" is an 8-bit unassigned integer that represents an image stored in a file.

When you wrote the array to a file "cv2.imwrite" the function encoded the pixel value in the array using a particular format (which in this case is .jpg). This function is using lossy compression (the data in a file is removed and not restored to its original form after decompression) to reduce the size of the image. As a result some of the info in the original image is lost during the encoding process when you call out "cv2.imwrite" function causing the pixel value to differ.

JPEG is a [lossy format](http://en.wikipedia.org/wiki/Lossy_compression) and will generally not produce exactly the same data when you save a file.

You can use .PNG format to fix this issue.

 Because of their different compression processes, JPEGs contain less data than PNGs
