### ISSUE TITLE
Two issues with CUDA_ENABLE_DELAYLOAD

### ISSUE THREAD

**Issue by mbechard** [opencv/opencv#23187]
### System Information

OpenCV version: 4.7.0
Operating System / Platform: Windows 10
Compiler & compiler version: Visual Studio 2019

### Detailed description

When using delayloading on Windows, the libraries using the /DELAYLOAD flag also need to link with delayimp.lib. I had to manually add this via CMAKE_SHARED_LINKER_FLAGS=delayimp.lib to get delayloading to compile.

Also, it would be nice if the python binary also applied the delay-loading to it's link stage as well. So we could import cv2 and not immediately load all of the CUDA binaries.

### Steps to reproduce

Try compiling on Windows with 
CUDA_ENABLE_DELAYLOAD=ON 
BUILD_SHARED_LIBS=ON

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by mbechard** [comment]
Attn: @CSBVision

**Comment by asmorkalov** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/linker-support-for-delay-loaded-dlls?view=msvc-170

**Comment by CSBVision** [comment]
Thanks for pointing out, we tried to reproduce the issue, still OpenCV 4.7.0 compiles as expected with both, VS2019 and VS2022, CUDA 11.8. Can you please share your full build configuration such that we can try to reproduce it?

The Python delay load options are missing, that's correct. We will investigate how to add the flags here, too. However, the `cv2.cpXX-win_amd64.pyd` does not directly depend on CUDA DLLs, at least if OpenCV is used as shared libraries (`BUILD_SHARED_LIBS=ON`) such that the CUDA DLLs should not be necessary at all.

Maybe the issue is caused by static build configuration, i.e. are you trying to compile OpenCV as static libraries using `BUILD_SHARED_LIBS=OFF` option? In this configuration, the cv2 pyd file is rather large but of course, depends on CUDA...

**Comment by asmorkalov** [comment]
`BUILD_SHARED_LIBS=OFF` is default configuration for OpenCV-Python in setup.py.

**Comment by CSBVision** [comment]
@asmorkalov Thanks for pointing out.

We will investigate the issue (unluckily, CUDA builds are rather slow) and once we succeed at reproducing, we will try to prepare a PR to fix it. Currently, at least the delay-load flags for some reason are not set for the opencv_python3 project. Thus, CUDA delay load does not work for the cv2.pyd package if static OpenCV libraries are used.

**Comment by mbechard** [comment]
Right sorry, I'm building with BUILD_SHARED_LIBS=ON, BUILD_STATIC_LIBS=OFF.
However I now realize that I thought this flag was doing something different than what it is. I thought it was delay-loading the opencv CUDA dlls (opencv_cuda*.dll). Since those .dlls are quite large, and can occur a long JIT CUDA compilation if running on a new GPU that wasn't part of the CUDA_BIN_ARCH, it would be nice of those were delay loaded both for the python .pyd as well as other .dlls that depend on them (opencv_videostab for example depends on a few of the opencv_cuda binaries).

**Comment by mbechard** [comment]
Attached is my full config script
[buildWin64.txt](https://github.com/opencv/opencv/files/10538003/buildWin64.txt)

Looking at it though I realize we don't have  BUILD_SHARED_LIBS explicitly set, although I do get shared binaries out..

**Comment by CSBVision** [comment]
Thanks for this information! There are different issues that should be discussed separately:

1. Currently, delay-loading only works for Visual Studio generator but not for Ninja, cf. discussion in #22675. In the CMake GUI, the delay-load option will only be available if VS generators are used. But this check was ignored because you explicitly defined the `CUDA_ENABLE_DELAYLOAD` flag in your CMake command line arguments. This is the reason for the error. Nevertheless, if only adding `delayimp.lib` to the linker flags fixes the delay-loading for Ninja as well, this can easily be added.
2. The delay load flags remain unset for the opencv_python3 package. This should be fixed. We will investigate why these are missing and how this can be fixed.
3. The CUDA delay load option currently only refers to the third-party CUDA libraries such that the same OpenCV build can be used on PCs with and without CUDA-supported hardware. Without delay-loading, a CUDA installation would be required whenever OpenCV was built with CUDA support, even though it won't be used for anything at all. Still, it might be worth investigating whether the configuration can be extended to add delay load flags for OpenCV's CUDA modules as well, i.e. the `opencv_cuda<module><version>.dll` files.

We will investigate issues 2 and 3 further. Regarding issue 1: Did adding `delayimp.lib` do both, fix the compiler/linker errors as well as correctly add the delay load for Ninja generators such that your compiled DLLs correctly delay-load the CUDA third-party DLLs? Would be very helpful if you could check this using the dependencies of your DLLs. If it holds, fixing issue 1 and fully supporting Ninja is rather straightforward.

**Comment by mbechard** [comment]
I can confirm that on the binaries made using ninja the npp*.dll files are delay-loaded, while cudart*.dll is not.

I do wonder if cudart* should also be delay-loaded though. The npp binaries ship with beside cudart, so I wouldn't expect cudart* to always be present but npp* to be optional, necessarily.

**Comment by mbechard** [comment]
I'll also mention for future proofing, I think nvcuda.dll should also be added to the delayloads. This file is installed by the driver in the system folder. I'm not entirely sure what action causes a binary to also link with that, but I know in my case I end up with some of my binaries becoming dependent on it. Likely something to do with the nvcc compile flags.

**Comment by CSBVision** [comment]
Alright, we just created PR #23209 that supports delay-loading for Ninja generators as well as fixes the delay load for Python and the exe files.

The CUDA runtime library (cudartXX_XX.dll) is always mandatory if CUDA was enabled at compile time, thus it's not delay-loaded. You can either distribute only this DLL along with OpenCV or use the static CUDA runtime instead by using the `CUDA_USE_STATIC_CUDA_RUNTIME` CMake flag. However, the current runtime DLL is only about 500 kb while using the static runtime instead increases the size of all CUDA-dependent DLLs by the same amount. Hence, using the static runtime seems not to be a real advantage (i.e. needs more space).

Regarding the nvcuda.dll issue: That's a really good point, the DLLs seems to be present in the system directory from the driver. However, installing CUDA on a non-CUDA PC - which is possible and makes sense to compile libraries like OpenCV with CUDA support - will not install this DLL and compiling OpenCV with CUDA support is possible without nvcuda.dll being present on the machine. We suspect that this DLL can at most be an indirect dependency of OpenCV, i..e it is required by one of the CUDA DLLs. So as long as these are delay-loaded, the nvcuda.dll should not cause any trouble. As it is not required while compiling OpenCV with CUDA support, we think it should not be contained in the linker flags. Still, if this changes at some time in the future, it's a minor issue to add it to the delay load flags.

Thus, delay loading of OpenCV CUDA modules remains to be solved. It is generally possible to add it as well, however our proposal is to introduce an additional delay load CMake variable that adds delay load for all OpenCV modules expect opencv_core and opencv_world. This allows to make all dependencies except the most relevant ones optional and allows to resolve them by distributing all OpenCV modules according to the actual runtime requirements. In particular, all CUDA modules will be delay loaded (i.e. ignored if unused) by the Python bindings. What other the opinions regarding this proposal?

**Comment by mbechard** [comment]
Ok sounds good with cudart*.

For nvcuda.dll, I'm not sure what compile setting causes it to happen, but in my own non-OpenCV dlls, I do have cases where they have a direct dependency on nvcuda.dll. I only mention it incase at some point in the future a CUDA kernel/compile setting changes in OpenCV that causes one of the OpenCV CUDA .dlls to have a direct dependency on nvcuda.dll. This would cause an issue later on, but could be addressed at that time.

Sounds good making everything delay-loaded. I think that would be quite helpful in general.

**Comment by CSBVision** [comment]
The issue with the nvcuda.dll still sounds interesting. In case you find out how this dependency is introduced, it's definitely worth analyzing whether this can also introduce a dependency for OpenCV. If this holds, it's still relatively easy to add this DLL (or in general, any other CUDA DLL outside of the CUDA installation path) to the delay load list: Only the `DELAYFLAGS` variable inside in `OpenCVDetectCUDA.cmake` has to be extended accordingly.

Delay-loading of all OpenCV modules is relatively easy, we only need to clarify in which CMake script this should be implemented. Maybe somebody who knows the code structure in a bit more detail could clarify this, implementing is straightforward.

**Comment by mbechard** [comment]
I can confirm what can cause a direct dependency on nvcuda.dll is the use of the Driver-API. cuInit() or cuCtxGetCurrent(), for example. If we think there is ever a chance someone will use the Driver-API in the CUDA modules, then it may make sense to include this as a delay-load. It doesn't do harm if it's listed and not yet needed.

**Comment by CSBVision** [comment]
Thanks for this information. Clearly, if this direct dependency is introduced, it should be added to the delay load list. However, this means that compiling the CUDA modules will only be possible on machines with CUDA hardware at compile time as otherwise the drivers wouldn't be installed at all. Don't know whether it is a good idea to add the DLL to the delay load flags... maybe some of the repository owners can share their thoughts about that.

**Comment by mbechard** [comment]
You can compile applications that have this dependency without CUDA available on the system. The .dll does not need to exist to link or for DELAYLOAD to be functional.

**Comment by CSBVision** [comment]
Yes correct, but if you have an explicit dependency to the DLL such that delay loading can be used (i.e. not loading the library explicitly by using any `LoadLibrary` function), you need the respective import library at compile/link time of your binary. Usually, this should be something like nvcuda.lib in this particular case, but we didn't find that lib file - maybe it's named differently?
Before, we implicitly assumed that the import lib is available if and only if the nvcuda.dll is. Even though we don't know whether this is true as the actual import lib is unknown...

**Comment by mbechard** [comment]
It seems like the cuda.lib that comes with the SDK is the import library that matches up with nvcuda.dll.

**Comment by CSBVision** [comment]
Yes, you are correct: `cuda.lib` yields a dependency to `nvcuda.dll` and similarly `nvml.lib` yields a dependency to `nvml.dll`. Thus, we think that both DLLs should be added to the delay load list (even though they might not be used at all) and just updated the PR accordingly.

**Comment by CSBVision** [comment]
As this issue was closed by merging the PR, we just created a new issue on whether the delay load option for all modules should be available or not.
