### ISSUE TITLE
Colud we use USAC with PNP?

### ISSUE THREAD

**Issue by TwiceMao** [opencv/opencv#23229]
### Descripe the feature and motivation

Because using RANSAC with PNP shows bad effects.

**Comment by scott-vsi** [comment]
I believe the answer to this is yes; however, then you cannot use the PnP [method](https://docs.opencv.org/4.x/d5/d1f/calib3d_solvePnP.html#calib3d_solvePnP_flags) of your choice.

The [documentation](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga50620f0e26e02caa2e9adc07b5fbf24e) should be improved. It says "flags: Method for solving a PnP problem (see solvePnP )." These are methods like cv.SOLVEPNP_ITERATIVE, etc. [link](https://docs.opencv.org/4.x/d5/d1f/calib3d_solvePnP.html#calib3d_solvePnP_flags). However, if we look at the code, we can see they test for the `USAC_*` flags, which then calls into usac and then returns:

https://github.com/opencv/opencv/blob/b0dc474160e389b9c9045da5db49d03ae17c6a6b/modules/calib3d/src/solvepnp.cpp#L224-L227

I believe this "[tutorial](https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/usac.markdown?plain=1#L161-L170)" explains what happens when solvePnPRansac is called with a `USAC_*` flag: "Perspective-n-Point – the minimal solver is classical 3 points with up to 4 solutions. For RANSAC the low number of sample size [sic] plays significant role as it requires less iterations..." (This tutorial can also be found on docs.opencv.org [here](https://docs.opencv.org/4.x/d0/d74/md__build_4_x-contrib_docs-lin64_opencv_doc_tutorials_calib3d_usac.html) (§ 8. Solver)).

So you can either choose to use usac::solvePnPRansac with a specific USAC ransac method (e.g., USAC_MAGSAC, USAC_ACCURATE, etc.) or use the older ransac and choose the PnP method.
