### ISSUE TITLE
Initializer with name Constant_117 not found in function 'getInputInitializerId'

### ISSUE THREAD

**Issue by NeoDhirendra** [opencv/opencv#23295]
### System Information

opencv version 4.7.0-dev
operation system ubuntu 20.04
python 3.8.10

### Detailed description

i am trying to read the paddle onnx model using cv.dnn.readnet() function , but it is throwing error. but the onnx model works fine with onnxruntime. 

``` cv2.error: OpenCV(4.7.0-dev) /home/neoastra/opencv/modules/dnn/src/onnx/onnx_graph_simplifier.cpp:85: error: (-212:Parsing error) Initializer with name Constant_119 not found in function 'getInputInitializerId' ```

### Steps to reproduce

install ppocr from paddleocr github repo.
export the recognition model into onnx format using paddle2onnx.

then use open.dnn.readnet(rec_model.onnx) you will get the error

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by fengyuentau** [comment]
Could you upload the model somewhere for me to take a look into the problem?

**Comment by NeoDhirendra** [comment]
> Could you upload the model somewhere for me to take a look into the problem?

here the google drive link of that model.

https://drive.google.com/file/d/1jocoPRtgWjZsevqtDAbdahelteagNcj6/view?usp=sharing

**Comment by NeoDhirendra** [comment]
> Could you upload the model somewhere for me to take a look into the problem?
here is the link of onnx model

https://drive.google.com/file/d/1rOGML5ljzvbI2ht1nLb9mGR0Y-2AvUhE/view?usp=sharing

**Comment by fengyuentau** [comment]
There is something wrong with the ONNX simplification process in OpenCV DNN. I will submit a patch to fix the issue.

However, even if it is fixed, the model still does not work with OpenCV DNN since it has dynamic input shape (dynamic height and width), which is not supported yet. I would suggest to simplify this model with a fixed input shape before hand using https://github.com/daquexian/onnx-simplifier.

**Comment by fengyuentau** [comment]
There is something wrong with the ONNX simplification process in OpenCV DNN. I will submit a patch to fix the issue.

However, even if it is fixed, the model still does not work with OpenCV DNN since it has dynamic input shape (dynamic height and width), which is not supported yet. I would suggest to simplify this model with a fixed input shape before hand using https://github.com/daquexian/onnx-simplifier.

**Comment by NeoDhirendra** [comment]
yea okay i will change the onnx model dynamic shape to static , then i will try again to read the model using opencv dnn.
