### ISSUE TITLE
Invalid Depth order causing assertion to fail

### ISSUE THREAD

**Issue by LeonardoPohl** [opencv/opencv#23302]
### System Information

OpenCV version: 4.5.0
Operating System / Platform: Windows 10
Compiler & compiler version: GCC 9.3.0

### Detailed description

When trying to save a matrix that has the depth CV_16F using cv::FileStorage the assertion `depth >=0 && depth <= CV_64F in function 'cv::fs::typeSymbol'` fails.

---

A possible explanation of the error might be found in `opencv2/core/hal/interface.h`. The order of the different depth definitions is incorrect and therefore the assertion fails:

```cpp
#define CV_8U   0
#define CV_8S   1
#define CV_16U  2
#define CV_16S  3
#define CV_32S  4
#define CV_32F  5
#define CV_64F  6
#define CV_16F  7
```

Therefore `CV_64F <= CV_16F` and if `CV_16F = depth` then `depth <= CV_64F` is `false` and the assertion failed. I did not manage to update opencv to 4.7.0 using vcpkg and therefore I could not verify if the issue still persists beyond 4.5.0.

### Steps to reproduce

```cpp
cv::Mat test = cv::Mat::zeros({100, 100}, CV_16F);
cv::FileStorage file("test.yml", cv::FileStorage::WRITE);
file.write("Test Mat", test);
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by Kumataro** [comment]
Hi, I think this issue is duplicated with  https://github.com/opencv/opencv/issues/20279

Version 4.5.0
---------------

https://github.com/opencv/opencv/blob/d5fd2f0155ffad366f9ac912dfd6d189a7a6a98e/modules/core/src/persistence.cpp#L143-L148

Version 4.5.3
--------------

https://github.com/opencv/opencv/blob/ad6e82942b37be8ee2c71c1d9bc7fe79cd16f7ab/modules/core/src/persistence.cpp#L143-L148


Version 4.7.0
---------------
https://github.com/opencv/opencv/blob/725e440d278aca07d35a5e8963ef990572b07316/modules/core/src/persistence.cpp#L147-L152

**Comment by LeonardoPohl** [comment]
Yes true thanks.
