### ISSUE TITLE
Unable to call LMSolver in python.

### ISSUE THREAD

**Issue by xiaomianzhou** [opencv/opencv#23505]
### Descripe the feature and motivation

I want to solve a Levenberg-Marquardt problem with LMSolver or CvLevMarq in OpenCV.
But I find I can't call LMSolver or CvLevMarq with Python.
Are these two interfaces not available in Python?

**Comment by xiaomianzhou** [comment]
I'm using opencv-contrib-python 4.7.0.72.

**Comment by opencv-alalek** [comment]
There are no bindings for `LMSolver`.
No plans to expose it due to heavy usage of C++ callbacks. Automatic wrapping doesn't work (and there is missing support for `noArray()`. Feature requires manual code for each language with proper memory / callbacks management. Also efficiency (speed) is questionable for that solution.
I believe current priority is "low" for that feature.

**Comment by xiaomianzhou** [comment]
Thank you for your answer, I will try other implementations that are not based on opencv-python.
