### ISSUE TITLE
error in 'Emgu.CV.OCR.OcrInvoke'

### ISSUE THREAD

**Issue by moraya77** [opencv/opencv#23551]
### System Information

windows server 2008 r2
OpenRPA latest version

### Detailed description

Hello, i use the open source application OpenRPA and i´m trying to do an automation with "get text", every time i run the code to get text the application crashs and says the error " The type initializer for 'Emgu.CV.OCR.OcrInvoke' threw an exception'", and i have no idea of how to solve it
in the application folder i found only 2 EMGU files: "EMGU.CV.UI.dll" and "EMGU.CV.WORLD.dll"
the log is attached.
[logfile.txt](https://github.com/opencv/opencv/files/11333416/logfile.txt)

### Steps to reproduce

inicialize open RPA->create a workflow with get text->run that workflow

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by berak** [comment]
@moraya77 
long story short -- you're asking in the wrong place (please close this issue, asap)
you probably came here, because openrpa github  did not enable issues, and emgu's forum is down since years 
(see all those red flags ?)

again, opencv does not maintain any of those 3rd party efforts.
maybe, https://github.com/emgucv/emgucv/discussions is a better place to ask ?

**Comment by mshabunin** [comment]
This is not correct repository for this issue, take a look at the following projects:
* https://github.com/open-rpa/openrpa
* https://github.com/emgucv/emgucv
