### ISSUE TITLE
Type stubs: `Optional` parameters incorrectly marked as not-None in `cv2.calcHist` and `cv2.resize`

### ISSUE THREAD

**Issue by Avasam** [opencv/opencv#23779]
### System Information

OpenCV python: opencv_python_headless-4.7.0+772599a-cp37-abi3-win_amd64.whl
Operating System / Platform: 10.0.19045 Build 19045
Python version: 3.9.13

### Detailed description

`cv2.calcHist`: the `mask` parameter should accept `None`
`cv2.resize`: the `dsize` parameter should accept `None`

### Steps to reproduce

```py
import cv2

image = cv2.imread("some_path", cv2.IMREAD_UNCHANGED)

# Argument of type "None" cannot be assigned to parameter "dsize" of type "Size" in function "resize"
#  Type "None" cannot be assigned to type "Size"PylancereportGeneralTypeIssues
cv2.resize(image, dsize=None)

# Argument of type "None" cannot be assigned to parameter "mask" of type "UMat" in function "calcHist"
#  Type "None" cannot be assigned to type "UMat"PylancereportGeneralTypeIssues
cv2.calcHist([image], [0, 1, 2], None, [8, 8, 8], [0, 256, 0, 256, 0, 256])
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by VadimLevin** [comment]
Thanks for checking stubs.
It is not possible to automatically handle such cases having only function interfaces from C++:

Interface
```cxx
cv::resize(cv::InputArray src, cv::OutputArray dst, cv::Size dsize,
           double fx = 0.0, double fy = 0.0, int interpolation);
```
From the API point of view `dsize` is not optional at all - it is required argument. 
Passing either empty `dsize` and `fx`/`fy` or non-empty `dsize` is a poor definition of overload set for this function.
Proper way to handle mutually exclusive arguments should be:
```cxx
cv::resize(cv::InputArray src, cv::OutputArray dst, double fx, double fy = 0.0, int interpolation) {
    cv::resize(src, dst, cv::Size{std::round(fx * src.cols()), std::round(fy * src.rows())},
               interpolation);
}

cv::resize(cv::InputArray src, cv::OutputArray dst, cv::Size dsize, int interpolation) {
 // Actual function implementation
}
```
There are other functions too (e.g. you've mentioned `cv::calcHist`) having "conventions" stated in their documentation rather than expressed in API.
All of them should be handled explicitly during typing stubs generation procedure:
- Create a list of such functions
- When all symbols are collected and just before types resolution:
  - Step through the list and manually add required overloads.
- Act as usual

The solution is quite fragile and requires manual handling, but I think it is only one solution that won't break C++ API for such cases.
