### ISSUE TITLE
Python type stubs: `__all__` and `__version__` dunders are missing

### ISSUE THREAD

**Issue by Avasam** [opencv/opencv#23950]
### System Information

OpenCV python: opencv-python-headless==4.8.0.74
Operating System / Platform: 10.0.19045 Build 19045
Python version: 3.9.13

### Detailed description

`cv2.__all__` and `cv2.__version__` are missing from the stubs.

`cv2.__version__` is useful for compatibility checks.
`cv2.__all__` is *important* for type checkers to know which symbols are.

Without `__all__` specified:
![image](https://github.com/opencv/opencv/assets/1350584/b4554180-5e88-4955-86e5-8704a2d17fa8)

With `__all__ = []` specified:
![image](https://github.com/opencv/opencv/assets/1350584/abab2789-9072-4f05-9b0a-f3dd75d83267)

Runtime:
```py
>>> from cv2 import *
>>> SORT_EVERY_ROW
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SORT_EVERY_ROW' is not defined
```

### Steps to reproduce

```py
>>> import cv2
>>> [x for x in dir(cv2) if x.startswith("__") and x.endswith("__")]
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__']
```

```py
import cv2
cv2.__all__  # "__all__" is not a known member of module "cv2"
cv2.__builtins__
cv2.__cached__
cv2.__doc__
cv2.__file__
cv2.__loader__
cv2.__name__
cv2.__package__
cv2.__path__
cv2.__spec__
cv2.__version__  # "__version__" is not a known member of module "cv2"
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by VadimLevin** [comment]
OpenCV `__all__` is hardcoded to be empty ([`__init__.py`](https://github.com/opencv/opencv/blob/fdc0c12b7fff00e1b41f75e11401073eee23b7e7/modules/python/package/cv2/__init__.py#L8C13-L8C13))

```python
>>> import cv2
>>> cv2.__all__
[]
```

and to satisfy current implementation it is enough to add the following lines to `__init__.pyi`:

```python
__all__ : list[str] = []
__version__: str = ...
```

Otherwise, there should be done 2 steps:
- Populate empty `__all__` in  [`bootstrap` function](https://github.com/opencv/opencv/blob/fdc0c12b7fff00e1b41f75e11401073eee23b7e7/modules/python/package/cv2/__init__.py#L68C5-L68C14).
- Add `__all__` typing stubs generation logic.

It is a bit tricky, because apart from the scan for symbols in runtime, we should somehow handle Python functions defined in `__init__.py` of several modules ([example](https://github.com/opencv/opencv/blob/4.x/modules/gapi/misc/python/package/gapi/__init__.py)). I don't think that the last one is possible...

**Comment by Avasam** [comment]
Personally I'm fine having it directly.
If a two-step generation is really needed later it can be reconsidered as a different stub generation feature.
