### ISSUE TITLE
Migrate to FindCUDAToolkit.cmake 

### ISSUE THREAD

**Issue by SomeoneSerge** [opencv/opencv#24034]
### Describe the feature and motivation

NVIDIA considers FindCUDA.cmake (`find_package(CUDA)`) deprecated: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#importing-tarballs-into-cmake. The common approach to consume cudatoolkit today is to use FindCUDAToolkit.cmake (`find_package(CUDAToolkit COMPONENTS cudart cublas ...)`).

Aside from FindCUDA being obsolete, there are notable differences between the modules: e.g. FindCUDAToolkit.cmake allows its CUDAToolkit_ROOT variable to take the form of a list of paths, and this way it supports splayed installations of cudatoolkit, where different components (cudart, cublas, ...) may reside in different prefixes (as is the case e.g. in [nixpkgs](https://github.com/NixOS/nixpkgs/))

Other big sci-comp projects are also moving away from FindCUDA, e.g. https://github.com/pytorch/pytorch/issues/76082

Thanks!

**Comment by cudawarped** [comment]
I think because OpenCV used `FindCUDA` for both genrating the build files for CUDA code and accessing the CUDA Toolkit it would be difficult to just use `FindCUDAToolkit` without enabling CUDA as a first class language.

In https://github.com/opencv/opencv/pull/23021 and https://github.com/opencv/opencv_contrib/pull/3400 I started the process of moving to CUDA as a first class language which includes using `FindCUDAToolkit`.

It would be great if you could check if this works for you and if `CUDAToolkit_ROOT` can except a list of paths when passed to OpenCV.
