### ISSUE TITLE
Inconsistency when using OpenCL

### ISSUE THREAD

**Issue by bgallois** [opencv/opencv#24077]
### System Information

OpenCV version: 4.8.0 and latest master
Operating System / Platform: Arch Linux
Compiler & compiler version: gcc (GCC) 13.1.1 20230714

### Detailed description

Using the attached code for image translation led to two different results:

1. When not using OpenCL, the translation is correct.
2. However, when using `opencl-nvidia`, the translation degrades the image if the output and input are the same `UMat` in `warpAffine`. 
![registered_screenshot_29 07 2023](https://github.com/opencv/opencv/assets/23381534/f52eaddb-59b1-4ab3-add7-e3959aaac6bc)

### Steps to reproduce

```cpp
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>

using namespace cv;

int main() {
  UMat frame, out;
  imread("astro.jpg", IMREAD_GRAYSCALE).copyTo(frame);

  Mat H = (Mat_<float>(2, 3) << 1.0, 0.0, 20, 0.0, 1.0, 20);
  warpAffine(frame, frame, H, frame.size());

  imshow("frame", frame);

  // This will fix the problem:
  /*warpAffine(frame, out, H, frame.size());
  imshow("frame", out);*/
  waitKey();
}
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by LaurentBerger** [comment]
https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#ga0203d9ee5fcd28d40dbc4a1ea4451983
Applies an affine transformation to an image.

The function warpAffine transforms the source image using the specified matrix:

dst(x,y)=src(M11x+M12y+M13,M21x+M22y+M23)

when the flag [WARP_INVERSE_MAP](https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#gga5bb5a1fea74ea38e1a5445ca803ff121aa48be1c433186c4eae1ea86aa0ca75ba) is set. Otherwise, the transformation is first inverted with [invertAffineTransform](https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#ga57d3505a878a7e1a636645727ca08f51) and then put in the formula above instead of M. The function cannot operate in-place.

**Comment by bgallois** [comment]
Think, missed this bit in the doc. Strange that it works perfectly in place without OpenCL. I was convinced that each OpenCV function that does/does not support in-place was checking and throwing an error.
