### ISSUE TITLE
How to avoid blocking with cv2.VideoCapture.read()?

### ISSUE THREAD

**Issue by wuyong139** [opencv/opencv#24393]
### System Information

OpenCV python version: 4.3.0.36
Operating System / Platform: Ubuntu 18.04
Python version: 3.7.7

### Detailed description

while i closed the rtsp stream, the code will block at "ret, frame = cap.read()"; 
how to avoid blocking with cv2.VideoCapture.read()?

### Steps to reproduce

cap = cv2.VideoCapture("rtsp://......")
while True:
     ret, frame = cap.read()
     if not ret: break
     cv2.imshow("test", frame)
     cv2.waitKey(1)
cap.release()

while i closed the rtsp stream, the code will block at "ret, frame = cap.read()", without any information returned
how to avoid blocking with cv2.VideoCapture.read()?

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by dkurt** [comment]
Take a look at [VideoCapture::grab()](https://docs.opencv.org/5.x/d8/dfe/classcv_1_1VideoCapture.html#ae38c2a053d39d6b20c9c649e08ff0146)

**Comment by UltimateCodeWarrior** [comment]
cap = cv2.VideoCapture(rtsp_url)

Looks like cap.grab() cap.retrieve() blocks too?         

This has no effect either:
        cap.set(cv2.CAP_PROP_OPEN_TIMEOUT_MSEC, 5000)  # 5 seconds open timeout
        cap.set(cv2.CAP_PROP_READ_TIMEOUT_MSEC, 5000)  # 5 second read timeout

I don't get why we can't just do a cap.read(5000) and specify a 5-second timeout or something.    Blocking is the worst behavior for something like this.  

I mean right now it seems the ffmpeg tie in will wait 30 seconds, puke out a warning, wait another 30 seconds, puke out a warning, then another 30 seconds and finally fail.  So, if your camera /network reboots, your software is missing like 90 seconds of video.   Not great for a security camera setup.         It needs to constantly signal the user so that the main software can respond gracefully.

**Comment by ManuelZ** [comment]
The solution is here:
https://github.com/opencv/opencv/issues/23207#issuecomment-1731674914

I just tested it and it works, at least with the backend I tested, ffmpeg.
