### ISSUE TITLE
OpenCVConfig.cmake is not usable with static build

### ISSUE THREAD

**Issue by ilya-lavrenov** [opencv/opencv#24432]
### System Information

OpenCV version: 4.8.0
Operating System / Platform: Ubuntu 20.04
Compiler & compiler version: GCC 9.3.0

### Detailed description

I've build OpenVINO statically and then OpenCV with OpenVINO support - also statically.
Then I have installed OpenCV into `<build dir>/install` and I expect it works and OpenCVConfig.cmake transitively finds its dependencies.

But I see the errors:
```
$ cmake -DOpenCV_DIR=/mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/lib/cmake/opencv4 ../../../git_repo/opencv/samples/cpp/example_cmake/
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install (found version "4.8.0")
-- OpenCV library status:
--     config: /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/lib/cmake/opencv4
--     version: 4.8.0
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
--     include path: /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/include/opencv4
-- Configuring done (0.6s)
CMake Error at /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/lib/cmake/opencv4/OpenCVModules.cmake:105 (set_target_properties):
  The link interface of target "opencv_core" contains:

    Eigen3::Eigen

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/lib/cmake/opencv4/OpenCVConfig.cmake:133 (include)
  CMakeLists.txt:10 (find_package)

.........................

CMake Error at /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/lib/cmake/opencv4/OpenCVModules.cmake:266 (set_target_properties):
  The link interface of target "ocv.3rdparty.openvino" contains:

    openvino::runtime

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /mnt/data3_1878/ilya/Documents/Programming/build/opencv-release/install/lib/cmake/opencv4/OpenCVConfig.cmake:133 (include)
  CMakeLists.txt:10 (find_package)


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

In `OpenCVModules.cmake` I see the following alias target is defined:
```
# Create imported target ocv.3rdparty.openvino
add_library(ocv.3rdparty.openvino INTERFACE IMPORTED)

set_target_properties(ocv.3rdparty.openvino PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "INF_ENGINE_RELEASE=2023020000;HAVE_NGRAPH;HAVE_DNN_NGRAPH;HAVE_INF_ENGINE"
  INTERFACE_LINK_LIBRARIES "openvino::runtime"
)
```
But no `find_dependency(OpenVINO)` is used to define `openvino::runtime` target to that file.

Because of this issue, OpenVINO and OpenCV cannot be used in vcpkg package manager, when OpenVINO is used as a dependency for OpenCV, because OpenCV does not correctly reports about its dependencies
See https://github.com/microsoft/vcpkg/pull/33883 and logs for _x64_linux_ specifically.

### Steps to reproduce

cmake -DOpenCV_DIR=<build dir>/install/lib/cmake/opencv4 <opencv source dir>/samples/cpp/example_cmake/

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by mshabunin** [comment]
OpenCV only provides exports for own 3rdparty libraries in static builds. We can not reliably find other dependencies in this case because they can be detected in many different ways (cmake, pkg-config, manually), can rely on environment and can bring their own dependencies. This is responsibility of end-user to provide all 3rdparty libraries in static builds.

Usually package managers (vcpkg, conan) provide all required dependencies automatically using features mechanism and relying on dependencies from same ecosystem. For example: https://github.com/conan-io/conan-center-index/blob/master/recipes/opencv/4.x/conanfile.py

**Comment by sergiud** [comment]
To complete your example, it is up to CMake to resolve the actual version of TBB. Therefore, calling `find_package` multiple times is not an issue if that's what you are implying.

> This is responsibility of end-user to provide all 3rdparty libraries in static builds.

That's fine. However, it is still the responsibility of the library to locate its dependencies because users cannot and, in fact, do not need to know which dependencies are necessary. Also, just because there are multiple ways to locate dependencies, it does not mean the user is responsible for this as well. vcpkg, conan, and other package manager are irrelevant because these are  wrappers around available CMake integration that should be self contained and work out of the box.

To provide a counter example, take the missing `Eigen3::Eigen` target definition from OP's problem description. There's exactly one correct way to locate it which is the `find_package`/`find_dependency` mechanism. You also need an exact version of the Eigen library that was used to compile OpenCV to avoid ODR violations or other problems that may stem from a version mismatch. This information is clearly not something that must be tracked by the user but rather by OpenCV.

**Comment by mshabunin** [comment]
If user has an application which requires static libraries `foo` and `bar`, but `fooConfig.cmake` has `find_package(TBB 2022.1 EXACT)` and `barConfig.cmake` has `find_package(TBB 2023.4 EXACT)`, then one of these dependencies will not be found or this app will be linked with two different TBB libraries. This is package management or dependency resolution problem: finding a list of package versions which satisfies a set of requirements.

What I tried to say is that in most cases a library also can not locate its dependencies even if it knows them, because user's environment might differ from the one in which the library has been built: compiler version and flags, _dev_-packages installed, `<lib>_DIR` and other cmake-related environment variables, `PKG_CONFIG_PATH` variable. Even small discrepancy might cause serious issues which would require even more effort and expertise to debug (like stack corruptions).

Fully-automatic dependency resolution might be possible if all components would have the same build/export format: pkg-config, cmake, meson(?), ... But this is not the case with OpenCV, so I can only recommend the following for static build users:
* use package manager if possible
* build OpenCV with minimal external dependencies (use built-in 3rdparty libraries if possible)
* use single stable environment for the whole build (all libraries and application)

**Comment by opencv-alalek** [comment]
> OpenCVConfig.cmake is not usable with static build

from the **installation** directory (as installation process doesn't manage dependencies - CMake is not a package manager).

Using the `build` directory of static build on the same machine should work (e.g. FFmpeg Windows wrapper, Python standalone bindings).
