### ISSUE TITLE
Decode GPU frame when really needed in cv::cudacodec::createVideoReader

### ISSUE THREAD

**Issue by robosina** [opencv/opencv#24442]
### Describe the feature and motivation

OpenCV version: 4.8.0

I'm working with the `cv::cudacodec::createVideoReader` class for a multi-camera surveillance project. In the CPU implementation using [cv::VideoCapture](https://docs.opencv.org/4.8.0/d8/dfe/classcv_1_1VideoCapture.html), there are grab and retrieve functions, that grab fetches the latest buffer without processing it, and retrieve handles decoding when called.

> The primary use of the function is in multi-camera environments, especially when the cameras do not have hardware synchronization. That is, you call [VideoCapture::grab()](https://docs.opencv.org/4.8.0/d8/dfe/classcv_1_1VideoCapture.html#ae38c2a053d39d6b20c9c649e08ff0146) for each camera and after that call the slower method [VideoCapture::retrieve()](https://docs.opencv.org/4.8.0/d8/dfe/classcv_1_1VideoCapture.html#a9ac7f4b1cdfe624663478568486e6712) to decode and get frame from each camera.

 However, with `cv::cudacodec::createVideoReader`, it seems that grab and retrieve function differently compared to the CPU version(And this is clearly mentioned in Document).
 
 > The primary use of the function is for reading both the encoded and decoded video data when rawMode is enabled.
 
  I'm bringing this up because in my setup with 15 streams, each stream is managed by a different thread. Simply by creating instances of `cv::cudacodec::createVideoReader` across 15 threads, I've noticed a 50% GPU utilization(**2080ti**), even without fetching any frames from `cv::cudacodec::createVideoReader`. So, is there a way to lower the GPU utilization when frames are not needed? I suspect some decoding might be happening behind the scenes. Is there a way to only decode when necessary(I mean decode only when retrieve called)?

```c++
      cv::cudacodec::VideoReaderInitParams params;
      if (_parseURL->_isRTSP) {
          params.allowFrameDrop = true;
          params.minNumDecodeSurfaces = 1;
      }
      params.rawMode = true;
      cudaReader = cv::cudacodec::createVideoReader(url, {}, params);
```

**Comment by asmorkalov** [comment]
h264, h265 and such are stateful codecs. it means that current frame decoding depends on previous frames and some other stream state values. You cannot start decoding in any time you want, you have to wait key frame. So it's not OpenCV or CUDA codecs issue.

**Comment by robosina** [comment]
@asmorkalov Thanks for replying back. 

So, I might have misunderstood the CPU part, but as I understand, in the CPU version, you can have two threads where one is continuously grabbing, and the other retrieves only when needed. This way, CPU processing significantly drops thanks to lazy-decoding. 

> The method decodes and returns the just grabbed frame. If no frames has been grabbed

Is that right? Now, I'm curious if this can be done on the GPU side as well?

(_I utilized this mechanism with two threads - one for grabbing and the other for retrieving when needed. Empirically, I observed that this significantly reduces CPU usage._)

**Comment by cudawarped** [comment]
> I'm bringing this up because in my setup with 15 streams, each stream is managed by a different thread. Simply by creating instances of `cv::cudacodec::createVideoReader` across 15 threads, I've noticed a 50% GPU utilization(**2080ti**), even without fetching any frames from `cv::cudacodec::createVideoReader`.

This initialization issue is due to the way  `cv::cudacodec::createVideoReader` is implemented.  To saturate the decoder and get the most performance a background threads is used to constantly decode the next available frame until the maximum number of decode surfaces ([ulNumDecodeSurfaces](https://docs.opencv.org/4.x/d8/db6/structcv_1_1cudacodec_1_1FormatInfo.html#a06ededd840266d9658d65f59bfdb949d)) have been filled  .  If your interested you can read the [Nvidia Video Coding SDK ](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/nvdec-video-decoder-api-prog-guide/index.html#writing-an-efficient-decode-application)docs for more information.  This causes the 50% GPU usage on initialization but it should drop to zero if you don't read any frames.

Does your GPU have 50% utilization or just the dedicated hardware decoding unit?  Is this important because you want to decode more streams on a single GPU or you want to use the GPU for something else at the same time (e.g. inference)?

> So, I might have misunderstood the CPU part, but as I understand, in the CPU version, you can have two threads where one is continuously grabbing, and the other retrieves only when needed. This way, CPU processing significantly drops thanks to lazy-decoding.

As @asmorkalov said this isn't possible as the key frame have to be decoded before the following frames.  If your video only has key frames then this would be possible but I am pretty sure that using and `grab()`/`retrieve()` combination would still decode every frame as that is how it is designed.

> (_I utilized this mechanism with two threads - one for grabbing and the other for retrieving when needed. Empirically, I observed that this significantly reduces CPU usage._)

I would guess that the utilization is lower due to less memory copies and CPU synchronization but I can't be 100% sure without checking myself.

**Comment by robosina** [comment]
@cudawarped Thanks, By this logic, I think that the reason for the below behavior:

> This causes the 50% GPU usage on initialization but it should drop to zero if you don't read any frames.

is that in the previous code, I'm using `params.allowFrameDrop` to be able to drop the frames:

```c++
params.allowFrameDrop = true;
```

And I think this will eagerly read all frames from the camera and the gpu usage will be 50% all the time even if I don't call to the `cudaReader->nextFrame(frame)`. Setting aside lazy-decoding, as it's required due to the main-frame you mentioned, from the steps in the [provided link](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/nvdec-video-decoder-api-prog-guide/index.html#video-decoder-pipeline), which one do you think is causing about 50% of the GPU utilization? Just to clarify, both the decoding hardware of the GPU and the GPU utilization are near 50%. Additionally, can we obtain the YUV format from the class, then convert it to RGB to lessen the GPU utilization?

**Comment by cudawarped** [comment]
> is that in the previous code, I'm using `params.allowFrameDrop` to be able to drop the frames:

Sorry I missed that in your previous post.  `params.allowFrameDrop` is a convenience I introduced to aid in development/prototyping when reading from a live source.  It enables the frames to be dropped automatically so you don't get disconnected if consuming frames at a slower rate than they are produced.  This is useful when debugging or before you have optimized your processing pipeline because it means you don't need to introduce an extra thread and synchronization logic while you are still at an exploratory phase of your development.  In production I would not recommend using this approach because you don't have any control over which frames are dropped or any information indicating that a drop has occurred.

I assume this is why you are using this flag and you have had disconnection problems without it?

> which one do you think is causing about 50% of the GPU utilization?

The `params.allowFrameDrop` flag is causing this.  Your GPU is constantly decoding so that you can always get a decoded frame without artifacts at the same time as preventing disconnection from the source.


> Just to clarify, both the decoding hardware of the GPU and the GPU utilization are near 50%. 

If CUDA is also at 50% it could be that the clock speed has been lowered due to low demand.  Which OS are you on?  Try increasing the number of threads to 30 to see what the impact on decoding and CUDA utilization are.

> Additionally, can we obtain the YUV format from the class, then convert it to RGB to lessen the GPU utilization?

You can obtain an NV12 frame (see the [accuracy tests](https://github.com/opencv/opencv_contrib/blob/5b95c334d7c78778de48948644458bfb8adbb7f7/modules/cudacodec/test/test_video.cpp#L305) for details) which should lower the processing slightly but again I would not expect 50% CUDA utilization on 15 threads unless your source is greater than 1080p?

**Comment by robosina** [comment]
> Sorry I missed that in your previous post. params.allowFrameDrop is a convenience I introduced to aid in development/prototyping when reading from a live source. It enables the frames to be dropped automatically so you don't get disconnected if consuming frames at a slower rate than they are produced. This is useful when debugging or before you have optimized your processing pipeline because it means you don't need to introduce an extra thread and synchronization logic while you are still at an exploratory phase of your development.

I understand now. In my scenario, it doesn't serve a beneficial purpose as I have another thread addressing this issue. I utilize this thread to access the latest data at all times, which almost same as your implementation of dropping frames, especially since I have inference integrated in my codes, which might cause issue if we don't empty out the buffers.

---

> I assume this is why you are using this flag and you have had disconnection problems 

Honestly, I had thought that perhaps this flag would automate the same actions based on my previous understanding of grab/retrieve. I removed it and now everything seems better from a GPU utilization perspective, with it being around 20%. However, I believe adding CV_LOG_WARNING here wouldn't cause any harm.

---

>  Which OS are you on?

I'm using windows OS(w10).

> Try increasing the number of threads to 30 to see what the impact on decoding and CUDA utilization are.

I have 5 cameras and each camera is providing 3 streams (as they don't support more), totaling 15 concurrent streams at the moment. However, I will increase the frame rate to show you the results:


### 15 threads on 12 frames per second 1080p

![image](https://github.com/opencv/opencv/assets/14973524/c86fb7f1-89b7-4500-87c0-7c0bb0aacd59)

## 15 thread on 20fps

![image](https://github.com/opencv/opencv/assets/14973524/cf87b33e-0c76-45f1-8adc-8aacd2733d59)

## 15 threads on 25fps

![image](https://github.com/opencv/opencv/assets/14973524/feff1a22-6e49-47f0-a492-ede4bed43b7c)

**Comment by cudawarped** [comment]
Can you change the toggle on Video Encode as you are not using it to CUDA to see the CUDA utilization as I suspect that is what is important to you if you are performing inference.

**Comment by robosina** [comment]
The CUDA utilization is displayed at the bottom of the previous images, and while I couldn't find a graph for GPU utilization(there isn't any option for that), I created a plot using data from `nvidia-smi` as shown below:

```python
import subprocess
import matplotlib.pyplot as plt

# Initialize lists to store data
gpu_utilization = []

# Set up the plot
plt.ion()  # Turn on interactive mode
fig, ax = plt.subplots()

while True:
    # Run the nvidia-smi command and get the output
    result = subprocess.run([r"nvidia-smi.exe",
                             '--query-gpu=utilization.gpu', '--format=csv', '-i', '0'],
                            stdout=subprocess.PIPE)
    output = result.stdout.decode('utf-8')
    utilization = int(output.strip().split("\r\n")[1].split()[0])

    # Update the data
    gpu_utilization.append(utilization)
    if len(gpu_utilization) > 100:
        gpu_utilization.pop(0) 

    # Update the plot
    ax.clear()
    ax.plot(gpu_utilization,'--o', label='GPU Utilization')
    ax.legend()
    ax.set_ylim([0, 100])
    ax.grid(True)  # Show grid lines
    plt.pause(0.5)

plt.ioff()
plt.show()
```

## 15 streams on 25fps

![image](https://github.com/opencv/opencv/assets/14973524/b93c7e20-be6f-4e36-a025-af99f0661bcf)

The discrepancy is odd; while Windows reports 60% GPU usage, nvidia-smi indicates a 20% GPU usage.

**Comment by cudawarped** [comment]
> The CUDA utilization is displayed at the bottom of the previous images, and while I couldn't find a graph for GPU utilization(there isn't any option for that), I created a plot using data from nvidia-smi as shown below:

I suspect you have [Hardware Accelerated GPU Sheduling](https://devblogs.microsoft.com/directx/hardware-accelerated-gpu-scheduling/) turned on.  Don't ask me why this can remove the CUDA option but it does.

>The discrepancy is odd; while Windows reports 60% GPU usage, nvidia-smi indicates a 20% GPU usage.

In windows that's known as a feature 😄!  My guess is that its some kind of weighted average, anyway if you turn off hardware accelerated GPU sheduling then you should be able to see the CUDA utilization in task manager.  I would hope while decoding it is pretty minimal meaning you don't have to worry the impact of decoding frames you are not using.  If it looks significant check that your GPU hasn't gone into low power mode as this always catches leading to unecessary panic.

**Comment by asmorkalov** [comment]
IMHO, there is nothing to do on OpenCV side. I propose to close the issue.
