### ISSUE TITLE
Unable to use Orbbec demo for Orbbec gemini2 to grab images

### ISSUE THREAD

**Issue by zhudisha** [opencv/opencv#24563]
### System Information

opencv-python version: 4.8.1.78
Operating System Ubuntu 22.04 (armv8, x86)
Python version: 3.11.5
Camera model: Orbbec Gemini2 (Error reporting), Orbbec Femto W

### Detailed description

When I connect my computer to Gemini2 and run the following code [https://github.com/opencv/opencv/blob/4.x/samples/python/videocapture_obsensor.py](url), it reports an error as follows

```
global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=3, req=-1072663263
[ WARN:0@5.225] global obsensor_stream_channel_v4l2.cpp:343 getXu ioctl error return: 110
Fail to grab data from the camera.
Fail to grab data from the camera....
```

When I switch Gemini2 to Femto W, the demo mentioned above can collect images normally. 
When I use the SDK provided by Orbbec, Gemini2 can also collect images normally.

### Steps to reproduce

```
import numpy as np
import cv2 as cv
import sys

def main():
    # Open Orbbec depth sensor
    orbbec_cap = cv.VideoCapture(0, cv.CAP_OBSENSOR)
    if orbbec_cap.isOpened() == False:
        sys.exit("Fail to open camera.")

    while True:
        # Grab data from the camera
        if orbbec_cap.grab():
            # RGB data
            ret_bgr, bgr_image = orbbec_cap.retrieve(None, cv.CAP_OBSENSOR_BGR_IMAGE)
            if ret_bgr:
                cv.imshow("BGR", bgr_image)

            # depth data
            ret_depth, depth_map = orbbec_cap.retrieve(None, cv.CAP_OBSENSOR_DEPTH_MAP)
            if ret_depth:
                color_depth_map = cv.normalize(depth_map, None, 0, 255, cv.NORM_MINMAX, cv.CV_8UC1)
                color_depth_map = cv.applyColorMap(color_depth_map, cv.COLORMAP_JET)
                cv.imshow("DEPTH", color_depth_map)
        else:
            print("Fail to grab data from the camera.")

        if cv.pollKey() >= 0:
            break

    orbbec_cap.release()


if __name__ == '__main__':
    main()
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by CODEWITHRIZA** [comment]
# Hi 
@zhudisha,

>The problem you're encountering with the Orbbec Gemini2 camera.

## Based on the error messages you've shared and the code snippet provided, it seems that the issue might be related to the camera initialization or its interaction with the OpenCV library.

# Here are a few steps that might help resolve the problem:

### 1. **Camera Initialization:** Ensure that the Gemini2 camera is correctly connected and recognized by your system. Sometimes, simply reconnecting the camera or checking the physical connections can resolve communication issues.

### 2. **Update OpenCV:** Although you've mentioned using OpenCV version 4.8.1.78, it might be beneficial to check for any recent updates or patches related to Orbbec cameras within the OpenCV library. Upgrading to the latest available version of OpenCV might contain fixes for compatibility issues with the Gemini2 camera.

### 3. **Check Camera Permissions:** On Ubuntu systems, sometimes camera access might be restricted due to permissions. Ensure that the user has proper permissions to access the camera device. You can check and adjust these permissions using system settings or by modifying the access controls.

### 4. **Driver or Firmware Updates:** Verify if there are any available updates for the camera drivers or firmware provided by Orbbec for the Gemini2 model. Installing the latest drivers or firmware updates might resolve any communication issues between the camera and OpenCV.

### 5. **Community Forums or Support:** Consider reaching out to the Orbbec community forums or their support channels. They might have specific insights or solutions for using the Gemini2 camera with OpenCV.

Please try these steps and let us know if any of them resolve the issue. If the problem persists or if you find an alternative solution, feel free to update this thread.

**Comment by WanliZhong** [comment]
@zhudisha Hi, thanks for reporting. As we tested before, this error may caused by your USB port or USB cable is not support USB 3.0 protocol. This error only occur on ubuntu, windows will not occur this error even use USB 2.0 protocol

**Comment by zhudisha** [comment]
I tried to replace the previously used data cable with the original one and confirmed it to be USB 3.0. The problem still exists.😥

> @zhudisha Hi, thanks for reporting. As we tested before, this error may caused by your USB port or USB cable is not support USB 3.0 protocol. This error only occur on ubuntu. Windows will not throw this error with USB 2.0 protocol.
> 
> This error will not only happen on Orbbec gemini2, but also on Realsense. So I proposed you to try other USB cable which support 3.0 protocol.

**Comment by WanliZhong** [comment]
@zhudisha Have you confirmed the usb port is support 3.0 protocol? Could you try to use Windows system to make sure the camera is work well?

**Comment by kaingwade** [comment]
> I tried to replace the previously used data cable with the original one and confirmed it to be USB 3.0. The problem still exists.😥

@zhudisha Does the smaller end of the cable connect to your computer while the bigger end connects to the camera? If it is like this, getting data from the camera fails, at least on Windows. And as @WanliZhong mentioned, is your USB port 3.0 too?

**Comment by zhudisha** [comment]
> @zhudisha Have you confirmed the usb port is support 3.0 protocol? Could you try to use Windows system to make sure the camera is work well?
> 
> Sorry for raising so many questions, I just wanted to rule out where the problem is.

I have changed many cables and they all support USB 3.0, but strangely enough, it was ultimately a C2C USB 3.2 cable that supports video output that solved the problem. Perhaps the problem was related to the bandwidth of the Type A interface on my development board.

**Comment by WanliZhong** [comment]
👍, maybe it's your usb port doesn't support 3.0 protocol, not the usb cable.
