### ISSUE TITLE
Segmentation fault (core dump) during run time while accessing floating point value from opencv Mat.

### ISSUE THREAD

**Issue by evertale888** [opencv/opencv#24579]
Im quite new with opencv. I try to plot a dense pointcloud from color & depth map from the data i collected from rgb-d camera. During the initial run of the program, it crash with segmentation fault (core dump). From manual testing & debugging from gdb, i find the error happen when i tried to access floating point value from opencv Mat ( float d = imDepth.ptr<float>(v)[u]; ) inside a nested for loop. Example as below:

for (int v = 0; v < imRGB.rows; v++)
    {
        for (int u = 0; u < imRGB.cols; u++)
        {
                float d = imDepth.ptr<float>(v)[u]; //####################//Get the depth value at (v,u)
        }
 }

I run this fine in ubuntu 20.04 before with opencv 4.2  but now having this issue in ubuntu 22.04. I have tried different openCV ver. 4.5.4 and 4.2. Still having same issue. Kindly, let me know if i can replace those ptr function if that is possible in case nothing can be done. Any help is appreciated.

**Comment by Kumataro** [comment]
This is only question, not issue. So I think it is better to ask at https://forum.opencv.org/ . 

1.  I guess `imRGB` (Image) and `imDepth`  (Depth) has difference width and height. Some RGB-D camera returns smaller depth image than color image. Please could you confirm it ? ( e.g.  RealSense D435 Max-Depth=1280x720@90fps, Max-Image=1920x1080@30fps. ) 
3.  Please could you use `at()` instead of `ptr()` ? Maybe OpenCV Library detects errors if it is wrong indexes.
https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#aa5d20fc86d41d59e4d71ae93daee9726

If your question is not cleared, please could you re-ask in forum.
(And it is better to share some information to reproduce your problem in other environment. )

**Comment by evertale888** [comment]
> This is only question, not issue. So I think it is better to ask at https://forum.opencv.org/ .
> 
> 1. I guess `imRGB` (Image) and `imDepth`  (Depth) has difference width and height. Some RGB-D camera returns smaller depth image than color image. Please could you confirm it ? ( e.g.  RealSense D435 Max-Depth=1280x720@90fps, Max-Image=1920x1080@30fps. )
> 2. Please could you use `at()` instead of `ptr()` ? Maybe OpenCV Library detects errors if it is wrong indexes.
>    https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#aa5d20fc86d41d59e4d71ae93daee9726
> 
> If your question is not cleared, please could you re-ask in forum. (And it is better to share some information to reproduce your problem in other environment. )

1. All images are already in 640x480. Downloaded from TUM.
2. at() also give same error. 

Its run ok on ubuntu 20.04 with opencv 4.2. Unfortunately, not in 22.04.

**Comment by Kumataro** [comment]
If your question is not cleared, please could you re-ask in forum.

**Comment by evertale888** [comment]
Yeah, still cannot solve it. Alright tq again.

> If your question is not cleared, please could you re-ask in forum.
