### ISSUE TITLE
FindChessboardCorners is consistently 0.5 pixels off in the x and y directions

### ISSUE THREAD

**Issue by thedigitalzorn** [opencv/opencv#24633]
### System Information

# System Information
OpenCV python version: 4.8.0.76
Operating System: Windows 10 Pro 
Python Version:  3.10.1

### Detailed description

I found a 800x800 calibration image of a 8x8 checkerboard. I ran cv.findChessboardCorners directly against the image. Because of the layout, I expected the detected corners to be multiples of 100. However, all of the values were off by 0.5 pixels in both directions. 

output of `print(corners)`
``` 
 [[ 99.50001 199.5    ]]
 [[199.5     199.5    ]]
 [[299.5     199.5    ]]
 [[399.5     199.5    ]]
 [[499.5     199.5    ]]
 [[599.5     199.5    ]]
 [[699.5     199.5    ]]
 [[ 99.49999 299.5    ]]
 [[199.5     299.5    ]]
 [[299.5     299.5    ]]
 [[399.5     299.5    ]]
 [[499.5     299.5    ]]
 [[599.5     299.5    ]]
 [[699.5     299.5    ]]
 [[ 99.50001 399.5    ]]
 [[199.5     399.5    ]]
 [[299.5     399.5    ]]
 [[399.5     399.5    ]]
 [[499.5     399.5    ]]
 [[599.5     399.5    ]]
 [[699.5     399.5    ]]
 [[ 99.49999 499.5    ]]
 [[199.5     499.5    ]]
 [[299.5     499.5    ]]
 [[399.5     499.5    ]]
 [[499.5     499.5    ]]
 [[599.5     499.5    ]]
 [[699.5     499.5    ]]
 [[ 99.50001 599.5    ]]
 [[199.5     599.5    ]]
 [[299.5     599.5    ]]
 [[399.5     599.5    ]]
 [[499.5     599.5    ]]
 [[599.5     599.5    ]]
 [[699.5     599.5    ]]
 [[ 99.49999 699.5    ]]
 [[199.5     699.5    ]]
 [[299.5     699.5    ]]
 [[399.5     699.5    ]]
 [[499.5     699.5    ]]
 [[599.5     699.5    ]]
 [[699.5     699.5    ]]]
```

### Steps to reproduce

To reproduce, run this code against the included image

```
import cv2 as cv

PATTERN = (7,7)
SCALE_FACTOR = 8

path = r'<path to image>\pattern.png'

img = cv.imread(path)
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
ret, corners = cv.findChessboardCorners(gray, PATTERN, None)

# If you want to test the cornerSubPix, just uncomment this
# cv.cornerSubPix mutates the corners variable, so you
# shouldn't need to change anything else
#if ret == True:
#    criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
#    cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)

# These corners should be multiples of 100
print(corners)

corners = corners * SCALE_FACTOR
img = cv.resize(img, (img.shape[0] * SCALE_FACTOR, img.shape[1] * SCALE_FACTOR), interpolation = cv.INTER_NEAREST) 
cv.drawChessboardCorners(img, PATTERN, corners, ret)
cv.imshow('corners.png', img)
cv.waitKey(0)
cv.destroyAllWindows()
```

![pattern](https://github.com/opencv/opencv/assets/36500157/8514c572-c971-459e-9406-77c7747188f3)

Note: `cv.cornerSubPixel` inherits this error.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by JStech** [comment]
I think the difference of 0.5 is correct. The image origin is at the [center of the top-left pixel](https://answers.opencv.org/question/87923/sub-pixel-coordinate-origin/), so the lines between pixels are not on integer coordinates, but halfway between.

**Comment by thedigitalzorn** [comment]
Thanks for responding. That would explain some of the behavior. 

Do you think `cv.drawChessboardCorners` is drawing in the wrong coordinates, then? Here is a screenshot, which you can replicate with the code included in the issue. 

Original position: ![original-position](https://github.com/opencv/opencv/assets/36500157/fdcb366f-84f5-4a54-8d7e-58b4ed6ed9fd)

Corners shifted by 0.5 pixels: 
![shifted_position](https://github.com/opencv/opencv/assets/36500157/c90cbe3d-5a42-4e0c-8ca4-66da3c0c51e2)

**Comment by JStech** [comment]
Hmm, good question. I saved the scaled-up image so I could zoom way in. It looks like the first corner is being drawn at the center of pixel (796, 796), where the top left pixel is (0, 0). 796 is 8*99.5, so that's correct. What's actually going on, I think, is that the transform from the original coordinate frame to the resized coordinate frame is not a pure scaling, but includes a translation as well.

You rescale by a factor of 8, with nearest interpolation. This means that each pixel just gets expanded to an 8x8 square. Think about just the (0, 0) pixel--the center of this pixel gets mapped to the center of the 8x8 square at the top left of the larger image. But OpenCV still defines the origin as the center of the top-left pixel. To translate the pixel coordinates, you actually need to multiply by 8 and also add 3.5. Try using `corners = corners * SCALING + SCALING/2 - 0.5`, and the corners will be drawn in the right place. (Well, almost right--it doesn't seem to actually use the subpixel precision, and the circle is centered a half pixel away from the actual corner. Not a terrible approximation.)

Another way to think about it is that the `resize` first translates the image down and right by a half pixel, does a pure scale transform, and then shifts up and left by a half pixel. So `x_new = (x_old + 0.5) * SCALING - 0.5`.

**Comment by thedigitalzorn** [comment]
I gotcha. That clarifies things. Thanks, @JStech!
