### ISSUE TITLE
Rename COLOR_BGR2RGB to SWAP_FIRST_AND_LAST_CHANNEL

### ISSUE THREAD

**Issue by Kaju-Bubanja** [opencv/opencv#24725]
### Describe the feature and motivation

Now that I know more about RGB, BGR and how opencv handles it, it is obvious to me that COLOR_BGR2RGB just swaps the channels, because it can't know if the underlying stored data was stored in BGR or RGB, it just assumes one and then converts RGB to BGR on read and write.

But when starting out with my journey into this topic I expected the image to be RGB when calling COLOR_BGR2RGB, similar to how when you pass English to a function which is called EN2DE you expect German. Now when you call EN2DE on some German text you still expect it to stay German, meaning the function should be idempotent, that is what a x2y function inherently represents.

Because this is not possible with BGR2RGB I propose to rename the function to SWAP_FIRST_AND_LAST_CHANNEL, this while maybe a bit verbose, will make it even to the novice clear, that he has to look into the topic and figure out how his data is stored and that they can't just expect the COLOR_BGR2RGB to give them what they want. Because it can't.

### Additional context

This has bitten me when training some machine learning model, where this kind of channel order does matter

**Comment by dkurt** [comment]
This discussion does not make sense because there are dozens of other flags relied on the color space names: https://docs.opencv.org/5.x/d8/d01/group__imgproc__color__conversions.html#ga4e0972be5de079fed4e3a10e24ef5ef0. So named color components and their order are significant.

Please help us reduce the number of opened issues instead:
https://github.com/opencv/opencv/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
https://github.com/opencv/opencv/issues?q=is%3Aopen+is%3Aissue+label%3A%22community+help+requested%22

**Comment by Kaju-Bubanja** [comment]
This doesn't really seem like good reasoning. I propose a clear improvement to an existing problem and your answer is just it will take work? Yeah I know it will, but that doesn't mean the direction is wrong. I didn't say it needs to happen soon, but I think it does make sense to make the names of things clearer, names do matter.

Do I see this right that the only current rational for not doing this is that other code uses this constant?
