### ISSUE TITLE
[CMAKE] CUDA virtual architectures support ?

### ISSUE THREAD

**Issue by chacha21** [opencv/opencv#24739]
When building OpenCV with CMake and CUDA support, the architectures options are defined through CUDA_ARCH_BIN and CUDA_ARCH_PTX
However, CMake (>= 3.8) also supports CUDA_ARCHITECTURES which can be used to map to the virtual architectures of nvcc "all" (CMake 3.23+), "all-major" (CMake 3.23+) and "native" (CMake  3.24+)
(I can't find when it was introduced in nvcc [https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html) )

When setting "all-major" in CUDA_ARCH_BIN, OpenCV will compile cuda code... but it is unclear if it is really using that feature or if it defaults to something.

What is the current status of CMake's CUDA_ARCHITECTURES support in OpenCV's CMakefile ?

**Comment by cudawarped** [comment]
Currently OpenCV does not use `CUDA_ARCHITECTURES` (I am almost 100% sure this requires CUDA to be a first class language). Instead it can do one of four things, build for
1) all architechtures supported by the installed version of CUDA toolkit (almost equivelent to _all_) if `CUDA_ARCH_BIN` and `CUDA_ARCH_PTX` are not specified, or
2) architectures specified by combinations of `CUDA_ARCH_BIN` and `CUDA_ARCH_PTX`, or
2) a specific generation, e.g. `CUDA_GENERATION=Lovelace`, or
4) the architechtures of the hosts GPUs if `CUDA_GENERATION=Auto` (equivelent to _native_).

If CUDA is a added as a first class language (https://github.com/opencv/opencv/pull/23021) these options could be supported however they would not enable the verbose output of the gpu and ptx architectures, e.g.

> --     NVIDIA GPU arch:             50 52 60 61 70 75 80 86 89 90
> --     NVIDIA PTX archs:            90

That's why in https://github.com/opencv/opencv/pull/23021 to limit the number of changes I chose to support `CUDA_ARCHITECTURES`  if they are explicitely set but not the special values, see
https://github.com/opencv/opencv/blob/64066c537fd98b283d85970bc50214c35191184d/cmake/OpenCVDetectCUDAUtils.cmake#L61

_all_ and _all-major_ could be supported aswell with the output being
> --     NVIDIA GPU arch:             all
> --     NVIDIA PTX archs:            all

but I'm not sure if this is really necessary.  In theory for maximum compatiblity they make sense but in practice most new users really just want __Auto__ and once they are familiar with CUDA they probably want to manually specify the real and virtual architectures to satisfy there use case.

**Comment by chacha21** [comment]
Ok, it's more clear.

But is it documented somewhere ? The tooltips in CMakeGUI above CUDA_GENERATION are not very informative.

**Comment by cudawarped** [comment]
> But is it documented somewhere ?

I don't think so apart from a mention [here](https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html#tutorial_config_reference_func_hetero).

**Comment by chacha21** [comment]
Should I suggest a doc improvement (for instance a URL in the CMake tooltip pointing to an explanation in a dedicated page), leaving this thread open as a reminder, or do I close it ?

**Comment by cudawarped** [comment]
> Should I suggest a doc improvement (for instance a URL in the CMake tooltip pointing to an explanation in a dedicated page),

You could add the information to the [CUDA Module Introduction](https://docs.opencv.org/4.x/d2/dbc/cuda_intro.html) page however that page is really out of date and all the information could do with an update.
