### ISSUE TITLE
New releases provideopencv_videoio_ffmpeg_64.dll by default

### ISSUE THREAD

**Issue by gongshuxuelang** [opencv/opencv#24811]
### Describe the feature and motivation

Compile source code yourself will encounter failure to download the situation.

Please include "opencv_videoio_ffmpeg_64.dll" in the source code by default.

```
#do_copy "opencv_videoio_ffmpeg_64.dll" "38a638851e064c591ce812e27ed43f1f" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/7da61f0695eabf8972a2c302bf1632a3d99fb0d5/ffmpeg/opencv_videoio_ffmpeg_64.dll" "C:/library/opencv-4.8.0/opencv-4.8.0/build/3rdparty/ffmpeg"
#missing "C:/library/opencv-4.8.0/opencv-4.8.0/build/3rdparty/ffmpeg/opencv_videoio_ffmpeg_64.dll"
#check_md5 "C:/library/opencv-4.8.0/opencv-4.8.0/.cache/ffmpeg/38a638851e064c591ce812e27ed43f1f-opencv_videoio_ffmpeg_64.dll"
#mismatch_md5 "C:/library/opencv-4.8.0/opencv-4.8.0/.cache/ffmpeg/38a638851e064c591ce812e27ed43f1f-opencv_videoio_ffmpeg_64.dll" "d41d8cd98f00b204e9800998ecf8427e"
#delete "C:/library/opencv-4.8.0/opencv-4.8.0/.cache/ffmpeg/38a638851e064c591ce812e27ed43f1f-opencv_videoio_ffmpeg_64.dll"
#cmake_download "C:/library/opencv-4.8.0/opencv-4.8.0/.cache/ffmpeg/38a638851e064c591ce812e27ed43f1f-opencv_videoio_ffmpeg_64.dll" "https://raw.githubusercontent.com/opencv/opencv_3rdparty/7da61f0695eabf8972a2c302bf1632a3d99fb0d5/ffmpeg/opencv_videoio_ffmpeg_64.dll"
#try 1
# timeout on name lookup is not supported
#   Trying 185.199.108.133:443...
# connect to 185.199.108.133 port 443 failed: Timed out
#   Trying 185.199.109.133:443...
# connect to 185.199.109.133 port 443 failed: Timed out
#   Trying 185.199.110.133:443...
# connect to 185.199.110.133 port 443 failed: Timed out
#   Trying 185.199.111.133:443...
# connect to 185.199.111.133 port 443 failed: Timed out
# Failed to connect to raw.githubusercontent.com port 443 after 87238 ms: Couldn't connect to server
# Closing connection 0
# 
```

**Comment by opencv-alalek** [comment]
> include "opencv_videoio_ffmpeg_64.dll" in the source code

There should be no binaries of 3rdparty dependencies in the source code repository controlled by git.
At least because that would explode repository size due to stored history.

BTW, LFS is not cheap for large projects and still requires extra steps from the user.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/

If used build system doesn't have regular Internet access:
- check these helper files to collect and provide binaries separately: https://github.com/opencv/opencv/blob/4.9.0/cmake/OpenCVDownload.cmake#L23-L24
- setup proxy/VPN or try this mirror of 3rdparty binaries https://gitee.com/mirrors_opencv/opencv_3rdparty (by fixing URLs in helper scripts)
