### ISSUE TITLE
Clean Objdetect module

### ISSUE THREAD

**Issue by vpisarev** [opencv/opencv#25004]
### Describe the feature and motivation

object detection is one of the key computer vision tasks where machine learning was used long before deep learning era. Nowadays, with deep learning, the problem is largely solved, at least for common cases.

But objdetect module in OpenCV still contains 'ancient' algorithms. We need to clean it up in OpenCV 5:

* Move HaarCascadeClassifier to opencv_contrib/xobjdetect.
* Move HOGDescriptor to opencv_contrib/xobjdetect.
* Move all Haar/LBP models (opencv/data/*) to opencv_contrib.
* Move/add Yolo postprocessing functions and DetectionModel from dnn to objdetect.
* Possibly move Macbeth color chart detector from opencv_contrib/mcc to this module.
* Maybe add deep learning-based detectors of basic geometric objects like circles and lines instead of traditional algorithms based on Hough transform ([which we suggest to remove from Imgproc](https://github.com/opencv/opencv/issues/25001)).

**Comment by LaurentBerger** [comment]
Is yolo detect a dog or rectangle where there is a dog? With [SAM ](https://segment-anything.com/)you detect a dog

**Comment by LaurentBerger** [comment]
Finally I like mediapipe [classification ](https://developers.google.com/mediapipe/solutions/guide): 
![image](https://github.com/opencv/opencv/assets/3591626/20ccdc2b-4d2b-4310-a4f0-e68ab95c41b5)

**Comment by LaurentBerger** [comment]
May be : 
DNN (4.0) -> DNNCore (5.0)
Objdetect (4.0) -> DNNModels (5.0) with subfolder as in mediapipe

**Comment by vpisarev** [comment]
@LaurentBerger, we have a dedicated repository [opencv_zoo](https://github.com/opencv/opencv_zoo/tree/main/models) that plays the role of DNNModels :)

**Comment by Dhanwanth1803** [comment]
@vpisarev Can I work on this? Because I am not sure if only members are working on this.

**Comment by TonyCongqianWang** [comment]
While I fully support moving the data/ folder, which had no reason to be there at the root. I can not fully agree on the decision to move the CascadeClassifier to the contrib repo. The CascadeClassifier is still much faster than the YN implementation on cpu especially when running on a raspberry pi. The improved frontal face cascade does offer a reasonable accuracy to be useful for simple tasks.

I can understand the move out of the main repository since it's more of a legacy feature, but it is still used and matured which doesn't fit well with the more unstable and experimental nature of the contrib repository. While building certain contrib modules is still, having to install the contrib python package is somewhat bad

**Comment by TonyCongqianWang** [comment]
As a side note or rather feature request:
While the current YN implementation is much slower than the cascade, it could be similarly fast if there was a quantizes version. If someone would add the, the cascade would become truly obsolete

**Comment by kaingwade** [comment]
@TonyCongqianWang There's a detailed comparison [OpenCV Face Detection: Cascade Classifier vs. YuNet](https://opencv.org/blog/opencv-face-detection-cascade-classifier-vs-yunet/). YuNet actually isn't much slower than Cascade. 

The [OpenCV Model Zoo](https://github.com/opencv/opencv_zoo) provides both the fp32 and quantized YuNet (and many other popular deep learning models too), which can both be run with DNN. You can have a try.

**Comment by TonyCongqianWang** [comment]
@kaingwade Thanks for the information! I was not aware that opencv hat an implementation for quantized networks and will definitely check it out. The report is indeed detailed but I have some problems: In particular, in the report, the outdated haar cascaded was used instead of the improved lbp cascade which is both (a lot) faster and more accurate. In my experience the lbp cascade runs in a few ms on 320x320 images instead of the reported 20+ms.

Additionally, only one x86 platform was used for the test, when both quantized and lbp features really shine on arm architecture. I will be happy to rerun the experiment on a raspberry pi with more configurations (cascades: haar, lbp, lbp_improved, YuNet: fp32, uint8) and report back the results if there is any interest on your side!

Lastly: even if the cascade is mostly obsolete I still disagree with moving it to the contrib repository. The contrib repository contains a lot of unmaintened, unfinished code which is very prone to breaking. The cascade module on the other hand is matured and at least right now works well with the rest of the opencv repository without needed maintenance.
Moving the current objectdetect into a legace module within the main repository would have very little cost while having a big advantage of not completely breaking any existing code that still uses cascade classifiers. Especially when custom trained models are used. While retraining with YuNet is possible, it is still a lot of work. The only other possibilities would be to either stay on 4.x or install the opencv_contrib package. Both options have significant disadvantages

**Comment by TonyCongqianWang** [comment]
If anyone is interested: I did the comparison of the blog (and more) on a raspberry pi and you can see the results [here](https://github.com/TonyCongqianWang/cv_facedetection_eval/). In short: using lbpCascades is slightly faster than YuNet, but quantized YuNet is slower than normal YuNet on both my Laptop and raspberry pi. This indicates, that there is no optimization for quantized nets yet, the only reason to use the quantized weights would be to save a bit of disk space (which is quite negligible though).

**Comment by kaingwade** [comment]
@TonyCongqianWang Thank you for the feedback. 
> This indicates, that there is no optimization for quantized nets yet,

No for now, the optimization on the int8 inference is still in progress: #23689
