### ISSUE TITLE
Could cv::Mat be nothrow movable?

### ISSUE THREAD

**Issue by Quuxplusone** [opencv/opencv#25065]
### Describe the feature and motivation

A Folly user has noticed that `Mat(Mat&&)` is noexcept(false). This means that it gets the ["vector pessimization"](https://quuxplusone.github.io/blog/2022/08/26/vector-pessimization/) with `std::vector` (making copies on reallocation rather than moving), and it can't be put into a `folly::fbvector<cv::Mat>` at all (https://github.com/facebook/folly/issues/1821), because Folly actually asserts at compile time that moving can be done without throwing exceptions.

Looking at the code, I don't see any _obvious_ reason `Mat(Mat&&)` couldn't just be replaced with `Mat(Mat&&) CV_NOEXCEPT`. But there might be a _subtle_ reason? If so, it would be great to document that reason with a code comment on the declaration and/or definition of the throwing move constructor, so that people don't ask this question again. :)

**Comment by kinchungwong** [comment]
After reviewing the code for [cv::Mat::Mat(Mat&&)](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L598-L620), I think we can investigate whether [```cv::MatSize```](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/include/opencv2/core/mat.hpp#L587-L599) and [```cv::MatStep```](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/include/opencv2/core/mat.hpp#L601-L614) can have nothrow move constructors. In the higher dimensional matrix case (```dims() >= 3```) both structs contain pointers to some heap-allocated buffers.

**Comment by Quuxplusone** [comment]
@kinchungwong: Maybe I don't understand the code's organization, but, just looking at the header files you linked to ([MatSize](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/include/opencv2/core/mat.hpp#L587-L599), [MatStep](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/include/opencv2/core/mat.hpp#L601-L614)) — it looks to me like we already have `is_trivially_copyable_v<cv::MatSize>` and `is_trivially_move_constructible_v<cv::MatStep>`. (`MatStep` does have a protected non-trivial copy-assignment operator, but its move and copy constructors are both implicitly defaulted and trivial.) So those aren't the blockers — unless I'm missing something!

**Comment by kinchungwong** [comment]
> So those aren't the blockers

Thanks, I should have provided the snippets for ```MatSize``` and ```MatStep``` method implementations. Here's [```MatSize::operator==(const MatSize&)```](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L203-L216)

While I was searching for these method implementations, I do notice that there are [non-member methods directly involved in the buffer allocations of MatStep.](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L218)

I see that it is possibly a violation of [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) that complicates my attempt to analyze the situation. I'm not in a position to criticize, but I'm also not confident enough to say whether it would have been safe to change the nothrow classification of the two structs. The LoD problem also makes it difficult to search for instances - I'd have to build the full project in order to detect all instances where non-members directly interfere with the allocations inside MatSize and MatStep. (I apologize that I don't have time for this currently.)

My understanding of nothrow is that we the programmers are ultimately responsible for the safety and correctness of the outcomes. If we classify them as nothrow, and if that leads to buggy scenarios, we cannot blame the compilers. Perhaps I need more time to study the situation.

**Comment by Quuxplusone** [comment]
> I'm not in a position to criticize, but I'm also not confident enough to say

Well, that makes two of us. ;) I'm definitely not familiar with the OpenCV codebase at all, so I recognize that you've taken on the harder job here of pointing at stuff, whereas I've got the easier job of just looking at each thing you indicate and saying "Nope... nope..."

For example: [`MatSize::operator==`](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L203-L216) definitely never throws, _and_ definitely is never called from [`Mat`'s move-constructor](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L598-L620), so it's not the problem, for both those reasons at once.

[`setSize(Mat&, ~~~)`](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L218) definitely _does_ throw (because it calls `fastMalloc`), but it's never called from [`Mat`'s move-constructor](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L598-L620), so it's not the problem.

Absolutely the _only_ way that [`Mat(Mat&&)`](https://github.com/opencv/opencv/blob/f9c3c3d66689443bb8dcff4e3c90a35e0d63617b/modules/core/src/matrix.cpp#L598-L620) could _ever_ throw an exception, is if it were to call a function that throws. And AFAICT it doesn't call any functions. So it can't throw. (Am I missing anything?) The existence of _other_ functions in the codebase that use exceptions is irrelevant to whether `Mat(Mat&&)` _itself_ could possibly throw.

**Comment by kinchungwong** [comment]
@Quuxplusone I agree with all points in your analysis.

**Comment by asmorkalov** [comment]
@vrabaud could you take a look?

**Comment by vrabaud** [comment]
Indeed, trivial members are just copied over, it can totally be marked as noexcept
