### ISSUE TITLE
cv2.xfeatures2d.LATCH bug

### ISSUE THREAD

**Issue by WennPaper** [opencv/opencv#25081]
### System Information

OpenCV python version: 4.9.0

### Detailed description

The function when used for image feature descriptor calculation, which should only compute image feature descriptor and output updated keypoints and corresponding descriptor, erroneously changes input image array values.

### Steps to reproduce

```
import cv2

im = cv2.imread('im.jpg', 0)
detector = cv2.xfeatures2d.TBMR_create()
descriptor = cv2.xfeatures2d.LATCH_create()
keypoints_detector = detector.detect(im, None)

print(im)
keypoints_descriptor, descriptors = descriptor.compute(im, keypoints_detector)
print(im)
```

The two printed `im` should be identical, but they are not.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by WennPaper** [comment]
Hi @Dhanwanth1803,
My OpenCV version is 4.9.0 and LATCH is still available in this version. The issue can only be replicated using the LATCH descriptor. I found this issue when I was comparing different image features available in OpenCV including ORB, and LATCH was the only buggy feature. 
![image](https://github.com/opencv/opencv/assets/67032259/6e441fb4-72ad-4dbd-b1b1-14e4e7917375)

**Comment by berak** [comment]
@WennPaper , your issue seems corect.

if a grayscale image is passed to Latch::compute, a *shallow* copy is taken here:
https://github.com/opencv/opencv_contrib/blob/bbce2ef9d60755a6096edc9ecfd0922aab60b030/modules/xfeatures2d/src/latch.cpp#L522

later, a gaussianblur is applied *in-place*:
https://github.com/opencv/opencv_contrib/blob/bbce2ef9d60755a6096edc9ecfd0922aab60b030/modules/xfeatures2d/src/latch.cpp#L535

(so you should see a blurred image coming out of it)

an `InputArray` must not be modified, this is a breach of contract, and a bug.

we could add a `clone()`here:
    
                    grayImage = image.clone();
to make it a 'deep' copy.

**Comment by WennPaper** [comment]
Hi @berak, that is exactly how my images were affected by the bug. Thanks for the explanation.

**Comment by Dhanwanth1803** [comment]
@berak @WennPaper I put up a PR with the changes @berak suggested in opencv_contrib. Is that relevant? And why is this closed before changing the source code?
