### ISSUE TITLE
error detecting MSVC preview compiler version

### ISSUE THREAD

**Issue by pattakosn** [opencv/opencv#25295]
### System Information

OpenCV version: 4.9.0 and latest
OS: W11 pro insiders
Compiler: MSVC 2022 preview
cmake 3.28.3

### Detailed description

while configuring the project i see this message
```
-- Detected processor: AMD64
CMake Warning at cmake/OpenCVDetectCXXCompiler.cmake:182 (message):
  OpenCV does not recognize MSVC_VERSION "1940".  Cannot set OpenCV_RUNTIME
Call Stack (most recent call first):
  CMakeLists.txt:174 (include)
```

the issue comes from `/cmake/OpenCVDetectCXXCompiler.cmake` where it tries to detect compilers, the VS2022's MSVC_VERSION is identified as 193 but VS2022 preview identifies itself as 194.Locally I hacked the abovementioned cmake file like this:
```
diff --git a/cmake/OpenCVDetectCXXCompiler.cmake b/cmake/OpenCVDetectCXXCompiler.cmake
index 1743aca11f..b3ec6fc3bf 100644
--- a/cmake/OpenCVDetectCXXCompiler.cmake
+++ b/cmake/OpenCVDetectCXXCompiler.cmake
@@ -176,7 +176,7 @@ elseif(MSVC)
     set(OpenCV_RUNTIME vc15)
   elseif(MSVC_VERSION MATCHES "^192[0-9]$")
     set(OpenCV_RUNTIME vc16)
-  elseif(MSVC_VERSION MATCHES "^193[0-9]$")
+  elseif(MSVC_VERSION MATCHES "^19[3,4][0-9]$")
     set(OpenCV_RUNTIME vc17)
   else()
     message(WARNING "OpenCV does not recognize MSVC_VERSION \"${MSVC_VERSION}\". Cannot set OpenCV_RUNTIME")
```
but I am not sure what is the correct way to fix that.

On one system this caused my build to fail on an other it compiles nevertheless.

### Steps to reproduce

checkout/download opencv 4.9.0 or latest and run `cmake configure` while using `MSVC 2022 preview`

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by asmorkalov** [comment]
@pattakosn Thanks a lot for the issue report. Feel free to submit pool request.

**Comment by pattakosn** [comment]
@asmorkalov, ok, sure [here it is](https://github.com/opencv/opencv/pull/25341)

**Comment by pattakosn** [comment]
I

**Comment by vestri** [comment]
Hi,
just for information, this problem also affects compilation of old OpenCV projects with old compiled OpenCV versions.
For example: I have a Cmake project I want to compile with let say OpenCV 4.5.5 that has been compiled with vc16.
I cannot build Visual Studio project because current MSVC_VERSION is 1940.
I got OpenCV RUNTIME empty and the error : "Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration."

maybe we should prevent future compilation troubles with future version of MSVS by using something like next line or something better:
 elseif(MSVC_VERSION MATCHES "^19[3,4][0-9]$" OR MSVC_VERSION GREATER 1949)

**Comment by asmorkalov** [comment]
The issue was fixed in https://github.com/opencv/opencv/pull/25632. The patch is a part of 4.10.0 release. OpenCV team does not support new compilers for old releases. Please update the library.
