### ISSUE TITLE
The difference between opencv2.4.9 and opencv4.8.1 in cv::blur

### ISSUE THREAD

**Issue by absdfge** [opencv/opencv#25664]
### Describe the doc issue

The following code causes a difference in processing results between version 2.4.9 and version 4.8.1.
Is it just me? Does anyone know?

cv::blur(img, blurred, cv::Size(4, 4), cv::Point(-1, -1), cv::BORDER_DEFAULT);

**Comment by absdfge** [comment]
im using visual studio 2022. i was using WinMerge to compare images.

**Comment by vrabaud** [comment]
I had the same experience and this is what I found out: a lot happened between 2.4.9 !
- bug fixes were done for edge handling
- the algorithm got ported to HAL, hence possibly different results on SSE and ARM due to rounding differences
- smaller kernels were treated differently
- It is normal if OpenCV gives different results over a 10 year period: it only got better.
