### ISSUE TITLE
Is there a bug fixes list that can point out which bugs or issues have been fixed from 3.4 to 3.4.20?

### ISSUE THREAD

**Issue by veyron95** [opencv/opencv#26323]
### Describe the doc issue

Is there a bug fixes list that can point out which bugs or issues have been fixed from 3.4 to 3.4.20?

### Fix suggestion

Can you provide a document such as a bug fixes list that can point out which bugs or problems have been fixed from 3.4 to 3.4.20!

For example, what specific bugs have been fixed in （3.4.0 vs 3.4.1）?
What specific bugs have been fixed in （3.4.1 vs 3.4.2）?
And so on

**Comment by Kumataro** [comment]
As first, could you close this issue because this is only Question, not issue, please ?
And if you want to continue more, re-asking at Q&A forum ( https://forum.opencv.org/ )  is better.
( This is last post from me at this issue. )

You can compare branches and/or tags from here. ( https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits )

e.g. ) `https://github.com/opencv/opencv/compare/3.4.20...3.4`

**Comment by sturkmen72** [comment]
also you can check closed milestones https://github.com/opencv/opencv/milestones
