### ISSUE TITLE
AttributeError: module 'cv2.ximgproc' has no attribute 'thinning'

### ISSUE THREAD

**Issue by TC9905** [opencv/opencv#26502]
### System Information

Ubuntu 11.4.0-1ubuntu1~22.04
opencv-contrib-python        4.10.0.84
opencv-python-headless       4.10.0.84
python             3.8.20

### Detailed description

python 111.py 
Traceback (most recent call last):
  File "111.py", line 11, in <module>
    thinned = cv2.ximgproc.thinning(thresh, cv2.ximgproc.THINNING_ZHANGSUEN)
AttributeError: module 'cv2.ximgproc' has no attribute 'thinning'

### Steps to reproduce

import cv2
import numpy as np

img = cv2.imread('/home/mambauser/arrow-detection/ReactionDataExtractor/testimage/1.png', 0)

ret, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

thinned = cv2.ximgproc.thinning(thresh, cv2.ximgproc.THINNING_ZHANGSUEN)

cv2.imshow('image', np.hstack((thresh, thinned)))
cv2.waitKey(0)
cv2.destroyAllWindows()

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by TC9905** [comment]
> The mentioned error typically arises when the ximgproc module from the opencv-contrib-python package is not properly installed or linked. Reinstalling the library might resolve the issue. **Try this:-** sudo pip3 uninstall opencv-contrib-python sudo pip3 install opencv-contrib-python I suppose this will reinstall opencv and resolve the error. Also I had the same issue on Google Colab and by reinstalling the library it was resolved.

Thank you for your reply. I tried reinstalling and installing other versions like 4.5.3.56 of opencv-contrib-python and opencv-python-headless,
 2023  pip uninstall opencv-contrib-python
 2024  pip install opencv-contrib-python

but the issue still persists.
thinned = cv2.ximgproc.thinning(thresh, cv2.ximgproc.THINNING_ZHANGSUEN)
AttributeError: module 'cv2.ximgproc' has no attribute 'thinning'

**Comment by unknownpersonai** [comment]
The error suggests that cv2.ximgproc.thinning is not available in your OpenCV installation. This could be due to an incomplete or improperly configured OpenCV installation or missing functionality in your OpenCV version.

Steps to Solve:
1. Verify Installation of opencv-contrib-python:
The cv2.ximgproc module is part of the extra modules provided by opencv-contrib-python. Make sure you have the correct version installed.

Run the following command to ensure you have the contrib package installed:
`pip install --upgrade opencv-contrib-python
`

You are already using opencv-contrib-python 4.10.0.84, but try reinstalling it to ensure a proper installation:

`pip uninstall opencv-contrib-python opencv-python-headless
pip install opencv-contrib-python
`
2. Check for cv2.ximgproc Availability:
Verify that the cv2.ximgproc module is accessible in your current installation.

Run the following Python script to check:

`import cv2

if hasattr(cv2, 'ximgproc') and hasattr(cv2.ximgproc, 'thinning'):
    print("thinning method is available in cv2.ximgproc")
else:
    print("thinning method is NOT available in cv2.ximgproc")
`
If it prints that the method is not available, it confirms the function is missing in your current OpenCV build.


3. Rebuild OpenCV from Source (Advanced):
If reinstalling the package doesn’t resolve the issue, you may need to build OpenCV with extra modules from source to ensure all functionality is included. Follow these steps:

Install Required Dependencies:

bash
Copy code
sudo apt update
sudo apt install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python3-dev python3-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev
Clone OpenCV and OpenCV-Contrib Repositories:

bash
Copy code
git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git
Build OpenCV with Extra Modules:

bash
Copy code
cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
make -j$(nproc)
sudo make install
Verify Installation: Test the Python script again after building and installing OpenCV.

**Comment by TC9905** [comment]
> The error suggests that cv2.ximgproc.thinning is not available in your OpenCV installation. This could be due to an incomplete or improperly configured OpenCV installation or missing functionality in your OpenCV version.
> 
> Steps to Solve:
> 
> 1. Verify Installation of opencv-contrib-python:
>    The cv2.ximgproc module is part of the extra modules provided by opencv-contrib-python. Make sure you have the correct version installed.
> 
> Run the following command to ensure you have the contrib package installed: `pip install --upgrade opencv-contrib-python `
> 
> You are already using opencv-contrib-python 4.10.0.84, but try reinstalling it to ensure a proper installation:
> 
> `pip uninstall opencv-contrib-python opencv-python-headless pip install opencv-contrib-python ` 2. Check for cv2.ximgproc Availability: Verify that the cv2.ximgproc module is accessible in your current installation.
> 
> Run the following Python script to check:
> 
> `import cv2
> 
> if hasattr(cv2, 'ximgproc') and hasattr(cv2.ximgproc, 'thinning'): print("thinning method is available in cv2.ximgproc") else: print("thinning method is NOT available in cv2.ximgproc") ` If it prints that the method is not available, it confirms the function is missing in your current OpenCV build.
> 
> 3. Rebuild OpenCV from Source (Advanced):
>    If reinstalling the package doesn’t resolve the issue, you may need to build OpenCV with extra modules from source to ensure all functionality is included. Follow these steps:
> 
> Install Required Dependencies:
> 
> bash Copy code sudo apt update sudo apt install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python3-dev python3-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev Clone OpenCV and OpenCV-Contrib Repositories:
> 
> bash Copy code git clone https://github.com/opencv/opencv.git git clone https://github.com/opencv/opencv_contrib.git Build OpenCV with Extra Modules:
> 
> bash Copy code cd opencv mkdir build cd build cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules .. make -j$(nproc) sudo make install Verify Installation: Test the Python script again after building and installing OpenCV.
