### ISSUE TITLE
Include `chrono` for 'high_resolution_clock' and `duration_cast`

### ISSUE THREAD

**Issue by NEIL-smtg** [opencv/opencv#26526]
### System Information

OpenCV version: latest commit
OS: Windows 11
Compiler: MSVC 19.43.34617.95

### Detailed description

I work on Microsoft Visual C++ testing, where we regularly build popular open-source projects, including yours, with development builds of our compiler and libraries to detect and prevent shipping regressions that would affect you. This also allows us to provide advance notice of breaking changes, which is the case here.

Recently https://github.com/microsoft/STL/pull/5105, revealed an issue in OpenCV.

Compiler error with this STL change:
```c++
C:\gitP\opencv\opencv\modules\gapi\test\gapi_sample_pipelines.cpp(86,22): error C2653: 'high_resolution_clock': is not a class or namespace name [C:\gitP\opencv\opencv\build_amd64\modules\gapi\opencv_test_gapi.vcxproj]
C:\gitP\opencv\opencv\modules\gapi\test\gapi_sample_pipelines.cpp(86,45): error C3861: 'now': identifier not found [C:\gitP\opencv\opencv\build_amd64\modules\gapi\opencv_test_gapi.vcxproj]
C:\gitP\opencv\opencv\modules\gapi\test\gapi_sample_pipelines.cpp(91,38): error C2672: 'std::chrono::duration_cast': no matching overloaded function found 
```

Affected code:
https://github.com/opencv/opencv/blob/65d4112fa52511cd609a5c794a263bee9b5a8d43/modules/gapi/test/gapi_sample_pipelines.cpp#L86-L99

This was assuming that including makes the chrono::high_resolution_clock type available, which is not guaranteed by the Standard. You need to explicitly include the `chrono` header in this file, and the error will be resolved.

### Steps to reproduce

Build log: [opencv.log](https://github.com/user-attachments/files/17914138/opencv.log)

### Issue submission checklist

- [X] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by StephanTLavavej** [comment]
Thanks for fixing this, @asmorkalov! If you weren't aware, your PR said "Address #26526", but if you said "Fix", "Close", or "Resolve" instead of "Address", that would have created a special link between the PR and the issue, such that merging the PR would automatically close the issue. (Otherwise it's just a "mention"; e.g. "Address #nnnn" can be appropriate when a PR works towards an issue without fully fixing it.)

See https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword for more info about this magical GitHub feature.
