### ISSUE TITLE
Failure in resizing very large image. 

### ISSUE THREAD

**Issue by ChaoyuanYeh** [opencv/opencv#5191]
I have posted as question here : 
http://answers.opencv.org/question/68571/how-to-resize-an-extremely-large-image/

Essentially, when I'm trying to resize image whose product of column and row number is larger than 2^31, I'll receive this error message "cv2.error: C:\opencv-3.0.0\source\modules\imgproc\src\imgwarp.cpp:3208: error: (-215) ssize.area() > 0 in function cv::resize".  So resizing and image that is (46340,46340,3) will work (46341,46341,3) won't. This is seemingly an integer overflow problem. I'm wondering if this can be addressed in future release?

**Comment by bjohannsson** [comment]
I wanted to have a look at this, but I can't find the source code where the size function is implemented. Is it in a pre-compiled opencv2 library perhaps?
If so, would there be a way for me to get at it somehow?

**Comment by sturkmen72** [comment]
@bjohannsson take a look at https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/imgwarp.cpp#L3229

**Comment by bjohannsson** [comment]
Thank you for the answer @sturkmen72.

It seems to me that one solution would be to change CV_Assert( ssize.area() > 0 ) to CV_Assert( ssize.width > 0 && ssize.height > 0 ), which according to the discussion in the link provided above, should also work(since the actual area doesn't seem to matter). 

This however does not tackle the integer overflow problem.
Please share your thoughts as I am a newcomer,  should I make a PR with this change?

**Comment by nicolargo** [comment]
Any head up for this issue ?

**Comment by ilya-lavrenov** [comment]
Fixed in https://github.com/opencv/opencv/pull/6883
