### ISSUE TITLE
nose(mouth)-detection  is really very slow with provided cascade classifier files 

### ISSUE THREAD

**Issue by liuyaoCS** [opencv/opencv#5257]
can provide developers a more fast classifier file or just try to solve it with efforts of optimum the code

**Comment by StevenPuttemans** [comment]
@mshabunin @alalek I am wondering if we can close this down for the following reasons
1. The issue has no information what so ever on the used setup.
2. The classifiers work just fine and realtime on VGA resolution and its possible to obtain also with even higher resolutions by applying some smart programming tricks.
3. Since august 2015 more optimizations have entered the cascade classification and thus it would already be faster then at that moment.

@liuyaoCS I suggest you to either 
- Add more information to this topic if it is still an issue
- Start a discussion about optimization at http://answers.opencv.org/questions where you will be helped much faster.
