### ISSUE TITLE
numl in comparison to orc

### ISSUE THREAD

**Issue by paroj** [opencv/opencv#5510]
as far as I understand numl is a ocaml subset for vectorized data processing.
The problem it tries to solve is that one has to write similar SIMD code for multiple architectures.

In this regard it is [similar to ORC](http://cgit.freedesktop.org/gstreamer/orc/tree/README). @vpisarev  are you aware of that project? How does it compare to numl? Probably the higher abstraction level of ocaml has its advantages - on the other hand ORC might already solve the problem at hand..

**Comment by bhack** [comment]
http://gstreamer.freedesktop.org/projects/orc.html

**Comment by vpisarev** [comment]
hello! I was not aware of ORC. Well, choose some 2 programming languages that are completely different in your opinion. There are likely more differences between numl and ORC than between the 2 languages that you chose :)

**Comment by bhack** [comment]
@vpisarev Yes if you have enough resources to build your own :). Also if you have this resource it is always useful to know how others has approached to the problem
 especially if this solution was already adopted inside a big open source frameworks/library like gstreamer.

**Comment by paroj** [comment]
the question was more about which problem you can solve with the languages rather than how the actual languages look like. To pick up your example: if I pick 2 arbitrary programming languages, they are likely both turing complete and thus exactly the same.

Anyways.. as far as I can see the higher abstraction of NUML allows compilation to OpenCL, while the lower level of ORC does not. Yet finding information about NUML is quite hard, as its repository is still private..

**Comment by bhack** [comment]
Probably has some similarity also to [SPOC](http://mathiasbourgoin.github.io/SPOC/)

**Comment by paroj** [comment]
[SPOC/Sarek](https://github.com/mathiasbourgoin/SPOC/blob/master/SpocLibs/Samples/Test_OpenCL/Test_OpenCL.ml) seems **very** similar to the way NUML is supposed to work. (from my limited information on NUML)

**Comment by bhack** [comment]
On SIMD side http://www.yeppp.info

**Comment by bhack** [comment]
[Another DSL] (http://hipacc-lang.org) with c++/cuda/opencl/renderscript  backends

**Comment by bhack** [comment]
And [HALIDE DSL](http://halide-lang.org/cvpr2015.html) presented at CVPR 2015

**Comment by bhack** [comment]
Some openvx function example in HALIDE https://github.com/netaz/halide-excursions/blob/master/functions/openvx.cpp

**Comment by paroj** [comment]
wow. this turned out much more educating than I thought. HALIDE actually seems to cover all of the NUML usecases, but already progressed to real-world usages. Being integrated into C++ is also neat.

**Comment by bhack** [comment]
@paroj And his backed by Google

**Comment by vpisarev** [comment]
Pavel, Stefano,
indeed, right now we have not disclosed any details about numl, not because we want to make it proprietary product, quite the opposite, it's going to be open-source, under quite liberal license. It's because we want to unveil it when it's in a good shape and is able to make a good impression. We are currently working really hard on it, and it's not just a figure of speech, you may have noticed that we even temporarily slowed down the process of reviewing patches, it's a side effect of that. I believe, the results will be presented quite soon.

thank you for all the links, I know about HALIDE, read their papers, looked at their code a bit, I have not heard of SPOC, it looks interesting too. GPGPU is a hot topic, but it's not among short-term goals for numl, we target mostly multi-core CPUs with vector instructions. Actually, if you ask me, I believe that in future GPUs will melt into CPUs, just like math coprocessor is now a part of CPU. Well, at least the GPGPU part. So, we target today's CPUs and future GPUs :) normally, it takes at least a few years for a language to take off (or fade into the darkness), so the timing is perfect.

**Comment by bhack** [comment]
@vpisarev I think that  HSA-HUMA (cache coherent CPU GPU) devices will make this timeline shorter cause some this AMD products are already on the market.
