### ISSUE TITLE
Supply imwrite/imread overloads to work with wstring, wchar_t 

### ISSUE THREAD

**Issue by comdiv** [opencv/opencv#5631]
In our project we use wide strings (`std::wstring + wchar_t*` ) by default - so it's more compatible to file names with locale symbols (cyr) and it's easy to integrate with .NET marshalling.

In our OpenCV code we use something like this:

```
    void load(wstring filename){
        Mat img = imread(string(filename.begin(), filename.end()), CV_LOAD_UNCHANGED);
    } 
   void load(wchar_t* filename){
    wstring wfname(filename);
        Mat img = imread(string(wfname.begin(), wfname.end()), CV_LOAD_UNCHANGED);
    } 
```

Our suggestion - supply overloads (or template) for imread/imwrite to use `std::wstring, wchar_t*`

Better if in nuts it will be wide char based, and `std::string` version - as overload.

**Comment by comdiv** [comment]
I see that in source it goes deep to codecs - if it's in policy i can try to fix it in whole imgcodecs and setup pull request.

**Comment by comdiv** [comment]
In provided commit where temporal solution that allow me to simplify code, but it's not real migration to wide chars for cv::String

**Comment by alalek** [comment]
There is no easy way.

BTW, `std::string != std::wstring`. It is different objects

**Comment by comdiv** [comment]
I know, but if wstring is ANSI-compatible `string(ws.begin(),ws.end())` is valid.
So i just suggest to rewrite cv::String to make it Unicode based, not ANSI based. So it will be much compatible with different languages and friendly for Java/.NET integration where Unicode is in nuts.

**Comment by defrag257** [comment]
Conversion from wstring to string is not proper, because it will drop some Unicode characters in Windows.

For example, in the English version of Windows, conversion from wstring to string will only convert 256 characters in Windows-1252, while there are 1112064 characters in Unicode.

Instead, you should add w_imread and w_imwrite which accept wchar_t, and modify the inner implementation calls _wfopen instead of fopen. _wfopen will call CreateFileW which accepts Unicode, while fopen calls CreateFileA which accepts Windows-1252.

**Comment by kinchungwong** [comment]
The ideal solution to this problem is to implement what libtiff (written in C) does: an "interface" with a group of "methods" which support functionality such as read, write, seek (absolute and relative), get total size, and close.

https://linux.die.net/man/3/tiffclientopen

Ignore the two related to map and unmap, because most file formats aren't designed to be block-based or strictly sequential (streaming), and therefore codecs couldn't predict what file offsets or blocks they will need next.

The minimum requirements are:

 - Read ( buffer, count = how many bytes to read )
 - Write ( buffer, count = how many bytes to write )
 - Seek ( offset, option ) 
    - option = one of { Seek from beginning; Seek from current offset; Seek from end of file }
 - GetSize = simply returns the current file size
 - Close, or a C++ destructor, or both (it is better to allow an explicit closing method.)

The buffer type should simply be pointer to char, for several reasons:

 - The caller to the Read and Write methods are responsible for the buffer's lifetime. The buffer's lifetime doesn't change within the Read and Write methods.
 - Most "byte buffer" types can be downgraded to a pointer to char, provided that the pointer isn't being used beyond its address bound or used beyond its lifetime.
 - Specifying a valid buffer size is the caller's responsibility.

Most low-level codecs can support redirecting file I/O operations back into client code, so that client code can mimic files without touching the file system, which is a necessity in embedded systems.

Once that is implemented, the OS-specific OpenCV build can bundle with an implementation of this file stream client that will work for their platform. In the case of Windows, two can be provided - one will open a file given a Code Page 1252 path name; another will open a file given a Unicode path name.

This also opens the door to "deflate-to-memory" implementations.

This idea is compatible with the current title of the issue, which is to **"Supply imwrite/imread overloads to work with wstring, wchar_t"**.

**Comment by Mr-DDDAlKilanny** [comment]
Any update?

**Comment by asmorkalov** [comment]
OpenCV team decided not to extend library API with `wchar_t` and `wstring` support and not add overloads. Reasons:
- Most of image decoding and encoding libraries use standard `fopen` call to open files and extra `wchar_t` support requires domain libraries modification
- Modern Linux, Mac OS and latest Windows releases support UTF-8 encoding that allows to use `std::string` as container to pass it to OpenCV functions.
- Popular FS on Linux does not use `wchar_t` natively and the overloads is not full cross platform.

Details and solutions are discussed in https://github.com/opencv/opencv/issues/4292#issuecomment-601686965
