### ISSUE TITLE
HaarCascade data files that come with 2.4.12 does not work with persistence.cpp

### ISSUE THREAD

**Issue by ghost** [opencv/opencv#5889]
I installed OpenCV 2.4.12 (through brew opencv) and do a simple code:

```
cv.Load("/usr/local/Cellar/opencv/2.4.12/share/OpenCV/haarcascades/haarcascade_eye.xml")
```

Just to load the file that comes with the 2.4.12 distribution. This file is the same as https://raw.githubusercontent.com/Itseez/opencv/2.4.12/data/haarcascades/haarcascade_eye.xml

Then, I got this error: 

```
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file /tmp/...[a temp path].../opencv-2.4.12/modules/core/src/persistence.cpp, line 5008
```

But if I get the xml files from the older versions like from the 2.4.9 tag or before, like this one:
https://raw.githubusercontent.com/Itseez/opencv/2.4.9/data/haarcascades/haarcascade_eye.xml

then the above code works fine. 

I noticed that the xml file was updated to the 2.4.11 and later since December 2014 to update the models. I assume that was a new model format for OpenCV 3? If we updated the model files for 2.4.x, should we also update the persistence.cpp code in there too in order to be able to read the data files that come with it?

**Comment by StevenPuttemans** [comment]
It is indeed because the older models where trained with an absolete interface and thus persistance has since then not been replaced and updated with the new code. Only models trained with the old haartraining tool work on it, models trained with traincascade (all models of 2.4.12 and on) even with HAAR features do not work.

Keep in mind that those old models contain bugs which were fixed over time. 

But like said, updating persistance.cpp is still on my TODO list :D

**Comment by pwnorbitals** [comment]
This can probably be closed now
