### ISSUE TITLE
cv::sqrt is not giving stable result, at least for the java-wrapper in OpenCV 3.1

### ISSUE THREAD

**Issue by justsosod** [opencv/opencv#5955]
By doing a simply test: 

for (int n=2; n < 10; n++)
{
   // create a diagonal matrix M of dimension n, assign the diagonal element by i*i, others by 0, where i is the column index

   // compute M's square root R by using Core.sqrt(M, R)
}

if we run several times the above program, a chance of 40% that we can have the result R is not a diagonal matrix, and a change of 15%-20% that some elements not on the diagonal are diverged over  1E200+. More important is, the result of each run cannot keep the same.

(see the code in the attachment)

**Comment by Aravind-Suresh** [comment]
Can you be more specific about the problem? I have tried similar stuff and found no problem with the output. You may get a wrong result, if you are trying to access elements with wrong types.

For instance, for a CV_32F type image, accessing elements with img.at<double>(i, j) returns different values ( unexpected ones ). You will get a similar error if you access a CV_64F image with img.at<float>(i, j).

So, try using proper types for storage and access. Hope this solves the problem :). Or attach the code snippet so that I can give better insights.
