### ISSUE TITLE
result error on matchTemplate of black image

### ISSUE THREAD

**Issue by WeiHungHuang** [opencv/opencv#5974]
The same post could be found at
http://answers.opencv.org/question/80640/result-error-on-matchtemplate-of-black-image/
But, get no answer there.

On both version 2.4.10 and 2.4.11.
Following codes are tested in Jython on Win7 64-bit

``` java
screen = Highgui.imread( "screen.png", Highgui.IMREAD_GRAYSCALE); 
target = Highgui.imread( "target.png", Highgui.IMREAD_GRAYSCALE); 
res = Mat();
Imgproc.matchTemplate(screen, target, res, Imgproc.TM_CCOEFF_NORMED);
print(res.get(0, 0));
```

The result is

array('d', [1.0])

Here [1.0] means that the matching at coordinate (0, 0) is 100%. It is incorrect.

Attached files: C:\fakepath\screen.png C:\fakepath\target.png

A similar problem is posted in DevZone 
http://code.opencv.org/issues/798 
It said the bug is solved. 
But my codes still showed the bug.

target.png
![target](https://cloud.githubusercontent.com/assets/16713690/12344921/b374d366-bb7d-11e5-882f-58804c762c1c.png)

screen.png
![screen](https://cloud.githubusercontent.com/assets/16713690/12344922/b375659c-bb7d-11e5-958f-35458be87fc1.png)

**Comment by mfs6174** [comment]
I do not think this is a bug. 

The comparison method which you are using is CV_TM_CCOEFF_NORMED. As shown in the formula in the documentation ([link]( http://docs.opencv.org/2.4.11/modules/imgproc/doc/object_detection.html?highlight=matchtemplate#cv2.matchTemplate) ), T'(x',y') is zero all across the target image because all the pixel values of your target image are the same (equal to the mean value). So the numerator and denominator are all zero in the matching result R(x,y), which does not make sense. 

I looked into the source code of this function. It calculate the standard deviation of the target image, and return a Scalar::all(1) when the method is CCOEFF_NORMED to avoid NaN (Divided by Zero). 

I suggest to close this issue.

**Comment by WeiHungHuang** [comment]
Apparently, anyone will say those two images do not match.
Every method needs to consider corner cases.
If math does not work on some cases, special handling should be taken.

Or the case will bite you someday.

**Comment by mfs6174** [comment]
This method simply makes no sense on your case. It's not right to return all ones or all zeros. 

I think adding a assertion for this case to alert the user may be a good solution. The user can change the method seeing the assertion failure. What do you think? 

If the official developer agrees on this solution, I can develop a pull request for this issue.

**Comment by WeiHungHuang** [comment]
Since there is no match. I think it should return all value close to zeros.
If the target.png is not all black, even with a little white dot, it works as expected.
But it fails on all black image.

**Comment by mfs6174** [comment]
I don't think it can be judged as "no match". For example, if I match a all
black image (pixel values are all zeros) to another all black image, do you
call it 100% match? If I match a all grey image  (pixel values are all
127) or a all white image (pixel values are all 255) to that all black
image, what value should the function return? Do you think the grey image
can match better than the white image or not?

I do not think the three cases I mentioned should get all 0 match values
together because there are difference in the degree of matching. But it's
just a undefined problem within this method for that cases. The matching
values of all the three cases can not be calculated at all with this
method. So I think adding the assertion and guiding the user to change the
method is a better solution.

2016-03-21 22:41 GMT+08:00 WeiHungHuang <notifications@github.com>:

> Since there is no match. I think it should return all value close to zeros.
> If the target.png is not all black, even with a little white dot, it works
> as expected.
> But it fails on all black image.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv/issues/5974#issuecomment-199319549>
>



-- 
--------------------
mfs6174
Web  mfs6174.org

**Comment by WeiHungHuang** [comment]
How about the case in the example?
I would say they are not match apparently.

Say again,
If the target.png is not all black, even with a little white dot, it works as expected.

**Comment by nguyenthaohut** [comment]
Same problem happen in version 4.0

**Comment by alalek** [comment]
There is a limitation on inputs of the algorithm.
