### ISSUE TITLE
opencv_ffmpeg and OpenH264-x.y.z

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#6080]
Hi,

opencv_ffmpeg need on windows openH264-x.y.z dll. IIn opencv3.1 it is version 1.4.0 of cisco needed I think and not last 1.5.0. Where can I find version number of openH264 in opnecv doc?

Thanks for your answer.

**Comment by alalek** [comment]
OpenH264 support is an optional experimental option (libx264 can't be used due license/patent issues) for Windows-only ffmpeg wrapper.
It is used only to encode video with H264 (AVC1) codec.

There is [info dump](http://pullrequest.opencv.org/buildbot/builders/master_noOCL_noICV_noSSE-broadwell-win64-vc14/builds/116/steps/test_videoio/logs/stdio) on `stderr` in case of trying to encode H264 video streams (I believe it is enough):
```
Failed to load OpenH264 library: openh264-1.4.0-win64msvc.dll
	Please check environment and/or download library from here: https://github.com/cisco/openh264/releases

[libopenh264 @ 000000c34db82340] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
```

There is no such version details about this in OpenCV documentation. The same thing is for other 3rdparty dependencies like libpng. There are too many setups, so it is very hard to document and maintain this.

BTW, Windows ffmpeg wrapper should be updated to new ffmpeg and openh264 releases.

**Comment by Zenopheus** [comment]
The info dump above is misleading if someone set the OPENH264_LIBRARY_PATH incorrectly because it is only printing what is in the environment variable. 

If you check the code (master/ffmpeg/openh264_wrapper/wels/codec_api.h) you'll see that it expects OPENH264_LIBRARY_PATH to point to the **complete path** to the openh264 library file. If the variable is not set it looks for "openh264-1.4.0-win64msvc.dll" (if under windows) anywhere in the path. 

If you assumed (like i did) that OPENH264_LIBRARY_PATH should be a directory then things get confusing.  For example:
`set OPENH264_LIBRARY_PATH = d:\openh264\bin`
Opencv will give you this error message:
`Failed to load OpenH264 library: d:\openh264\bin`

The docs should state that OPENH264_LIBRARY_PATH should point to a **library** not a path to a library and what version of openh264 the code expects (1.4.0).

_Even better:_ I OPENH264_LIBRARY_PATH should either be renamed to OPENH264_LIBRARY_LIB or the code should look for the specific library that it was tested against in the OPENH264_LIBRARY_PATH.

**Comment by alalek** [comment]
OpenH264 is updated to 1.5.0 (1.6.0 is not supported by ffmpeg yet)
Environment variable name is changed to [`OPENH264_LIBRARY`](https://github.com/opencv/opencv_3rdparty/blob/0d62a4a128da306d45e62099691f161e550246c6/ffmpeg/openh264_wrapper/wels/codec_api.h#L122)

**Comment by 3d-illusions** [comment]
what's the solution to this?  Just started happening here with avc1
