### ISSUE TITLE
Cuda context initialization with multithreading.

### ISSUE THREAD

**Issue by mbarnach** [opencv/opencv#6086]
When multiple threads launch a cuda function in parallel, the behavior is undefined (wrong results or even SEGFAULT).
This could be proved with the followning code:

    std::thread t[2];
    for( int i = 0 ; i < 2 ; ++i )
    {
        t[i] = std::thread( cuda_function );
    }
    for( int i = 0 ; i < 2 ; ++i )
    {
        t[i].join();
    }

Where cuda_function is any cuda OpenCV function.
Setting the device to the right one at the begining of the main thread and in each thread isn't enough, but calling any cuda OpenCV function (synchronously) from the main thread do the trick.

**Comment by hfassold** [comment]
When using CUDA Runtime API only (as OpenCV does i suppose), the context is initialized automatically the first time you call an API function. 
Does each CPU thread use its "own" GPU ? That should work.
But if multiple CPU threads launch kernels on the same GPU in parallel, that generally is dangerous as most kernels are not CPU-thread-safe. This is due to usage of file-static "global" variables like texture references, constant memory etc. See https://devtalk.nvidia.com/default/topic/711438/are-npp-routines-cpu-thread-safe-/
