### ISSUE TITLE
Reject levels of cv::CascadeClassifier::detectMultiScale are erased when skipping groupRectangles

### ISSUE THREAD

**Issue by ShakedDovrat** [opencv/opencv#6185]
I call `cv::CascadeClassifier::detectMultiScale` with `minNeighbors==0` in order to skip `groupRectangles`, while also requesting reject level and weights (by calling the right overloaded method).

Unfortunately, `groupRectangles` overrides all reject levels (variable `weights`) to `1` when `minNeighbors<=0`, as seen here: https://github.com/Itseez/opencv/blob/master/modules/objdetect/src/cascadedetect.cpp#L69
Therefore, I cannot get the reject levels **and** skip grouping.
I seem to miss the benefit of such behavior. If the method should return without running, then the output should be equal to the input. Also note that as oppose to `weights`, the `levelWeights` are not being overridden.

(My motivation in using `detectMultiScale` this way is that I want to call `groupRectangles` independently on the results of `detectMultiScale` and count the number of rectangles grouped in each final rectangle. This metric is a good evaluation to the quality of the detection, other than the reject levels and weights.)

**Comment by ShakedDovrat** [comment]
The only reasonable explanation I could think of for overriding the `weights` (reject levels) to `1` is that the author thought the `weights` indicate the number of rectangles in each grouped detection, which obviously should be `1` for all when the grouping is not done.

**Comment by StevenPuttemans** [comment]
2 ways to handle this in my opinion:

1) Use the overwrite detectMultiScale() function that returns you the amount of overlapping detections, which is unknown to most of the public out there. You can find it [here](https://github.com/Itseez/opencv/blob/master/modules/objdetect/src/cascadedetect.cpp#L1361).

2) Or you could break open the code and supply a PR with a fix.

**Comment by StevenPuttemans** [comment]
But I agree that it is quite the contradictory approach of simply setting it to 1 if you select no grouping.

**Comment by terfendail** [comment]
>  the weights indicate the number of rectangles in each grouped detection

Actually `weights` vector could be used to store number of grouped rectangles at least for other detectMultiScale [mode](http://docs.opencv.org/master/d1/de5/classcv_1_1CascadeClassifier.html#a90fe1b7778bed4a27aa8482e1eecc116)

While I can't consider it a best option to mix different `groupRectangles` function behaviors depending on the input values it is already done. Also `groupRectangles` is a public though not very well documented function so it could be used different way by different people. IMO we should retain as much behavior features as possible and therefore retain weights array initialization, however for described case it's definitely a bug.
`groupRectangles` work in "reject level" mode if there are both `weights` and `levelWeights` vectors which are not empty. And it count grouped rectangles otherwise. So `weights` vector should be initialized in the latter case only.
