### ISSUE TITLE
fitting the code to specific hardware?

### ISSUE THREAD

**Issue by itai257** [opencv/opencv#6323]
Hello,
I have A question about contributing optimization to the openCV code that will run on specific hardware,
does OpenCV have mechanism of fitting the version (at compilation time? at runtime?) to specific Hardware?
Specifically, Can I contribute an optimization that will run only on intel platform ? vectorizing the code (to SSE,AVX,etc)?

**Comment by StevenPuttemans** [comment]
It should be possible in my opinion since when you build OpenCV through CMAKE, you can specify which optimization techniques is supported. For example, take a look at the hits on [SSE search in the code](https://github.com/Itseez/opencv/search?utf8=%E2%9C%93&q=SSE&type=Code). I am sure you can figure out how to do this!

**Comment by mshabunin** [comment]
@itai257 , there is [cv::checkHardwareSupport](http://docs.opencv.org/master/db/de0/group__core__utils.html#ga83400136ccc28490087722ef5b3a27d9) function which returns available CPU features during runtime.

If you want to make very specific platform optimization, please consider using [HAL mechanism](https://github.com/opencv/opencv/tree/master/samples/hal) instead - you will need to create an external library implementing subset of low-level functionality and build OpenCV with it.
