### ISSUE TITLE
Cascade file for face detection

### ISSUE THREAD

**Issue by aiilab** [opencv/opencv#6566]
How to choose the cascade file for face detection? what's the size of training data for haarcascade_frontalface_alt.xml?

**Comment by arpit1997** [comment]
You can choose a haar cascade files based on the input data which you are getting. Suppose you expect you expect only full front face images then you can frontal face cascade file although if you have some other orientation then you can try profile face cascade file.

Choosing the size of training data depends upon how much complex your input image in your program will. for example a banana's picture will have very less feattrained to ure rather than a human's image so human image will be more complex. 

A machine can be trained to recognise a banana with almost 1000 positive images and more or less same number of negative images. But for a human detection this count can go up to 10000 positive images and 15000 negative images

Hope this helps
