### ISSUE TITLE
[keans] "best_compactness" will not be updated in last iteration of for loop

### ISSUE THREAD

**Issue by LinkHS** [opencv/opencv#6614]
### Please state the information for your system
- OpenCV version: 3.1
### In which part of the OpenCV library you got the issue?
- core
- kmeans
### Additional description

```
double cv::kmeans( InputArray _data, int K,
                   InputOutputArray _bestLabels,
                   TermCriteria criteria, int attempts,
                   int flags, OutputArray _centers )
```

the fucntion `double cv::kmeans( InputArray _data, int K...)` in `modules\core\src\kmeans.cpp` returns `best_compactness` at the end as shown below:

```
        if( compactness < best_compactness )
        {
            best_compactness = compactness;
            if( _centers.needed() )
                centers.copyTo(_centers);
            _labels.copyTo(best_labels);
        }
    }

    return best_compactness;
```

But `compactness` will not be updated in last iteration if  meet the condition `++iter == MAX(criteria.maxCount, 2) || max_center_shift <= criteria.epsilon`.

```
            if( ++iter == MAX(criteria.maxCount, 2) || max_center_shift <= criteria.epsilon )
                break;

            // assign labels
            Mat dists(1, N, CV_64F);
            double* dist = dists.ptr<double>(0);
            parallel_for_(Range(0, N),
                         KMeansDistanceComputer(dist, labels, data, centers));
            compactness = 0;
            for( i = 0; i < N; i++ )
            {
                compactness += dist[i];
            }
```

 I think `KMeansDistanceComputer(dist, labels, data, centers));` is needed because the centers of each clusters has been re-computed before checking the if condition.

To make best_compactness be more accuate, should we move the condition check after updating compactness? 

Dawei

**Comment by souch55** [comment]
Hi mshabunin maked the required changes for' [keans] "best_compactness" ',please review and merge my RFC  PR #https://github.com/opencv/opencv/pull/7168,thanks

**Comment by terfendail** [comment]
As far as I could see algorithm do the following(for each attempt):
Stage 0: Prepare initial locations **c(0)** for cluster centers(randomly or in accordance with a-priory labels)
Stage 1a(KMeansDistanceComputer): Prepare new label set **l(1)** in accordance with distances to **c(0)** and measure best compactness as **f( l(1), c(0) )**
Stage 1b: Update cluster center locations to **c(1)** in accordance with **l(1)** and ensure that all K clusters are not empty(since caller requested K clusters)
Stage i(i = 2 to n, applicable if termination criteria for iteration is higher than 2): repeat actions from 1a,1b producing **l(i)**, **f( l(i), c(i-1) )** and **c(i)**

Original implementation stops after evaluating Stage ib. That will be exactly the right result if it stops due to accuracy criteria(so **c(i)** is equal to **c(i-1)** and compactness measure is the same). On the other hand if we stop due to iteration limit the result is just an approximation to the right one and evaluated measure is some approximation to the within-cluster sum of squares so the decision to return **f( l(i+1), c(i) )** instead of **f( l(i), c(i-1) )** is rather a question of iteration counting agreement.

Of course we could update the function to evaluate the compactness measure strictly as within-cluster sum of squares **f( l(i), c(i) )** but that will require additional processing time and provide improvement for iteration terminated evaluations only which anyway produce approximated result.

IMO it would be better to retain the function as is and add a note to function documentation stating how the compactness measure is evaluated in case of iteration based termination.
