### ISSUE TITLE
On high resultion jpg files imread/imwrite changes the image orientation. 

### ISSUE THREAD

**Issue by Suberri** [opencv/opencv#6723]
### Please state the information for your system
- OpenCV version: 2.4.13
- Host OS:  Windows 8.1
- python 2.7
- Windows photo viewer to view the images.

### In which part of the OpenCV library you got the issue?
Examples:
- imread, imwrite 

### Expected behaviour
. step 1 - reading an image (1-0.jpg)
. step 2 - writing the same image back (1-1.jpg)
. step 3 - picture orientation should stay the same

### Actual behaviour
. step 3 - on pictures that were taken from high resolution camera the picture orientation is changing 

### Additional description
After the imread,imwrite operation the viewer shows the photo in a different orientation and the picture size is cut by half.
If I first open the picture in Windows Paint and save it and then do imread,imwrite the orientation does not change and the file size stay the same.

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
=====================
import numpy as np
import cv2

img = cv2.imread('1-0.jpg')
cv2.imwrite('1-1.jpg',img)

=====================================================

1-0.jpg size =  19.1 MB (20,065,690 bytes)
1-1.jpg size =  9.05 MB (9,492,507 bytes)

**Comment by alalek** [comment]
1) "imread" in OpenCV 2.4 doesn't use EXIF information which is related to camera orientation. It just read image data "as is". OpenCV 3.1 has basic support for EXIF reading.
2) "imwrite" always re-encode image data (with some parameters which is not same as for original image, so image quality may be reduced).
3) "imwrite" doesn't write any EXIF information (so original EXIF information is lost).
4) JPEG is not lossless format in general. You should use PNG or similar if you want bit-exact results.

> picture size is cut by half

I believe you mean file size here instead of picture/image size.


P.S. Usage questions should live on Q/A forum (http://answers.opencv.org) instead of this bug/features tracker.
