### ISSUE TITLE
StereoBM disparityMap resolution (CV_16U) seams low

### ISSUE THREAD

**Issue by LeoBras** [opencv/opencv#6898]
- OpenCV => 3.1
- Operating System / Platform => Linux x86_64 (Arch)
- Compiler => GCC 6

##### Detailed description

I am on a Stereo Camera project using OpenCV (StereoBM) + PCL (Only for Visualization ).

I was filtering some points do estimate a plane's normal vector, and as result I was getting  a noisy normal vector. Trying to understand better the problem I got this Point Cloud from PCL Visualizer :
![point_cloud](https://cloud.githubusercontent.com/assets/19741247/16806852/a5f61e1e-48ec-11e6-968e-52d92fc92766.png)

Tracing back the error,  I got that the disparity map from StereoBM was causing the small 'steps' on my point cloud. It seems it's on the resolution limit (ex.: disparity values jumping from 876 to 877).

In visualization, I could see that the points in border between the 'steps' are changing up and down, very much. I believe it's due to small noise and truncating. 

I know that StereoBM output is a CV_16U Mat, is there a way to change the type to CV_32U or float, so we can get better resolution?

I know the output of compute (in stereoBM) can be a Mat either CV_16U or float, but it seems it don't raise the resolution, just translate the final int value to a float value. 

I believe it's a feature request, sorry if I miss some obvious thing and I am just being a noob). 

Thanks !

**Comment by mshabunin** [comment]
@snosov1 , could you please comment on this?

**Comment by snosov1** [comment]
I'm not sure I understand the use case fully, but I'll try to provide some explanation of how StereoBM works.

Current StereoBM implementation evaluates disparity with 1/16px precision, i.e. the values 876 and 877 correspond to disparity values of 54.75 and 54.8125. In theory, the precision could be made even higher - say, 1/32px. But practically, I doubt that doing this will actually increase the quality.

For the sake of experiment, you could try to upscale your input images with a 2x factor and see if it helps (After the upscale, it kind of makes the 1/16px precision in the bigger images to correspond to 1/32px precision in the original images).

**Comment by LeoBras** [comment]
I have tried to upscale the images, but I don't see significant quality increasing. By results only, would say I get 2x the precision, so it's around 1/17px.

Where can I find information (like the original Paper) about the StereoBM algorithm ? Maybe I can use it better if I get o understand it.

Thanks!

**Comment by snosov1** [comment]
> I have tried to upscale the images, but I don't see significant quality increasing.

Yeah, that's kind of the point. When you upscale the images you don't actually introduce new visual information, you only increase the "interpolation rate". If you would actually shoot the higher resolution images (not simply upscale them) - you could, actually, get a better precision. 

So, it kind of shows that having a higher precision in the algorithm won't necessarily produce more accurate results.

> By results only, would say I get 2x the precision, so it's around 1/17px.

2x precision increase should be 1/32px =)

> Where can I find information (like the original Paper) about the StereoBM algorithm ? Maybe I can use it better if I get o understand it.

That could be tough =) The algorithm is pretty simple and straightforward, to the extent where people consider it obvious enough to not describe it in details. From the top of google, one link looks like a useful one for a novice in the subject:

http://mccormickml.com/2014/01/10/stereo-vision-tutorial-part-i/

For something more fundamental, obviously, http://szeliski.org/Book/ will be a good place to look.

Summarizing, I think we can close the issue as "won't fix" for now. Agree?

**Comment by LeoBras** [comment]
Sorry, I think I misinterpreted your previous message. 

The implementation appear to use 4 from the 16 bits to decimal point (0,0625).
If 1px is 1 mm, the depth resolution would be 1/16 == 0,0625mm. And so, the maximum depth would be 2^12 == 4096 mm, is it right?

What you recommend is to get higher resolution images, so this 1px woud be, for example, equivalent to 0.5mm. Then my depth resolution would be 0.5/16 == 0,03125, and my max depth would be 0.5 * 2^12 == 2048mm. 

If I interpreted it right, and my calculations are correct, I would get twice the resolution and use 4 times more processing and memory. By using a 32 bit variable, I would use twice the memory, but be able to store depth with more resolution and max depth. (Of course the precision would be limited to Algorithm's precision).

Well I don't know if the algorithm would benefit for more resolution and maximum depth, but I have seen on my application that I get truncated values that I wouldn't see if there were an option to have more resolution.

Anyway, thanks!

**Comment by snosov1** [comment]
> If I interpreted it right, and my calculations are correct,

The interpretation is not entirely correct. 1px can actually be equal to different lengths in mm depending how big the number is, i.e. the farther the object - the bigger is the error. But for the sake of this discussion - yes, you can think that 1px is equal to 1mm in the real world.

> If I interpreted it right, and my calculations are correct, I would get twice the resolution and use 4 times more processing and memory. By using a 32 bit variable, I would use twice the memory, but be able to store depth with more resolution and max depth. (Of course the precision would be limited to Algorithm's precision).

Yeah, that's totally correct. I proposed to upscale the input images only for the sake of argument, to show that 1/16px precision is already much lower than the algorithm accuracy. So, it doesn't make sense to use an even finer precision (BTW, it's not even necessary to use 32 bits instead of 16 to do this).

>  Well I don't know if the algorithm would benefit for more resolution and maximum depth, 

It would, if it would've been a more accurate algorithm (I'm not sure such precise algorithms for stereo matching exist at all). For the current StereoBM implementation, it doesn't make a lot of sense.

> but I have seen on my application that I get truncated values that I wouldn't see if there were an option to have more resolution.

Since the algorithm is unable to improve the resolution, you can do this as a post-processing step by yourself. For example, to add one bit of precision, you can multiply the resulting image by 2 and apply box-filter (or gaussian blur, or whatever you prefer).

**Comment by LeoBras** [comment]
> (...) to show that 1/16px precision is already much lower than the algorithm accuracy. So, it doesn't make sense to use an even finer precision (...).

But when I upscaled, I got 2x the precision, as I said before.

> (...) For the current StereoBM implementation, it doesn't make a lot of sense.

It seems to make sense, as in some cases (like mine) I could get more precision than the 16 bit variable could store. As shown when I upscaled the image.

Thanks

**Comment by snosov1** [comment]
> It seems to make sense, as in some cases (like mine) I could get more precision than the 16 bit variable could store. As shown when I upscaled the image.

That's kind of a separate matter. You increase the resolution of the storage format. As a simplified example - let's say we have an algorithm that evaluates something with 1px accuracy. We can store the result using integer types, but we can use floats, doubles or long doubles. Technically, the precision of the output is increased, but the accuracy is not - since the accuracy of the algorithm is 1px and the ability to store sub-pixel values is redundant in this case. So, there's not much sense for the algorithm to use long doubles if it can't effectively use the increase in precision. 

If you need a higher precision after the algorithm evaluation - you can convert the result to double or whatever you want and make some kind of smoothing/interpolation. But, again, it doesn't make a lot of sense to make this a part of the algorithm, since it can't effectively use the increased precision.

In case of stereoBM - the algorithm can't really provide an accuracy higher than 1/16px. So, making the output 1/32px _inside the algorithm_ is useless - it can't make good use of the additional bits. However, if you want to increase the precision as a post-processing step - you are free to do this. Hence, my suggestion: 

> Since the algorithm is unable to improve the resolution, you can do this as a post-processing step by yourself. For example, to add one bit of precision, you can multiply the resulting image by 2 and apply box-filter (or gaussian blur, or whatever you prefer).

The effect will be similar to the upscaling procedure I suggested originally.

**Comment by mshabunin** [comment]
@LeoBras , check out the disparity filtering algorithm implemented last year during Google Summer of Code, it can be found in the [opencv_contrib](https://github.com/opencv/opencv_contrib) repository. 
Here is the example: https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/samples/disparity_filtering.cpp
And the tutorial: http://docs.opencv.org/master/d3/d14/tutorial_ximgproc_disparity_filtering.html#gsc.tab=0

**Comment by LeoBras** [comment]
@mshabunin Thanks! I was using it already.
My main problem is that I get the same problem in both filtered and unfiltered disparity maps, which are these little 'steps' you can  see on the first post, and seem to make noise very hard to threat.
