### ISSUE TITLE
Is masked matchTemplate implementation correct?

### ISSUE THREAD

**Issue by snosov1** [opencv/opencv#6919]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform / Compiler => any
##### Detailed description
#6773 has brought a couple of question about masked matchTemplate implementation.
1. The `CV_8U` and `CV_32F` masks seem to be treated differently. `CV_8U` mask is treated as binary, but in case of a `CV_32F` mask, the template pixels will be multiplied by the mask values (presumably, in [0..1] range). Is that intended? See https://github.com/opencv/opencv/blob/master/modules/imgproc/src/templmatch.cpp#L860
2. I'm in doubt regarding the implementation correctness:
   1. For CV_TM_CCORR_NORMED metric, I would expect that the implementation will simply multiply the template by mask. But it does something more involved.
   2. For CV_TM_SQDIFF metric, I would expect it to multiply the squared bracket by mask. It looks like the implementation tries to replace the square of sum into separate units and multiply them by mask individually. But to me, the evaluation doesn't look correct.

@vpisarev, are you familiar with the implementation? Can you comment on this? Also, it looks like @wangyan42164 is the author of the implementation. Is that so? If yes, can you, please, comment as well?

**Comment by ai-snow** [comment]
@snosov1 I may have run into a similar thoughts concerning the correctness of the implementation.

OpenCV => 3.3
Operating System => Windows

Here's 2 scenarios:

1. No mask
2. With mask

Both scenarios produce identical results no matter the main image and template image are supplied, and for various masks.  It is as if the mask is just ignored.

**Comment by jumostedu** [comment]
The current implementation of `matchTemplate()` with a mask indeed seems to not really do a masking as expected. Furthermore there is no documentation, so it is hard to trace what the code author actually intended that the function should do. I have (re)implemented the whole masked template matching for all methods, with documentation, and with tests, so I am quite confident that it does what I want: #15214

**Comment by Jordak** [comment]
I also have a concern about the correctness of `matchTemplateMask`. Specifically, here:
https://github.com/opencv/opencv/blob/5dd3e6052ed9e614cf4303eee64d092fefbabd8e/modules/imgproc/src/templmatch.cpp#L764-L770

We have defined `type` to be the type of `img`, and `ttype` to be the type of `templ`. But then we define `mtype` to be again the type of `img` instead of `mask` (and subsequently `mdepth` and `mcn` are based on `img` as well). Then further down, we use `mdepth` to know whether or not we want to convert the `mask`, even though `mdepth` has information about `img`, not `mask`:
https://github.com/opencv/opencv/blob/5dd3e6052ed9e614cf4303eee64d092fefbabd8e/modules/imgproc/src/templmatch.cpp#L786-L792

I only have a very basic understanding of how this image processing works, but this strikes me as a typo. It seems to me that `mtype` was supposed to be the type of `mask` instead of `img`, especially since we already have a variable `type` to represent the image type, and we could have easily combined `if` blocks. Can somebody here either confirm my suspicions, or let me know why I'm wrong? Thanks in advance!

**Comment by alalek** [comment]
@Jordak You can try this proposed patch: #15214 (linked above)
