### ISSUE TITLE
Matlab Installation not found on OS "X El Capitan" with current code of OpenCVFindMatlab.cmake 

### ISSUE THREAD

**Issue by l33tl4bs** [opencv/opencv#7003]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => OS X El Capitan 10.11.3
- Compiler => Xcode 7.3.1 - Apple LLVM version 7.3.0 (clang-703.0.31)

##### Detailed description

This line in OpenCVFindMatlab.cmake does not find an existing Matlab installation:
```
file(GLOB MATLAB_ROOT_DIR_ ${DIR_}/MATLAB/R*)
```

However, changing it to the following finds the installation correctly:
```
file(GLOB MATLAB_ROOT_DIR_ ${DIR_}/MATLAB_R*)
```

**Comment by ilya-lavrenov** [comment]
@l33tl4bs, can you provide Matlab version you use?

**Comment by l33tl4bs** [comment]
R2016A

**Comment by alalek** [comment]
Looks like this version is not supported. The latest supported version is 2014: https://github.com/opencv/opencv_contrib/issues/634
Closing this issue, because Mathlab bindings/issues are located in [opencv_contrib](https://github.com/opencv/opencv_contrib/issues?utf8=%E2%9C%93&q=is%3Aissue%20matlab%20) repository.

**Comment by l33tl4bs** [comment]
I'm not sure what being supported would mean but after the described modification and build everything works perfectly in R2016A.

**Comment by alalek** [comment]
@l33tl4bs Thanks! Could you take a look on this patch #7212?

**Comment by l33tl4bs** [comment]
Tested. Works as expected.

**Comment by alalek** [comment]
Thank you!
