### ISSUE TITLE
Some thing in HOG,I think may be a bug.

### ISSUE THREAD

**Issue by eshaoliu** [opencv/opencv#7036]
Sorry,I'm not sure whether my question should be asked here or not.But due to the problem of China's Internet,I fail to registor an account in http://answers.opencv.org/.
I didn't find the problem when I run certain code,but when I  read the code in opencv/modules/objdetect/src/hog.cpp(https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp )The method 
void HOGDescriptor::computeGradient(const Mat& img, Mat& grad, Mat& qangle,
    Size paddingTL, Size paddingBR) const
After calculating the gradient Dx,Dy,we need to convert the to magnitude and angle.
Just as the following codes in line 478 do 
 cartToPolar( Dx, Dy, Mag, Angle, false );
After that,we do the following things to make serveral changes to  angles and put the angles into 9 bins.
for( ; x < width; x++ )
        {
            float mag = dbuf[x+width_2], angle = dbuf[x+width_3]*angleScale - 0.5f;
.....
From here,I know you must take the variable Angle is in range [-pi/2,pi/2],
but  after my test,carToPolar function changes the angle to[0,2pi],and the documentation(http://www.opencv.org.cn/opencvdoc/2.3.2/html/modules/core/doc/operations_on_arrays.html?highlight=carttopolar#cv2.cartToPolar  )implicates the same,
 Such code occurs in all opencv versions,I'm not sure if it is 
a bug.Maybe my understanding is wrong.

**Comment by StevenPuttemans** [comment]
If you take absolute values, the range [-pi/2, pi/2] can be mapped to [0, pi/2]. I think that is what happening here. But let me take a closer look and get back to you!

**Comment by StevenPuttemans** [comment]
O well, the original paper of Dallal and Triggs suggest to map between [0,180] degrees. Because the [180, 360] degree bins are essentially the same gradient directions. Looking at the [most recent docs](http://docs.opencv.org/master/d2/de8/group__core__array.html#gac5f92f48ec32cacf5275969c33ee837d&gsc.tab=0) the cartToPolar function does map to [0,2PI] so I guess you are just looking at old docs and deprecated code!

Guess this can be closed!

**Comment by gylns** [comment]
> for( ; x < width; x++ )
{
float mag = dbuf[x+width2], angle = dbuf[x+width3]*angleScale - 0.5f;
.....
From here,I know you must take the variable Angle is in range [-pi/2,pi/2]

why I must take the variable Angle in range [-pi/2,pi/2]?

**Comment by StevenPuttemans** [comment]
Because that is 180 degrees. and thus will capture all orientations possible. It is just how it is programmed and due to the fact that the origin of an image is in upper left corner, with y axis pointing downwards.

**Comment by eshaoliu** [comment]
Old docs and deprecated code?YES,I am using 2.4.9 .
However,I am testing cartTopolar just in version 2.4.9,its range is just [0,2*pi].
As to HOG code,
this is the old version 2.4.9
#else
        cartToPolar( Dx, Dy, Mag, Angle, false );
#endif
        for( x = 0; x < width; x++ )
        {
#ifdef HAVE_IPP
            int hidx = (int)pHidxs[x];
#else
            float mag = dbuf[x+width*2], angle = dbuf[x+width*3]*angleScale - 0.5f;
            int hidx = cvFloor(angle);
            angle -= hidx;
            gradPtr[x*2] = mag*(1.f - angle);
            gradPtr[x*2+1] = mag*angle;
#endif
            if( hidx < 0 )
                hidx += _nbins;
            else if( hidx >= _nbins )
                hidx -= _nbins;
            assert( (unsigned)hidx < (unsigned)_nbins );

            qanglePtr[x*2] = (uchar)hidx;
            hidx++;
            hidx &= hidx < _nbins ? -1 : 0;
            qanglePtr[x*2+1] = (uchar)hidx;
        }
    }
}
This is the  newest version  at https://github.com/opencv/opencv/blob/master/modules/objdetect/src/hog.cpp as follows，
we can see that the mean idea are the same.
       // computing angles and magnidutes
        cartToPolar( Dx, Dy, Mag, Angle, false );

        // filling the result matrix
        x = 0;
#if CV_SSE2
        ....codes for optimization,doesn't affact the main process...
#endif
        for( ; x < width; x++ )
        {
            float mag = dbuf[x+width*2], angle = dbuf[x+width*3]*angleScale - 0.5f;
            int hidx = cvFloor(angle);
            angle -= hidx;
            gradPtr[x*2] = mag*(1.f - angle);
            gradPtr[x*2+1] = mag*angle;

            if( hidx < 0 )
                hidx += nbins;
            else if( hidx >= nbins )
                hidx -= nbins;

            CV_Assert( (unsigned)hidx < (unsigned)nbins );

            qanglePtr[x*2] = (uchar)hidx;
            hidx++;
            hidx &= hidx < nbins ? -1 : 0;
            qanglePtr[x*2+1] = (uchar)hidx;
        }
    }
The main ideas are the same.the difference between them is just optimization MACRO part which I don't care about.
Why [-pi/2,pi/2]?
Mag and dbuf+width*2 share same address,Angle and dbuf+width*3 share same address.
Only if the Angle range is [-pi/2,pi/2] ,then
'float mag = dbuf[x+width*2], angle = dbuf[x+width*3]*angleScale - 0.5f;
  int hidx = cvFloor(angle);
  angle -= hidx;
  gradPtr[x*2] = mag*(1.f - angle);
  gradPtr[x*2+1] = mag*angle;
" makes sense.

**Comment by StevenPuttemans** [comment]
Ok let me reply so some stuff

> Old docs and deprecated code?YES,I am using 2.4.9.

Why would you do that. We are now at the 2.4.13 branch and actually OpenCV moved on to the OpenCV 3.x interface. You are using code that is still full of bugs, errors and stuff that is not fixed yet. My guess, but probably the right one, is that in between 2.4.9 and 3.1, someone already found this bug and adjusted the cartToPolar to have the correct range. Thats why the most recent code is correct and yours is not.

> Why [-pi/2,pi/2]?

Again, as stated before, because in order to capture all orientations between 0-360 degrees, you need to capture 0-180 degrees. This also covers the 180-360 degree angles because for orientation binning, you are not interested in vector direction, only in vector angle.

Furthermore due to the origin being at the top left corner, -pi/2 --> pi/2 is exactly the range that covers all possible bins. It could also have been from 0 --> pi, but they chose not too. Its just a matter of preference I guess...

**Comment by eshaoliu** [comment]
Well,when I check out the newest version [3.1](https://github.com/opencv/opencv/blob/3.1.0/modules/objdetect/src/hog.cpp) the same part of HOG code is the same,and cartToPolar, FastAtan2 also have no changes from 2.4->3.1,they all return range [0,2*pi].From I know,hog is a method of feature descriptor,its result is fed into classifier.When it goes wrong,it may not occur compiling error or runtime error,it should just reduce the accuracy of recognizing pedestrian and look like everthing is ok.But in theory,it goes wrong,I guess.

**Comment by vpisarev** [comment]
I checked the code and it appears to work correctly whenever signedGradient=false or true.
