### ISSUE TITLE
the description of IMWRITE_PNG_COMPRESSION is wrong

### ISSUE THREAD

**Issue by atinfinity** [opencv/opencv#7310]
##### System information (version)

I checked the following environment.
- OpenCV => 3.1
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2013
##### Detailed description

The description of [document](http://docs.opencv.org/3.1.0/d4/da8/group__imgcodecs.html#gga292d81be8d76901bff7988d18d2b42acad2548321c69ab9c0582fd51e75ace1d0) is as follows.

> Default value is 3.

But, <code>compression_level</code> is set to <code>Z_BEST_SPEED</code>(=1) in [grfmt_png.cpp](https://github.com/opencv/opencv/blob/3.1.0/modules/imgcodecs/src/grfmt_png.cpp#L407).
So, I think that the description of <code>IMWRITE_PNG_COMPRESSION</code> is wrong.

**Comment by StevenPuttemans** [comment]
Actually, I think this is a bug in the code itself, becaue the Z_BEST_SPEED is another parameter than the compression level. That one should be replaced.

But looking at the actual default value, on the [following line](https://github.com/opencv/opencv/blob/1e17ffe9ac5bfa6cb834afdaffeab6f444c0a92e/modules/imgcodecs/src/grfmt_png.cpp#L381) we define the compression level for a first time as `compression_level = MIN(MAX(compression_level, 0), Z_BEST_COMPRESSION);` since compression_level is by default -1, if the level is not specified explicitly, it will take the minimum value as Z_BEST_COMPRESSION. And that value is set to 9 by default [here](https://github.com/opencv/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/3rdparty/zlib/zlib.h#L188). The docs should thus state that the default value is 9, and not 3. 

Can you provide a PR with a fix?

**Comment by StevenPuttemans** [comment]
Also, to my best understanding, i dont know if the second case, the else is actually ever hit inside the code 

https://github.com/opencv/opencv/blob/1e17ffe9ac5bfa6cb834afdaffeab6f444c0a92e/modules/imgcodecs/src/grfmt_png.cpp#L400

**Comment by alalek** [comment]
Related issue: #6729 , fix: #6730

**Comment by StevenPuttemans** [comment]
True, but the default value is still at 3 there while it is not by default right?

**Comment by saskatchewancatch** [comment]
Some of my thoughts:

1. `Z_BEST_SPEED` is a constant specifying a compression setting, one of 4 conveniently defined in [zlib.h](https://github.com/opencv/opencv/blob/3.1.0/3rdparty/zlib/zlib.h#L190).

2. The `else` block ([see here](https://github.com/opencv/opencv/blob/1e17ffe9ac5bfa6cb834afdaffeab6f444c0a92e/modules/imgcodecs/src/grfmt_png.cpp#L400) gets hit if you don't specify `IMWRITE_PNG_COMPRESSION` and the png compression level gets set to `Z_BEST_SPEED`, which is defined as `#define Z_BEST_SPEED 1` in  ([zlib](https://github.com/opencv/opencv/blob/3.1.0/3rdparty/zlib/zlib.h#L189)). Hence, if we were to update the doc, it would be to say that the default compression level is 1.

Right?
