### ISSUE TITLE
add more binarization algorithms

### ISSUE THREAD

**Issue by andrewluetgers** [opencv/opencv#7315]
Binarization is a key early step for many processes so improvements here can have a large impact on an end result. Otsu is a good all around algorithm and very fast but there are [many improvements in this space](https://www.irjet.net/archives/V3/i3/IRJET-V3I3241.pdf). 

I have submitted a [PR of Niblack based algorithms](https://github.com/creatale/node-dv/pull/41) to the Node DV project but am now thinking they properly belong here instead. My focus has been on document processing and would love some guidance on weather this is a good add for OpenCV before I work on a PR. 

Would love to hear if others have more advanced code up their sleeves as well, Wolf and Nick are great but not the state of the art. 

Here is a sample of the differences between the algorithms from the above linked PR

![](https://cloud.githubusercontent.com/assets/232036/18606757/635bc052-7c7e-11e6-84df-0527e14cd772.png)

**Comment by alalek** [comment]
Feel free to [contribute](https://github.com/opencv/opencv/wiki/How_to_contribute) into [opencv_contrib](https://github.com/opencv/opencv_contrib) repository.
Some implementation of Niblack algorithm is available [here](https://github.com/opencv/opencv_contrib/blob/246ea8f3bdf174a2aad6216c2601e3a93bf75c29/modules/ximgproc/include/opencv2/ximgproc.hpp#L77-L105).

**Comment by kinchungwong** [comment]
If you would like a survey of document binarization algorithms, please take a look at the following conferences and algorithm competitions:

 * ICDAR - International Conference on Document Analysis and Recognition
 * DIBCO - Document Image Binarization Contest

The relevant implementation papers, surveys and reports might be behind paywall. Perhaps you can work with some members of academia to get full access to these resources, which will give you an informed choice on where to focus your OpenCV contribution efforts.

Historically, the open source community tend to associate document imaging related algorithms more with Leptonica than with OpenCV due to a widely perceived specialization of purposes. Now that there is a convergence of vision with document understanding, I am sure that end-users will appreciate better interoperability between the two libraries.

**Comment by sturkmen72** [comment]
The algorithms are already implemented in contrib module

**Comment by andrewluetgers** [comment]
@sturkmen72 having trouble finding where these are implemented in contrib, a link would be great
