### ISSUE TITLE
openNI

### ISSUE THREAD

**Issue by PMARINA** [opencv/opencv#7352]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Didn't even get to this part

##### Detailed description

In [documentation](http://docs.opencv.org/2.4/doc/tutorials/introduction/windows_install/windows_install.html) , under instructions to compile open cv for other versions of python or to just compile it yourself, it states that openNI framework is requireed. When the links for openNI are clicked, they lead to [apple's website](http://www.apple.com/), either to the main page, or to an error 404. This is a huge part of the process and I really would appreciate help with finding a proper installation source. I attempted to use some versions found online; however, those either run different versions for the prime sensor and development build or their installer just fails. It took me about 10 hours to get to this point, and another 2 hours to attempt to fix the issue with openNI. Please fix ASAP.

##### Steps to reproduce
Just follow your own instructions -- 6h

**Comment by kinchungwong** [comment]
If you do not need OpenNI (note: the documentation did not say it is required), you should uncheck the WITH_OPENNI checkbox when configuring the project in CMake. OpenCV should be able to build without OpenNI. In general, you should be able to uncheck anything you don't have, or anything you don't plan to use.

If there are still issues, please post your "CMakeCache.txt" which is useful for troubleshooting. If you see compiler errors, please also post them here.

When choosing the output directory in CMake ("Where to build the binaries"), you should either use a newly created directory, or manually empty the directory before using it in CMake. This is because some pre-existing files in that output directory will be picked up by CMake.

If you need OpenNI, unfortunately this project has been shut down by Apple after PrimeSense was acquired. Several organizations provide access to archived versions of OpenNI.

(I'm not familiar with OpenNI. This answer is based on information I find on the internet.)

**Comment by StevenPuttemans** [comment]
Well the official docs are these: http://docs.opencv.org/master/d3/d52/tutorial_windows_install.html

But the issue is still there also, so I will make a PR to change this issue.

**Comment by StevenPuttemans** [comment]
Oh btw, you can find OpenNI binaries here: http://structure.io/openni
