### ISSUE TITLE
Add template<> class DataType<long> to traits.hpp

### ISSUE THREAD

**Issue by hallonterror** [opencv/opencv#7357]
##### System information (version)
- OpenCV => 3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2010

##### Detailed description

We have a multi platform solution that implements a special typedef int32 to bridge over the differences between different compilers in terms of int vs long naming.

Our int32 is always 32 bits or 4 bytes long. That is, it is compatible with the CV_32S datatype.

On Win32, GCC and with INTEL64 compilers we see no problems in using our datatype for cv::Mat. We can even do indexing into images using mat.at<int32>(y, x).

However, on Win64 it seems that the int32 type which evaluates to long does not properly match to the predefined template<> class DataType<int> in traits.hpp. As it apparently it does on other platforms/compilers. Just to be sure I checked the sizeof(long) on Win64 and it is 4 bytes. The result from OpenCV when running is the following message when attempting to do indexing of a matrix.

`OpenCV Error: Assertion failed (dims <= 2 && data && (unsigned)i0 < (unsigned)size.p[0] && (unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels()) && ((((sizeof(size_t)<<28)|0x8442211) >> ((DataType<_Tp>::depth) & ((1 << 3) - 1))*4) & 15) == elemSize1()) in cv::Mat::at, file e:\hudsonslave\bundles\workspace\machvis_bundle_win64\libs\opencv\include\opencv2\core\mat.inl.hpp, line 894`

And is caused by CV_ELEM_SIZE1(cv::DataType<int32>::depth) returning 8 instead of 4, which in turn is caused by cv::DataType<int32>::depth returning -1 instead of CV_32S.

##### Steps to reproduce

1. Create a cv matrix of type long.
2. Attempt to index the matrix by calling `mat.at<long>(y, x)`.
3. Run the code in Debug mode (the problem is a debug assert).

##### Suggested patch
Add the following template definition to traits.hpp:

`#if !(defined __x86_64 || defined __powerpc64__ || defined _LP64 || defined __LP64__)`
`template<> class DataType<long>`
`{`
`public:`
`  typedef long value_type;`
`  typedef value_type work_type;`
`  typedef value_type channel_type;`
`  typedef value_type vec_type;`
`  enum {`
`    generic_type = 0,`
`    depth = CV_32S,`
`    channels = 1,`
`    fmt = (int)'i',`
`    type = CV_MAKETYPE(depth, channels)`
`  };`
`};`
`#endif`

The `#ifdef` should possibly be changed to use some other flag that is available already by the OpenCV build. Here is a good list for different sizes of the long datatype to isolate the different cases:
https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os

Of course there might be a better solution to this problem...

**Comment by ilya-lavrenov** [comment]
@hallonterror, please, create MR with proposed changes.

**Comment by hallonterror** [comment]
@ilya-lavrenov 

I have re-contemplated, discussed it with my colleagues and we believe that it might be better if we handle this on our end. It seems bad to adjust for this case in OpenCV itself as it is a quite specific use case.

It might be enough that other people can find the solution to the problem if they get this error message. It is really just a matter of specifying this template specialization in another location or avoiding the specific types not already declared.

From my end this topic can be closed. If you still want a MR I can try to manage that before the end of the week.

Best Regards, Daniel

**Comment by kinchungwong** [comment]
This is just my technical point of view. Please do not take this as harsh criticism. I have researched and experimented this issue for some time and here are my findings.

If this is due to headers that are similar to boost/cstdint.hpp (http://www.boost.org/doc/libs/1_62_0/boost/cstdint.hpp), it may be worth considering updating to their latest versions. To summarize, it is preferable to use 32-bit int before using 32-bit long, even if both types have the same number of bits and have the same arithmetic behavior. Very early versions of Boost "cstdint.hpp" preferred 32-bit long to 32-bit int, which may have created the technical debt you're faced with.

Boost's current version of "cstdint.hpp" takes the approach of comparing `INT_MAX` with `LONG_MAX` in the preprocessor, and likewise `INT_MIN` with `LONG_MIN`, to make sure they are losslessly inter-convertible, before considering either one to be eligible as a substitute for the other.

As far as C++ is concerned, int and long are different types, as in 
```
std::is_same<int, long>::value
```
giving false, even on platforms where `int` and `long` are both 32-bit.

In fact, Visual C++ on Windows on Intel-based architecture is one such platform where such redefinition of fundamental types are unnecessary and maybe harmful.

Before adding that change to "traits.hpp", please fully understand the existing definitions in "core/hal/interface.h" (https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/interface.h), which plays a similar role as Boost's "cstdint.hpp" which I linked above.

The reason that adding a `DataType<long>` works is because OpenCV API functions accept `cv::InputArray`, which performs type erasure according to `cv::DataType` traits. Thus, it can accept a `cv::Mat_<long>` as input, while returning a `cv::Mat_<int>` to the implementation of the OpenCV API function. This would not be the case with normal C++ functions: you cannot pass `cv::Mat_<long>` argument directly to a C++ function that expects a `const cv::Mat_<int> &`, even if the `DataType<long>` template is added.

**Comment by hallonterror** [comment]
Hello I think I should clarify my position.

I agree that it should be prefered to use inte instead of long. I also understand why long and int are not the same type although they are both signed and 32 bits.

My original inquiry was if we could allow ourselves to have both template specializations in case the long type has the appropriate size.

Good tip about boost. For our part this is not the reason, but rather our own typedefs for different platforms. Currently I have put forward a change request internally to change the type to int. If this does not happen I will specify the specialization locally.

From my point there is no need to add the long template specialization in OpenCV, I actually consider it a bad idea after some thought. As such I agree with every word you wrote @kinchungwong.

I do not take offense. Thanks for writing a clear explanation!
