### ISSUE TITLE
import cv2  raise importerror

### ISSUE THREAD

**Issue by saicoco** [opencv/opencv#7666]
##### System information (15.10)
- OpenCV => 3.1
- ubuntu 15.10
- Compiler => gcc 4.7

##### Detailed description  
When I have compiled opencv3.1, and I use it with `caffe`, c++ API is okay, however, python's API will be raise error.  
~~~
In [3]: import cv2
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-72fbbcfe2587> in <module>()
----> 1 import cv2

ImportError: /usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: cairo_surface_get_device_scale

~~~  

Just Find the solution everywhere, however it's nothing

**Comment by StevenPuttemans** [comment]
I am pretty sure, that it is because of a mismatch between your compiler and the caffe version. Take a look to the suggestions here: https://github.com/BVLC/caffe/issues/3932

**Comment by Karim-92** [comment]
I'm getting the same error but I'm not using it with Caffe, my system's running Ubuntu16.04 LTS and using Anaconda with python 2.7.12  & gcc 5.3.1. It's very frustrating indeed.

**Comment by Karim-92** [comment]
Here's what solved the error for me, apparently there are symbolic link issues with the cv2.so that you compile on your system, instead of linking to libgdk-x11-2.0.so.0 and libgtk-x11-2.0.so.0 it links to libgdk-3.so.0 and libgtk-3.so.0.

Back up those files i mention before you proceed in case you want to rollback if it doesn't work. The solution was to run the following line: conda install -c menpo opencv3=3.1.0 .. this will install the opencv 3.1 into your anaconda2 (Which I'm assuming you're using). This one installs with the correct links and will work immediately. You can then go to opencv->build->libs and copy the cv2.so to replace the one in anaconda2/libs/python2.7/site-packages to ensure it matches the one you built, it'll have the correct symbolic links as well.

**Comment by saicoco** [comment]
Thanks a lot!@Karim-92 @StevenEWright ,there are gcc-4.7 and gcc-5.3 in my system, and I alternativly config them， it maybe make this trouble,  and I just reinstall opencv in your way @Karim-92, it works. Thanks so much~

**Comment by lwkobe** [comment]
@Karim-92 Did you build the opencv yourself and with anaconda?

**Comment by Karim-92** [comment]
@lwkobe Yes I did.

**Comment by DreamInSun** [comment]
It is weird! It comes to the same problem to me. But it does have a walk around. if I run python on the path '/usr/lib/x86_64-linux-gnu' . the command "import cv2" works well. so I was doubt if is the python loading path error.  I'm using conda, when I was compiling opencv, the default PYTHON3_LIBRARY_PATH is "/usr/lib/x86_64-linux-gnu/libpython3.5m.so", not the conda path.

**Comment by TonyTangYu** [comment]
@Karim-92  I get the same error when I run 'import cv2' today. But I install opencv-3.1.0 by compiling its source code. But I still get the same problem.
