### ISSUE TITLE
error  cvCaptureFromCAM(CV_CAP_ANY); cvCreateFileCapture("‪x.avi"); with Logitech HD1080p

### ISSUE THREAD

**Issue by zkl99999** [opencv/opencv#7723]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

open video file or WebCam, occuring error:

![image](https://cloud.githubusercontent.com/assets/10251153/20613272/4f8f17bc-b2fd-11e6-9ba8-40744ac73338.png)
![image](https://cloud.githubusercontent.com/assets/10251153/20613274/567f6662-b2fd-11e6-97ba-49e7e8a42a6d.png)
![image](https://cloud.githubusercontent.com/assets/10251153/20613278/60439d30-b2fd-11e6-9667-fb20b5f664e9.png)

**Comment by zkl99999** [comment]
#include "stdafx.h"

#include <iostream>
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"
#include <stdio.h>


using namespace cv;
using namespace std;

int main()
{
	/*
	
	//VideoCapture capture(0);
	//获取摄像头  
	cvNamedWindow("video", 0);
	CvCapture* capture = 0;
	//capture = cvCaptureFromCAM(CV_CAP_ANY);
	capture = cvCreateFileCapture("‪people.avi");
	
	if (capture ==NULL)
	{
		printf("xxx");
	}

	IplImage *image = NULL;
	while (1) {
		image = cvQueryFrame(capture);    //这里不进行内存的重新分配 这里是两种方法哦  
		//cvGrabFrame(capture);
		//image = cvRetrieveFrame(capture);
		//if (!image)break;
		cvShowImage("video", image);
		char c = cvWaitKey(33);   // == 视频的帧率为30帧/s  
		if (c == 27)break;
	}
	cvReleaseCapture(&capture);
	cvDestroyWindow("video");

	*/


	VideoCapture cap("‪people.avi");
	//cap.open("‪people.avi");
	double fps=cap.get(CAP_PROP_FPS);
	namedWindow("xxx", 0);
	while (true) {	
		Mat img;
		cap>>img;
		imshow("xxx",img);	
		char c = waitKey(33);   // == 视频的帧率为30帧/s  
		if (c == 27)break;
	}
	

	return 0;
}

**Comment by alalek** [comment]
### Screenshots is not acceptable form of console error messages reports. They are useless for OpenCV community because similar issues can't be found.

There are 2 problems:
- FFMPEG is not able to open your video file. Probably `opencv_ffmpeg*.dll` was not loaded. Other possible reason is missing codec support in ffmpeg.
- `imshow` can't show empty images and so it raises an exception (your app doesn't catch exceptions so you see these "strange" windows)

There is nothing to fix in OpenCV.
