### ISSUE TITLE
OpenCV cannot save 32FC1 Mat as a tiff image

### ISSUE THREAD

**Issue by jasjuang** [opencv/opencv#7762]
- OpenCV => Latest
- Operating System / Platform => Ubuntu 16.04
- Compiler => gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

##### Steps to reproduce

For some weird reason OpenCV is unable to save a CV_32FC1 type cv::Mat into a tiff. Below is the minimal example to duplicate this

``````
// doesn't work
cv::Mat test = cv::Mat(100, 100, CV_32FC1, cv::Scalar(128));
cv::imwrite("test.tif", test);
``````

No file is written. 

However the different variations below all works properly
``````
// works
cv::Mat test = cv::Mat(100, 100, CV_32FC3, cv::Scalar(128, 128, 128));
cv::imwrite("test.tif", test);

// works
cv::Mat test = cv::Mat(100, 100, CV_8UC3, cv::Scalar(128, 128, 128));
cv::imwrite("test.tif", test);

// works
cv::Mat test = cv::Mat(100, 100, CV_8UC1, cv::Scalar(128));
cv::imwrite("test.tif", test);

// works
cv::Mat test = cv::Mat(100, 100, CV_32FC1, cv::Scalar(128));
cv::imwrite("test.png", test);

// works
cv::Mat test = cv::Mat(100, 100, CV_32FC1, cv::Scalar(128));
cv::imwrite("test.jpg", test);
``````

Why is it that CV_32FC1 Mat cannot be save as tiff?

**Comment by mshabunin** [comment]
This format has [not been implemented](https://github.com/opencv/opencv/blob/a8e550f5bfd809cb2ec4c58621a25b2902f46ce1/modules/imgcodecs/src/grfmt_tiff.cpp#L683-L701) yet.

**Comment by jasjuang** [comment]
Would a workaround such as converting 32FC1 Mat to 8UC1 Mat and save it in TiffEncoder::write appropriate?

**Comment by mshabunin** [comment]
Looks like this mechanism [has been implemented](https://github.com/opencv/opencv/blob/a8e550f5bfd809cb2ec4c58621a25b2902f46ce1/modules/imgcodecs/src/loadsave.cpp#L449-L465) already. But it does not work for TIFF: _TiffEncoder::isFormatSupported_ [returns _true_](https://github.com/opencv/opencv/blob/a8e550f5bfd809cb2ec4c58621a25b2902f46ce1/modules/imgcodecs/src/grfmt_tiff.cpp#L491-L498) for _CV_32F_, because it supports _CV_32FC3_ HDR images.

**Comment by jasjuang** [comment]
Seems to me adding another parameter that represents the number of channels in TiffEncoder::isFormatSupported to distinguish CV_32FC3 and CV_32FCN (N= anything other than 3) is the easiest way to do it, what do you think?

**Comment by mshabunin** [comment]
Yes, it should work.

**Comment by jasjuang** [comment]
@mshabunin do you plan to implement this? If not I can try to do it but it might take me a long time because I am not familiar with the OpenCV code base and coding standards.

**Comment by mshabunin** [comment]
We don't plan to implement this feature in nearest future, so feel free to do it yourself. You can take a look at the [contribution guide](https://github.com/opencv/opencv/wiki/How_to_contribute) and the [coding style guide](https://github.com/opencv/opencv/wiki/Coding_Style_Guide) for more information.

**Comment by alalek** [comment]
Implicit unexpected data loss in encoders must be avoided. Or we really support this format or we raise an exception. No "magic" is needed here.

This behavior is assumed by function [documentation](http://docs.opencv.org/master/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce):
> If the format, depth or channel order is different, use Mat::convertTo , and cv::cvtColor to convert it before saving.

Also [this existed line](https://github.com/opencv/opencv/blob/a8e550f5bfd809cb2ec4c58621a25b2902f46ce1/modules/imgcodecs/src/loadsave.cpp#L463) looks buggy, because 8U values range is usually [0; 255] and 32F image maps usually uses range [0; 1.0]. So multiplier should be applied.

Moreover this code is [untested](http://pullrequest.opencv.org/buildbot/export/opencv_releases/master_coverage-lin64-debug/20170103-054320_333/coverage_html/opencv/modules/imgcodecs/src/loadsave.cpp.gcov.html#519), not documented, not convenient with other OpenCV functions (see [imshow](http://docs.opencv.org/master/d7/dfc/group__highgui.html#ga453d42fe4cb60e5723281a89973ee563)) and probably not used anywhere.

**Comment by jasjuang** [comment]
If no "magic" is desired, how does CV_32FC1 mat got saved into pngs and jpgs? When I re-read these pngs and jpgs it showed up as CV_8UC1 so I believe some conversion happened.

**Comment by prusnak** [comment]
You can use OpenEXR format to store CV_32FC1 images. If you use `.exr` extension in `imwrite()` it will work (if OpenCV was compiled with OpenEXR support).

**Comment by romainreignier** [comment]
I think PR https://github.com/opencv/opencv/pull/10493 fixed this issue, isn't it?
