### ISSUE TITLE
RGB2Luv black pixel artifacts.

### ISSUE THREAD

**Issue by redfeatherplusplus** [opencv/opencv#7829]
##### System information (version)

- OpenCV => 2.4.13
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

Conversion from RGB2Luv creates image artifacts for near black pixels. This is due to a division by zero error present in the RGB2Luv_f struct in: https://github.com/opencv/opencv/blob/1c18b1d245a875565c9b9e49ccec901e9b516337/modules/imgproc/src/color.cpp#L5678. Here, (whitept[0] + whitept[1]*15 + whitept[2]*3) can equal zero, but no effort is done to check for a division by zero error. In cases where the sum of the whitepoints is zero, the resulting value for 'd' will yield a value of +INF. As the IEE 754 standard for floating point numbers defines 1.0F / 0.0F to be +INF.

A solution to this bug would be to simply check if: (whitept[0] + whitept[1]*15 + whitept[2]*3) is zero, and set 'd, u, and v' to be zero if it is. This solution is valid because: (whitept[0] + whitept[1]*15 + whitept[2]*3) is zero iff R, G, and B are zero for the original pixel.

##### Steps to reproduce

Sample code attached. Run using parameters: "0.5 0.5 0.6 0.6 fruits.jpg out.bmp" with fruits.jpg being the commonly used fruits image at: http://cpansearch.perl.org/src/YUTA/Cv-0.02/t/fruits.jpg.

[Project4.zip](https://github.com/opencv/opencv/files/641136/Project4.zip)

**Comment by savuor** [comment]
@redfeatherplusplus The main problem is not in OpenCV but in your code.
At Source.cpp:140 you wrote:
`float L_scalingFactor = L_inputImage.at<float>(i, j) / L_inputImage.at<float>(i, j);`
but the correct code is:
`float L_scalingFactor = L_inputImageScaled.at<float>(i, j) / L_inputImage.at<float>(i, j);`
This replacement fixes all the artifacts on image you provided.

However there were several minor bugs in to/from Luv conversion which are to be fixed by PR #9098
