### ISSUE TITLE
Embedding colorspace information in image structure

### ISSUE THREAD

**Issue by iev6** [opencv/opencv#7845]
Hi, I constantly face trouble converting from Lab to BGR and viceversa, is there a way to store the colorspace information while writing to the image file somehow?

**Comment by Vinit-Koshti** [comment]
yes you can have some code words such as first 5 pixels of the image you overwrite with your code word like: 120,120,120,120,120 remember that number should be between 0-255 or as per respective colorspace range and same for all R,B,G just so that it is easy to remember, just some code in the beginning that you can check when you read the image and find out the colorspace info changing first few pixels while writing image will not make any change

**Comment by iev6** [comment]
Thank you, this seems like a nice idea! Very similar to watermarking.
