### ISSUE TITLE
Create an official NuGet Package

### ISSUE THREAD

**Issue by rogersachan** [opencv/opencv#7903]
I think OpenCV should support NuGet because
* NuGet has allowed the downloading of C++ libraries for use in C++ projects since 2013. 
* The unofficial downloads exceed 100K per month
* Makes it easier for development
* Most *unofficial* OpenCV libraries available on NuGet date back to last year.
    * This leads unjust blame on OpenCV for not maintaining "their" packages 
* NuGet works on Linux and Mac via build scripts
* Popular libraries like Boost are available and kept up to date.

**Comment by rogersachan** [comment]
@mshabunin If I were to make a PR with preliminary .nuspec files, would it get committed?

**Comment by mshabunin** [comment]
@rogersachan , feel free to make a PR. We will consider moving to NuGet for binary Windows packages.

**Comment by rogersachan** [comment]
@mshabunin I will make a PR around spring break.

**Comment by glopesdev** [comment]
@rogersachan @mshabunin I am the current maintainer of the first "unofficial" OpenCV distribution hosted under the OpenCV ID at: https://www.nuget.org/packages/OpenCV/

This package has been downloaded more than 70,000 times and many users still depend on it daily for an easy entrypoint into using OpenCV in Visual Studio for C++ projects. I am very happy that the OpenCV devs are finally open to maintaining such a NuGet package themselves.

However, given the excessive number of users that are currently depending on this package, myself included, I would like to inquire how exactly will these official NuGet packages be generated. The reason I am asking is that the organization of the current package was far from trivial, and required a lot of thought to make sure that it works "out-of-the-box" for all kinds of different projects, under different architectures.

Specifically, some of the issues I had to think about included:

1. Distribution of static vs dynamic libraries: should the NuGet contain only pre-built shared libraries or also the static binaries? If both, should these be distributed in separate NuGet packages?

2. Distribution of pre-built binaries vs import libraries: OpenCV pre-built binaries are used not only for C++ projects but also for projects in other languages that interop with C++ (e.g. C# wrappers). While C++ projects require also import libraries (.lib) files to compile and use OpenCV, many other languages only require the DLLs themselves (C#). Therefore, the current wrapper separates between DLL distribution and import library distribution, with the C++ native package including the LIB files and depending on separate DLL distribution packages.

3. How to handle different architectures and runtime versions (x86 / x64 / ARM / UWP and VC11, VC12, etc runtimes)? Handling all possible combinations can easily create close to a dozen possible distributions. Should the package user include all combinations explicitly, or should the package use the current project configuration to determine which distribution to use? In the current nuget package, the [coapp](http://coapp.org/) project was used to automatically download, on demand, the appropriate distribution depending on the specified build configuration, such that users only have to add the OpenCV package once, and everything else will be handled for them.

4. Should all binaries be bundled into a single package, or split into individual packages, one per module?

I have many thoughts on how to handle these and other issues, based on 4 years of experience maintaining this package, that I would love to share with whoever is willing to handle this from now. Also, I am open to transferring ownership of the current NuGet package to the OpenCV project, so that you can use the official "OpenCV" ID to upload your packages, if you so desire. This would help transfer current users to the "correct" package once development is complete.

I would love if we can do this correctly, as improving distribution of OpenCV for C++/C# in windows is badly needed/wanted and the recent proliferation of hundreds of "unofficial" packages is making everything very confusing.

**Comment by rogersachan** [comment]
I should probably add some info to this. Microsoft is now investing into a new package manager for C++/C dependencies: [vcpkg](https://github.com/Microsoft/vcpkg), which works for all platforms. Since this is being invested into more than the current state of nuget for c++ dependencies, I will now close the issue.

**Comment by alalek** [comment]
Feel free to provide feedback for this PR: #20389
