### ISSUE TITLE
ConnectedComponnents and zero level in binary image

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8014]
Hi,

In this [post ](http://answers.opencv.org/question/59083/connectedcomponnents-and-zero-level-in-binary-image/ )I wrote that connectedComponent looks for connected component only with non zero values (foreground pixel). I think that It could be a problem to do not process background pixel. I wrote an answer how to solve this problem : 

```
threshold(x, y, 50, 255, THRESH_BINARY);
Mat labels1, labels2;
connectedComponents(y, labels1, 8, CV_32S);
minMaxIdx(labels1, &ccMin, &ccMax);
bitwise_not(y, y);
connectedComponents(y, labels2, 8, CV_32S);
Mat mask = labels1 == 0;
add(labels2, ccMax, labels2, mask);
labels1 = labels1 + labels2 - 1;

```

I think it is easy to add an argument to connectedComponent : 
int cv::connectedComponents 	( 	InputArray  	image,OutputArray  	labels,int  	connectivity = 8,
int  	ltype = CV_32S ,int backAndForeground) 	like this connectedComponents is able to deal zero back and forground components.

My question is it a good idea for a PR ?

**Comment by StevenPuttemans** [comment]
@LaurentBerger I suggest you to provide the PR and await review there. This works way faster than asking around here. The fact that a RFC label has been added gives me the impression the team is up for suggestions on this topic!

**Comment by kinchungwong** [comment]
<h3>Will this be a good idea? Will this be useful to people?</h3>

I personally think this algorithm variant is useful because I am using something similar to process document images. Document images can contain dark-text-on-light-background, or the opposite. Labeling both light-colored and dark-colored blobs in a single pass would simplify subsequent algorithm steps (this may depend on algorithm design choices), reduce memory usage (only one copy of labels matrix), and perhaps reduce processing time.

----

<h3>How to design a reasonable API function (call signature) for this idea?</h3>

In the simplest design, the new functionality can be added without modifying the API call signature, A new supported value can be added for the `ccltype` parameter ([docs](http://docs.opencv.org/3.2.0/d3/dc0/group__imgproc__shape.html#gaedef8c7340499ca391d459122e51bef5)): 

```
int connectedComponents(
    InputArray image, OutputArray labels, 
    int connectivity, int ltype, int ccltype);

enum ConnectedComponentsAlgorithmsTypes 
{ 
    CCL_WU = 0, 
    CCL_DEFAULT = -1, 
    CCL_GRANA = 1 
}
```

----

<h3>How much implementation code will be needed? In other words, will this lead to code bloat of OpenCV (imgproc)?</h3>

If we are satisfied with the approach suggested by @LaurentBerger, the increase in code size will be minimal. 

The execution time will be the sum of the **two** calls to `cv::connectedComponents`, **plus**:

 - Logical negation (commuting zero with non-zero) of input matrix, preferably without overwriting the caller's matrix
 - Post-processing and combination of the two output labels matrices
 - Post-processing and combination of the connected components statistics, if the with-statistics API is used.

If we aim for faster execution time, lower memory usage (throughout the algorithm's execution; the "memory peak" is what matters in memory-constrained environments), and/or better utilization of multicore CPU processing, that could require substantial changes or entirely new algorithms. 

The currently-implemented algorithms (Wu; Grana) take advantage of the fact that runs of same-labeled (foreground; non-zero) pixels are interspersed between background pixels that don't need to be unique labeled. In other words, to uniquely label two kinds of pixels, it always require two passes of the currently-implemented algorithms. This is not universally true for all types of connected components algorithms; however, those that don't require two passes are less optimized than Wu or Grana.

One remark with respect to @LaurentBerger's sample code is that the `minMaxIdx` step is not needed. The integer returned from `cv::connectedComponents` is the number of unique labels values in the output matrix. As of OpenCV 3.0, if the returned integer value is N, that means the output labels matrix will contain values from 0 ... N-1, with 0 being the background label and (1 ... N-1) being the foreground labels. This is required by the API specification.

Simply speaking, we can take each pair of values from `labels1(row, col)` and `labels2(row, col)`, select the value that is non-zero (non-background), then add an offset value to it, depending on which matrix it comes from.

----

<h3>Will this API function (call signature) hinder future development (extensions) of this algorithm?</h3>

It will not hinder future extensions, given the flexibility of specifying completely different algorithms using the `ccltype` parameter on the API.

One can foresee an extension of treating each unique input pixel value in `(0 ... 255)` as its own blob. In one of the papers I've read, this is termed *"multimodal connected component labeling"*. (I don't know whether this term is agreed upon universally or not.) Please refer to the paper's Section 2, "Basics", and Figure 2, for their description.

Paper: Connected Component Labeling Algorithm for very complex and high resolution images on an FPGA platform. 
Authors: Kurt Schwenk and Felix Huber.

Incidentally, if one is aiming for very high utilization of multicore CPU processing, it would have required a very different design, and some labels post-processing will need to be deferred. I recently did an implementation (different from what I did last year) and it requires a C++ object-based design (i.e. it returns an opaque object that allows sub-rectangles or stats to be queried, one-by-one, in order to evade the processing of majority of pixels belonging to blobs that are not of interest.)
