### ISSUE TITLE
access to split doc 

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv#8057]
Hi,

Something I don't understand. I want to read cv::split doc on http://docs.opencv.org/master I write split in search box and press return and : nothing no link. Problem occurs with edge or mozilla (windows 10) only with master doc.

with my own doc I haven't got this problem.

reference[ this post](http://answers.opencv.org/question/123524/access-to-split-doc/)

**Comment by PkLab** [comment]
Just to add infos...my local build of the doc (current master) doesn't have the issue. (Win7/doxygen 1,8,12)

**Comment by LaurentBerger** [comment]
same problem today with split again

**Comment by alalek** [comment]
https://docs.opencv.org/3.4.6/ - works
https://docs.opencv.org/3.4.7/ - doesn't work again

**Comment by crackwitz** [comment]
the generated HTML is faulty. two elements with the same ID are generated.

![image](https://user-images.githubusercontent.com/7065108/62471730-8f186580-b79d-11e9-8146-2015a447596a.png)

![image](https://user-images.githubusercontent.com/7065108/62471720-8889ee00-b79d-11e9-8522-d31483dbecf1.png)

I think the first entry is meant to go *into* the subtree, not be listed as its own root entry.

I haven't looked at *how* this is generated. that's where I suspect the bug is.

**Comment by crackwitz** [comment]
bug in doxygen. they seem to be aware of it.
https://github.com/doxygen/doxygen/issues/7127

**Comment by asmorkalov** [comment]
@alalek I think we can close it, right?

**Comment by alalek** [comment]
Fix has been landed for doxygen 1.8.16.
But we are still using doxygen 1.8.13 (from Ubuntu 18.04) to build documentation for docs.opencv.org.
