### ISSUE TITLE
CV_8UC3 Mat not convertible to ocl::Image2D

### ISSUE THREAD

**Issue by cuihaoleo** [opencv/opencv#8108]
OpenCV version: 3.1.0

Example code:
```c++
#include "opencv2/imgproc.hpp"
#include "opencv2/core/ocl.hpp"
int main() {
    cv::UMat m(10, 10, CV_8UC3);
    cv::ocl::Image2D i2d(m);
    return 0;
}
```

gives:
```
OpenCV Error: Unknown error code -220 (Image format is not supported) in init, file /build/opencv/src/opencv-3.1.0/modules/core/src/ocl.cpp, line 5917
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv/src/opencv-3.1.0/modules/core/src/ocl.cpp:5917: error: (-220) Image format is not supported in function init
```

I glanced at the code. `Image2D::Impl::getImageFormat` in `modules/core/src/ocl.cpp` writes:
```c++
static const int channelOrders[] = { -1, CL_R, CL_RG, -1, CL_RGBA };
```

If I'm not wrong, 3-channel images are not supported by design. But It seems strange not to support common RGB image as there is CL_RGB channel order in OpenCL.

I think commit da5b316b4e brought in the change, but commit log didn't give much info. Any reason why?

**Comment by cuihaoleo** [comment]
Hmm, I think I found the reason. It's because CL_RGB channel order can only be used with  CL_UNORM_SHORT_565/CL_UNORM_SHORT_555/CL_UNORM_INT101010 data type (to maximize memory usage with 16/32bit align?).

So it's acceptable that CV_8UC3 Mat is not directly convertible to ocl::Image2D.

BTW, the interface of OpenCV's OpenCL wrapper and OpenCV-OpenCL interoperation are poorly documented now. I have to dig into the source code and try to find correct application of these APIs. Do you have any plan to complete these documentation?

**Comment by mshabunin** [comment]
@cuihaoleo , issue #7197 tracks T-API (OpenCL) documentation improvement.

**Comment by Darker** [comment]
"documentation improvement" I've been googling for 2 hours now, and the only information I found was in stackoverflow questions. Where is the "documentation" that is being improved?

**Comment by crackwitz** [comment]
the code uses `clGetSupportedImageFormats`
https://github.com/opencv/opencv/blob/c3bb57afeaf030f10939204d48d7c2a3842f4293/modules/core/src/ocl.cpp#L6461

this lists possible channel orders, `CL_RGB` exists for OpenCL in general:
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_image_format.html

the OpenCV code explicitly supports only 1/2/4-channel data. 

https://github.com/opencv/opencv/blob/c3bb57afeaf030f10939204d48d7c2a3842f4293/modules/core/src/ocl.cpp#L6499-L6504

https://github.com/opencv/opencv/blob/c3bb57afeaf030f10939204d48d7c2a3842f4293/modules/core/src/ocl.cpp#L6445-L6452

I think the "fix" could be as simple as changing L6452 so the array contains
`{ -1, CL_R, CL_RG, CL_RGB, CL_RGBA }`

OpenCL can still refuse this but at least it is being asked.

if that causes failure somewhere else, it must be because 2 and 4 channels are handled in some way, but not 3 channels.
