### ISSUE TITLE
An empty cv::Mat has the continuous flag set

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#8180]
##### System information (version)

- OpenCV => 3.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

While an instance of `cv::Mat` is constructed from an empty container, its continuous
flag is set and the data member `cols` is set to 1, which is unexpected.

##### Steps to reproduce

```.cpp
std::vector<uchar> v;
cv::Mat m(v);

std::cout << "Size: " << m.size() << std::endl
	<< "It is continuous: " << (m.isContinuous() ? "true" : "false") << std::endl;
```
The output of the above code is 
```
Size: [1 x 0]
It is continuous: true
```

The expected output should be:
```
Size: [0 x 0]
It is continuous: false
```

**Comment by alalek** [comment]
What is about an assertion?
There is no reason to work with empty Mat, because there is no data or this Mat was freed.

**Comment by csukuangfj** [comment]
Thank you for the quick response.

It just feels unnatural for me that an empty matrix has a column of 1, though it will throw exception
when we try to access its element. 

Would it be possible to set its data members only when the container
is not empty?

**Comment by alalek** [comment]
There is very old problem with vector representation in OpenCV. It is tried to be represented as a single column (`cols=1`, `rows=v.size()`) of 2D-matrix (because Mat has cols/rows parameters and OpenCV need to fill them somehow).
Both calls for isContinuous() seems not valid to me, because "inputs" (empty Mat) are in range of **undefined** values (output is not well defined for these values, and probably this call should not be used at all)
