### ISSUE TITLE
Replace round with cvRound in modules/core/src/hal_internal.cpp to compile with Visual Studio 2012

### ISSUE THREAD

**Issue by pclausen** [opencv/opencv#8190]
##### System information (version)

- OpenCV => 2.4
- Operating System / Platform => Windows 7 x64
- Compiler => Visual Studio 2012 MSVC 17.0.61030.0

##### Detailed description

Replace round with cvRound in modules/core/src/hal_internal.cpp to compile with Visual Studio 2012

##### Steps to reproduce

1. mkdir build
2. cmake .. -G"Visual Studio 11 2012 Win64"
3. OpenCV.sln
4. --> click build

**Comment by pclausen** [comment]
I have already made the changes in my git repo, but I am an absolute noob with git....

What I have done so far:
```
git clone
git add modules/core/src/hal_internal.cpp
# changed file
git commit
```
How should I proceed?

**Comment by csukuangfj** [comment]
You could possibly do
```
git push
```
to push the commit to your GitHub repository. Afterwards, you can do a pull request to submit your change.

**Comment by pclausen** [comment]
I guess I cant push changes:

```
git push
remote: Permission to opencv/opencv.git denied to pclausen.
fatal: unable to access 'https://github.com/opencv/opencv.git/': The requested
URL returned error: 403
```
How to proceed?

**Comment by csukuangfj** [comment]
You should push it to your GitHub repository, not the official one. Because you do not have write permission.

I find that currently you have no OpenCV repository in your GitHub. You can first go to the official GitHub page of [OpenCV](https://github.com/opencv/opencv) and do a fork. Then clone your own fork to the local computer, merge your changes, push it to GitHub. Afterwards, you could find an option to create a new pull request in the web page.

**Comment by alalek** [comment]
You can push into your GitHub fork only.

Try this [tutorial](https://guides.github.com/activities/hello-world/) (or similar) but create fork of OpenCV repository instead of creation a new empty one:
- https://guides.github.com/activities/contributing-to-open-source/
