### ISSUE TITLE
imshow and waitKey combination in multi-thread environment on Linux

### ISSUE THREAD

**Issue by lesomnus** [opencv/opencv#8407]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Raspbian Jessie
- Compiler => g++-6

##### Detailed description

I'm sorry but I can not speak English very well.

<code>imshow</code> and <code>waitKey</code> combination in multi-thread environment on Linux

I do not know exactly how it happens, but expect,
While a thread is blocked by <code>waitKey</code>, calling <code>imshow</code> on another thread freezes the target window. Or <code>waitKey</code> may have been called with <code>imshow</code> in progress.

Windows10 works fine on 64bit, but since I know that <code>waitKey</code> does not work on threads that are not main threads. So I have called the two functions on different threads on Windows.

I just modified the code to call the same thread on linux so that the <code>waitKey</code> works fine even if it is not the main thread. However, on Linux, unlike Windows, I noticed that <code>waitKey</code> can be called from a non-main thread, and the problem is solved.

**Comment by alalek** [comment]
You should interact with UI from the "main" thread only.

There are a lot of UI backends: GTK/QT/OpenGL/Win32/etc
Some UI backends may support "more or less" multi-thread interaction. But in general, multi-threading is not supported well by UI.

**Comment by TheTesla** [comment]
I tested multithreading on ubuntu 14.04 with opencv 3.1.0 and on ubuntu 16.04 with opencv 3.2.0:
ubuntu 14.04 with opencv 3.1.0 is very stable; on ubuntu 16.04 with opencv 3.2.0 the window freezes. It happens if there is a transition running imshow and waitKey from main thread and later running from an extra thread. (But I did not test concurrency)

If it was working without any problems in 3.1.0, way not trying to bring it to work on 3.2.0?

**Comment by scm-ns** [comment]
Are you sure you are not writing to imshow from multiple threads ? I was having the same issue. I synchronized the calls to imshow using a mutex and now it doesn't crash. 

The issue is actually with the X11 library that opencv uses to draw on screen. It doesn't seem to support writing from multiple threads. Makes sense. Do UI interactions from the main thread.

**Comment by Spiffy1** [comment]
I'm running a camera thread with another thread. I have use waitkey() and imshow() in the main thread. When I use imshow() for a random picture in another thread, the image could not be shown unless I put waitkey(0) to freeze it. When I break the freeze using a break, the program crash.
