### ISSUE TITLE
InputArray::getMat crashes on data of type std::vector<std::vector<bool>>

### ISSUE THREAD

**Issue by csukuangfj** [opencv/opencv#8411]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

The following program causes segmentation fault:
```cpp
std::vector<std::vector<bool>> vec{ {false,true}, {true,false,true} };
cv::InputArray input(vec);
std::cout << input.getMat(0) << std::endl;
std::cout << input.getMat(1) << std::endl;
```

It works fine for type of  `std::vector<std::vector<char>>`.

##### Steps to reproduce
Execute the above program.

**Comment by Vedranh13** [comment]
Hi,

I have never contributed to OpenCV before, but I am interested in doing so, and I believe I have a solution to the above issue. However, my solution, although it passes all the opencv tests, feels hackish and not up to OpenCV standards, so, I was wondering if a more experienced contributor was available to review it quickly before I submit a pull request. I understand if no one is available to do so, so if I don't hear anything by tomorrow, I will submit the request anyway.  

The cause of this crash was in `Mat _InputArray::getMat_(int i)` in matrix.cpp, specifically, it was failing the assert statement on line 1244 because the size of the `std::vector<std::vector<uchar> > vv` it was casting the inputted object to had a negative size. So, I added code that instead cast it to `std::vector<std::vector<bool> >` if size was less than zero and then did the proper processing. I feel that it is improper to simply assume that if `vv.size()` is negative vv should be recast to` std::vector<std::vector<bool> >`, but it is all I could come up with.

Here is a link to my [fork](https://github.com/Vedranh13/opencv) and attached is a patch with my added code.

Thanks

[patch.txt](https://github.com/opencv/opencv/files/853712/patch.txt)

**Comment by Vedranh13** [comment]
Hi,

I have not previously contributed to OpenCV, but I am interesting in doing so and I believe I have found a solution to the above issue. While my solution passes all the tests, I am unsure whether it is up to OpenCV standards or not. I was wondering if a more experienced contributor could take a look at my code and quickly approve it. I understand if no one is available, and so if I don't hear back by tomorrow, I will just go ahead and submit a pull request anyway and let the reviewer there decide.

The cause of this crash was in `Mat _InputArray::getMat_(int i)` in matrix.cpp, specifically, it was failing the assert statement on line 1244 because the size of the `std::vector<std::vector<uchar> > vv` it was casting the inputted object to had a negative size. So, I added code that instead cast it to `std::vector<std::vector<bool> >` if size was less than zero and then did the proper processing. I feel that it is improper to simply assume that if `vv.size()` is negative vv should be recast to `std::vector<std::vector<bool> >`, but it is all I could come up with.

Here is a link to my [fork](https://github.com/Vedranh13/opencv) and attached is a patch with my added code.

Thanks

[patch.txt](https://github.com/opencv/opencv/files/853749/patch.txt)

**Comment by Vedranh13** [comment]
Disregard the above, I believe I have found a real, robust solution and will be submitting a pull request shortly.

**Comment by alalek** [comment]
Problem is related to invalid default type traits: #7599
Related: #8189

**Comment by csukuangfj** [comment]
In my opinion, it has nothing to do with the default type traits.  Because `DataType<bool>` is well defined.

If we have a variable `v`: 
```.cpp
std::vector<bool> v{1, 1, 1, 1, 0, 0, 0, 0};
```

According to the [cppreference.com](http://en.cppreference.com/w/cpp/container/vector_bool#firstHeading), the number of bytes of `v` is implementation defined,  it may occupy only 1 byte, instead of `sizeof(bool)*8` bytes! This explains why it caused the segmentation fault.

The developer who implemented the `_InputArray` class must be aware of this special case and
handled `std::vector<bool>` explicitly. (But for some unknown reason, he/she forgot to process the case`std::vector<std::vector<bool>>`.)

Therefore, the easiest workaround is to forbid the user instantiating `std::vector<std::vector<bool>>`.
