### ISSUE TITLE
Feature request: do not redownload the ippicv file at every clean build

### ISSUE THREAD

**Issue by dbermond** [opencv/opencv#8419]
The build system always redownloads the ippicv file at every new clean build (first time build using a clean source tree).

In the past (pre v3.2?), the method described in [Linux from Scratch](http://www.linuxfromscratch.org/blfs/view/svn/general/opencv.html) was working: download the ippicv file, place it in the correct folder and start to build. In this way, you would need to download the ippicv file just once and place it in the correct folder for every clean build. This saved a lot of download time.

But in recent OpenCV versions the behavior has changed. Even if you place the file in the correct folder in a first time build, OpenCV still redownloads it. Some change was made in CMake scripts that setted this to be this way. I'm not sure, but as far as I could gather, CMake checks some variables, and this variables are setted during the first time build, so it always redownloads in clean builds.

The result is that, even if I have the file already downloaded in disk in a separate folder and want to use it, CMake does not allow. It would be good if CMake detected the presence of the file as in the past and simply extracts it, even in the first time build. This redownload is taking a lot of time during my clean builds.

**Comment by alalek** [comment]
[Can't reproduce](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/10046/steps/cmake/logs/stdio):
```
-- ICV: Unpacking ippicv_linux_20151201.tgz to /build/master-lin64/build/3rdparty/ippicv...
-- ICV: Package successfully downloaded
```

There is no downloading step.

You can see log with downloading step [here](http://pullrequest.opencv.org/buildbot/builders/master-lin64/builds/10000/steps/cmake/logs/stdio):
```
-- ICV: Downloading ippicv_linux_20151201.tgz...
-- ICV: Unpacking ippicv_linux_20151201.tgz to /build/master-lin64/build/3rdparty/ippicv...
-- ICV: Package successfully downloaded
```

Downloaded file is cached in the source tree (under `.gitignore` pattern, so `git clean` ignores these cached files in the default mode without special flags).

Also you can take a look on [`OPENCV_ICV_URL`](https://github.com/opencv/opencv/blob/3.2.0/3rdparty/ippicv/downloader.cmake#L63-L69) internal variable.

**Comment by bermond** [comment]
Thank you for the reply.

I understand. But I'm using ```git reset --hard HEAD``` and ```git clean -xdf``` to clear the git source tree when needing to do a clean build. This restores the tracked files and removes all untracked files, making the source tree equals to a ```git clone```. In this case it will download the ippicv file because the cache files will be removed by the second command.

The same happens when using the release version. A clean build (delete everything and extract again) will also download the ippicv file because it will be a first run. Copying an already manually downloaded ippicv file to the correct folder (```3rdparty/ippicv/downloads/linux-<md5sum>```) and start compiling a clean build using these mentioned steps will not work. CMake will download anyway.

By having a more detailed look at the pointed [downloader.cmake](https://github.com/opencv/opencv/blob/3.2.0/3rdparty/ippicv/downloader.cmake) script I could make a patch that did the job for my needs. It will not download ippicv anymore and just copy the file to the expected folder. But it would be to good to have something similiar implemented in the project.

**Comment by mshabunin** [comment]
@bermond , please take a look at the PR #8421, it adds a single download cache folder which can be changed by `OPENCV_DOWNLOAD_DIR` cmake option. It can be located outside the source folder, so it will not be affected by `git clean`.

**Comment by bermond** [comment]
@mshabunin 
Running CMake with `-DOPENCV_DOWNLOAD_DIR` (or `-DOPENCV_ICV_URL`) does not worked for me.

Besides the patch that I've made, I found following working method using the interval variable `OPENCV_ICV_PACKAGE_DOWNLOADED` (3.2 and git master):
```
$ tar xf /path/to/ippfile --directory=3rdparty/ippicv
$ _ippicv_md5="$(md5sum /path/to/ippfile | cut -d" " -f1)" # calculate md5sum
$ cmake -DOPENCV_ICV_PACKAGE_DOWNLOADED:INTERNAL="$_ippicv_md5" <other_cmake_args>
```
