### ISSUE TITLE
Problem in make, while building opencv_contrib

### ISSUE THREAD

**Issue by anuj-rathore** [opencv/opencv#8507]
I am trying to build opencv_contrib, but it is giving me following error:

/usr/bin/ld: cannot find -lFALSE
/usr/bin/ld: cannot find -lFALSE
collect2: error: ld returned 1 exit status
modules/core/CMakeFiles/opencv_core.dir/build.make:1782: recipe for target 'lib/libopencv_core.so.3.2.0' failed
make[2]: *** [lib/libopencv_core.so.3.2.0] Error 1
make[2]: Leaving directory '/users/anuj.rathore/new/opencv/build'
CMakeFiles/Makefile2:2097: recipe for target 'modules/core/CMakeFiles/opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: Leaving directory '/users/anuj.rathore/new/opencv/build'
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

How to fix -lFalse ?

**Comment by hpalikareva** [comment]
Same problem here...

**Comment by anuj-rathore** [comment]
This error is generally encountered when the version of opencv and opencv_contrib mismatches, and due to which "make" tries to search some flag which it can't find in the code, so it returns -lFalse.

To resolve it, I tried installing opencv-3.2.0 with same version of opencv_contrib i.e. opencv_contrib-3.2.0 and it worked for me! :smile:

**Comment by consaisai** [comment]
Thank you
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ANUJ RATHORE<mailto:notifications@github.com>
发送时间: 2017年4月6日 1:53
收件人: opencv/opencv<mailto:opencv@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [opencv/opencv] Problem in make, while building opencv_contrib (#8507)


This error is generally encountered when the version of opencv and opencv_contrib mismatches, and due to which "make" tries to search some flag which it can't find in the code, so it returns -lFalse.

To resolve it, I tried installing opencv-3.2.0 with same version of opencv_contrib i.e. opencv_contrib-3.2.0 and it worked for me! 😄

**Comment by antecessor** [comment]
Dear,
I tried this and everything seems ok:

BUILD_DOCS should be unchecked (aka disabled).
BUILD_TESTS should be unchecked (aka disabled).
BUILD_PERF_TESTS should be unchecked (aka disabled).
ENABLE_PRECOMPILED_HEADERS should be unchecked.
ENABLE_CXX11 should be checked.
BUILD_opencv_saliency should be unchecked (aka disabled)
