### ISSUE TITLE
Compilation error:cv2.cpp.o: relocation R_X86_64_PC32 against undefined Symbol `_Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_' 

### ISSUE THREAD

**Issue by AlexLuya** [opencv/opencv#8509]
[opencv-cmake-output.txt](https://github.com/opencv/opencv/files/901823/opencv-cmake-output.txt)

##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => ubuntu 16.04 64 Bit
- Compiler => gcc version 5.4.0 20160609

configure command:
`cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=$(python -c "import sys; print(sys.prefix)") -D PYTHON_EXECUTABLE=$(which python) -D OPENCV_EXTRA_MODULES_PATH=/path/to/opencv_contrib/modules -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_JPPEG=ON -D WITH_PNG=ON -D WITH_CUDA=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1 -D WITH_NVCUVID=ON -D WITH_V4L=ON -DWITH_FFMPEG=ON -DWITH_GSTREAMER=OFF ..`

same bug like this:
https://github.com/yzbx/yzbxLib/issues/2

Have done:
```
  sed -i -e 's/libavformat\.a/libavformat.so/g' \
      -e 's/libavutil\.a/libavutil.so/g' \
      -e 's/libswscale\.a/libswscale.so/g' \
      -e 's/libavresample\.a/libavresample.so/g' \
      -e 's/libavcodec\.a/libavcodec.so/g' \
      cmake/OpenCVFindLibsVideo.cmake
```

but still got 
```
[100%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
[100%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
[100%] Linking CXX shared module ../../lib/cv2.so
/usr/bin/ld: CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o: relocation R_X86_64_PC32 against undefined Symbol `_Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Ungültiger Wert
collect2: error: ld returned 1 exit status
modules/python2/CMakeFiles/opencv_python2.dir/build.make:383: die Regel für Ziel „lib/cv2.so“ scheiterte
make[2]: *** [lib/cv2.so] Fehler 1
CMakeFiles/Makefile2:18336: die Regel für Ziel „modules/python2/CMakeFiles/opencv_python2.dir/all“ scheiterte
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Fehler 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
[100%] Linking CXX shared module ../../lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o: relocation R_X86_64_PC32 against undefined Symbol `_Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Ungültiger Wert
collect2: error: ld returned 1 exit status
modules/python3/CMakeFiles/opencv_python3.dir/build.make:383: die Regel für Ziel „lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so“ scheiterte
make[2]: *** [lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so] Fehler 1
CMakeFiles/Makefile2:18440: die Regel für Ziel „modules/python3/CMakeFiles/opencv_python3.dir/all“ scheiterte
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Fehler 2
```

**Comment by mshabunin** [comment]
Please, try to do a clean build and provide cmake output (attach or via GitHub gist).

**Comment by jkairborne** [comment]
I have been experiencing the same problem for two days. Trying to get the "tracking" library to work.
Ubuntu 16.04 GNOME (also a dual-boot system with Win10 if that's important)

This is a brand new install. I wiped my Ubuntu16.04 partition today, did a fresh install from disk. From that time I ran a "script" so all of my commands/outputs are logged (see attachement - unfortunately it doesn't seem to play very nicely with gedit/vim)

What I did:
Installed OpenCV dependencies, etc.

Installed OpenCV (successfully) to a /home/user/libs/opencv-3.2.0/release directory.

Downloaded and unzipped latest Opencv-contribs
Attempted to build using command:
make -DOPENCV_EXTRA_MODULES_PATH=/home/user/libs/opencv-3.2.0/release/opencv_contrib-master/modules DCMAKE_INSTALL_PREFIX=/home/user/libs/opencv-3.2.0/release/installed ..

This fails due to a downloading error of some sort:
"CMake Error at /home/user/libs/opencv-3.2.0/release/opencv-3.2.0/cmake/OpenCVUtils.cmake:1043 (file):
  file DOWNLOAD cannot open file for write.
Call Stack (most recent call first):
  /home/user/libs/opencv-3.2.0/release/opencv_contrib-master/modules/dnn/cmake/OpenCVFindLibProtobuf.cmake:32 (ocv_download)
  /home/user/libs/opencv-3.2.0/release/opencv_contrib-master/modules/dnn/CMakeLists.txt:5 (include)"
[...]

To fix this, I change to the directory of opencv_contrib/modules, and run: 
rm -rf dnn*
rm -rf xfeatures2d

This gets rid of the error above, but I then get stuck at the error mentioned by the OP.
I followed the instructions in the question he linked, I tried the sed replacement solution, then compile with FFMPEG ON but GSTREAMER OFF. This gave the same error.  then I tried to compile with FFMPEG OFF. Still no go, I get the same error (full output below). I did not try the ninja stuff, it seemed above my level.

/usr/bin/ld: CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o: relocation R_X86_64_PC32 against undefined symbol `_Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
modules/python2/CMakeFiles/opencv_python2.dir/build.make:370: recipe for target 'lib/cv2.so' failed
make[2]: *** [lib/cv2.so] Error 1
CMakeFiles/Makefile2:13270: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error
[output.txt](https://github.com/opencv/opencv/files/901315/output.txt)
 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFil
[output.txt](https://github.com/opencv/opencv/files/901312/output.txt)
es/opencv_python3.dir/__/src2/cv2.cpp.o: relocation R_X86_64_PC32 against undefined symbol `_Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
modules/python3/CMakeFiles/opencv_python3.dir/build.make:370: recipe for target 'lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so' failed
make[2]: *** [lib/python3/cv2.cpython-35m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:13363: recipe for target 'modules/python3/CMakeFiles/opencv_python3.dir/all' failed
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AlexLuya** [comment]
@mshabunin 
cmake output attachted

**Comment by berak** [comment]
@AlexLuya , @jkairborne :

can you try to update your **main** opencv repo to latest github master branch ?

it seem's you're lacking [this recent patch](https://github.com/opencv/opencv/commit/232d6b87f44a284e39a18e15e10ff29efbfa4352) , which added the Matx bindings.

**Comment by jkairborne** [comment]
OK, I tried that. I again just wiped everything and started from scratch while running script ([output2.txt](https://github.com/opencv/opencv/files/903001/output2.txt)). I'm now getting multiple cmake errors while running the "cmake -DOPENCV....." saying it is unable to determine the linker language (see below). I just followed the tutorial here http://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html. Apologize if this is something easy to solve, I'm relatively new. I'm currently meld-ing the differences between CMakeLists from 3.2.0 release to the current master, seeing if I can find what the current hiccup is caused by.

```
CMake Error: CMake can not determine linker language for target: opencv_imgcodecs
CMake Error in modules/imgcodecs/CMakeLists.txt:
  Exporting the target "opencv_imgcodecs" is not allowed since its linker
  language cannot be determined
```

**Comment by consaisai** [comment]
OK,Thank you

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: berak<mailto:notifications@github.com>
发送时间: 2017年4月6日 16:38
收件人: opencv/opencv<mailto:opencv@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [opencv/opencv] Compilation error:cv2.cpp.o: relocation R_X86_64_PC32 against undefined Symbol `_Z13pyopencv_fromIN2cv4MatxIdLi4ELi4EEEEP7_objectRKT_' (#8509)


@AlexLuya<https://github.com/AlexLuya> , @jkairborne<https://github.com/jkairborne> :

can you try to update your main opencv repo to latest github master branch ?

it seem's you're lacking this recent patch<https://github.com/opencv/opencv/commit/232d6b87f44a284e39a18e15e10ff29efbfa4352> , which added the Matx bindings.

―

**Comment by AlexLuya** [comment]
@consaisai ,lastest opencv master+opencv-contrib master give this error:
```
[ 95%] Built target opencv_test_cudaobjdetect
[ 96%] Built target opencv_interactive-calibration
[ 96%] Linking CXX executable ../../bin/opencv_test_optflow
[ 96%] Linking CXX executable ../../bin/opencv_perf_optflow
[ 96%] Built target opencv_perf_cudaobjdetect
[ 96%] Linking CXX executable ../../bin/opencv_test_stitching
[ 96%] Built target opencv_perf_tracking
[ 96%] Linking CXX executable ../../bin/opencv_perf_stitching
[ 96%] Built target opencv_test_tracking
[ 96%] Built target opencv_perf_optflow
[ 96%] Built target opencv_test_optflow
[ 97%] Built target opencv_test_stitching
[ 97%] Built target opencv_perf_stitching
Segmentation fault (core dumped)
CMake Error at cuda_compile_generated_pyrlk.cu.o.cmake:266 (message):
  Error generating file
  /path/to/opencv/release/modules/cudaoptflow/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_pyrlk.cu.o


modules/cudaoptflow/CMakeFiles/opencv_cudaoptflow.dir/build.make:318: the rule for target„modules/cudaoptflow/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_pyrlk.cu.o“ failed
make[2]: *** [modules/cudaoptflow/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_pyrlk.cu.o] error 1
CMakeFiles/Makefile2:14889: 
the rule for target,modules/cudaoptflow/CMakeFiles/opencv_cudaoptflow.dir/all“ failed
make[1]: *** [modules/cudaoptflow/CMakeFiles/opencv_cudaoptflow.dir/all] error 2
Makefile:149: 
the rule for target,all“ failed
make: *** [all] error 2

```
