### ISSUE TITLE
coding errors with matchcontours.cpp?

### ISSUE THREAD

**Issue by dave-watts** [opencv/opencv#8513]
Is line 155 and 156 in file matchcontours.cpp correct?

  if( result < mmm )
                    result = mmm;

It seems at this point result can only be 0. the fabs statement on the previous line means that mmm can only ever be positive the only can in which the statement can be false is if mmm == 0 in which case setting result to mmm will be the same result. 

But the main problem with the code that I can see is that there is no summing up of the result value for each moment on line 156. Algorithm 3 (which seems to be mathematically the best, as the division by the moment scales for magnitude) is rendered useless since the moments are not summed. 

the 

    if (anyA != anyB)
        result = DBL_MAX;

part on line 167 also seems crazy, I don't get the logic: if one of the moments of a contour is non zero and the same moment from the other contour is zero then fail the comparison? this is regardless of the agreement between the other moments or precision errors (so 0.000001 vs 0 -> fail). Strange idea, where does that come from?
  
I also wish that the OpenCV documentation would include a statement regarding meaning of the return result, ie the score value range what is a good score (values -> 0?).

**Comment by berak** [comment]
i don't think, there's any bug here.

    if( result < mmm )
         result = mmm;

is just another way of saying:

    result = max(result, mmm);

(which is, what is required [here, for CONTOURS_MATCH_I3](http://docs.opencv.org/master/d3/dc0/group__imgproc__shape.html#gaf2b97a230b51856d09a2d934b78c015f).  (the max, not the sum)).

then,  

    if (anyA != anyB)
        result = DBL_MAX;

may look weird, but it's a (late) sanity check, that saves you from false positives.
think of it this way, anyA or anyB are only false, when one of the hu-moments is completely zero (because e.g. the input was a completely black image). and any of the 3 formulas would (wrongly) return 0 distance in that case.)

**Comment by dave-watts** [comment]
Ok thanks for clearing that up, I don't have it to hand, but maybe the Learning OpenCV 3 book may have a typo for that equation (or I read it wrong) I thought it had a sum also for this equation. I will check tomorrow.

**Comment by berak** [comment]
> Wouldn't the 'summed' scaled difference also be a good similarity measure (I4)?

feel free to do [your own experiments](https://gist.github.com/berak/6b601138e4218c21cbe127bd9e62e88a) here !

could you close this issue ?

**Comment by dave-watts** [comment]
Thanks, I informed the authors of the Leaning OpenCV 3  book of the error
