### ISSUE TITLE
linux tutorials install &| eclipse missing "ldconfig"

### ISSUE THREAD

**Issue by kaefert** [opencv/opencv#8643]
Hey there!

I just went through these tutorials:

http://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html
http://docs.opencv.org/master/d7/d16/tutorial_linux_eclipse.html
-->
https://github.com/opencv/opencv/blob/master/doc/tutorials/introduction/linux_install/linux_install.markdown
https://github.com/opencv/opencv/blob/master/doc/tutorials/introduction/linux_eclipse/linux_eclipse.markdown

And when trying to run the demo I got stuck with the error message
`./DisplayImage: error while loading shared libraries: libopencv_core.so.3.2: cannot open shared object file: No such file or directory`

A few minutes of googling got me the solution that I needed to run `ldconfig` to make my system know the newly installed library. I think it would be a good idea if you told your tutorial readers about this potential problem in advance, would make for a better experience.

Otherwise really smooth and well done tutorials so far, will continue with them now :)
(btw. sorry if this bugtracker is not meant for discussing documentation, please tell me if you want me to report this somewhere else)

**Comment by alalek** [comment]
Hi!

If you use CMake in your projects, then it should handle `RPATH` for your binaries:
- https://cmake.org/Wiki/CMake_RPATH_handling

Output for [example project](https://github.com/opencv/opencv/blob/master/samples/cpp/example_cmake/CMakeLists.txt):
```
$ objdump -x opencv_example|grep RPATH
  RPATH                /home/alalek/projects/opencv/build/opencv/lib
```

If not, then you can fix this problem:
- add linker option `-Wl,-rpath,<opencv-path>/lib`
- or use of `LD_LIBRARY_PATH` environment variable during application launching.

Touching of `ldconfig` is not recommended (it requires "root" access, and can cause conflicts with system-wide OpenCV packages or with other OpenCV installations).

**Comment by kaefert** [comment]
Hi there alalek!
Thanks for the reply!
Well the linux install tutorial said to run `sudo make install` which is very system global. I used `checkinstall` instead to be able to remove it again should I wish to.

**Comment by StevenPuttemans** [comment]
Actually in Linux, if I follow the complete tutorial, and I do a `sudo make install`, which effictively copies OpenCV into the standard paths, then I do not need to do anything else for getting OpenCV to run. 

If you do not do this, then add an entry to the `~/.bashrc` file, something like `export LD_LIBRARY_PATH=/path/to/your/opencv/installation`. This is what I do for all projects that do not support a global install through CMAKE in default paths.

I guess in your case the issue is that

- `sudo make install` installs opencv inside /usr/local/lib`
- `checkinstall` makes a deb package and I am unsure it goes to this location, you should verify, but it might be different and thus it is not a standard search path!

**Comment by kaefert** [comment]
`checkinstall` makes and installs a deb package, but the paths despite making that detour through the deb package land at the same places they would have landed would one use `make install`.

The opencv library files landed in the `/usr/local/lib/` directory on my system as well, but to make them known to the system I had to run `sudo ldconfig`. I did not have to add the path `/usr/local/lib/` in any config file. And from what I've read on my google research it is quite normal to have to run `sudo ldconfig` to make newly installed libraries visible without a reboot.

**Comment by StevenPuttemans** [comment]
Actually all that the `sudo ldconfig` command does is reloading the configuration files under `/etc/ld.so.conf.d/`. The only explanation I can find, why I did not have to do this call explicitly is because there is already a `libc.conf` file on my system. This file is auto added by `libc`, which is the default `c` compiler. Is it possible you worked on a clean install without any build tools?

**Comment by kaefert** [comment]
yes.

**Comment by alalek** [comment]
Looks like "/etc/ld.so.conf.d/libc.conf" with "/usr/local/lib" is Ubuntu stuff: http://packages.ubuntu.com/xenial/libc-bin ("list of files" link)
