### ISSUE TITLE
Get errors while using cv2.calibrateCamera of opencv(3.2.0) with python(2.7)  : (-211) The number of points in the view #0 is < 4 in function cvCalibrateCamera2Internal

### ISSUE THREAD

**Issue by ghur** [opencv/opencv#8784]
##### System information (version)

- OpenCV => :grey_question:3.2.0
- Operating System / Platform => :grey_question:windows 64bit
- Compiler => :grey_question:

##### Detailed description

Here is the code:
import numpy as np
import cv2

img=np.array([[[ 476.5       ,   47.5       ]],

       [[ 477.        ,  103.        ]],

       [[ 475.        ,  155.5       ]],

       [[ 476.        ,  210.        ]],

       [[ 475.        ,  263.5       ]],

       [[ 474.5       ,  317.        ]],

       [[ 474.        ,  371.        ]],

       [[ 423.        ,   49.5       ]],

       [[ 423.        ,  104.        ]],

       [[ 420.99487305,  156.96131897]],

       [[ 422.        ,  210.        ]],

       [[ 421.51452637,  262.4593811 ]],

       [[ 421.5       ,  316.        ]],

       [[ 418.12008667,  369.7225647 ]],

       [[ 370.        ,   50.5       ]],

       [[ 370.49984741,  103.49343872]],

       [[ 369.5       ,  156.5       ]],

       [[ 369.5       ,  209.5       ]],

       [[ 367.69796753,  260.41433716]],

       [[ 368.5       ,  313.        ]],

       [[ 367.5       ,  366.        ]],

       [[ 316.5       ,   52.        ]],

       [[ 317.50354004,  104.73719788]],

       [[ 316.5       ,  157.        ]],

       [[ 317.14056396,  207.0791626 ]],

       [[ 316.5       ,  260.        ]],

       [[ 317.5       ,  312.5       ]],

       [[ 315.5       ,  364.5       ]],

       [[ 265.57183838,   52.00492477]],

       [[ 265.35064697,  103.89572144]],

       [[ 265.5       ,  155.5       ]],

       [[ 265.41320801,  209.05813599]],

       [[ 267.        ,  260.        ]],

       [[ 266.        ,  310.        ]],

       [[ 265.5       ,  361.5       ]],

       [[ 214.5       ,   53.        ]],

       [[ 214.5       ,  104.        ]],

       [[ 216.07672119,  155.37322998]],

       [[ 216.        ,  207.        ]],

       [[ 217.5       ,  257.5       ]],

       [[ 217.        ,  309.        ]],

       [[ 216.        ,  359.        ]],

       [[ 162.5       ,   53.        ]],

       [[ 165.        ,  104.5       ]],

       [[ 166.        ,  156.        ]],

       [[ 168.5       ,  205.5       ]],

       [[ 169.        ,  256.5       ]],

       [[ 168.        ,  307.        ]],

       [[ 168.        ,  356.        ]]],'float32')

obj=np.array([[[0, 0, 0]], [[0, 1, 0]], [[0, 2, 0]], [[0, 3, 0]], [[0, 4, 0]], [[0, 5, 0]], [[0, 6, 0]], [[1, 0, 0]], [[1, 1, 0]], [[1, 2, 0]], [[1, 3, 0]], [[1, 4, 0]], [[1, 5, 0]], [[1, 6, 0]], [[2, 0, 0]], [[2, 1, 0]], [[2, 2, 0]], [[2, 3, 0]], [[2, 4, 0]], [[2, 5, 0]], [[2, 6, 0]], [[3, 0, 0]], [[3, 1, 0]], [[3, 2, 0]], [[3, 3, 0]], [[3, 4, 0]], [[3, 5, 0]], [[3, 6, 0]], [[4, 0, 0]], [[4, 1, 0]], [[4, 2, 0]], [[4, 3, 0]], [[4, 4, 0]], [[4, 5, 0]], [[4, 6, 0]], [[5, 0, 0]], [[5, 1, 0]], [[5, 2, 0]], [[5, 3, 0]], [[5, 4, 0]], [[5, 5, 0]], [[5, 6, 0]], [[6, 0, 0]], [[6, 1, 0]], [[6, 2, 0]], [[6, 3, 0]], [[6, 4, 0]], [[6, 5, 0]], [[6, 6, 0]]],'float32')

cv2.calibrateCamera(obj,img,(640,480),None,None)

but got errror like:cv2.error: C:\build\master_winpack-bindings-win32-vc14-static\opencv\modules\calib3d\src\calibration.cpp:1396: error: (-211) The number of points in the view #0 is < 4 in function cvCalibrateCamera2Internal

I'm new to this and cannot find why.Anyone can help?

**Comment by sfranzyshen** [comment]
What was the solution to this problem please?

**Comment by tovornik** [comment]
I'm getting the same error: `One of arguments' values is out of range (The number of points in the view #0 is < 4) in cvCalibrateCamera2Internal` and I would like to know the solution to this, if there was any, please.

**Comment by laik97** [comment]
UPDATE!!! Still in need of solution!

**Comment by quitmeyer** [comment]
ahhh dang i was looking for a solution too :(

**Comment by blarkj** [comment]
Same here!

**Comment by quitmeyer** [comment]
Okay I figured it out, it's just an error that comes up if some of the captures were not good and it's not able to parse enough points from the particular image. I think they closed it because not really an issue with the code but more so how it runs. So just try again and get better shots when you do your capture

**Comment by blarkj** [comment]
I checked the images, they don't seem to be the issue. But I still get the same error.

**Comment by githuuuuub** [comment]
I have this problem too. I use a wrong board at first which  is created by "create_board.cpp". Then I use "create_board_charuco.cpp" create another chArucoBoard, it works.

**Comment by rk800506** [comment]
Any solution to this problem, or at-least the root cause?

**Comment by natesimon** [comment]
I came across this issue with [calibrate.py](https://github.com/opencv/opencv/blob/4.x/samples/python/calibrate.py). One solution was to modify [L167-L170](https://github.com/opencv/opencv/blob/f3c724d449b6431c407611fcc5d1ecedfe81e77d/samples/python/calibrate.py#L167-L170) to the following:
```
    chessboards = [x for x in chessboards if x is not None]
    for idx, (corners, pattern_points) in enumerate(chessboards):
        if len(corners) < 4:
            print("Not enough obj/img points for %d, skipping image!" % idx)
        else:
            img_points.append(corners)
            obj_points.append(pattern_points)
```
I wasn't sure whether this would cause any issues with the order of file corner labeling / undistortion downstream, but it did not seem to cause any problems.

**Comment by DanielBajoCollados** [comment]
The problem seems to be that img_points is less than 4. What I did was the following:
`board->matchImagePoints(CharucoCorners, CharucoIds, ObjectPoints, ImagePoints);
                if (ObjectPoints.size()>4){
                    allCharucoIds.push_back(CharucoIds);
                    allCharucoCorners.push_back(CharucoCorners);
                    allObjectPoints.push_back(ObjectPoints);
                    allImagePoints.push_back(ImagePoints);
                )
.
.
.
double repError = cv::calibrateCamera(allObjectPoints, allImagePoints, cv::Size(1600, 1200), cameraMatrix, distCoeffs, rvecs, tvecs, cv::noArray(), cv::noArray(), cv::noArray());
`

**Comment by ArnobTurja2002Ghosh** [comment]
I see that a lot of people in this thread faced this problem for years and unlike other threads most of the people here came to look for a solution instead of suggesting a solution! The [solution by Quitmeyer](https://github.com/opencv/opencv/issues/8784#issuecomment-581994885) is helpful and I am writing a [cv2.aruco.calibrateCameraCharuco](https://docs.opencv.org/3.4/d9/d6a/group__aruco.html#ga54cf81c2e39119a84101258338aa7383) version of it. First, let us take an image that would give us this error.

![Image](https://github.com/user-attachments/assets/fbc13eda-e2a3-4b7f-a132-4dd6de0a28d2)

The image above is not that bad, right? I bet you with your human eyes can see all the ArUco markers here, and this is probably what Anjali Jogeshwar meant when she said that [the images do not "seem" to be the issue](https://github.com/opencv/opencv/issues/8784#issuecomment-582010598). 

Problem is, there is no trick in which you see a photo and predict how many corners cv2 would be able to detect from there. cv2 detected only 3 corners from the above photo ("view" in terms of openCV) but for calibration, you should have at least 4 detected corners ("points" in terms of openCV). The detected points from the above photo are labelled in the image below in aqua color (you may want to zoom-in here):

![Image](https://github.com/user-attachments/assets/30f97ea5-5bb3-4e24-bf7c-997251624cea)

Now there are two possible "solutions" already mentioned in this thread:

[1](https://github.com/opencv/opencv/issues/8784#issuecomment-1741608553). As suggested by Nate Simon, skip the images where only less than 4 corners are detected.

[2](https://github.com/opencv/opencv/issues/8784#issuecomment-581994885). As suggested implicitly by Quitmeyer, remove the photo(s) that are causing this error and "get better shots when you do your capture". Disadvantage of this is that you will have to take the time to find the bad photo instead of letting your program automatically skip it (suggestion-1) but I like this more than suggestion-1 because then you know which ones are bad photos and have only clean data (good views) in your directory.
