### ISSUE TITLE
Bug in name of variable in Documentation

### ISSUE THREAD

**Issue by animeshsrivastava24** [opencv/opencv#8889]
http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html

```
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    # Take each frame
    _, frame = cap.read()

    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # define range of blue color in HSV
    lower_blue = np.array([110,50,50])
    upper_blue = np.array([130,255,255])

    # Threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_green, upper_green) 
     #name of variables should be lower_blue and upper_blue

    # Bitwise-AND mask and original image
    res = cv2.bitwise_and(frame,frame, mask= mask)

    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
```

**Comment by krishraghuram** [comment]
@animeshsrivastava24 

You are looking at 3.0.0-beta docs. This documentation error has been in fixed in 3.0-last-rst docs.
Link to 3.0-rst-last docs : 
http://docs.opencv.org/3.0-last-rst/doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html#converting-colorspaces
Link to docs : 
http://docs.opencv.org/

Also, opencv only maintains version 2.4 and master(currently 3.2). 
OpenCV doesnt fix bugs that only affect **deprecated versions** like 3.0.0-beta.
