### ISSUE TITLE
Linker Error with lineDescriptor

### ISSUE THREAD

**Issue by eshirima** [opencv/opencv#8928]
##### System information (version)
- OpenCV => 3.2.0:
- Operating System / Platform => Mac OS X 10.12.5:
- Compiler => g++/Xcode 8.3.3:
- Linker Flags => -lopencv_calib3d -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videoio -lopencv_videostab

##### Detailed description

I built OpenCV from source along with *opencv_contrib* as well.

For some reason all my attempts to access the classes in [`lineDescriptor`](http://docs.opencv.org/master/d2/d51/namespacecv_1_1line__descriptor.html) lead to a linker error.

All of these declarations throw a linker error

	BinaryDescriptor bsd = BinaryDescriptor();
	Ptr<BinaryDescriptor> bsd1 = BinaryDescriptor::createBinaryDescriptor();
	Ptr<LSDDetector> lsd1 = LSDDetector::createLSDDetector();

##### Steps to reproduce

```
#include <iostream>
#include "opencv2/opencv.hpp"
#include "opencv2/line_descriptor.hpp"

using namespace cv;
using namespace std;
using namespace line_descriptor;

void detectLines(Mat& original, Mat grey)
{
    Ptr<LineSegmentDetector> lsd = createLineSegmentDetector(2);

    vector<Vec4f> lines;

    lsd->detect(grey, lines);

    cout << "Detected " << lines.size() << endl;

    lsd->drawSegments(original, lines);

    // Linker problems galore
//  BinaryDescriptor bsd = BinaryDescriptor();
//  Ptr<BinaryDescriptor> bsd1 = BinaryDescriptor::createBinaryDescriptor();
//  Ptr<LSDDetector> lsd1 = LSDDetector::createLSDDetector();

}
```

**Comment by eshirima** [comment]
Fixed some formatting issue

**Comment by berak** [comment]
* the [createLineSegmentDetector](http://docs.opencv.org/master/dd/d1a/group__imgproc__feature.html#ga6b2ad2353c337c42551b521a73eeae7d) is in imgproc, so you're already covered, linking against `opencv_imgproc`
* both [BinaryDescriptor](http://docs.opencv.org/master/d6/d83/classcv_1_1line__descriptor_1_1BinaryDescriptor.html#ab1b463cf10057541d43bb2c1729da806) and [LSDDetector](http://docs.opencv.org/master/d1/dbd/classcv_1_1line__descriptor_1_1LSDDetector.html)
 are from the [line_descriptor](http://docs.opencv.org/master/dc/ddd/group__line__descriptor.html) module in opencv_contrib, you simply forgot to add `-lopencv_line_descriptor` to your library list.

since this is not an opencv bug, but a usage problem, i think, you should kindly close this issue.

**Comment by eshirima** [comment]
@berak Thank u so much for the help!
