### ISSUE TITLE
cv::Mat_<value_t1>::copyTo(cv::Mat_<value_t2>) is unsafe

### ISSUE THREAD

**Issue by maddanio** [opencv/opencv#9163]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => osx
- Compiler => clang

##### Detailed description

copyTo does not use the type information available when copying between two typed matrices.

##### Steps to reproduce

cv::Mat1b a{10, 10};
cv::Mat2b b{10, 10};
b.copyTo(a) // will fail at runtime, though it should not compile

**Comment by alalek** [comment]
OpenCV widely uses dynamic types. `cv::Mat_` is just wrappers over "untyped" `cv::Mat`. Main purpose of  these wrappers is easy initialization with values and easy values retrieval. The most part of operations are done via regular `cv::Mat`.
We prefer to keep code simple and to avoid massive duplication of similar things.

**Comment by maddanio** [comment]
so instead of providing a simple override preventing pointless runtime errors you will just go on principle? do you accept pull requests? (this one should be about 10 lines...)

**Comment by maddanio** [comment]
template<typename T> void copyTo(cv::Mat_<T>& other)
{
    throw...
}

template<> void copyTo(cv::Mat_<my_type>& other) {cv::Mat::copyTo(other);}

**Comment by maddanio** [comment]
https://en.wikipedia.org/wiki/Type_safety

**Comment by alalek** [comment]
I see, but you mention one operation only and miss similar cases like arithmetic operations (`+ / * /`), convertTo, resize and many others. Do you want typed cvtColor?
Sorry, but this change would bloat OpenCV codebase with duplicated code seriously. I'm not sure that we would see here some robust "code generator" for this to avoid manual work with "duplicated" code.

Current runtime assertion works well enough - it is raised in 100% of cases - you just need to have simple smoke test for your application. This problem is very similar to applications written on Python / JavaScript with dynamic types.

**Comment by maddanio** [comment]
Hmm, I guess it's a matter of opinion. I like the type safety of Mat_ very much and would love to see functions use it, because often it takes me quite a while to figure out what is legal to pass into them. It's often very hard to tell from the error messages

Gruß!

Daniel Oberhoff
