### ISSUE TITLE
DNN: Upsample layer support?

### ISSUE THREAD

**Issue by tirinox** [opencv/opencv#9353]
Hello!
I'm developing an application that uses pixelwise image segmentation based on U-nets. Such networks need Upsample layers which rely on "**ResizeNearestNeighbor**" operation in TensorFlow. Also "Shape" and "StridedSlice" are needed but I guess they are for dimensions calculation which can be hardcoded. 

It'd be great to have those operations available in the DNN module.

**Comment by dkurt** [comment]
Hi, @tirinox! We prepared PR #9349 with `tf.nn.conv2d_transpose` support. You may find a test case at corresponding PR https://github.com/opencv/opencv_extra/pull/363 (see `generate_tf_models.py` tool). It's interesting to know how it works for your model. Could you try and leave feedback? Thanks!

**Comment by lvzhen3931** [comment]
Hi, @dkurt , I have a question regarding using `tf.nn.conv2d_transpose`. It needs an explicit `output_shape`, which may be `[batch_size, img_rows, img_cols, img_channels]`, since `tf.shape()` is not supported by `dnn`, `batch_size` should be inferred from input `tf.placeholder(tf.float32, shape=[batch_size, img_rows, img_cols, img_channels])`. The question is, if I use a batch size of 8 in training, how should I infer a single image using trained model in dnn? In other words, if training batch_size is greater than one,  how to change it to one when deploying without crashing `conv2d_transpose`?
Here is an example that illustrates dynamically changing `output_shape `by using `tf.shape()`
[https://stackoverflow.com/questions/38822411/conv2d-transpose-is-dependent-on-batch-size-when-making-predictions](url)
Can you think of a way that bypass `tf.shape()`? The only way I can think of is to train using `batch_size=1` for now.
Thank you!

**Comment by dkurt** [comment]
@lvzhen3931, thank you for an interesting note! You're right, `tf.shape()` isn't supported. If I'm correct, we can't use an implicit `output_shape` in `conv2d_transpose`: neither  `-1` nor `None` for batch dimension. So we can extract the batch size using `tf.shape()` or define just a variable `batch_size=8` and use it like:
```python
deconv = tf.nn.conv2d_transpose(inp, filter=deconv_weights,
                                output_shape=[batch_size, 9, 8, 4], strides=[1, 1, 1, 1],
                                padding='VALID')
```
It let you have flexible by batch size graph without extra nodes. DNN can parse it anyway because it doesn't read `output_shape` argument at all (see https://github.com/opencv/opencv/blob/master/modules/dnn/src/tensorflow/tf_importer.cpp#L1014): deconvolution layer calculates it later based on input layer shape, kernel size, strides, paddings etc.
