### ISSUE TITLE
Allow longer trackbar names

### ISSUE THREAD

**Issue by dustsigns** [opencv/opencv#9489]
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Ubuntu 16.04 (x86-64) with QT 5.5
- Compiler => g++ 5.4.0

##### Detailed description

Trackbar names are truncated after the tenth character, regardless of their actual length on-screen. The following example illustrates the effect:

##### Steps to reproduce

```
#include <opencv2/highgui.hpp>

using namespace std;
using namespace cv;

static constexpr auto trackbar_name = "X angle [deg.]"; //Use "X angle [°]" to see the same effect

int main()
{
  namedWindow("Test window");
  imshow("Test window", Mat(600, 600, CV_8UC1, Scalar(128)));
  int dummy;
  createTrackbar(trackbar_name, "Test window", &dummy, 360, [](const int, void * const){});
  waitKey(0);
  return 0;
}
```

This limitation does not seem to be documented. But even so, it would be more desirable to use names as long as one pleases, i.e., without arbitrary character limitations. Being limited to ten characters is not really meaningful when using narrow characters/symbols or wide windows.

**Comment by saskatchewancatch** [comment]
The issue is being caused by the way [this](https://github.com/opencv/opencv/blob/80519a0278f1156fe09dde808871c14d4a240a21/modules/highgui/src/window_QT.cpp#L1413) QString string formatting method is being called; see [QString doc.](http://doc.qt.io/qt-5/qstring.html#leftJustified)

 The option to truncate is currently set to `true`. If it is set to `false` or just removed, we should see the behaviour desired by the OP. 

When the truncate option is set to `false`, names less than 10 characters long will have trailing whitespace filling to the right whereas names greater than 10 characters long will just show up. This is more desirable than just truncating the name to 10 characters max.

Like @dustsigns@ I see no reason why the name should be truncated to 10 characters.

I can have a PR for this soon. Any feedback is appreciated.

**Comment by saskatchewancatch** [comment]
@dustsigns PR #9521 should solve your issue. Care to give it a try and let us know how it works? It worked for me on Windows.

**Comment by dustsigns** [comment]
Of course, I'll try it and report back.

In my opinion, aligning the names to 10 characters does not really make sense since the font is not monospace (at least it is not with QT and xfce).

**Comment by dk00001101** [comment]
this is still an issue.... In python, any version of ocv. How can i change the displayable length of the trackbar labels? 
![opencv_trackbar_bug](https://github.com/opencv/opencv/assets/93824523/50ebff4e-3878-460a-9fce-7fc246438129)
