### ISSUE TITLE
AttributeError: 'cv2.dnn_Net' object has no attribute 'getPerfProfile'

### ISSUE THREAD

**Issue by smajida** [opencv/opencv#9607]
##### System information (version)

- OpenCV => :grey_question:3.3.0
- Operating System / Platform => :grey_question:Ubuntu 16.04 / Jetson TX1
- Compiler => :grey_question:g++-5.4 /python2.7 & python3.5

##### Detailed description

 problem comes from the following line:
```.py
perf_stats = net.getPerfProfile()


nvidia@tegra-ubuntu:~/softwares/opencv/samples/dnn$ python(3) resnet_ssd_face_python.py 
Traceback (most recent call last):
  File "resnet_ssd_face_python.py", line 34, in <module>
    perf_stats = net.getPerfProfile()
AttributeError: 'cv2.dnn_Net' object has no attribute 'getPerfProfile'
```

##### Steps to reproduce
 In order to reproduce the problem, one just has to run `resnet_ssd_face_python.py` in sample/dnn folder. I commented out the above line plus a print function afterwards. Scripts is workly properly.

**Comment by dkurt** [comment]
@smajida, this is a relatively new function and I hope it's just because of out-of-date version of `cv2.so` that was linked. Let's try to follow this hypothesis and check that OpenCV was built with python module (clean the build directory, build again and check that `build/lib` has `cv2.so`), check that `PYTHONPATH` has a reference to actual `cv2.so` (if not `build/lib`, remove cv2.so from `PYTHONPATH` locations and check that `sudo make install` restore it).
