### ISSUE TITLE
Memory leak in rowRange ?

### ISSUE THREAD

**Issue by tarasvinnik** [opencv/opencv#9732]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

If the final rowRange parameter is less than then "start rowRange" an exception occurs (in the constructor of the Mat object). For this, not properly created Mat object destructor is not called. But refCount is already increased. As a result, we get a memory leak, see sample code below. Is it a bug or desired behavior? Thanks. 

##### Steps to reproduce

```
  for (int k = 0; k < 500; k++)
  {
    try
    {
      std::cout << k << std::endl;
      Sleep(200);
      cv::Mat sourceMat(2000, 2000, CV_8UC1,cv::Scalar(0));
      cv::Mat copyheader = sourceMat.rowRange(19, 9);

    }
    catch (...)
    {
      std::cout << "error " << k << std::endl;

    }
  }    
```

**Comment by IgWod** [comment]
I managed to recreate this bug. I built opencv from the master branch.

Valgrind output:

```
==3335== LEAK SUMMARY:
==3335==    definitely lost: 44,000 bytes in 500 blocks
==3335==    indirectly lost: 1,676,000,000 bytes in 419 blocks
==3335==      possibly lost: 324,000,000 bytes in 81 blocks
==3335==    still reachable: 628 bytes in 9 blocks
==3335==         suppressed: 0 bytes in 0 blocks
```

I'll give it a go and try to fix.

**Comment by IgWod** [comment]
I found out there are more cases that can cause a memory leak. There are few coying constructors in the matrix.cpp that call CV_Assert macro. Unfortunatelly this macro only throws the excpetion without cleaning up hence the memory leak. The simplest solution I can think of is to first check for the condition, then clean up everyting and throw the excpetion at the end.

Here is a example of solution fixing problem reported in this issue:

```C++
if( !( 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows ) )
{
    this->~Mat();
    CV_Assert( 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows );
}
```

Replacing every CV_Assert macro in every constructor with a similar chunk of code seems a bit redundant. I think this should be extracted as a function. I'm not sure if it should be a private function inside Mat or something more generic somewhere else (where tho?)

I'll submit a pull request within 1-2 days with some solution, but in the meantime I open for suggestions.

**Comment by alalek** [comment]
There is [link](https://github.com/opencv/opencv/blob/3.3.0/modules/core/src/matrix.cpp#L470-L512) to related code.

Proposed solution is not robust (additional checks may be added in the future without such tricks) and doesn't look good (direct call of destructor).

Also there are lot of other places with the same problem. So we do not want to add such tricks into many places.

Problem is related to increased "refcount" (via pointer) without proper cleanup (because it is just a C pointer and there is no destructor).
It should be wrapped into some class with destructor which would be called by C++ [automatically](https://stackoverflow.com/a/32323458) on exception in constructor body:
>  If the ctor throws, then the dtor is not called.
> (But dtors of any member variable objects, whose ctors already ran to completion before this ctor ran, are called.)

Unfortunately approach with wrapper class can't be applied safe right now (we should preserve binary and source compatibility until OpenCV 4.0).

Probably this workaround should work too:
```
Mat::Mat(...)
{
    *this = m; // original line: refcount increased here

    try {
        ... just move original body here without "*this = m" line ...
    }
    catch (...)
    {
        release(); // decrease refcounter
        throw;
    }
}
```
