### ISSUE TITLE
ENABLE_CXX11 option doesn't enable C++11 for GNU Make 4.1

### ISSUE THREAD

**Issue by abratchik** [opencv/opencv#9898]
##### System information (version)

- OpenCV => master (5ed354221c)
- Operating System / Platform => Ubuntu 16.04
- Compiler => GNU Make 4.1

##### Detailed description

CMake flag  ENABLE_CXX11 does not enable C++11 option.  

##### Steps to reproduce

1. Set ENABLE_CXX11 = ON, for example using ccmake
2. Run make. The code containing C++11 extensions will fail.

**Comment by alalek** [comment]
0. Build from scratch (clean build directory / CMake cache) - we need reproducible results
1. Dump complete stdout from CMake with log files (see [here](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl_linux/builds/13050) step 8)
2. Dump log of `make VERBOSE=1 opencv_core`
3. Dump log of `make VERBOSE=1 your_failed_target`

**Comment by abratchik** [comment]
Hi, alalek. I believe no need logs as the issue is cured by complete wipe out of the build folder and reconfig/rebuild from scratch.

I think the issue is in this code in opencv/cmake/OpenCVDetectCXXCompiler.cmake:

```
if(ENABLE_CXX11)
  #cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)
  set(CMAKE_CXX_STANDARD 11)
  set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
  set(CMAKE_CXX_EXTENSIONS OFF) # use -std=c++11 instead of -std=gnu++11
  if(CMAKE_CXX11_COMPILE_FEATURES)
    set(HAVE_CXX11 ON)
  endif()
endif()
if(NOT HAVE_CXX11)
  ocv_check_compiler_flag(CXX "" HAVE_CXX11 "${OpenCV_SOURCE_DIR}/cmake/checks/cxx11.cpp")
  if(NOT HAVE_CXX11 AND ENABLE_CXX11)
    ocv_check_compiler_flag(CXX "-std=c++11" HAVE_STD_CXX11 "${OpenCV_SOURCE_DIR}/cmake/checks/cxx11.cpp")
    if(HAVE_STD_CXX11)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
      set(HAVE_CXX11 ON)
    endif()
  endif()
endif()
```

if the CMAKE_CXX11_COMPILE_FEATURES is set then HAVE_CXX11 is always set to ON, which is fine as long as CMAKE_CXX_FLAGS already contain "-std=c++11". But if it does not then setting ENABLE_CXX11 to ON will have no effect.

**Comment by alalek** [comment]
The first part of code here is CMake-way (requires modern versions of CMake) - via `CMAKE_CXX_STANDARD`. There is no touching of CMAKE_CXX_FLAGS. `make VERBOSE=1` should show flag if it is required (in some cases, see below about default compiler mode).
The next part is auto-detection / manual flags approach.

`-std=c++11` flag is not forced because there are other flags like `-std=c++14`/`-std=c++17`/etc, so we use auto-detection too.
For example, GCC 7 in Fedora 26 enables C++11 features (actually C++14) by default without any `-std` flag:
```
$ c++ -x c++ -dM -E - < /dev/null | grep cplus
#define __cplusplus 201402L
```

I believe this issue can be closed.

**Comment by abratchik** [comment]
Ok

**Comment by myradio** [comment]
To make it clear: the issue was just due to an old cmake version the OP was using?
