### ISSUE TITLE
Is the explanation of code of "the Load Caffe framework models tutorial"　wrong?

### ISSUE THREAD

**Issue by iwaki2009** [opencv/opencv#9967]
##### System information (version)

- OpenCV => :3.3.1
- Operating System / Platform => :ubuntu 16.04 bit
- Compiler => :grey_question:

##### Detailed description

tutrial is here
https://docs.opencv.org/3.3.1/d5/de7/tutorial_dnn_googlenet.html

section 4 Read input image and convert to the blob

It is explained as "Firstly, we resize the image and change its channel sequence order.",
Is the correct explanation like this, "Firstly, we resize the image and subtract mean values from channels"?

**Comment by iwaki2009** [comment]
one more

section 4 Read input image and convert to the blob

In the case of resize, is false correct for the crop parameter of blobFromImage ?

**Comment by dkurt** [comment]
@iwaki2009, thanks for notes! Could you replace a content of https://github.com/opencv/opencv/issues/9966 to this issue? It looks like we need to refresh dnn samples. Let's also rename detections' postprocessing as we discusses at https://github.com/opencv/opencv/issues/9861.

**Comment by alphadose** [comment]
@iwaki2009 can I take up this issue ?

**Comment by dkurt** [comment]
@alphadose, I think you may freely start work with it. The problem is to find all invocations of `blobFromImage` and check that comments correspond to function's arguments. Also you may hide some preprocessing procedures like mean subtraction (https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_object_detection.cpp#L16) or resize (https://github.com/opencv/opencv/blob/master/samples/dnn/ssd_object_detection.cpp#L31) into `blobFromImage`. Thank you!

**Comment by haritha1313** [comment]
@dkurt  I would like to take up this issue. Is it already being worked upon?

**Comment by dkurt** [comment]
@haritha1313, Actually we have no response neither from @alphadose nor @iwaki2009. We just have a rule to open a single PR for a one issue. So you can freely start to do it because we have no corresponding PR for now. Thank you!

One more thing, please add a reference `resolves https://github.com/opencv/opencv/issues/9967` in description of the future PR.

**Comment by iwaki2009** [comment]
I don't know how to pull request well, so please someone take over.

**Comment by haritha1313** [comment]
@dkurt  i have worked on this issue and updated the PR. Please review the same.
